import ts from 'typescript';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
import { workspaceRepositoryRegistryService } from '../../core/services/workspaceRepositoryRegistryService';
export type AdvancedDomain='COMPLEX_UI'|'LARGE_STATE'|'EXTERNAL_API'|'ADVANCED_PERFORMANCE'|'THREAT_MODEL'|'COMPLEX_DB_MIGRATION'|'MULTI_REPOSITORY';
export interface ExecutableGate{gateId:string;name:string;testId:string;command:string;method:'STATIC_AST'|'GRAPH'|'SANDBOX'|'BENCHMARK'|'CONTRACT'|'ROUNDTRIP';threshold:string;environment:'CANDIDATE_WORKSPACE'|'NODE_SANDBOX'|'BROWSER'|'DEVICE'|'MULTI_REPOSITORY';timeoutMs:number;retry:number;evidenceKind:string;failureClass:string;}
export interface ConcreteOperation{operationId:string;domain:AdvancedDomain;path:string;symbol?:string;kind:'ADD_IMPORT'|'ADD_GUARD'|'PROPAGATE_CONTRACT'|'UPDATE_JSX'|'UPDATE_STATE'|'ADD_TEST'|'ADD_MIGRATION'|'ADD_BENCHMARK'|'ADD_SECURITY_TEST'|'PIN_REVISION'|'MODEL_CHANGE';anchorType:string;preconditions:string[];postconditions:string[];}
class AdvancedDomainExecutionModelService{
 detectAll(instruction:string):AdvancedDomain[]{const text=instruction.toLowerCase();const rules:Array<[AdvancedDomain,RegExp[]]>=[['COMPLEX_UI',[/複雑.*ui|画面設計|component tree|accessibility|responsive|ui\/ux/,/画面.*状態|操作.*画面|表示.*遷移/]],['LARGE_STATE',[/大規模.*状態|state management|event sourcing/,/状態.*競合|再水和|rehydration|single writer/]],['EXTERNAL_API',[/外部api|api.*仕様|openapi|webhook|oauth|rate limit/,/client.*server|契約.*api/]],['ADVANCED_PERFORMANCE',[/高度.*性能|performance|benchmark|p95|hotspot|memory/,/重くなる|遅くなる|処理時間|応答.*遅/]],['THREAT_MODEL',[/脅威モデル|threat model|trust boundary|stride|attack surface/,/認証.*抜け|権限.*漏れ|危険.*入力|攻撃/]],['COMPLEX_DB_MIGRATION',[/複雑.*db|database migration|schema migration|backfill|zero downtime/,/止めずに.*db|データ.*移行|旧.*schema/]],['MULTI_REPOSITORY',[/多数.*repository|multi.?repo|複数.*repository|monorepo|依存repository/,/別々.*プロジェクト|複数.*プロジェクト|跨いで.*反映/]]];return rules.filter(([,patterns])=>patterns.some(pattern=>pattern.test(text))).map(([domain])=>domain);}
 buildOperations(domain:AdvancedDomain,paths:string[]):ConcreteOperation[]{return paths.flatMap(path=>{const source=workspaceRepositoryRegistryService.listCompositeFiles().find(file=>file.path===path)?.content||'';const sf=ts.createSourceFile(path,source,ts.ScriptTarget.ES2022,true,path.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);const symbols:string[]=[];const visit=(node:ts.Node)=>{if((ts.isFunctionDeclaration(node)||ts.isClassDeclaration(node)||ts.isInterfaceDeclaration(node)||ts.isVariableDeclaration(node))&&node.name)symbols.push(node.name.getText(sf));ts.forEachChild(node,visit);};visit(sf);const symbol=symbols[0];const kinds:Record<AdvancedDomain,ConcreteOperation['kind'][]>= {COMPLEX_UI:['UPDATE_JSX','ADD_TEST'],LARGE_STATE:['UPDATE_STATE','ADD_TEST'],EXTERNAL_API:['PROPAGATE_CONTRACT','ADD_TEST'],ADVANCED_PERFORMANCE:['ADD_BENCHMARK','MODEL_CHANGE'],THREAT_MODEL:['ADD_GUARD','ADD_SECURITY_TEST'],COMPLEX_DB_MIGRATION:['ADD_MIGRATION','ADD_TEST'],MULTI_REPOSITORY:['PIN_REVISION','PROPAGATE_CONTRACT']};return kinds[domain].map((kind,index)=>({operationId:`AOP-${canonicalSha256({domain,path,symbol,kind,index}).slice(0,20)}`,domain,path,symbol,kind,anchorType:symbol?'SYMBOL':'SOURCE_FILE',preconditions:['BASELINE_SHA_MATCH',symbol?'UNIQUE_SYMBOL_ANCHOR':'SOURCE_FILE_PARSE_VALID'],postconditions:['PARSE_VALID','NO_UNRELATED_CHANGE','DOMAIN_GATE_EVIDENCE']}));});}
 buildGates(domain:AdvancedDomain):ExecutableGate[]{const names:Record<AdvancedDomain,string[]>={COMPLEX_UI:['COMPONENT_TREE','ROUTE_REACHABILITY','INTERACTION','ACCESSIBILITY','VISUAL_REGRESSION'],LARGE_STATE:['STATE_GRAPH','OWNERSHIP','CONCURRENCY','REHYDRATION','ROLLBACK'],EXTERNAL_API:['CONTRACT_DIFF','CLIENT_CALLSITE','AUTH','BACKWARD_COMPATIBILITY','CONTRACT_TEST'],ADVANCED_PERFORMANCE:['BASELINE','MEDIAN','P95','MEMORY','OUTPUT_EQUIVALENCE'],THREAT_MODEL:['TRUST_BOUNDARY','STRIDE','AUTHZ','DANGEROUS_SINK','COUNTEREXAMPLE'],COMPLEX_DB_MIGRATION:['VERSION_GRAPH','FORWARD_BACKWARD','BACKFILL_RESUME','IDEMPOTENCY','DATA_INVARIANT'],MULTI_REPOSITORY:['DEPENDENCY_GRAPH','REVISION_PIN','BUILD_ORDER','ATOMIC_CANDIDATE','ROLLBACK_ORDER']};return names[domain].map((name,index)=>{const method=this.method(name);return {gateId:`AG-${canonicalSha256({domain,name}).slice(0,18)}`,name,testId:`TEST-${domain}-${String(index+1).padStart(2,'0')}`,command:`node scripts/verify_advanced_gate.mjs ${domain} ${name}`,method,threshold:this.threshold(name),environment:method==='BENCHMARK'?'NODE_SANDBOX':method==='ROUNDTRIP'?'CANDIDATE_WORKSPACE':method==='STATIC_AST'?'CANDIDATE_WORKSPACE':'NODE_SANDBOX',timeoutMs:method==='BENCHMARK'?120000:30000,retry:method==='BENCHMARK'?2:1,evidenceKind:`${domain}_${name}_EVIDENCE`,failureClass:`${domain}_${name}_FAILED`};});}
 batch<T>(items:T[],size:number){const result:T[][]=[];for(let index=0;index<items.length;index+=size)result.push(items.slice(index,index+size));return result.map((values,index)=>({batchId:`BATCH-${index+1}`,index,total:Math.ceil(items.length/size),values,continuation:index+size<items.length?`OFFSET:${index+size}`:undefined}));}
 private method(name:string):ExecutableGate['method']{if(/P95|MEDIAN|MEMORY|BASELINE/.test(name))return 'BENCHMARK';if(/CONTRACT|BACKWARD|CLIENT/.test(name))return 'CONTRACT';if(/ROUND|REHYDRATION|IDEMPOTENCY|DATA_INVARIANT|ROLLBACK/.test(name))return 'ROUNDTRIP';if(/GRAPH|BOUNDARY|STRIDE|ROUTE|OWNERSHIP/.test(name))return 'GRAPH';if(/VISUAL|INTERACTION|COUNTEREXAMPLE/.test(name))return 'SANDBOX';return 'STATIC_AST';}
 private threshold(name:string){if(name==='P95')return 'candidate_p95_ms <= baseline_p95_ms * 1.05';if(name==='MEDIAN')return 'candidate_median_ms <= baseline_median_ms';if(name==='MEMORY')return 'candidate_peak_bytes <= baseline_peak_bytes * 1.10';if(name==='VISUAL_REGRESSION')return 'pixel_diff_ratio <= 0.01';return 'all_required_assertions_pass';}
}
export const advancedDomainExecutionModelService=new AdvancedDomainExecutionModelService();
