import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
export type BrowserE2EAction={type:'CLICK'|'FILL'|'CHECK'|'SELECT'|'WAIT'|'ASSERT_VISIBLE'|'ASSERT_TEXT'|'ASSERT_VALUE'|'ASSERT_URL'|'ASSERT_NO_CONSOLE_ERRORS';selector?:string;value?:string;expected?:string;timeoutMs?:number};
export interface BrowserE2EScenario{scenarioId:string;name:string;startUrl:string;actions:BrowserE2EAction[];}
export interface BrowserE2EResult{runId:string;passed:boolean;status:'PASSED'|'FAILED'|'BLOCKED';environment:'ANDROID_WEBVIEW'|'WEB_BROWSER';startedAt:number;finishedAt:number;scenarioResults:Array<{scenarioId:string;passed:boolean;steps:Array<{index:number;type:string;passed:boolean;durationMs:number;error?:string}>;finalUrl:string;bodyTextHash:string}>;reasons:string[];evidenceHash:string;}
class BrowserE2ERunnerService{
 async run(input:{candidateSha256:string;scenarios:BrowserE2EScenario[];root?:Window;defaultTimeoutMs?:number}):Promise<BrowserE2EResult>{const startedAt=Date.now(),reasons:string[]=[];const root=input.root||window;const scenarioResults:BrowserE2EResult['scenarioResults']=[];if(!input.candidateSha256||!input.scenarios.length)return this.finish(startedAt,[],['BROWSER_E2E_INPUT_INVALID'],root);
 for(const scenario of input.scenarios){const steps:any[]=[];let passed=true;try{if(scenario.startUrl&&new URL(scenario.startUrl,root.location.href).origin!==root.location.origin)throw new Error('CROSS_ORIGIN_START_URL_BLOCKED');if(scenario.startUrl&&root.location.href!==new URL(scenario.startUrl,root.location.href).href)root.history.pushState({},'',scenario.startUrl);for(let i=0;i<scenario.actions.length;i++){const action=scenario.actions[i],begin=Date.now();try{await this.execute(root,action,input.defaultTimeoutMs||5000);steps.push({index:i,type:action.type,passed:true,durationMs:Date.now()-begin});}catch(e){passed=false;steps.push({index:i,type:action.type,passed:false,durationMs:Date.now()-begin,error:e instanceof Error?e.message:String(e)});break;}}}catch(e){passed=false;steps.push({index:-1,type:'SCENARIO_SETUP',passed:false,durationMs:0,error:e instanceof Error?e.message:String(e)});}if(!passed)reasons.push(`SCENARIO_FAILED:${scenario.scenarioId}`);scenarioResults.push({scenarioId:scenario.scenarioId,passed,steps,finalUrl:root.location.href,bodyTextHash:canonicalSha256(root.document.body?.innerText||'')});}
 return this.finish(startedAt,scenarioResults,reasons,root);}
 private async execute(root:Window,a:BrowserE2EAction,defaultTimeout:number){const timeout=Math.min(30000,Math.max(100,a.timeoutMs||defaultTimeout));if(a.type==='WAIT'){await new Promise(r=>setTimeout(r,Math.min(timeout,Number(a.value||250))));return;}if(a.type==='ASSERT_URL'){if(!root.location.href.includes(a.expected||''))throw new Error('ASSERT_URL_FAILED');return;}if(a.type==='ASSERT_NO_CONSOLE_ERRORS'){const errors=(root as any).__MIKI_E2E_CONSOLE_ERRORS__||[];if(errors.length)throw new Error(`CONSOLE_ERRORS:${errors.length}`);return;}const el=await this.waitFor(root,a.selector||'',timeout);if(a.type==='CLICK'){(el as HTMLElement).click();return;}if(a.type==='FILL'){const input=el as HTMLInputElement;input.focus();input.value=a.value||'';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));return;}if(a.type==='CHECK'){const input=el as HTMLInputElement;if(!input.checked)(input as HTMLElement).click();return;}if(a.type==='SELECT'){const select=el as HTMLSelectElement;select.value=a.value||'';select.dispatchEvent(new Event('change',{bubbles:true}));return;}if(a.type==='ASSERT_VISIBLE'){const rect=(el as HTMLElement).getBoundingClientRect();if(rect.width<=0||rect.height<=0)throw new Error('ASSERT_VISIBLE_FAILED');return;}if(a.type==='ASSERT_TEXT'){if(!(el.textContent||'').includes(a.expected||''))throw new Error('ASSERT_TEXT_FAILED');return;}if(a.type==='ASSERT_VALUE'){if((el as HTMLInputElement).value!==(a.expected||''))throw new Error('ASSERT_VALUE_FAILED');return;}throw new Error('ACTION_NOT_SUPPORTED');}
 private async waitFor(root:Window,selector:string,timeout:number){if(!selector)throw new Error('SELECTOR_REQUIRED');const started=Date.now();while(Date.now()-started<timeout){const el=root.document.querySelector(selector);if(el)return el;await new Promise(r=>setTimeout(r,50));}throw new Error(`ELEMENT_TIMEOUT:${selector}`);}
 private finish(startedAt:number,scenarioResults:BrowserE2EResult['scenarioResults'],reasons:string[],root:Window):BrowserE2EResult{const finishedAt=Date.now(),passed=reasons.length===0&&scenarioResults.length>0&&scenarioResults.every(x=>x.passed);const details={startedAt,finishedAt,scenarioResults,reasons,url:root.location.href};return {runId:`BE2E-${canonicalSha256(details).slice(0,24)}`,passed,status:scenarioResults.length===0?'BLOCKED':passed?'PASSED':'FAILED',environment:/Android/i.test(root.navigator.userAgent)?'ANDROID_WEBVIEW':'WEB_BROWSER',startedAt,finishedAt,scenarioResults,reasons,evidenceHash:canonicalSha256(details)};}}
export const browserE2ERunnerService=new BrowserE2ERunnerService();
