import JSZip from 'jszip';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { callSelfCodeApi,isApiFailure } from './selfCodeApiClient';
import { nativeWorkManagerService } from '../../execution/services/nativeWorkManagerService';
import { capabilityProofRegistryService } from './capabilityProofRegistryService';
import type { RuntimeProof } from './runtimeExecutionDepthService';
export type CandidateE2EStep={type:'CLICK'|'FILL'|'CHECK'|'SELECT'|'WAIT'|'ASSERT_VISIBLE'|'ASSERT_TEXT'|'ASSERT_VALUE'|'ASSERT_URL'|'ASSERT_NO_CONSOLE_ERRORS';selector?:string;value?:string;expected?:string;timeoutMs?:number};
export type CandidateE2EScenario={scenarioId:string;name:string;path:string;steps:CandidateE2EStep[];baselineScreenshotBase64?:string;maxPixelDifferenceRatio?:number};
export interface CandidateBrowserE2EEvidence{passed:boolean;required:boolean;workspaceId:string;candidateSha256:string;previewUrl?:string;environmentFingerprint:string;repositoryRevision:string;results:any[];consoleErrors:string[];network:Array<Record<string,unknown>>;screenshots:Array<{scenarioId:string;base64:string;sha256:string;differenceRatio?:number}>;domSnapshots:Array<{scenarioId:string;html:string;sha256:string}>;traceZipBase64?:string;traceZipSha256?:string;reasons:string[];}
class CandidateBrowserE2EOrchestratorService{
 isRequired(paths:string[]){return paths.some(path=>/\.(tsx|jsx|html|css|scss)$|(^|\/)components\/|(^|\/)pages\/|(^|\/)ui\//i.test(path));}
 async run(input:{workspaceId:string;candidateSha256:string;files:Array<{path:string;content:string}>;scenarios?:CandidateE2EScenario[]}):Promise<CandidateBrowserE2EEvidence>{const required=this.isRequired(input.files.map(file=>file.path));const environmentFingerprint=canonicalSha256({engine:'ANDROID_INDEPENDENT_WEBVIEW_E2E',version:2});const repositoryRevision=input.candidateSha256;if(!required)return {passed:true,required:false,workspaceId:input.workspaceId,candidateSha256:input.candidateSha256,environmentFingerprint,repositoryRevision,results:[],consoleErrors:[],network:[],screenshots:[],domSnapshots:[],reasons:[]};const scenarios=input.scenarios?.length?input.scenarios:this.loadScenarios(input.files);const started=await callSelfCodeApi<any>('/api/self-code/candidate-preview/start',{method:'POST',body:{workspaceId:input.workspaceId,candidateSha256:input.candidateSha256,files:input.files}});if(isApiFailure(started))return this.fail(input,environmentFingerprint,[started.reason]);try{const native=await nativeWorkManagerService.runCandidateBrowserE2E({url:started.previewUrl,scenarios,timeoutMs:120000});const results=native.results||[],consoleErrors=native.consoleErrors||[],network=native.network||[],screenshots=(native.screenshots||[]).map((item:any)=>({...item,sha256:canonicalSha256(item.base64||'')}));const domSnapshots=(native.domSnapshots||[]).map((item:any)=>({...item,sha256:canonicalSha256(item.html||'')}));const reasons=[...(native.reasons||[])];for(const result of results)if(!result.passed)reasons.push(`BROWSER_E2E_SCENARIO_FAILED:${result.scenarioId}`);if(consoleErrors.length)reasons.push(`BROWSER_CONSOLE_ERRORS:${consoleErrors.length}`);for(const shot of screenshots){const scenario=scenarios.find(item=>item.scenarioId===shot.scenarioId);if(scenario?.baselineScreenshotBase64&&Number(shot.differenceRatio||0)>Number(scenario.maxPixelDifferenceRatio??0.01))reasons.push(`SCREENSHOT_DIFFERENCE_EXCEEDED:${shot.scenarioId}:${shot.differenceRatio}`);}const evidence:any={passed:reasons.length===0,required:true,workspaceId:input.workspaceId,candidateSha256:input.candidateSha256,previewUrl:started.previewUrl,environmentFingerprint,repositoryRevision,results,consoleErrors,network,screenshots,domSnapshots,reasons};const trace=await this.traceZip(evidence);evidence.traceZipBase64=trace.base64;evidence.traceZipSha256=trace.sha256;const now=Date.now();const proof:RuntimeProof={proofId:`RTP-${canonicalSha256(evidence).slice(0,24)}`,capability:'BROWSER_E2E_CANDIDATE',level:'DEVICE',passed:evidence.passed,status:evidence.passed?'SAFE':'UNSAFE',environmentFingerprint,repositoryRevision,evidenceHash:canonicalSha256(evidence),observedAt:now,expiresAt:now+86400000,reasons,details:evidence};capabilityProofRegistryService.record('BROWSER_E2E_CANDIDATE','android-independent-webview',proof,[]);return evidence;}finally{await callSelfCodeApi('/api/self-code/candidate-preview/stop',{method:'POST',body:{workspaceId:input.workspaceId}});}}
 private loadScenarios(files:Array<{path:string;content:string}>):CandidateE2EScenario[]{const configured=files.find(file=>/(^|\/)browser-e2e\.scenarios\.json$/i.test(file.path));if(configured){try{const value=JSON.parse(configured.content);if(Array.isArray(value)&&value.length)return value;}catch{}}return [{scenarioId:'AUTO-SMOKE',name:'Candidate UI smoke',path:'/',steps:[{type:'ASSERT_VISIBLE',selector:'body'},{type:'ASSERT_NO_CONSOLE_ERRORS'}]}];}
 private async traceZip(evidence:any){const zip=new JSZip();zip.file('trace/manifest.json',JSON.stringify({formatVersion:1,workspaceId:evidence.workspaceId,candidateSha256:evidence.candidateSha256,createdAt:new Date().toISOString()},null,2));zip.file('trace/results.json',JSON.stringify(evidence.results,null,2));zip.file('trace/console.json',JSON.stringify(evidence.consoleErrors,null,2));zip.file('trace/network.json',JSON.stringify(evidence.network,null,2));for(const item of evidence.domSnapshots)zip.file(`trace/dom/${item.scenarioId}.html`,item.html);for(const item of evidence.screenshots)zip.file(`trace/screenshots/${item.scenarioId}.png`,item.base64,{base64:true});const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return {base64:btoa(binary),sha256:canonicalSha256(Array.from(bytes))};}
 private fail(input:any,environmentFingerprint:string,reasons:string[]):CandidateBrowserE2EEvidence{return {passed:false,required:true,workspaceId:input.workspaceId,candidateSha256:input.candidateSha256,environmentFingerprint,repositoryRevision:input.candidateSha256,results:[],consoleErrors:[],network:[],screenshots:[],domSnapshots:[],reasons};}}
export const candidateBrowserE2EOrchestratorService=new CandidateBrowserE2EOrchestratorService();
