import ts from 'typescript';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import type { FeatureIntegrationPatchCandidate } from './featureArtifactWiringService';
export interface AppliedIntegrationPatch { patchId:string; targetPath:string; baselineSha256:string; candidateSha256:string; candidateContent:string; reasons:string[]; }
class IntegrationPatchAstApplierService {
 public apply(patch:FeatureIntegrationPatchCandidate,baselineContent:string,expectedSha256:string):AppliedIntegrationPatch{
  const actual=canonicalSha256(baselineContent);const reasons:string[]=[];if(actual!==expectedSha256)reasons.push('INTEGRATION_BASELINE_SHA_MISMATCH');
  const kind=patch.targetPath.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS;const source=ts.createSourceFile(patch.targetPath,baselineContent,ts.ScriptTarget.Latest,true,kind);
  if(this.parseDiagnostics(source).length)reasons.push('INTEGRATION_BASELINE_PARSE_FAILED');if(baselineContent.includes(patch.registrationStatement))reasons.push('INTEGRATION_PATCH_ALREADY_APPLIED');
  let updated=source;if(reasons.length===0){updated=patch.target==='CORE_COMMAND'?this.applyCore(source,patch,reasons):this.applyReact(source,patch,reasons);updated=this.addImport(updated,patch.importStatement,reasons);}
  const candidate=ts.createPrinter({newLine:ts.NewLineKind.LineFeed}).printFile(updated);const check=ts.createSourceFile(patch.targetPath,candidate,ts.ScriptTarget.Latest,true,kind);if(this.parseDiagnostics(check).length)reasons.push('INTEGRATION_CANDIDATE_PARSE_FAILED');
  return {patchId:patch.patchId,targetPath:patch.targetPath,baselineSha256:actual,candidateSha256:canonicalSha256(candidate),candidateContent:candidate,reasons:[...new Set(reasons)]};
 }
 private applyCore(source:ts.SourceFile,patch:FeatureIntegrationPatchCandidate,reasons:string[]):ts.SourceFile{const parsed=ts.createSourceFile('case.ts',`switch(command){${patch.registrationStatement}}`,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);let caseClause:ts.CaseClause|undefined;const find=(node:ts.Node)=>{if(ts.isCaseClause(node))caseClause=node;ts.forEachChild(node,find);};find(parsed);if(!caseClause){reasons.push('CORE_CASE_PARSE_FAILED');return source;}let applied=false;const transformer:ts.TransformerFactory<ts.SourceFile>=context=>root=>{const visit=(node:ts.Node):ts.VisitResult<ts.Node>=>{if(!applied&&ts.isSwitchStatement(node)){applied=true;return ts.factory.updateSwitchStatement(node,node.expression,ts.factory.updateCaseBlock(node.caseBlock,[...node.caseBlock.clauses,caseClause!]));}return ts.visitEachChild(node,visit,context);};return ts.visitNode(root,visit) as ts.SourceFile;};const result=ts.transform(source,[transformer]);const output=result.transformed[0];result.dispose();if(!applied)reasons.push('CORE_SWITCH_NOT_FOUND');return output;}
 private applyReact(source:ts.SourceFile,patch:FeatureIntegrationPatchCandidate,reasons:string[]):ts.SourceFile{const parsed=ts.createSourceFile('jsx.tsx',`const x=()=>(${patch.registrationStatement});`,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let element:ts.JsxElement|ts.JsxSelfClosingElement|undefined;const find=(node:ts.Node)=>{if(!element&&(ts.isJsxElement(node)||ts.isJsxSelfClosingElement(node)))element=node;ts.forEachChild(node,find);};find(parsed);if(!element){reasons.push('REACT_JSX_PARSE_FAILED');return source;}let applied=false;const transformer:ts.TransformerFactory<ts.SourceFile>=context=>root=>{const visit=(node:ts.Node):ts.VisitResult<ts.Node>=>{if(!applied&&ts.isReturnStatement(node)&&node.expression&&(ts.isJsxElement(node.expression)||ts.isJsxSelfClosingElement(node.expression)||ts.isJsxFragment(node.expression))){applied=true;const fragment=ts.factory.createJsxFragment(ts.factory.createJsxOpeningFragment(),[node.expression,element!],ts.factory.createJsxJsxClosingFragment());return ts.factory.updateReturnStatement(node,fragment);}return ts.visitEachChild(node,visit,context);};return ts.visitNode(root,visit) as ts.SourceFile;};const result=ts.transform(source,[transformer]);const output=result.transformed[0];result.dispose();if(!applied)reasons.push('REACT_RETURN_JSX_NOT_FOUND');return output;}
 private addImport(source:ts.SourceFile,text:string,reasons:string[]):ts.SourceFile{const parsed=ts.createSourceFile('import.ts',text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);const declaration=parsed.statements.find(ts.isImportDeclaration);if(!declaration){reasons.push('INTEGRATION_IMPORT_PARSE_FAILED');return source;}const module=(declaration.moduleSpecifier as ts.StringLiteral).text;if(source.statements.some(item=>ts.isImportDeclaration(item)&&(item.moduleSpecifier as ts.StringLiteral).text===module))return source;return ts.factory.updateSourceFile(source,[declaration,...source.statements]);}
 private parseDiagnostics(source:ts.SourceFile):readonly ts.Diagnostic[]{return (source as ts.SourceFile&{parseDiagnostics:readonly ts.Diagnostic[]}).parseDiagnostics||[];}
}
export const integrationPatchAstApplierService=new IntegrationPatchAstApplierService();
