import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
export interface ItemDefinition { name:string; key:string; attributes:Record<string,string|number|boolean>; }
export interface ItemFamilyExpansionPlan { planId:string; familyName:string; items:ItemDefinition[]; affectedPaths:string[]; updateCategories:string[]; proposedNames:string[]; acceptanceChecks:string[]; reasons:string[]; }
class ItemFamilyExpansionPlannerService {
 public plan(instruction:string,explicitNames:string[]=[]):ItemFamilyExpansionPlan {const family=this.family(instruction);const count=this.count(instruction);const files=selfCodeSpaceService.listSourceFiles();const terms=[family,...explicitNames].filter(Boolean);const affected=files.filter(file=>terms.some(term=>file.path.toLowerCase().includes(term.toLowerCase())||file.content.toLowerCase().includes(term.toLowerCase()))).map(file=>file.path).slice(0,100);const proposedNames=explicitNames.length===count?explicitNames:Array.from({length:count},(_,index)=>`${family || 'Item'}_${String(index+1).padStart(2,'0')}`);const items=proposedNames.map(name=>({name,key:name.replace(/[^A-Za-z0-9_\u3040-\u30ff\u3400-\u9fff]+/g,'_').toUpperCase(),attributes:{enabled:true}}));const categories=['TYPE_OR_SCHEMA','MASTER_DATA','FACTORY_OR_REGISTRY','UI_LABEL_OR_ICON','BALANCE_OR_RULES','PERSISTENCE','SERIALIZATION','TEST_FIXTURE','LOCALIZATION'];const reasons:string[]=[];if(!family)reasons.push('ITEM_FAMILY_NOT_RESOLVED');if(count<=0)reasons.push('ITEM_COUNT_NOT_RESOLVED');return {planId:`ITEMEXP-${canonicalSha256({instruction,family,items,affected}).slice(0,24)}`,familyName:family,items,affectedPaths:affected,updateCategories:categories,proposedNames,acceptanceChecks:[`追加数が${count}件である`,'全Item Keyが一意','Registryから全Itemを生成可能','保存・読込Round Trip','UI表示名が欠落しない','既存Itemの回帰なし'],reasons}; }
 private count(value:string):number {const match=value.match(/([0-9０-９]+)\s*種類/);if(match)return Number(match[1].replace(/[０-９]/g,char=>String(char.charCodeAt(0)-0xfee0)));const kanji:Record<string,number>={'一':1,'二':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9,'十':10};for(const [key,count] of Object.entries(kanji))if(value.includes(`${key}種類`))return count;return 0;}
 private family(value:string):string {const match=value.match(/(?:こういう感じの|同系統の|既存の)?\s*([A-Za-z0-9_\u3040-\u30ff\u3400-\u9fff]+?)\s*(?:を|の)?\s*[0-9０-９一二三四五六七八九十]+種類/);return match?.[1]?.replace(/^(こういう感じの|同系統の|既存の)/,'')||'';}
}
export const itemFamilyExpansionPlannerService=new ItemFamilyExpansionPlannerService();
