import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
import { componentCompositionService } from '../../capability/services/componentCompositionService';
export type DevelopmentIntentKind='ITEM_EXPANSION'|'DATA_ARCHITECTURE'|'BUG_FIX'|'REFACTOR'|'UI_FEATURE'|'PERSISTENCE'|'API_CHANGE'|'TESTING'|'PERFORMANCE'|'SECURITY'|'ASSET_CHANGE'|'GENERIC_FEATURE';
export interface DevelopmentIntent { kind:DevelopmentIntentKind; confidence:number; evidence:string[]; quantity?:number; entities:string[]; targetPaths:string[]; }
export interface NaturalLanguageDevelopmentUnderstanding { understandingId:string; normalizedText:string; intents:DevelopmentIntent[]; primary:DevelopmentIntent; ambiguities:string[]; repositoryEvidence:string[]; compositionPlanId?:string; }
const lexicon:Record<DevelopmentIntentKind,string[]>={ITEM_EXPANSION:['アイテム','種類増','種類追加','同系統','バリエーション','item','weapon','potion','装備','キャラ','敵を追加'],DATA_ARCHITECTURE:['データ構造','schema','モデル改善','正規化','migration','永続化形式','保存形式','拡張しやす'],BUG_FIX:['修正','直して','不具合','バグ','エラー','動かない','壊れる','fix'],REFACTOR:['リファクタ','整理','共通化','重複削除','読みやす','保守性','設計改善'],UI_FEATURE:['画面','UI','ボタン','表示','フォーム','レイアウト','操作'],PERSISTENCE:['保存','読込','再起動','永続化','store','serializer'],API_CHANGE:['API','route','endpoint','payload','request','response'],TESTING:['テスト','検証','coverage','回帰'],PERFORMANCE:['高速','遅い','性能','最適化','メモリ','キャッシュ'],SECURITY:['安全','権限','認証','秘密','脆弱','検証'],ASSET_CHANGE:['画像','アイコン','音声','asset','png','unity','unreal'],GENERIC_FEATURE:['追加','機能','できるよう','対応','実装']};
class NaturalLanguageDevelopmentIntentService {
 public understand(text:string,targetPaths:string[]=[]):NaturalLanguageDevelopmentUnderstanding {const normalizedText=text.normalize('NFKC').replace(/\s+/g,' ').trim();const files=selfCodeSpaceService.listSourceFiles();const intents=(Object.keys(lexicon) as DevelopmentIntentKind[]).map(kind=>this.score(kind,normalizedText,targetPaths,files)).filter(intent=>intent.confidence>=0.2).sort((a,b)=>b.confidence-a.confidence);if(!intents.length)intents.push({kind:'GENERIC_FEATURE',confidence:0.2,evidence:['FALLBACK'],entities:this.entities(normalizedText),targetPaths:[...targetPaths]});const primary=intents[0];const ambiguities:string[]=[];if(intents.length>1&&Math.abs(intents[0].confidence-intents[1].confidence)<0.08)ambiguities.push(`PRIMARY_INTENT_CLOSE:${intents[0].kind}:${intents[1].kind}`);if(primary.kind==='ITEM_EXPANSION'&&!primary.quantity)ambiguities.push('ITEM_QUANTITY_UNRESOLVED');const repositoryEvidence=[...new Set(intents.flatMap(intent=>intent.targetPaths))].slice(0,50);const composition=componentCompositionService.compose(normalizedText,6,[],undefined);return {understandingId:`NLU-${canonicalSha256({normalizedText,intents,repositoryEvidence}).slice(0,24)}`,normalizedText,intents,primary,ambiguities,repositoryEvidence,compositionPlanId:composition?.plan_id}; }
 private score(kind:DevelopmentIntentKind,text:string,targetPaths:string[],files:Array<{path:string;content:string}>):DevelopmentIntent {const lower=text.toLowerCase();const hits=lexicon[kind].filter(term=>lower.includes(term.toLowerCase()));const entities=this.entities(text);const targets=files.filter(file=>targetPaths.includes(file.path)||entities.some(entity=>file.path.toLowerCase().includes(entity.toLowerCase())||file.content.toLowerCase().includes(entity.toLowerCase()))).map(file=>file.path).slice(0,30);const repositoryBoost=Math.min(0.2,targets.length*0.02);const confidence=Math.min(1,hits.length*0.24+repositoryBoost+(kind==='GENERIC_FEATURE'?0.05:0));return {kind,confidence,evidence:[...hits,...targets.slice(0,5).map(path=>`REPO:${path}`)],quantity:this.quantity(text),entities,targetPaths:[...new Set([...targetPaths,...targets])]}; }
 private quantity(text:string):number|undefined {const digit=text.match(/([0-9０-９]+)\s*(?:種類|個|件|つ|人|体)/);if(digit)return Number(digit[1].replace(/[０-９]/g,char=>String(char.charCodeAt(0)-0xfee0)));const map:Record<string,number>={一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10};for(const [key,value] of Object.entries(map))if(new RegExp(`${key}(?:種類|個|件|つ|人|体)`).test(text))return value;return undefined; }
 private entities(text:string):string[] {return [...new Set((text.match(/[A-Za-z_][A-Za-z0-9_]{2,}|[\u3040-\u30ff\u3400-\u9fff]{2,}/g)||[]).filter(value=>!['追加して','実装して','できるよう','もっと','さらに','既存の','新しい'].includes(value)).slice(0,20))]; }
}
export const naturalLanguageDevelopmentIntentService=new NaturalLanguageDevelopmentIntentService();
