import { canonicalSha256 } from '../../core/services/canonicalSha256Service';import { callSelfCodeApi,isApiFailure } from './selfCodeApiClient';
export type RuntimeAdapterKind='BROWSER'|'BENCHMARK'|'MOCK_API'|'SECURITY_SANDBOX'|'TEST_DB'|'MULTI_REPOSITORY_BUILD';
class RuntimeAdapterService{async run(kind:RuntimeAdapterKind,input:any){const startedAt=Date.now();if(kind==='BENCHMARK')return this.benchmark(input,startedAt);if(kind==='MOCK_API')return this.mockApi(input,startedAt);if(kind==='SECURITY_SANDBOX')return this.security(input,startedAt);if(kind==='TEST_DB')return this.testDb(input,startedAt);const endpoint=kind==='BROWSER'?'/api/self-code/browser-gate':'/api/self-code/multi-repository-build';const response=await callSelfCodeApi<any>(endpoint,{method:'POST',body:input});if(isApiFailure(response))return {passed:false,kind,reasons:[response.reason],evidenceId:`RTA-${canonicalSha256({kind,input,reasons:[response.reason]}).slice(0,20)}`};return {passed:response.success!==false,kind,result:response,reasons:[],durationMs:Date.now()-startedAt,evidenceId:`RTA-${canonicalSha256({kind,response}).slice(0,20)}`};}
 private benchmark(input:any,startedAt:number){const values=(input.samples||[]).map(Number).sort((a:number,b:number)=>a-b);if(!values.length)return {passed:false,kind:'BENCHMARK',reasons:['BENCHMARK_SAMPLES_REQUIRED']};const percentile=(p:number)=>values[Math.min(values.length-1,Math.floor((values.length-1)*p))];const result={median:percentile(.5),p95:percentile(.95),peakMemory:Number(input.peakMemory||0)};return {passed:true,kind:'BENCHMARK',result,durationMs:Date.now()-startedAt,reasons:[],evidenceId:`RTA-${canonicalSha256(result).slice(0,20)}`};}
 private mockApi(input:any,startedAt:number){const scenarios=['200','400','401','403','404','429','500','TIMEOUT'];const results=scenarios.map(status=>({status,handled:Array.isArray(input.handledStatuses)&&input.handledStatuses.includes(status)}));return {passed:results.every(row=>row.handled),kind:'MOCK_API',result:results,durationMs:Date.now()-startedAt,reasons:results.filter(row=>!row.handled).map(row=>`UNHANDLED:${row.status}`),evidenceId:`RTA-${canonicalSha256(results).slice(0,20)}`};}
 private security(input:any,startedAt:number){const attacks=['__proto__','<script>','../','OR 1=1','oversized'];const rejected=attacks.filter(value=>String(input.guard?.(value)??false)==='false');return {passed:rejected.length===attacks.length,kind:'SECURITY_SANDBOX',result:{attacks,rejected},durationMs:Date.now()-startedAt,reasons:rejected.length===attacks.length?[]:['COUNTEREXAMPLE_ACCEPTED'],evidenceId:`RTA-${canonicalSha256(rejected).slice(0,20)}`};}
 private testDb(input:any,startedAt:number){let value=structuredClone(input.baseline);try{const migrated=input.forward(value);const restored=input.rollback(structuredClone(migrated));const passed=canonicalSha256(restored)===canonicalSha256(input.baseline);return {passed,kind:'TEST_DB',result:{migratedHash:canonicalSha256(migrated),restoredHash:canonicalSha256(restored)},durationMs:Date.now()-startedAt,reasons:passed?[]:['ROUNDTRIP_MISMATCH'],evidenceId:`RTA-${canonicalSha256({migrated,restored}).slice(0,20)}`};}catch(error){return {passed:false,kind:'TEST_DB',reasons:[error instanceof Error?error.message:String(error)]};}}
}
export const runtimeAdapterService=new RuntimeAdapterService();
