import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
export type EnforcementLevel='KERNEL'|'PROCESS'|'APPLICATION'|'OBSERVATIONAL'|'NONE';
export interface SemanticIntentFrame{frameId:string;actor:string;target:string;currentProblem:string;desiredState:string;requiredBehaviors:string[];forbiddenBehaviors:string[];preconditions:string[];postconditions:string[];invariants:string[];sideEffects:string[];dependencies:string[];failureSemantics:string[];evidenceRequirements:string[];acceptanceCriteria:string[];}
class SemanticApplicationEnforcementService{
 frame(text:string):SemanticIntentFrame{const clauses=text.split(/[\n。]/).map(x=>x.trim()).filter(Boolean);const negative=clauses.filter(x=>/してはいけ|禁止|壊さず|変更せず|使わず|not |without /i.test(x));const required=clauses.filter(x=>/必要|する|追加|実装|確認|生成|検証|must|should/i.test(x)&&!negative.includes(x));const target=(text.match(/(?:対象|target)[:：]?\s*([^\n。]+)/i)?.[1]||'CANDIDATE').trim();const base={actor:'MIKI_CORE',target,currentProblem:clauses[0]||text,desiredState:clauses.at(-1)||text,requiredBehaviors:required,forbiddenBehaviors:negative,preconditions:clauses.filter(x=>/前提|場合|when|if /i.test(x)),postconditions:clauses.filter(x=>/完了|成功|結果|after/i.test(x)),invariants:negative.filter(x=>/壊さず|維持|不変|変更せず/i.test(x)),sideEffects:clauses.filter(x=>/更新|書込|送信|保存|削除/i.test(x)),dependencies:clauses.filter(x=>/依存|必要|接続/i.test(x)),failureSemantics:['FAIL_CLOSED','NO_REVIEW_ZIP_ON_UNMET_CONTRACT'],evidenceRequirements:['CANDIDATE_SHA','WORKSPACE_ID','CONTRACT_HASH','POSTCONDITION_EVIDENCE'],acceptanceCriteria:clauses.filter(x=>/完成条件|合格|PASS|成功/i.test(x))};return {...base,frameId:`SIF-${canonicalSha256(base).slice(0,24)}`};}
 compile(frame:SemanticIntentFrame){const contracts={intent:{actor:frame.actor,target:frame.target,desiredState:frame.desiredState,forbidden:frame.forbiddenBehaviors},behavioral:{required:frame.requiredBehaviors,preconditions:frame.preconditions,postconditions:frame.postconditions,sideEffects:frame.sideEffects},structural:{dependencies:frame.dependencies,evidence:frame.evidenceRequirements},operational:{failureSemantics:frame.failureSemantics,invariants:frame.invariants}};return {contractId:`SC-${canonicalSha256(contracts).slice(0,24)}`,contracts,contractHash:canonicalSha256(contracts)};}
 enforcement(input:{kernelAvailable:boolean;processIsolation:boolean;applicationChecks:boolean;observability:boolean;operationRisk:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';operation:string}){const level:EnforcementLevel=input.kernelAvailable?'KERNEL':input.processIsolation?'PROCESS':input.applicationChecks?'APPLICATION':input.observability?'OBSERVATIONAL':'NONE';const forbiddenWithoutKernel=/PROMOTE_CANONICAL|MODIFY_RUNNING_CODE|EXECUTE_UNKNOWN_BINARY|ROOT_OPERATION|UNBOUNDED_SHELL|SECRET_STORE_ACCESS/.test(input.operation);const allowed=level!=='NONE'&&!((input.operationRisk==='CRITICAL'||forbiddenWithoutKernel)&&level!=='KERNEL');const reasons:string[]=[];if(level==='NONE')reasons.push('APPLICATION_ENFORCEMENT_UNAVAILABLE');if(!allowed&&forbiddenWithoutKernel)reasons.push('OPERATION_REQUIRES_KERNEL_ENFORCEMENT');if(level!=='KERNEL')reasons.push(`ENFORCEMENT_DOWNGRADED_TO_${level}`);return {level,allowed,reasons,claimableGuarantees:this.guarantees(level)};}
 capabilityToken(input:{workspaceId:string;candidateSha256:string;allowedOperations:string[];deniedOperations:string[];ttlMs:number}){const issuedAt=Date.now();const base={...input,issuedAt,expiresAt:issuedAt+input.ttlMs,nonce:canonicalSha256({issuedAt,input})};return {...base,tokenId:`CAP-${canonicalSha256(base).slice(0,24)}`};}
 authorize(token:ReturnType<SemanticApplicationEnforcementService['capabilityToken']>,operation:string,workspaceId:string,candidateSha256:string){const reasons:string[]=[];if(token.expiresAt<=Date.now())reasons.push('CAPABILITY_TOKEN_EXPIRED');if(token.workspaceId!==workspaceId)reasons.push('CAPABILITY_WORKSPACE_MISMATCH');if(token.candidateSha256!==candidateSha256)reasons.push('CAPABILITY_CANDIDATE_MISMATCH');if(token.deniedOperations.includes(operation)||!token.allowedOperations.includes(operation))reasons.push('CAPABILITY_OPERATION_DENIED');return {allowed:reasons.length===0,reasons};}
 changeGraph(frame:SemanticIntentFrame,contractId:string,items:Array<{kind:string;id:string;relations:string[]}>){const nodes=[{id:frame.frameId,kind:'REQUIREMENT'},{id:contractId,kind:'CONTRACT'},...items];const edges=[{from:frame.frameId,to:contractId,relation:'COMPILES_TO'},...items.flatMap(item=>item.relations.map(relation=>({from:contractId,to:item.id,relation})) )];return {graphId:`SCG-${canonicalSha256({nodes,edges}).slice(0,24)}`,nodes,edges};}
 contradictions(frame:SemanticIntentFrame,actual:{target:string;ordering:string[];sideEffects:string[];failurePolicy:string;evidence:string[];enforcementLevel:EnforcementLevel}){const contradictions:string[]=[];if(actual.target!==frame.target)contradictions.push('TARGET_CONTRADICTION');for(const forbidden of frame.forbiddenBehaviors)if(actual.sideEffects.some(x=>forbidden.includes(x)||x.includes(forbidden)))contradictions.push('SIDE_EFFECT_CONTRADICTION');if(frame.failureSemantics.includes('FAIL_CLOSED')&&!/FAIL_CLOSED/.test(actual.failurePolicy))contradictions.push('FAILURE_POLICY_CONTRADICTION');for(const e of frame.evidenceRequirements)if(!actual.evidence.includes(e))contradictions.push(`EVIDENCE_CONTRADICTION:${e}`);if(actual.enforcementLevel!=='KERNEL'&&actual.evidence.includes('KERNEL_ISOLATED'))contradictions.push('SECURITY_ASSUMPTION_CONTRADICTION');return [...new Set(contradictions)];}
 counterexamples(frame:SemanticIntentFrame){return [...frame.preconditions.map(x=>`PRECONDITION_FALSE:${x}`),...frame.evidenceRequirements.map(x=>`EVIDENCE_MISSING:${x}`),'CANDIDATE_SHA_CHANGED','WORKSPACE_EXPIRED','CLEANUP_FAILED','EVIDENCE_HASH_MISMATCH','STALE_BASELINE_USED'];}
 private guarantees(level:EnforcementLevel){const map:Record<EnforcementLevel,string[]>={KERNEL:['OS_RESOURCE_BOUNDARY','FILESYSTEM_BOUNDARY','PROCESS_BOUNDARY','APPLICATION_POLICY'],PROCESS:['PROCESS_BOUNDARY','WORKING_DIRECTORY_BOUNDARY','APPLICATION_POLICY'],APPLICATION:['IDENTITY_CHECKS','HASH_CHECKS','OPERATION_ALLOWLIST','REVIEW_GATE'],OBSERVATIONAL:['AUDIT_ONLY'],NONE:[]};return map[level];}}
export const semanticApplicationEnforcementService=new SemanticApplicationEnforcementService();
