import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
export type FailureClass='ENVIRONMENT'|'DEPENDENCY'|'SOURCE'|'SEMANTIC'|'TRANSFORMATION'|'VALIDATION'|'TEST'|'RUNTIME'|'RESOURCE'|'PERMISSION'|'SECURITY'|'NETWORK'|'PERSISTENCE'|'CONCURRENCY'|'REVIEW_PACKAGE'|'DEVICE';
export interface UnifiedFailure{failureId:string;failureClass:FailureClass;failureCode:string;stage:string;retryable:boolean;repairable:boolean;userActionRequired:boolean;environmentActionRequired:boolean;candidateSha256?:string;workspaceId?:string;jobId?:string;repositoryRevision?:string;firstObservedAt:number;lastObservedAt:number;occurrenceCount:number;relatedEvidenceIds:string[];recommendedNextAction:string;diagnosticSignature:string;details:Record<string,unknown>;}
const KEY='miki_unified_failure_taxonomy_v1';
class UnifiedFailureTaxonomyService{
 classify(input:{code?:string;message?:string;stdout?:string;stderr?:string;stage:string;candidateSha256?:string;workspaceId?:string;jobId?:string;repositoryRevision?:string;evidenceIds?:string[];targetFiles?:string[];symbol?:string;testName?:string;stack?:string;environmentFingerprint?:string;details?:Record<string,unknown>}):UnifiedFailure{const text=`${input.code||''}\n${input.message||''}\n${input.stdout||''}\n${input.stderr||''}`;const mapped=this.map(text,input.code);const signature=canonicalSha256({failureClass:mapped.failureClass,failureCode:mapped.failureCode,targetFiles:[...(input.targetFiles||[])].sort(),symbol:input.symbol,testName:input.testName,stack:this.normalizeStack(input.stack||text),environmentFingerprint:input.environmentFingerprint,candidateSha256:input.candidateSha256});const existing=this.list().find(f=>f.diagnosticSignature===signature&&f.workspaceId===input.workspaceId);const now=Date.now();const failure:UnifiedFailure={failureId:existing?.failureId||`FAIL-${signature.slice(0,24)}`,failureClass:mapped.failureClass,failureCode:mapped.failureCode,stage:input.stage,retryable:mapped.retryable,repairable:mapped.repairable,userActionRequired:mapped.userActionRequired,environmentActionRequired:mapped.environmentActionRequired,candidateSha256:input.candidateSha256,workspaceId:input.workspaceId,jobId:input.jobId,repositoryRevision:input.repositoryRevision,firstObservedAt:existing?.firstObservedAt||now,lastObservedAt:now,occurrenceCount:(existing?.occurrenceCount||0)+1,relatedEvidenceIds:[...new Set([...(existing?.relatedEvidenceIds||[]),...(input.evidenceIds||[])])],recommendedNextAction:mapped.next,diagnosticSignature:signature,details:{...(input.details||{}),message:input.message,targetFiles:input.targetFiles,symbol:input.symbol,testName:input.testName}};this.save(failure);return failure;}
 route(failure:UnifiedFailure){if(failure.userActionRequired)return 'WAITING_USER';if(failure.environmentActionRequired)return failure.retryable?'ENVIRONMENT_RECOVERY':'WAITING_RESOURCE';if(failure.repairable)return 'CANDIDATE_REPAIR';if(failure.retryable)return 'RETRY';return 'PERMANENT_STOP';}
 list():UnifiedFailure[]{try{const v=JSON.parse(storageService.getItem(KEY)||'[]');return Array.isArray(v)?v:[];}catch{return [];}}
 private save(failure:UnifiedFailure){storageService.setItem(KEY,JSON.stringify([failure,...this.list().filter(f=>f.failureId!==failure.failureId)].slice(0,5000)));}
 private normalizeStack(value:string){return value.replace(/\b0x[a-f\d]+\b/gi,'<ADDR>').replace(/:\d+:\d+/g,':<LINE>:<COL>').replace(/\b\d{4}-\d\d-\d\d[T ][\d:.Z+-]+\b/g,'<TIME>').replace(/\/[^\s)]+/g,'<PATH>').split('\n').slice(0,30).map(x=>x.trim()).filter(Boolean).sort().join('\n');}
 private map(text:string,code?:string){const rows:Array<[RegExp,FailureClass,string,boolean,boolean,boolean,boolean,string]>=[[/E503|ECONNRESET|registry.*unavailable|REGISTRY_UNAVAILABLE/i,'NETWORK','REGISTRY_UNAVAILABLE',true,false,false,true,'Retry after registry health changes or use verified offline cache'],[/Cannot find module|MODULE_NOT_FOUND|MISSING_DEPENDENCY/i,'DEPENDENCY','MISSING_DEPENDENCY',false,false,false,true,'Restore dependencies from lockfile or verified cache'],[/lockfile|npm ci.*package-lock|LOCKFILE_MISMATCH/i,'DEPENDENCY','LOCKFILE_MISMATCH',false,false,false,true,'Repair lockfile in candidate environment and review the diff'],[/engine.*node|Node.*version|TOOLCHAIN_VERSION_MISMATCH/i,'ENVIRONMENT','TOOLCHAIN_VERSION_MISMATCH',false,false,false,true,'Use the repository-pinned toolchain version'],[/ERESOLVE|peer dependency|PEER_DEPENDENCY_CONFLICT/i,'DEPENDENCY','PEER_DEPENDENCY_CONFLICT',false,false,false,true,'Resolve peer dependency using locked compatible versions'],[/ENOSPC|no space left|DISK_SPACE/i,'RESOURCE','DISK_SPACE_INSUFFICIENT',false,false,false,true,'Free workspace disk or increase quota'],[/heap out of memory|ENOMEM|MEMORY_LIMIT/i,'RESOURCE','MEMORY_LIMIT_EXCEEDED',false,false,false,true,'Increase bounded memory or reduce wave scope'],[/TIMEOUT|timed out|PROCESS_TIMEOUT/i,'RUNTIME','PROCESS_TIMEOUT',true,false,false,true,'Retry only after timeout or workload conditions change'],[/error TS\d+|TYPECHECK_FAILED/i,'VALIDATION','TYPECHECK_FAILED',false,true,false,false,'Repair affected candidate symbols and rerun typecheck'],[/test.*fail|TEST_FAILED|AssertionError/i,'TEST','TEST_FAILED',false,true,false,false,'Repair candidate or test contract after classifying flakiness'],[/assert|RUNTIME_ASSERTION_FAILED/i,'RUNTIME','RUNTIME_ASSERTION_FAILED',false,true,false,false,'Repair candidate behavior and rerun the failing scenario'],[/permission denied|EACCES|EPERM/i,'PERMISSION','PERMISSION_DENIED',false,false,false,true,'Correct workspace permission without changing candidate code'],[/security|auth.*fail|secret/i,'SECURITY','SECURITY_POLICY_FAILED',false,true,true,false,'Resolve the security contract or request human review'],[/manifest.*missing|zip.*mismatch|REVIEW_PACKAGE/i,'REVIEW_PACKAGE','REVIEW_PACKAGE_INVALID',false,true,false,false,'Regenerate package from sealed candidate evidence'],[/stale|revision mismatch|SHA_MISMATCH/i,'CONCURRENCY','STALE_REVISION',false,false,false,false,'Discard stale candidate and replan from current revision']];for(const row of rows)if(row[0].test(`${code||''}\n${text}`))return {failureClass:row[1],failureCode:row[2],retryable:row[3],repairable:row[4],userActionRequired:row[5],environmentActionRequired:row[6],next:row[7]};return {failureClass:'SOURCE' as FailureClass,failureCode:code||'UNCLASSIFIED_FAILURE',retryable:false,repairable:true,userActionRequired:false,environmentActionRequired:false,next:'Inspect source-level evidence and produce a bounded repair candidate'};}}
export const unifiedFailureTaxonomyService=new UnifiedFailureTaxonomyService();
