import type { NativeOperationKind } from './nativeOperationContractService';

export interface NativeOperationExecutionOptions<T=unknown> {
  requestId?:string;
  timeoutMs?:number;
  signal?:AbortSignal;
  inputSha256?:string;
  idempotencyKey?:string;
  validateOutput?:(value:T)=>void;
}
interface CircuitState { failures:number; openedAt?:number; }
interface OperationMetrics { started:number;completed:number;failed:number;cancelled:number;timedOut:number;deduplicated:number;totalDurationMs:number;recentDurations:number[]; }
const MAX_GLOBAL_CONCURRENCY=4;const OPERATION_CONCURRENCY:Partial<Record<NativeOperationKind,number>>={HEALTH:4,COMPARE_REVISIONS:3,GIT_BLOB_SHA:3,HASH_FILES:2,SEARCH_TEXT:2,VERIFY_ARTIFACTS:2,SCAN_REPOSITORY:1,BUILD_ZIP:1,COPY_ZIPTXT:1};const MAX_OPERATION_CONCURRENCY=2,CIRCUIT_FAILURE_THRESHOLD=3,CIRCUIT_COOLDOWN_MS=30_000,MIN_TIMEOUT_MS=1_000,MAX_TIMEOUT_MS=30*60_000,IDEMPOTENCY_TTL_MS=5*60_000,MAX_METADATA_ENTRIES=24,MAX_METADATA_TEXT=512;
class NativeOperationRuntimePolicyService {
  private activeGlobal=0;private readonly activeByOperation=new Map<NativeOperationKind,number>();private readonly circuits=new Map<NativeOperationKind,CircuitState>();private readonly metrics=new Map<NativeOperationKind,OperationMetrics>();private readonly activeRequests=new Set<string>();private readonly idempotency=new Map<string,{expiresAt:number;promise:Promise<unknown>}>();
  createRequestId(operation:NativeOperationKind):string { const uuid=globalThis.crypto?.randomUUID?.()||Math.random().toString(16).slice(2);return `NATIVE-${operation}-${Date.now()}-${uuid}`; }
  normalizeTimeout(value?:number):number { return Math.min(MAX_TIMEOUT_MS,Math.max(MIN_TIMEOUT_MS,Number.isFinite(value)?Math.trunc(value as number):30_000)); }
  adaptiveTimeout(operation:NativeOperationKind,requested?:number):number { if(requested!==undefined)return this.normalizeTimeout(requested);const recent=this.metrics.get(operation)?.recentDurations||[];if(recent.length<3)return 30_000;const sorted=[...recent].sort((a,b)=>a-b);const p95=sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))];return this.normalizeTimeout(Math.max(5_000,p95*3)); }
  validateInputSha256(value?:string):void { if(value!==undefined&&!/^[a-f0-9]{64}$/.test(value))throw new Error('NATIVE_INPUT_SHA256_INVALID'); }
  sanitizeMetadata(metadata:Record<string,string|number|boolean>):Record<string,string|number|boolean>{ const entries=Object.entries(metadata).slice(0,MAX_METADATA_ENTRIES).map(([key,value])=>[key.slice(0,80),typeof value==='string'?value.slice(0,MAX_METADATA_TEXT):value]);return Object.fromEntries(entries); }
  enter(operation:NativeOperationKind,requestId:string):()=>void { this.assertCircuitClosed(operation);if(this.activeRequests.has(requestId))throw new Error(`NATIVE_DUPLICATE_REQUEST_ID:${requestId}`);const count=this.activeByOperation.get(operation)||0;if(this.activeGlobal>=MAX_GLOBAL_CONCURRENCY)throw new Error('NATIVE_GLOBAL_CONCURRENCY_LIMIT');const operationLimit=OPERATION_CONCURRENCY[operation]||MAX_OPERATION_CONCURRENCY;if(count>=operationLimit)throw new Error(`NATIVE_OPERATION_CONCURRENCY_LIMIT:${operation}`);this.activeRequests.add(requestId);this.activeGlobal++;this.activeByOperation.set(operation,count+1);this.bump(operation,'started');let released=false;return()=>{if(released)return;released=true;this.activeRequests.delete(requestId);this.activeGlobal=Math.max(0,this.activeGlobal-1);const next=Math.max(0,(this.activeByOperation.get(operation)||1)-1);if(next===0)this.activeByOperation.delete(operation);else this.activeByOperation.set(operation,next);}; }
  assertNotCancelled(signal?:AbortSignal):void { if(signal?.aborted)throw new DOMException('Native operation cancelled','AbortError'); }
  awaitBoundary<T>(work:Promise<T>,timeoutMs:number,signal?:AbortSignal):Promise<T>{ return new Promise((resolve,reject)=>{let settled=false;const finish=(fn:()=>void)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);fn();};const abort=()=>finish(()=>reject(new DOMException('Native operation cancelled','AbortError')));const timer=setTimeout(()=>finish(()=>reject(new Error(`NATIVE_OPERATION_TIMEOUT:${timeoutMs}`))),timeoutMs);signal?.addEventListener('abort',abort,{once:true});work.then(v=>finish(()=>resolve(v)),e=>finish(()=>reject(e)));}); }
  validateIdempotencyKey(key?:string):void { if(key!==undefined&&!/^[A-Za-z0-9._:-]{1,160}$/.test(key))throw new Error('NATIVE_IDEMPOTENCY_KEY_INVALID'); }
  getIdempotent<T>(operation:NativeOperationKind,key?:string):Promise<T>|undefined { if(!key)return;this.pruneIdempotency();const hit=this.idempotency.get(key);if(hit){this.bump(operation,'deduplicated');return hit.promise as Promise<T>;} }
  putIdempotent<T>(key:string|undefined,promise:Promise<T>):void { if(!key)return;this.idempotency.set(key,{expiresAt:Date.now()+IDEMPOTENCY_TTL_MS,promise});promise.catch(()=>this.idempotency.delete(key)); }
  recordSuccess(operation:NativeOperationKind,durationMs:number):void { this.circuits.delete(operation);this.bump(operation,'completed',durationMs); }
  recordFailure(operation:NativeOperationKind,error:unknown,durationMs:number):void { const message=error instanceof Error?error.message:String(error);if(error instanceof DOMException&&error.name==='AbortError')this.bump(operation,'cancelled',durationMs);else if(message.startsWith('NATIVE_OPERATION_TIMEOUT:'))this.bump(operation,'timedOut',durationMs);else{this.bump(operation,'failed',durationMs);const state=this.circuits.get(operation)||{failures:0};state.failures++;if(state.failures>=CIRCUIT_FAILURE_THRESHOLD)state.openedAt=Date.now();this.circuits.set(operation,state);} }
  snapshot(){ return {activeGlobal:this.activeGlobal,activeRequests:[...this.activeRequests],activeByOperation:Object.fromEntries(this.activeByOperation),circuits:Object.fromEntries([...this.circuits].map(([op,s])=>[op,{...s,open:Boolean(s.openedAt&&Date.now()-s.openedAt<CIRCUIT_COOLDOWN_MS)}])),metrics:Object.fromEntries([...this.metrics].map(([op,m])=>[op,{...m,averageDurationMs:m.completed?Math.round(m.totalDurationMs/m.completed):0,p95DurationMs:this.percentile(m.recentDurations,.95)}]))}; }
  private assertCircuitClosed(operation:NativeOperationKind){const state=this.circuits.get(operation);if(!state?.openedAt)return;if(Date.now()-state.openedAt>=CIRCUIT_COOLDOWN_MS){this.circuits.delete(operation);return;}throw new Error(`NATIVE_CIRCUIT_OPEN:${operation}`);}
  private pruneIdempotency(){const now=Date.now();for(const[key,value]of this.idempotency)if(value.expiresAt<=now)this.idempotency.delete(key);}
  private percentile(values:number[],ratio:number){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor(sorted.length*ratio))];}
  private bump(operation:NativeOperationKind,key:keyof Omit<OperationMetrics,'totalDurationMs'|'recentDurations'>,duration=0){const m=this.metrics.get(operation)||{started:0,completed:0,failed:0,cancelled:0,timedOut:0,deduplicated:0,totalDurationMs:0,recentDurations:[]};m[key]++;if(duration>0){m.totalDurationMs+=duration;m.recentDurations.push(duration);if(m.recentDurations.length>100)m.recentDurations.shift();}this.metrics.set(operation,m);}
}
export const nativeOperationRuntimePolicyService=new NativeOperationRuntimePolicyService();
