export type StartupPhase='ENTRY'|'STORAGE_WAIT'|'APP_IMPORT'|'APP_RENDERED'|'FAILED';
export interface StartupDiagnostic{phase:StartupPhase;startedAt:number;updatedAt:number;message:string;error?:string;userAgent:string;}
const KEY='miki_startup_diagnostic_v1';
class StartupRecoveryService{
 private diagnostic:StartupDiagnostic={phase:'ENTRY',startedAt:Date.now(),updatedAt:Date.now(),message:'JavaScript entry loaded',userAgent:typeof navigator==='undefined'?'unknown':navigator.userAgent};
 update(phase:StartupPhase,message:string,error?:unknown):StartupDiagnostic{this.diagnostic={...this.diagnostic,phase,message,error:error instanceof Error?`${error.name}: ${error.message}`:error?String(error):undefined,updatedAt:Date.now()};try{localStorage.setItem(KEY,JSON.stringify(this.diagnostic));}catch{}return {...this.diagnostic};}
 get():StartupDiagnostic{return {...this.diagnostic};}
 clear():void{try{localStorage.removeItem(KEY);}catch{}}
 renderFatal(root:HTMLElement,error:unknown):void{const detail=error instanceof Error?`${error.name}: ${error.message}`:String(error);this.update('FAILED','Application bootstrap failed',error);root.innerHTML='';const box=document.createElement('main');box.style.cssText='min-height:100vh;background:#020617;color:#e2e8f0;padding:24px;display:flex;align-items:center;justify-content:center;font-family:system-ui,sans-serif';const panel=document.createElement('section');panel.style.cssText='max-width:720px;width:100%;border:1px solid #e11d48;background:#0f172a;border-radius:16px;padding:20px';const title=document.createElement('h1');title.textContent='MIKIの起動に失敗しました';title.style.cssText='font-size:20px;color:#fecdd3;margin:0 0 12px';const text=document.createElement('p');text.textContent='ブラックアウトを避けるため、安全な診断画面へ切り替えました。再起動しても直らない場合は下の内容を診断ログとして使用してください。';text.style.cssText='line-height:1.7;color:#cbd5e1';const pre=document.createElement('pre');pre.textContent=detail;pre.style.cssText='white-space:pre-wrap;word-break:break-word;background:#020617;border-radius:8px;padding:12px;color:#fda4af';const retry=document.createElement('button');retry.textContent='再起動';retry.style.cssText='border:0;border-radius:8px;padding:10px 18px;background:#7c3aed;color:white;font-weight:700';retry.onclick=()=>location.reload();panel.append(title,text,pre,retry);box.append(panel);root.append(box);}
}
export const startupRecoveryService=new StartupRecoveryService();
