import { canonicalSha256Object } from './canonicalSha256Service';
import type { MikiDomain } from './crossDomainCirculationService';

export type CollectionArtifactKind='CLAIM'|'KNOWLEDGE_GAP'|'KNOWLEDGE_COMPONENT'|'CODE_COMPONENT'|'CONVERSATION_COMPONENT'|'TEACHER_MATERIAL'|'RESEARCH_NOTE'|'CANDIDATE_EVALUATION'|'UNKNOWN_ATTEMPT';
export interface CollectionSourceDescriptor {sourceType:string;ownerDomain:MikiDomain;repositoryOrStore:string;canonicalAdapter:string;supportedArtifactKinds:CollectionArtifactKind[];verificationRequirement:string;freshnessRequirement:string;retrievalOperation:string;descriptorSha256:string;}
export interface CollectionReceipt {collectionReceiptId:string;taskId:string;sourceType:string;sourceRecordIds:string[];collectedArtifactKind:CollectionArtifactKind;canonicalSha256:string;duplicateOf?:string;verificationStatus:'RETRIEVED'|'NORMALIZED'|'VERIFIED'|'CONFLICT'|'REJECTED';storedByDomain:MikiDomain;coreDecisionId:string;createdAt:number;}
export interface CollectionPlan {planId:string;taskId:string;sourceTypes:string[];artifactKinds:CollectionArtifactKind[];requiredVerification:string[];stopConditions:string[];planSha256:string;}
class CollectionSourceRegistryService{
 private descriptors=new Map<string,CollectionSourceDescriptor>();private receipts=new Map<string,CollectionReceipt>();
 constructor(){this.registerDefaults();}
 register(input:Omit<CollectionSourceDescriptor,'descriptorSha256'>):CollectionSourceDescriptor{const descriptor={...input,supportedArtifactKinds:[...input.supportedArtifactKinds],descriptorSha256:canonicalSha256Object(input)};this.descriptors.set(input.sourceType,descriptor);return {...descriptor,supportedArtifactKinds:[...descriptor.supportedArtifactKinds]};}
 createPlan(input:{taskId:string;artifactKinds:CollectionArtifactKind[]}):CollectionPlan{const sources=this.list().filter(source=>source.supportedArtifactKinds.some(kind=>input.artifactKinds.includes(kind)));const base={taskId:input.taskId,sourceTypes:sources.map(x=>x.sourceType),artifactKinds:[...input.artifactKinds],requiredVerification:[...new Set(sources.map(x=>x.verificationRequirement))],stopConditions:['REQUIRED_CLAIMS_COLLECTED','COUNTEREVIDENCE_CHECKED','DUPLICATE_GROWTH_DETECTED','LOW_INFORMATION_GAIN','BUDGET_LIMIT','USER_CONFIRMATION_REQUIRED']};const planSha256=canonicalSha256Object(base);return {...base,planId:`COLP-${planSha256.slice(0,20)}`,planSha256};}
 record(input:Omit<CollectionReceipt,'collectionReceiptId'|'createdAt'|'duplicateOf'>):CollectionReceipt{const duplicate=[...this.receipts.values()].find(x=>x.canonicalSha256===input.canonicalSha256&&x.collectedArtifactKind===input.collectedArtifactKind);const createdAt=Date.now();const base={...input,sourceRecordIds:[...input.sourceRecordIds],duplicateOf:duplicate?.collectionReceiptId,createdAt};const receipt={...base,collectionReceiptId:`COLR-${canonicalSha256Object(base).slice(0,20)}`};this.receipts.set(receipt.collectionReceiptId,receipt);return {...receipt,sourceRecordIds:[...receipt.sourceRecordIds]};}
 list():CollectionSourceDescriptor[]{return [...this.descriptors.values()].map(x=>({...x,supportedArtifactKinds:[...x.supportedArtifactKinds]}));}
 listReceipts(taskId?:string):CollectionReceipt[]{return [...this.receipts.values()].filter(x=>!taskId||x.taskId===taskId).map(x=>({...x,sourceRecordIds:[...x.sourceRecordIds]}));}
 private registerDefaults():void{const rows:Array<Omit<CollectionSourceDescriptor,'descriptorSha256'>>=[
 {sourceType:'UNKNOWN_RESOLUTION',ownerDomain:'unknown',repositoryOrStore:'unknownResolutionService',canonicalAdapter:'unknownAttemptAdapter',supportedArtifactKinds:['UNKNOWN_ATTEMPT','CLAIM','KNOWLEDGE_GAP'],verificationRequirement:'verification domain SUPPORTED',freshnessRequirement:'per attempt',retrievalOperation:'RETRIEVE_UNKNOWN_HISTORY'},
 {sourceType:'RESEARCH_NOTES',ownerDomain:'research',repositoryOrStore:'digitalResearchNoteService',canonicalAdapter:'researchNoteAdapter',supportedArtifactKinds:['RESEARCH_NOTE','CLAIM'],verificationRequirement:'claim verification',freshnessRequirement:'source timestamp required',retrievalOperation:'RETRIEVE_RESEARCH_NOTES'},
 {sourceType:'OFFLINE_KNOWLEDGE',ownerDomain:'research',repositoryOrStore:'offlineKnowledgePackService',canonicalAdapter:'offlineKnowledgeAdapter',supportedArtifactKinds:['CLAIM','KNOWLEDGE_COMPONENT'],verificationRequirement:'pack validation',freshnessRequirement:'pack revision',retrievalOperation:'RETRIEVE_OFFLINE_KNOWLEDGE'},
 {sourceType:'TEACHER_MATERIAL',ownerDomain:'learning',repositoryOrStore:'teacherRequestService',canonicalAdapter:'teacherMaterialAdapter',supportedArtifactKinds:['TEACHER_MATERIAL','KNOWLEDGE_COMPONENT','CONVERSATION_COMPONENT'],verificationRequirement:'teacher material validation',freshnessRequirement:'material revision',retrievalOperation:'RETRIEVE_TEACHER_MATERIAL'},
 {sourceType:'CANDIDATE_REVIEW',ownerDomain:'improvement',repositoryOrStore:'reviewLearningArtifactService',canonicalAdapter:'reviewLearningAdapter',supportedArtifactKinds:['CANDIDATE_EVALUATION','KNOWLEDGE_COMPONENT','CODE_COMPONENT','CONVERSATION_COMPONENT'],verificationRequirement:'user decision and core decision',freshnessRequirement:'package revision',retrievalOperation:'RETRIEVE_REVIEW_LEARNING'},
 {sourceType:'CONVERSATION_LEARNING',ownerDomain:'conversation',repositoryOrStore:'conversationComponentCompositionService',canonicalAdapter:'conversationLearningAdapter',supportedArtifactKinds:['CONVERSATION_COMPONENT'],verificationRequirement:'dialogue evaluation',freshnessRequirement:'conversation episode revision',retrievalOperation:'RETRIEVE_CONVERSATION_COMPONENTS'}];for(const row of rows)this.register(row);}
}
export const collectionSourceRegistryService=new CollectionSourceRegistryService();
