import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from './canonicalSha256Service';
import { selfCodeSpaceService,type SelfCodeFile } from './selfCodeSpaceService';
export interface WorkspaceRepository{repositoryId:string;displayName:string;rootLabel:string;source:'MIKI_SELF'|'WORKSPACE_IMPORT'|'GITHUB_IMPORT';remote?:string;branch?:string;revision:string;packageManager?:string;buildCommand?:string;testCommand?:string;files:SelfCodeFile[];registeredAt:number;enabled:boolean;}
const KEY='miki_workspace_repository_registry_v1';
class WorkspaceRepositoryRegistryService{
 register(input:Omit<WorkspaceRepository,'repositoryId'|'revision'|'registeredAt'>):WorkspaceRepository{const normalized=input.files.map(file=>({...file,path:file.path.replace(/^\/+/,''),sha256:file.sha256||canonicalSha256(file.content)})).sort((a,b)=>a.path.localeCompare(b.path));if(!normalized.length)throw new Error('WORKSPACE_REPOSITORY_FILES_REQUIRED');const revision=canonicalSha256(normalized.map(file=>({path:file.path,sha256:file.sha256})));const repositoryId=`REPO-${canonicalSha256({root:input.rootLabel,remote:input.remote||'',revision}).slice(0,20)}`;const item={...input,files:normalized,repositoryId,revision,registeredAt:Date.now()};const all=this.list().filter(value=>value.repositoryId!==repositoryId&&value.rootLabel!==item.rootLabel);all.push(item);this.save(all);return this.clone(item);}
 unregister(repositoryId:string){const before=this.list();const next=before.filter(item=>item.repositoryId!==repositoryId);this.save(next);return next.length!==before.length;}
 setEnabled(repositoryId:string,enabled:boolean){const all=this.list();const target=all.find(item=>item.repositoryId===repositoryId);if(!target)throw new Error('WORKSPACE_REPOSITORY_NOT_FOUND');target.enabled=enabled;this.save(all);return this.clone(target);}
 list():WorkspaceRepository[]{const imported=this.load();const self=selfCodeSpaceService.get();if(self){const files=self.files;const revision=self.repoSha256;const item:WorkspaceRepository={repositoryId:'REPO-MIKI-SELF',displayName:'MIKI-AI',rootLabel:'MIKI-AI',source:'MIKI_SELF',remote:self.repository,branch:self.branch,revision,packageManager:this.packageManager(files),buildCommand:this.command(files,'build'),testCommand:this.command(files,'test'),files,registeredAt:self.syncedAt,enabled:true};return [item,...imported.filter(value=>value.repositoryId!=='REPO-MIKI-SELF')].map(value=>this.clone(value));}return imported.map(value=>this.clone(value));}
 listEnabled(){return this.list().filter(item=>item.enabled);}
 listCompositeFiles(){return this.listEnabled().flatMap(repository=>repository.files.map(file=>({...file,path:`@repo/${repository.repositoryId}/${file.path}`,repositoryId:repository.repositoryId,repositoryRoot:repository.rootLabel,originalPath:file.path})));}
 dependencyGraph(){const repos=this.listEnabled();const nodes=repos.map(repo=>({repositoryId:repo.repositoryId,root:repo.rootLabel,revision:repo.revision,remote:repo.remote,branch:repo.branch,packageManager:repo.packageManager,buildCommand:repo.buildCommand,testCommand:repo.testCommand}));const edges:any[]=[];const packageNames=new Map<string,string>();for(const repo of repos){const pkg=repo.files.find(file=>file.path==='package.json');if(pkg)try{const value=JSON.parse(pkg.content);if(value.name)packageNames.set(value.name,repo.repositoryId);}catch{}}
 for(const repo of repos){const pkg=repo.files.find(file=>file.path==='package.json');if(!pkg)continue;try{const value=JSON.parse(pkg.content);const deps={...(value.dependencies||{}),...(value.devDependencies||{}),...(value.peerDependencies||{})};for(const [name,version] of Object.entries(deps)){const to=packageNames.get(name);if(to)edges.push({from:repo.repositoryId,to,kind:'PACKAGE',name,version});}}catch{}}
 return {graphId:`WRG-${canonicalSha256({nodes,edges}).slice(0,22)}`,nodes,edges,buildOrder:this.topological(nodes.map(node=>node.repositoryId),edges),rollbackOrder:this.topological(nodes.map(node=>node.repositoryId),edges).reverse()};}
 private packageManager(files:SelfCodeFile[]){if(files.some(file=>file.path==='pnpm-lock.yaml'))return 'pnpm';if(files.some(file=>file.path==='yarn.lock'))return 'yarn';if(files.some(file=>file.path==='package-lock.json'))return 'npm';if(files.some(file=>file.path==='Cargo.toml'))return 'cargo';if(files.some(file=>file.path==='pom.xml'))return 'maven';if(files.some(file=>/build\.gradle/.test(file.path)))return 'gradle';return undefined;}
 private command(files:SelfCodeFile[],name:string){const pkg=files.find(file=>file.path==='package.json');if(!pkg)return undefined;try{const value=JSON.parse(pkg.content);return value.scripts?.[name]?`${this.packageManager(files)||'npm'} run ${name}`:undefined;}catch{return undefined;}}
 private topological(nodes:string[],edges:any[]){const result:string[]=[];const remaining=new Set(nodes);while(remaining.size){const ready=[...remaining].filter(node=>!edges.some(edge=>edge.to===node&&remaining.has(edge.from))).sort();if(!ready.length){result.push(...[...remaining].sort());break;}for(const node of ready){remaining.delete(node);result.push(node);}}return result;}
 private load():WorkspaceRepository[]{try{const value=JSON.parse(storageService.getItem(KEY)||'[]');return Array.isArray(value)?value:[];}catch{return [];}}
 private save(items:WorkspaceRepository[]){storageService.setItem(KEY,JSON.stringify(items.slice(0,20)));}
 private clone(item:WorkspaceRepository):WorkspaceRepository{return {...item,files:item.files.map(file=>({...file}))};}
}
export const workspaceRepositoryRegistryService=new WorkspaceRepositoryRegistryService();
