import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
export type UnknownCapabilityGapKind='MISSING_INTERFACE'|'MISSING_IMPLEMENTATION_PATTERN'|'MISSING_DEPENDENCY_KNOWLEDGE'|'MISSING_REPOSITORY_CONTEXT'|'MISSING_RUNTIME_EVIDENCE'|'MISSING_TEST_ORACLE'|'MISSING_TOOL_ADAPTER'|'EXTERNAL_ONLY_CAPABILITY';
export interface UnknownFingerprintInput {unknownKind:string;requiredCapability:string;targetEnvironment:string;interfaceFingerprint:string;repositoryContextFingerprint:string;evidenceFingerprint:string;userConstraintFingerprint:string;}
export interface UnknownFingerprint {unknownFingerprintId:string;canonicalSha256:string;normalized:UnknownFingerprintInput;}
class UnknownFingerprintService{
 create(input:Partial<UnknownFingerprintInput>):UnknownFingerprint{const normalized:UnknownFingerprintInput={unknownKind:this.text(input.unknownKind),requiredCapability:this.text(input.requiredCapability),targetEnvironment:this.text(input.targetEnvironment),interfaceFingerprint:this.text(input.interfaceFingerprint),repositoryContextFingerprint:this.text(input.repositoryContextFingerprint),evidenceFingerprint:this.text(input.evidenceFingerprint),userConstraintFingerprint:this.text(input.userConstraintFingerprint)};const canonicalSha256=canonicalSha256Object(normalized);return {unknownFingerprintId:`UFP-${canonicalSha256.slice(0,20)}`,canonicalSha256,normalized};}
 classifyCapabilityGap(input:{requiredCapability?:string;interfaceAvailable?:boolean;repositoryContextAvailable?:boolean;runtimeEvidenceAvailable?:boolean;testOracleAvailable?:boolean;toolAdapterAvailable?:boolean;externalOnly?:boolean}):UnknownCapabilityGapKind[]{const gaps:UnknownCapabilityGapKind[]=[];if(input.externalOnly)gaps.push('EXTERNAL_ONLY_CAPABILITY');if(input.interfaceAvailable===false)gaps.push('MISSING_INTERFACE');if(input.repositoryContextAvailable===false)gaps.push('MISSING_REPOSITORY_CONTEXT');if(input.runtimeEvidenceAvailable===false)gaps.push('MISSING_RUNTIME_EVIDENCE');if(input.testOracleAvailable===false)gaps.push('MISSING_TEST_ORACLE');if(input.toolAdapterAvailable===false)gaps.push('MISSING_TOOL_ADAPTER');if(input.requiredCapability&&!input.externalOnly&&gaps.length===0)gaps.push('MISSING_IMPLEMENTATION_PATTERN');return gaps;}
 canResolve(input:{answer?:string;componentArtifactId?:string;supportingEvidenceIds:string[];verificationStatus:string;applicableScope?:string;doesNotApplyWhen:string[];persistenceReceiptId?:string}):{resolved:boolean;reasons:string[]}{const reasons:string[]=[];if(!input.answer&&!input.componentArtifactId)reasons.push('ANSWER_OR_COMPONENT_REQUIRED');if(input.supportingEvidenceIds.length===0)reasons.push('SUPPORTING_EVIDENCE_REQUIRED');if(input.verificationStatus!=='SUPPORTED')reasons.push('SUPPORTED_VERIFICATION_REQUIRED');if(!input.applicableScope)reasons.push('APPLICABLE_SCOPE_REQUIRED');if(!Array.isArray(input.doesNotApplyWhen))reasons.push('DOES_NOT_APPLY_WHEN_REQUIRED');if(!input.persistenceReceiptId)reasons.push('PERSISTENCE_RECEIPT_REQUIRED');return {resolved:reasons.length===0,reasons};}
 private text(value?:string):string{return (value||'unknown').trim().toLowerCase().replace(/\s+/g,' ');}
}
export const unknownFingerprintService=new UnknownFingerprintService();
