import type { ConversationSemanticContext } from '../../selfDevelopment/services/semanticExecutionPlanCompiler';
import { semanticContextBudgetService } from '../../core/services/semanticContextBudgetService';
import { typedDiscourseModelService, type DiscourseEntity } from './typedDiscourseModelService';
export interface ConversationContextSnapshot{version:1;summary:string;retained:ConversationSemanticContext[];topics:Array<{label:string;turnId:string;score:number;status:string}>;constraints:string[];checksum:string;}
export interface FocusDecision{selected?:DiscourseEntity;ambiguous:boolean;candidates:DiscourseEntity[];reason:string;}
const hash=(text:string)=>{let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');};
class ConversationContinuityService{
 compress(history:ConversationSemanticContext[],query='',limit=24):ConversationContextSnapshot{const mandatory=history.filter(x=>/(しない|触らない|残す|維持|必須|禁止)/.test(x.text));const ranked=semanticContextBudgetService.rank(history,query,x=>`${x.text} ${(x.entities||[]).join(' ')}`,limit);const retained=[...new Map([...mandatory,...ranked.map(x=>x.item)].map(x=>[x.turnId,x])).values()].slice(0,limit);const discourse=typedDiscourseModelService.build(retained);const topics=discourse.slice(0,20).map(x=>({label:x.label,turnId:x.turnId,score:x.salience,status:x.status}));const constraints=retained.flatMap(x=>x.text.match(/[^。]*(?:しない|触らない|消さない|残す|維持|必須|禁止)[^。]*/g)||[]).slice(-20);const summary=topics.map(x=>`${x.label}:${x.status}`).join(' / ');const body={version:1 as const,summary,retained,topics,constraints};return{...body,checksum:hash(JSON.stringify(body))};}
 restore(snapshot:ConversationContextSnapshot):ConversationSemanticContext[]{const {checksum,...body}=snapshot;if(hash(JSON.stringify(body))!==checksum)throw new Error('CONVERSATION_CONTEXT_CHECKSUM_MISMATCH');return snapshot.retained.map(x=>({...x,entities:[...(x.entities||[])]}));}
 reselectFocus(text:string,history:ConversationSemanticContext[],previousTopic?:string):FocusDecision{const entities=typedDiscourseModelService.build(history);const explicit=entities.filter(x=>text.includes(x.label));if(explicit.length===1)return{selected:explicit[0],ambiguous:false,candidates:explicit,reason:'EXPLICIT_MENTION'};const topicReturn=/(話を戻|さっき|前の|以前の|戻る)/.test(text);if(topicReturn&&previousTopic){const matched=entities.filter(x=>x.label===previousTopic);if(matched.length)return{selected:matched[0],ambiguous:false,candidates:matched,reason:'TOPIC_RETURN'};}const active=entities.filter(x=>x.status==='ACTIVE');if(!active.length)return{ambiguous:false,candidates:[],reason:'NO_ACTIVE_FOCUS'};const top=active[0],ties=active.filter(x=>Math.abs(x.salience-top.salience)<.2);return{selected:ties.length===1?top:undefined,ambiguous:ties.length>1,candidates:ties.slice(0,5),reason:ties.length>1?'SALience_TIE':'ACTIVE_SALIENCE'};}
 recover(history:ConversationSemanticContext[],failedTurnId:string,correction:string):ConversationSemanticContext[]{const index=history.findIndex(x=>x.turnId===failedTurnId);const safe=index<0?[...history]:history.slice(0,index);return[...safe,{turnId:`recovery:${failedTurnId}`,text:correction,entities:[]}];}
}
export const conversationContinuityService=new ConversationContinuityService();
