export type DiscourseEntityKind='ARTIFACT'|'ACTION'|'CONDITION'|'RESULT'|'CANDIDATE'|'TOPIC'|'UNKNOWN';
export interface DiscourseEntity{id:string;label:string;kind:DiscourseEntityKind;turnId:string;salience:number;status:'ACTIVE'|'COMPLETED'|'REJECTED'|'DEFERRED';sourceText:string;}
export interface DiscourseIntent{kind:'QUESTION'|'CONFIRM'|'CONTINUE'|'IMPROVE'|'IMPLEMENT'|'PRESERVE'|'PROHIBIT'|'COMPARE'|'CORRECT'|'EXPLAIN'|'ROLLBACK'|'UNKNOWN';scope:string;confidence:number;}
export interface DiscourseResolution{resolvedText:string;entities:DiscourseEntity[];referent?:DiscourseEntity;ambiguous:boolean;intents:DiscourseIntent[];constraints:{preserve:string[];prohibit:string[];conditions:string[]};}
const kindOf=(text:string):DiscourseEntityKind=>/候補/.test(text)?'CANDIDATE':/条件/.test(text)?'CONDITION':/結果|確認|検証/.test(text)?'RESULT':/実装|変更|処理|更新|修正/.test(text)?'ACTION':/ファイル|zip|コード|機能/.test(text)?'ARTIFACT':'TOPIC';
const labels=(text:string)=>[...new Set([...(text.match(/[A-Za-z_][A-Za-z0-9_.\/-]{1,}|[一-龠ァ-ヶー]{2,}(?:機能|処理|条件|結果|候補|ファイル|コード|実装|検証)/g)||[])])];
class TypedDiscourseModelService{
 build(history:Array<{turnId:string;text:string;entities?:string[]}>):DiscourseEntity[]{const rows:DiscourseEntity[]=[];history.forEach((turn,index)=>{const distance=history.length-1-index;const values=[...(turn.entities||[]),...labels(turn.text)];for(const label of new Set(values)){const status=/保留|後回し/.test(turn.text)?'DEFERRED':/却下|不採用|違う/.test(turn.text)?'REJECTED':/完了|できた|採用/.test(turn.text)?'COMPLETED':'ACTIVE';rows.push({id:`${turn.turnId}:${label}`,label,kind:kindOf(`${label} ${turn.text}`),turnId:turn.turnId,salience:Math.max(.1,1-distance*.18)+(status==='ACTIVE'?.2:0),status,sourceText:turn.text});}});return rows.sort((a,b)=>b.salience-a.salience||b.turnId.localeCompare(a.turnId));}
 resolve(text:string,history:Array<{turnId:string;text:string;entities?:string[]}>):DiscourseResolution{const entities=this.build(history);const reference=/(これ|それ|あれ|前の(?:やつ|処理|条件|結果|機能)?|さっきの(?:やつ|処理|条件|結果|機能)?|残り)/.exec(text)?.[1];let expected:DiscourseEntityKind|undefined;if(/条件/.test(reference||''))expected='CONDITION';else if(/結果/.test(reference||''))expected='RESULT';else if(/処理/.test(reference||''))expected='ACTION';else if(/機能/.test(reference||''))expected='ARTIFACT';const candidates=entities.filter(x=>x.status==='ACTIVE'&&(!expected||x.kind===expected));const referent=reference?candidates[0]:undefined;const ambiguous=Boolean(reference&&(!referent||(candidates[1]&&Math.abs(candidates[0].salience-candidates[1].salience)<.12)));const resolvedText=referent&&!ambiguous?text.replace(reference!,`「${referent.label}」`):text;const intents:DiscourseIntent[]=[];const add=(kind:DiscourseIntent['kind'],re:RegExp,confidence=.9)=>{if(re.test(text))intents.push({kind,scope:referent?.label||'CURRENT_FOCUS',confidence});};add('CONFIRM',/どう\?|問題ない|大丈夫|本当/);add('CONTINUE',/続け|進め|残り/);add('IMPROVE',/良く|改善|強化|深く/);add('IMPLEMENT',/実装|作って|追加|直して|修正/);add('PRESERVE',/残して|維持|そのまま|消さない/);add('PROHIBIT',/しない|触らない|消さない|禁止/);add('COMPARE',/比較|どっち|違い/);add('CORRECT',/違う|ではなく|じゃなく/);add('EXPLAIN',/意味|なぜ|どういう|詳しく/);add('ROLLBACK',/戻して|復元|ロールバック/);if(!intents.length)intents.push({kind:'UNKNOWN',scope:referent?.label||'CURRENT_FOCUS',confidence:.3});return{resolvedText,entities,referent,ambiguous,intents,constraints:{preserve:[...text.matchAll(/([^、。]+?)(?:は|を)?(?:残して|維持|そのまま|消さない)/g)].map(x=>x[1].trim()),prohibit:[...text.matchAll(/([^、。]+?)(?:は|を)?(?:しない|触らない|消さない)/g)].map(x=>x[1].trim()),conditions:[...text.matchAll(/([^、。]+?(?:場合|とき|なら|だけ))/g)].map(x=>x[1].trim())}};}
}
export const typedDiscourseModelService=new TypedDiscourseModelService();
