import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
export type GovernedMemoryKind='FACT'|'DECISION'|'PREFERENCE'|'CONSTRAINT'|'HYPOTHESIS'|'TASK'|'EVIDENCE'|'ARTIFACT';
export type GovernedMemoryStatus='ACTIVE'|'UNVERIFIED'|'SUPERSEDED'|'REJECTED'|'EXPIRED'|'INVALIDATED';
export type GovernedScopeType='GLOBAL'|'REPOSITORY'|'FEATURE'|'MODULE'|'FUNCTION'|'WORKBOOK'|'SHEET'|'ACTION'|'TASK'|'CONVERSATION';
export interface GovernedMemoryScope{type:GovernedScopeType;id:string;targets?:string[];excludedTargets?:string[];validFrom?:number;validUntil?:number;}
export interface GovernedMemorySource{turnIds:string[];fileIds:string[];evidenceIds:string[];artifactSha256?:string;repositoryRevision?:string;}
export interface GovernedMemoryRecord{id:string;subject:string;content:string;kind:GovernedMemoryKind;status:GovernedMemoryStatus;scope:GovernedMemoryScope;source:GovernedMemorySource;confidence:number;createdAt:number;updatedAt:number;supersedes?:string;supersededBy?:string;invalidationReason?:string;}
export interface GovernedMemoryQuery{subject?:string;scopeType?:GovernedScopeType;scopeId?:string;target?:string;now?:number;includeUnverified?:boolean;limit?:number;}
const KEY='miki_scoped_versioned_memory_v1';
class ScopedVersionedMemoryService{
 private records=new Map<string,GovernedMemoryRecord>();constructor(){this.load();}
 propose(input:Omit<GovernedMemoryRecord,'id'|'status'|'createdAt'|'updatedAt'>):GovernedMemoryRecord{const now=Date.now();const record:GovernedMemoryRecord={...input,id:`MEM-${canonicalSha256({subject:input.subject,content:input.content,scope:input.scope,source:input.source}).slice(0,24)}`,status:input.kind==='HYPOTHESIS'?'UNVERIFIED':'ACTIVE',confidence:Math.max(0,Math.min(1,input.confidence)),createdAt:now,updatedAt:now};this.records.set(record.id,record);this.save();return record;}
 supersede(previousId:string,next:Omit<GovernedMemoryRecord,'id'|'status'|'createdAt'|'updatedAt'|'supersedes'>):GovernedMemoryRecord|undefined{const previous=this.records.get(previousId);if(!previous||!['ACTIVE','UNVERIFIED'].includes(previous.status))return undefined;const replacement=this.propose({...next,supersedes:previousId});previous.status='SUPERSEDED';previous.supersededBy=replacement.id;previous.updatedAt=Date.now();this.records.set(previous.id,previous);this.save();return replacement;}
 invalidate(id:string,reason:string):GovernedMemoryRecord|undefined{const record=this.records.get(id);if(!record)return undefined;record.status='INVALIDATED';record.invalidationReason=reason;record.updatedAt=Date.now();this.records.set(id,record);this.save();return record;}
 invalidateBySource(sourceId:string,reason:string):GovernedMemoryRecord[]{const changed=[] as GovernedMemoryRecord[];for(const record of this.records.values()){const linked=[...record.source.turnIds,...record.source.fileIds,...record.source.evidenceIds].includes(sourceId);if(linked&&['ACTIVE','UNVERIFIED'].includes(record.status)){const item=this.invalidate(record.id,reason);if(item)changed.push(item);}}return changed;}
 retrieve(query:GovernedMemoryQuery):GovernedMemoryRecord[]{const now=query.now??Date.now();return[...this.records.values()].filter(record=>{if(record.status!=='ACTIVE'&&!(query.includeUnverified&&record.status==='UNVERIFIED'))return false;if(record.scope.validFrom&&record.scope.validFrom>now)return false;if(record.scope.validUntil&&record.scope.validUntil<now)return false;if(query.subject&&record.subject!==query.subject)return false;if(query.scopeType&&record.scope.type!==query.scopeType)return false;if(query.scopeId&&record.scope.id!==query.scopeId)return false;if(query.target){if(record.scope.excludedTargets?.includes(query.target))return false;if(record.scope.targets?.length&&!record.scope.targets.includes(query.target))return false;}return true;}).sort((a,b)=>this.score(b,query)-this.score(a,query)||b.updatedAt-a.updatedAt).slice(0,query.limit??50);}
 resolveReference(candidates:Array<{id:string;taskMatch:number;featureMatch:number;targetMatch:number;recency:number;evidenceStrength:number;contradiction:number}>):{resolvedId?:string;ambiguous:boolean;scores:Array<{id:string;score:number}>}{const scores=candidates.map(item=>({id:item.id,score:item.taskMatch+item.featureMatch+item.targetMatch+item.recency+item.evidenceStrength-item.contradiction})).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));return{resolvedId:scores.length&&(!scores[1]||scores[0].score-scores[1].score>=0.15)?scores[0].id:undefined,ambiguous:scores.length>1&&scores[0].score-scores[1].score<0.15,scores};}
 list():GovernedMemoryRecord[]{return[...this.records.values()].sort((a,b)=>b.updatedAt-a.updatedAt);}
 private score(record:GovernedMemoryRecord,query:GovernedMemoryQuery):number{return(record.scope.type===query.scopeType?2:0)+(record.scope.id===query.scopeId?2:0)+(record.source.evidenceIds.length?1:0)+record.confidence;}
 private save():void{storageService.setItem(KEY,JSON.stringify(this.list().slice(0,5000)));}
 private load():void{try{const parsed=JSON.parse(storageService.getItem(KEY)||'[]') as GovernedMemoryRecord[];for(const item of parsed)this.records.set(item.id,item);}catch{}}
}
export const scopedVersionedMemoryService=new ScopedVersionedMemoryService();
