import React,{useState} from 'react';
import { Save, RefreshCw } from 'lucide-react';
import { typedCoreUiGatewayService } from '../miki/core/ui/typedCoreUiGatewayService';

export const CoreCycleSettingsPanel:React.FC=()=>{
 const [settings,setSettings]=useState(()=>typedCoreUiGatewayService.getCoreCycleSettings());
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const save=async()=>{setBusy(true);setMessage('');try{const r=await typedCoreUiGatewayService.saveCoreCycleSettings(settings);if(r.status==='SUCCESS'){setSettings(r.data!.settings);setMessage('保存しました');}else setMessage(r.summary);}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const reset=()=>setSettings(typedCoreUiGatewayService.getCoreCycleSettings());
 return <section className="rounded-3xl border border-indigo-500/20 bg-slate-900 p-4 space-y-4"><div><h2 className="font-bold">COREサイクル設定</h2><p className="mt-1 text-xs text-slate-400">会話と自己コード改善の上限を分離します。自己コード改善は工程回数ではなく、安全停止用の上限です。</p></div><div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">会話：最大COREサイクル</span><input type="number" min={1} max={100} value={settings.conversationMaxCycles} onChange={e=>setSettings(x=>({...x,conversationMaxCycles:Number(e.target.value)}))} className="min-h-12 w-full rounded-2xl border border-slate-700 bg-slate-950 px-3"/></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">自己コード改善：安全上限</span><input type="number" min={1} max={100} value={settings.selfImprovementMaxCycles} onChange={e=>setSettings(x=>({...x,selfImprovementMaxCycles:Number(e.target.value)}))} className="min-h-12 w-full rounded-2xl border border-slate-700 bg-slate-950 px-3"/></label></div><div className="grid grid-cols-2 gap-3"><button disabled={busy} onClick={save} className="min-h-12 rounded-2xl bg-indigo-600 font-bold disabled:opacity-50"><Save className="mr-2 inline h-4 w-4"/>保存</button><button disabled={busy} onClick={reset} className="min-h-12 rounded-2xl bg-slate-800 font-bold"><RefreshCw className="mr-2 inline h-4 w-4"/>再読込</button></div>{message&&<div role="status" className="rounded-2xl bg-indigo-500/10 p-3 text-xs">{message}</div>}</section>;
};
