use serde::{Deserialize,Serialize};use sha2::{Digest,Sha256};use std::{fs::{self,OpenOptions},io::{Read,Write},path::{Path,PathBuf}};
#[derive(Debug,Serialize,Deserialize)]pub struct CommitRequest{pub transaction_id:String,pub expected_generation:u64,pub graph_json:String}
#[derive(Debug,Serialize,Deserialize)]pub struct CommitReceipt{pub transaction_id:String,pub generation:u64,pub graph_sha256:String,pub journal_sha256:String,pub recovered:bool}
#[derive(Debug,Serialize,Deserialize)]struct Manifest{generation:u64,active_snapshot:String,graph_sha256:String}
fn hex(bytes:&[u8])->String{Sha256::digest(bytes).iter().map(|b|format!("{b:02x}")).collect()}
fn sync_write(path:&Path,data:&[u8])->Result<(),String>{let mut f=OpenOptions::new().create(true).truncate(true).write(true).open(path).map_err(|e|e.to_string())?;f.write_all(data).map_err(|e|e.to_string())?;f.sync_all().map_err(|e|e.to_string())}
fn paths(root:&Path)->(PathBuf,PathBuf,PathBuf){(root.join("manifest.json"),root.join("journal.ndjson"),root.join("snapshots"))}
pub fn recover(root:&Path)->Result<CommitReceipt,String>{fs::create_dir_all(root).map_err(|e|e.to_string())?;let(m,j,s)=paths(root);fs::create_dir_all(&s).map_err(|e|e.to_string())?;if !m.exists(){let empty=b"{\"nodes\":[],\"edges\":[]}";let sha=hex(empty);sync_write(&s.join("graph-0.json"),empty)?;sync_write(&m,serde_json::to_vec(&Manifest{generation:0,active_snapshot:"graph-0.json".into(),graph_sha256:sha.clone()}).unwrap().as_slice())?;return Ok(CommitReceipt{transaction_id:"RECOVERY-INIT".into(),generation:0,graph_sha256:sha,journal_sha256:hex(b""),recovered:true})}let manifest:Manifest=serde_json::from_slice(&fs::read(&m).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let journal=fs::read(&j).unwrap_or_default();Ok(CommitReceipt{transaction_id:"RECOVERY".into(),generation:manifest.generation,graph_sha256:manifest.graph_sha256,journal_sha256:hex(&journal),recovered:true})}
pub fn commit(root:&Path,req:&CommitRequest)->Result<CommitReceipt,String>{let current=recover(root)?;if current.generation!=req.expected_generation{return Err("GRAPH_GENERATION_CONFLICT".into())}serde_json::from_str::<serde_json::Value>(&req.graph_json).map_err(|_|"GRAPH_JSON_INVALID")?;let(m,j,s)=paths(root);let generation=current.generation+1;let graph_sha256=hex(req.graph_json.as_bytes());
let snapshot=format!("graph-{generation}.json");
let tmp=s.join(format!("{snapshot}.tmp"));
let final_path=s.join(&snapshot);sync_write(&tmp,req.graph_json.as_bytes())?;fs::rename(&tmp,&final_path).map_err(|e|e.to_string())?;let journal_line=serde_json::to_string(&serde_json::json!({"transactionId":req.transaction_id,"generation":generation,"graphSha256":graph_sha256,"snapshot":snapshot})).unwrap()+"\n";let mut jf=OpenOptions::new().create(true).append(true).open(&j).map_err(|e|e.to_string())?;jf.write_all(journal_line.as_bytes()).map_err(|e|e.to_string())?;jf.sync_all().map_err(|e|e.to_string())?;let manifest=Manifest{generation,active_snapshot:snapshot,graph_sha256:graph_sha256.clone()},mtmp=m.with_extension("json.tmp");sync_write(&mtmp,&serde_json::to_vec(&manifest).unwrap())?;fs::rename(mtmp,&m).map_err(|e|e.to_string())?;let mut journal=Vec::new();OpenOptions::new().read(true).open(j).map_err(|e|e.to_string())?.read_to_end(&mut journal).map_err(|e|e.to_string())?;Ok(CommitReceipt{transaction_id:req.transaction_id.clone(),generation,graph_sha256,journal_sha256:hex(&journal),recovered:false})}
pub fn commit_json(root:&str,input:&str)->Result<String,String>{let req:CommitRequest=serde_json::from_str(input).map_err(|e|e.to_string())?;serde_json::to_string(&commit(Path::new(root),&req)?).map_err(|e|e.to_string())}
#[cfg(test)]mod tests{use super::*;#[test]fn atomic_file_roundtrip(){let root=std::env::temp_dir().join(format!("miki-graph-{}",std::process::id()));let _=fs::remove_dir_all(&root);let r=commit(&root,&CommitRequest{transaction_id:"T1".into(),expected_generation:0,graph_json:"{\"nodes\":[1],\"edges\":[]}".into()}).unwrap();assert_eq!(r.generation,1);assert!(root.join("manifest.json").exists());assert!(root.join("journal.ndjson").exists());assert_eq!(recover(&root).unwrap().generation,1);let _=fs::remove_dir_all(root);}}
