use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SemanticAsset { pub asset_id:String, pub concept_id:String, pub normalized:String, pub confidence:f64, pub enabled:bool, #[serde(default)] pub evidence_ids:Vec<String>, #[serde(default)] pub counterexample_ids:Vec<String> }
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct SemanticCandidate { pub concept_id:String, pub score:f64, pub matched_asset_ids:Vec<String>, pub evidence_ids:Vec<String>, pub counterexample_ids:Vec<String> }
pub fn rank(query:&str, assets:&[SemanticAsset], counterexamples:&BTreeSet<String>)->Vec<SemanticCandidate>{let q=query.to_lowercase();let mut grouped:BTreeMap<String,Vec<&SemanticAsset>>=BTreeMap::new();for asset in assets.iter().filter(|a|a.enabled&&q.contains(&a.normalized.to_lowercase())){grouped.entry(asset.concept_id.clone()).or_default().push(asset)}let mut result:Vec<_>=grouped.into_iter().map(|(concept_id,items)|{let mut score=items.iter().map(|a|a.confidence).sum::<f64>()/items.len() as f64;let mut negative=Vec::new();for item in &items{for id in &item.counterexample_ids{if counterexamples.contains(id){score-=0.45;negative.push(id.clone())}}}SemanticCandidate{concept_id,score:score.clamp(0.0,1.0),matched_asset_ids:items.iter().map(|a|a.asset_id.clone()).collect(),evidence_ids:items.iter().flat_map(|a|a.evidence_ids.clone()).collect(),counterexample_ids:negative}}).collect();result.sort_by(|a,b|b.score.total_cmp(&a.score).then(a.concept_id.cmp(&b.concept_id)));result}
#[cfg(test)] mod tests{use super::*;#[test]fn counterexample_changes_ranking(){let assets=vec![SemanticAsset{asset_id:"continue".into(),concept_id:"intent.continue".into(),normalized:"続き".into(),confidence:.9,enabled:true,evidence_ids:vec!["ev".into()],counterexample_ids:vec!["cx".into()]}];let normal=rank("続きを実装",&assets,&BTreeSet::new());let blocked=rank("続きを実装",&assets,&BTreeSet::from(["cx".into()]));assert!(normal[0].score>blocked[0].score);assert_eq!(blocked[0].counterexample_ids,vec!["cx"]);}}
