import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
import { isolatedCandidateWorkspaceService } from '../../core/services/isolatedCandidateWorkspaceService';
import { advancedDomainExecutionModelService } from './advancedDomainExecutionModelService';
import { advancedRepositoryGraphAnalysisService } from './advancedRepositoryGraphAnalysisService';
import { workspaceRepositoryRegistryService } from '../../core/services/workspaceRepositoryRegistryService';
export type AdvancedDepthDomain='COMPLEX_UI'|'LARGE_STATE'|'EXTERNAL_API'|'ADVANCED_PERFORMANCE'|'THREAT_MODEL'|'COMPLEX_DB_MIGRATION'|'MULTI_REPOSITORY';
export interface AdvancedDepthPlan{planId:string;domain:AdvancedDepthDomain;instruction:string;targets:string[];evidence:Record<string,unknown>;gates:string[];blockedReasons:string[];candidateOperations:Array<{path:string;operation:string;anchor:string}>;}
class AdvancedDevelopmentDepthExecutorService{
 detectAll(instruction:string):AdvancedDepthDomain[]{return advancedDomainExecutionModelService.detectAll(instruction);}
 detect(instruction:string):AdvancedDepthDomain|undefined{const text=instruction.toLowerCase();const rules:Array<[AdvancedDepthDomain,RegExp]>=[['COMPLEX_UI',/複雑.*ui|画面設計|component tree|accessibility|responsive|ui\/ux/],['LARGE_STATE',/大規模.*状態|state management|store|reducer|event sourcing/],['EXTERNAL_API',/外部api|api.*仕様|openapi|webhook|oauth|rate limit/],['ADVANCED_PERFORMANCE',/高度.*性能|performance|benchmark|p95|hotspot|memory/],['THREAT_MODEL',/脅威モデル|threat model|trust boundary|stride|attack surface/],['COMPLEX_DB_MIGRATION',/複雑.*db|database migration|schema migration|backfill|zero downtime/],['MULTI_REPOSITORY',/多数.*repository|multi.?repo|複数.*repository|monorepo|依存repository/]];return rules.find(([,pattern])=>pattern.test(text))?.[0];}
 async execute(domain:AdvancedDepthDomain,instruction:string,targetPaths:string[],runId?:string){const all=workspaceRepositoryRegistryService.listCompositeFiles();const selected=all.filter(file=>targetPaths.includes(file.path)||this.match(domain,file.path,file.content)).slice(0,120);const baseEvidence=this.analyze(domain,selected);const graph=advancedRepositoryGraphAnalysisService.analyze(selected.map(file=>file.path));const executableGates=advancedDomainExecutionModelService.buildGates(domain);const concreteOperations=advancedDomainExecutionModelService.buildOperations(domain,selected.map(file=>file.path));const batches=advancedDomainExecutionModelService.batch(selected.map(file=>file.path),40);const evidence={...baseEvidence,graph,executableGates,batches};const blockedReasons=this.blockers(domain,evidence);const plan:AdvancedDepthPlan={planId:`ADP-${canonicalSha256({domain,instruction,paths:selected.map(file=>file.path),evidence}).slice(0,24)}`,domain,instruction,targets:selected.map(file=>file.path),evidence,gates:this.gates(domain),blockedReasons,candidateOperations:concreteOperations as any};const evidenceId=`EVD-${plan.planId}`;const files=[{path:`review/advanced/${domain}/PLAN.json`,baselineContent:'',candidateContent:JSON.stringify(plan,null,2),evidenceIds:[evidenceId]},{path:`review/advanced/${domain}/ACCEPTANCE.json`,baselineContent:'',candidateContent:JSON.stringify({planId:plan.planId,gates:plan.gates,passCondition:'ALL_GATES_PASS',blockedReasons},null,2),evidenceIds:[evidenceId]}];const workspace=await isolatedCandidateWorkspaceService.create(`${domain}:${plan.planId}`,files,runId);return {kind:domain,accepted:blockedReasons.length===0,workspace,plan,requiresOriginalPipeline:true};}
 private analyze(domain:AdvancedDepthDomain,files:Array<{path:string;content:string}>){const joined=files.map(file=>file.content).join('\n');const paths=files.map(file=>file.path);const imports=[...joined.matchAll(/(?:from\s+|require\()['\"]([^'\"]+)/g)].map(match=>match[1]);const base={fileCount:files.length,totalBytes:joined.length,pathSha256:canonicalSha256(paths),importCount:imports.length,externalImports:[...new Set(imports.filter(value=>!value.startsWith('.')))].sort()};if(domain==='COMPLEX_UI')return {...base,components:paths.filter(path=>/\.tsx?$/.test(path)),routes:paths.filter(path=>/route|router/i.test(path)),styles:paths.filter(path=>/css|style|theme/i.test(path)),a11ySignals:(joined.match(/aria-|role=|tabIndex/g)||[]).length};if(domain==='LARGE_STATE')return {...base,stores:paths.filter(path=>/store|state|reducer|slice/i.test(path)),mutationSignals:(joined.match(/setState|dispatch|update|mutate|reducer/g)||[]).length,asyncSignals:(joined.match(/Promise|async |subscribe|effect/g)||[]).length};if(domain==='EXTERNAL_API')return {...base,contracts:paths.filter(path=>/openapi|schema|contract|dto/i.test(path)),clients:paths.filter(path=>/client|api|gateway/i.test(path)),routes:paths.filter(path=>/route|controller|endpoint/i.test(path)),errorSignals:(joined.match(/status|error|retry|timeout/g)||[]).length};if(domain==='ADVANCED_PERFORMANCE')return {...base,hotspotSignals:(joined.match(/\.filter\(|\.map\(|for\s*\(|JSON\.parse|JSON\.stringify/g)||[]).length,cacheSignals:(joined.match(/cache|memo|Map\(|Set\(/g)||[]).length,benchmarkFiles:paths.filter(path=>/bench|perf|load/i.test(path))};if(domain==='THREAT_MODEL')return {...base,authFiles:paths.filter(path=>/auth|permission|policy|guard/i.test(path)),inputSignals:(joined.match(/validate|sanitize|parse|schema/g)||[]).length,dangerousSinks:(joined.match(/eval\(|innerHTML|exec\(|spawn\(|SELECT.*\+/g)||[]).length,secretSignals:(joined.match(/api[_-]?key|secret|token|password/gi)||[]).length};if(domain==='COMPLEX_DB_MIGRATION')return {...base,migrations:paths.filter(path=>/migration|schema|database|sql/i.test(path)),transactionSignals:(joined.match(/transaction|commit|rollback/g)||[]).length,backfillSignals:(joined.match(/backfill|batch|cursor|checkpoint/g)||[]).length};return {...base,repositories:[...new Set(paths.map(path=>path.split('/')[0]))],packageManifests:paths.filter(path=>/package\.json|pom\.xml|build\.gradle|cargo\.toml/i.test(path)),lockFiles:paths.filter(path=>/lock|shrinkwrap/i.test(path))};}
 private blockers(domain:AdvancedDepthDomain,evidence:Record<string,unknown>){const reasons:string[]=[];if(Number(evidence.fileCount||0)===0)reasons.push('NO_REPOSITORY_EVIDENCE');if(domain==='EXTERNAL_API'&&!(evidence.contracts as unknown[])?.length)reasons.push('API_CONTRACT_NOT_FOUND');if(domain==='ADVANCED_PERFORMANCE'&&!(evidence.benchmarkFiles as unknown[])?.length)reasons.push('PERFORMANCE_BASELINE_REQUIRED');if(domain==='COMPLEX_DB_MIGRATION'&&!(evidence.migrations as unknown[])?.length)reasons.push('MIGRATION_HISTORY_NOT_FOUND');if(domain==='MULTI_REPOSITORY'&&Number((evidence.repositories as unknown[])?.length||0)<2)reasons.push('MULTIPLE_REPOSITORIES_NOT_DISCOVERED');return reasons;}
 private gates(domain:AdvancedDepthDomain){return {COMPLEX_UI:['COMPONENT_TREE','ROUTE_REACHABILITY','STATE_BINDING','INTERACTION','ACCESSIBILITY','RESPONSIVE','VISUAL_REGRESSION'],LARGE_STATE:['STATE_GRAPH','OWNERSHIP','IMMUTABILITY','CONCURRENCY','PERSISTENCE','REHYDRATION','ROLLBACK'],EXTERNAL_API:['CONTRACT_DIFF','SERVER_ROUTE','CLIENT_CALLSITE','AUTH','ERROR_MODEL','RETRY_TIMEOUT','BACKWARD_COMPATIBILITY','CONTRACT_TEST'],ADVANCED_PERFORMANCE:['BASELINE','WARMUP','MEDIAN','P95','MEMORY','OUTPUT_EQUIVALENCE','REGRESSION_BUDGET'],THREAT_MODEL:['ASSET','ACTOR','TRUST_BOUNDARY','STRIDE','AUTHN','AUTHZ','INPUT','SECRET','DANGEROUS_SINK','COUNTEREXAMPLE'],COMPLEX_DB_MIGRATION:['VERSION_GRAPH','FORWARD','BACKWARD','TRANSACTION','BACKFILL','CHECKPOINT','IDEMPOTENCY','ZERO_DOWNTIME','ROLLBACK','DATA_INVARIANT'],MULTI_REPOSITORY:['DEPENDENCY_GRAPH','REVISION_PIN','BUILD_ORDER','CONTRACT_COMPATIBILITY','ATOMIC_CANDIDATE','PARTIAL_FAILURE','ROLLBACK_ORDER']}[domain];}
 private operations(domain:AdvancedDepthDomain,paths:string[]){return paths.slice(0,40).map(path=>({path,operation:'REPOSITORY_SPECIFIC_AST_OR_MODEL_TRANSFORMATION',anchor:`${domain}:${canonicalSha256(path).slice(0,12)}`}));}
 private match(domain:AdvancedDepthDomain,path:string,content:string){const text=`${path}\n${content}`.toLowerCase();const terms={COMPLEX_UI:['component','tsx','route','theme','aria'],LARGE_STATE:['store','state','reducer','dispatch','effect'],EXTERNAL_API:['api','route','openapi','client','webhook'],ADVANCED_PERFORMANCE:['performance','benchmark','cache','batch','worker'],THREAT_MODEL:['auth','permission','policy','sanitize','secret'],COMPLEX_DB_MIGRATION:['migration','schema','database','sql','backfill'],MULTI_REPOSITORY:['package.json','workspace','dependency','repository','lock']}[domain];return terms.some(term=>text.includes(term));}
}
export const advancedDevelopmentDepthExecutorService=new AdvancedDevelopmentDepthExecutorService();
