import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
export type DataArchitecturePattern='EXTEND_EXISTING'|'VERSIONED_ENVELOPE'|'NORMALIZED_RECORDS'|'ID_KEYED_MAP'|'READ_WRITE_SPLIT';
export interface DataArchitectureCandidate { pattern:DataArchitecturePattern; score:number; benefits:string[]; risks:string[]; migrationSteps:string[]; affectedPaths:string[]; }
export interface DataArchitecturePlan { planId:string; objective:string; selected:DataArchitectureCandidate; candidates:DataArchitectureCandidate[]; invariants:string[]; }
class DataArchitecturePlannerService {
 public plan(objective:string,targetTerms:string[]=[]):DataArchitecturePlan {const files=selfCodeSpaceService.listSourceFiles();const terms=[...targetTerms,...objective.split(/[^A-Za-z0-9_\u3040-\u30ff\u3400-\u9fff]+/)].filter(term=>term.length>=3);const affected=files.filter(file=>terms.some(term=>file.path.toLowerCase().includes(term.toLowerCase())||file.content.toLowerCase().includes(term.toLowerCase()))).map(file=>file.path).slice(0,80);const patterns:DataArchitecturePattern[]=['EXTEND_EXISTING','VERSIONED_ENVELOPE','NORMALIZED_RECORDS','ID_KEYED_MAP','READ_WRITE_SPLIT'];const candidates=patterns.map(pattern=>this.candidate(pattern,objective,affected));candidates.sort((a,b)=>b.score-a.score);return {planId:`DARCH-${canonicalSha256({objective,affected,candidates}).slice(0,24)}`,objective,selected:candidates[0],candidates,invariants:['BACKWARD_COMPATIBILITY','NO_DATA_LOSS','DETERMINISTIC_MIGRATION','ROLLBACK_AVAILABLE','CALLSITE_AND_TEST_PROPAGATION']}; }
 private candidate(pattern:DataArchitecturePattern,objective:string,affectedPaths:string[]):DataArchitectureCandidate {const complexity={EXTEND_EXISTING:1,VERSIONED_ENVELOPE:2,NORMALIZED_RECORDS:4,ID_KEYED_MAP:3,READ_WRITE_SPLIT:5}[pattern];const fit=(/将来|拡張|version|互換/i.test(objective)&&pattern==='VERSIONED_ENVELOPE'?5:0)+(/検索|id|参照/i.test(objective)&&pattern==='ID_KEYED_MAP'?4:0)+(/重複|正規化/i.test(objective)&&pattern==='NORMALIZED_RECORDS'?5:0);return {pattern,score:10+fit-complexity-Math.min(4,affectedPaths.length/20),benefits:[`${pattern}による明示的構造改善`,'型・保存・呼出し元を同一Candidateで更新'],risks:[`変更対象${affectedPaths.length}ファイル`,'Migrationと後方互換の検証が必要'],migrationSteps:['現行Schemaを読込','新Schemaへ決定論的変換','旧形式読込互換を維持','Round Trip Test','失敗時Rollback'],affectedPaths:[...affectedPaths]}; }
}
export const dataArchitecturePlannerService=new DataArchitecturePlannerService();
