import { browserE2EReviewPackageGateService } from './browserE2EReviewPackageGateService';
import JSZip from 'jszip';
import { semanticReviewPackageGateService } from './semanticReviewPackageGateService';
import { semanticTransactionReviewEvidenceService } from './semanticTransactionReviewEvidenceService';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { contextClosureReceiptService } from '../../core/services/contextClosureReceiptService';
export interface EvaluationPackageInput { packageId:string; manifest:Record<string,unknown>; files:Array<{path:string;content:string}>; semanticEvidence?:{manifest:Record<string,unknown>;files:Array<{path:string;content:string}>}; }
export interface EvaluationPackageOutput { packageId:string; zipBytes:Uint8Array; zipTxtBytes:Uint8Array; zipSha256:string; fileCount:number; }
class EvaluationPackageExportService {
 public async create(input:EvaluationPackageInput):Promise<EvaluationPackageOutput>{const zip=new JSZip();const txId=typeof input.manifest.transactionId==='string'?input.manifest.transactionId:undefined;const semanticEvidence=input.semanticEvidence||(txId?semanticTransactionReviewEvidenceService.get(txId):undefined);const semanticFiles=semanticEvidence?.files||[];const contextReceiptId=typeof input.manifest.contextReceiptId==='string'?input.manifest.contextReceiptId:undefined;const contextReceipt=contextReceiptId?contextClosureReceiptService.get(contextReceiptId):undefined;if(contextReceiptId&&!contextReceipt)throw new Error('CONTEXT_CLOSURE_RECEIPT_NOT_FOUND');if(contextReceipt&&contextReceipt.status!=='CLOSED')throw new Error('CONTEXT_CLOSURE_RECEIPT_INCOMPLETE');const contextFiles=contextReceipt?[{path:'review/CONTEXT_CLOSURE_RECEIPT.json',content:JSON.stringify(contextReceipt,null,2)}]:[];const sorted=[...input.files,...semanticFiles,...contextFiles].sort((a,b)=>a.path.localeCompare(b.path));for(const file of sorted)zip.file(file.path,file.content);const manifest={...input.manifest,semanticTransaction:semanticEvidence?.manifest,contextClosure:contextReceipt};zip.file('EVALUATION_MANIFEST.json',JSON.stringify(manifest,null,2));const zipBytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});if(txId){const gate=await semanticReviewPackageGateService.verify(zipBytes,txId);if(!gate.passed)throw new Error(`SEMANTIC_REVIEW_PACKAGE_GATE_FAILED:${gate.reasons.join('|')}`);}const transactionId=typeof input.manifest.transactionId==='string'?input.manifest.transactionId:undefined;const gate=await semanticReviewPackageGateService.verify(zipBytes,transactionId);if(!gate.passed)throw new Error(`SEMANTIC_REVIEW_PACKAGE_GATE_FAILED:${gate.reasons.join('|')}`);const browserGate=await browserE2EReviewPackageGateService.verify(zipBytes);if(!browserGate.passed)throw new Error(`BROWSER_E2E_REVIEW_PACKAGE_GATE_FAILED:${browserGate.reasons.join('|')}`);const zipTxtBytes=new Uint8Array(zipBytes);return {packageId:input.packageId,zipBytes,zipTxtBytes,zipSha256:canonicalSha256(Array.from(zipBytes)),fileCount:sorted.length+1};}
}
export const evaluationPackageExportService=new EvaluationPackageExportService();
