import { storageService } from '../../../services/storageService';
import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
import { formalAdoptionAuthorizationService, type FormalAdoptionAuthorization } from './formalAdoptionAuthorizationService';
const KEY='miki_formal_adoption_authorization_ledger_v1';
const QUARANTINE_KEY='miki_formal_adoption_authorization_ledger_quarantine_v1';
export type AuthorizationLedgerStatus='ISSUED'|'CLAIMED'|'CONSUMED'|'STALE'|'REVOKED';
export interface AuthorizationLedgerRecord{authorization:FormalAdoptionAuthorization;status:AuthorizationLedgerStatus;candidateId:string;claimedAt?:number;consumedAt?:number;invalidatedAt?:number;reason?:string;taskId?:string;recordSha256:string;}
class FormalAdoptionAuthorizationLedgerService{
 private validRecord(row:AuthorizationLedgerRecord):boolean{const {recordSha256,...unsigned}=row;return canonicalSha256Object(unsigned)===recordSha256&&formalAdoptionAuthorizationService.validate(row.authorization).length===0;}
 private load():AuthorizationLedgerRecord[]{try{const parsed=JSON.parse(storageService.getItem(KEY)||'[]');const rows=Array.isArray(parsed)?parsed as AuthorizationLedgerRecord[]:[];const valid=rows.filter(row=>this.validRecord(row));const invalid=rows.filter(row=>!this.validRecord(row));if(invalid.length){storageService.setItem(QUARANTINE_KEY,JSON.stringify(invalid));storageService.setItem(KEY,JSON.stringify(valid));}return valid;}catch{return[];}}
 private save(rows:AuthorizationLedgerRecord[]):void{storageService.setItem(KEY,JSON.stringify(rows.slice(0,1000)));}
 private replace(rows:AuthorizationLedgerRecord[],index:number,base:Omit<AuthorizationLedgerRecord,'recordSha256'>):AuthorizationLedgerRecord{const next={...base,recordSha256:canonicalSha256Object(base)};rows[index]=next;this.save(rows);return next;}
 register(a:FormalAdoptionAuthorization):AuthorizationLedgerRecord{const errors=formalAdoptionAuthorizationService.validate(a);if(errors.length)throw new Error(errors.join('|'));const unsigned={authorization:a,status:'ISSUED' as const,candidateId:a.candidateId};const record={...unsigned,recordSha256:canonicalSha256Object(unsigned)};const rows=this.load().filter(x=>x.authorization.authorizationId!==a.authorizationId);rows.unshift(record);this.save(rows);return record;}
 list(candidateId?:string):AuthorizationLedgerRecord[]{return this.load().filter(x=>!candidateId||x.candidateId===candidateId);}
 listQuarantined():AuthorizationLedgerRecord[]{try{const x=JSON.parse(storageService.getItem(QUARANTINE_KEY)||'[]');return Array.isArray(x)?x:[];}catch{return[];}}
 claim(authorizationId:string,taskId:string):AuthorizationLedgerRecord{const rows=this.load();const index=rows.findIndex(x=>x.authorization.authorizationId===authorizationId);if(index<0)throw new Error('ADOPTION_AUTHORIZATION_NOT_REGISTERED');const current=rows[index];if(current.status!=='ISSUED')throw new Error(`ADOPTION_AUTHORIZATION_REPLAY_BLOCKED:${current.status}`);const {recordSha256:_old,...base}=current;return this.replace(rows,index,{...base,status:'CLAIMED',claimedAt:Date.now(),taskId});}
 consume(authorizationId:string):AuthorizationLedgerRecord{const rows=this.load();const index=rows.findIndex(x=>x.authorization.authorizationId===authorizationId);if(index<0||rows[index].status!=='CLAIMED')throw new Error('ADOPTION_AUTHORIZATION_NOT_CLAIMED');const {recordSha256:_old,...base}=rows[index];return this.replace(rows,index,{...base,status:'CONSUMED',consumedAt:Date.now()});}
 release(authorizationId:string,reason:string,retryable:boolean):AuthorizationLedgerRecord{const rows=this.load();const index=rows.findIndex(x=>x.authorization.authorizationId===authorizationId);if(index<0||rows[index].status!=='CLAIMED')throw new Error('ADOPTION_AUTHORIZATION_NOT_CLAIMED');const {recordSha256:_old,claimedAt:_claimed,taskId:_task,...base}=rows[index];return this.replace(rows,index,{...base,status:retryable?'ISSUED':'STALE',invalidatedAt:Date.now(),reason});}
 invalidateCandidate(candidateId:string,reason:string):void{const rows=this.load();rows.forEach((row,index)=>{if(row.candidateId===candidateId&&['ISSUED','CLAIMED'].includes(row.status)){const {recordSha256:_old,...base}=row;this.replace(rows,index,{...base,status:'STALE',invalidatedAt:Date.now(),reason});}});}
}
export const formalAdoptionAuthorizationLedgerService=new FormalAdoptionAuthorizationLedgerService();
