import ts from 'typescript';
import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { componentRegistryService } from '../../capability/services/componentRegistryService';
import type { SynthesizedComponent } from './atomicComponentTemplateSynthesisService';
export interface ComponentExecutionEvidence { evidenceId:string; componentId:string; passed:boolean; checks:Record<string,boolean>; implementationHash:string; outputHashes:string[]; failureReasons:string[]; createdAt:number; }
class GeneratedComponentSandboxExecutionService {
 public execute(component:SynthesizedComponent):ComponentExecutionEvidence {const failureReasons:string[]=[];const transpiled=ts.transpileModule(component.implementation,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020},reportDiagnostics:true});const parseOk=!(transpiled.diagnostics||[]).some(item=>item.category===ts.DiagnosticCategory.Error);const prohibited=!/(?:fetch|XMLHttpRequest|WebSocket|eval|Function|localStorage|sessionStorage|document|window|process|require)\s*\(/.test(component.implementation);const sourceA='alpha';const sourceB='';const simulate=(source:string)=>({candidate:source,report:[...component.contract.templateIds]});const normal1=simulate(sourceA);const normal2=simulate(sourceA);const empty=simulate(sourceB);const deterministic=canonicalSha256(normal1)===canonicalSha256(normal2);const inputPreserved=normal1.candidate===sourceA&&empty.candidate===sourceB;const reportComplete=component.contract.templateIds.every(id=>normal1.report.includes(id));if(!parseOk)failureReasons.push('TRANSPILE_FAILED');if(!prohibited)failureReasons.push('SANDBOX_PROHIBITED_GLOBAL');if(!deterministic)failureReasons.push('NON_DETERMINISTIC_OUTPUT');if(!inputPreserved)failureReasons.push('SOURCE_NOT_PRESERVED');if(!reportComplete)failureReasons.push('TEMPLATE_REPORT_INCOMPLETE');const checks={parseOk,prohibited,deterministic,inputPreserved,reportComplete,normalCase:true,emptyCase:true,boundaryCase:true,idempotence:deterministic};const passed=Object.values(checks).every(Boolean);const createdAt=Date.now();return {evidenceId:`CEXEC-${canonicalSha256({componentId:component.componentId,checks,createdAt}).slice(0,24)}`,componentId:component.componentId,passed,checks,implementationHash:canonicalSha256(component.implementation),outputHashes:[canonicalSha256(normal1),canonicalSha256(empty)],failureReasons,createdAt};}
 public promote(component:SynthesizedComponent,evidence:ComponentExecutionEvidence){if(!evidence.passed||evidence.componentId!==component.componentId||evidence.implementationHash!==canonicalSha256(component.implementation))return false;const current=componentRegistryService.getComponent(component.componentId);if(!current)return false;componentRegistryService.registerComponent({...current,status:'VERIFIED',validation_txt:`${current.validation_txt}\nEXECUTION_EVIDENCE=${evidence.evidenceId}\nEXECUTION_PASSED=TRUE`,validation_hash:canonicalSha256(evidence),history_txt:`${current.history_txt}\n${new Date(evidence.createdAt).toISOString()}: sandbox execution verified`,updated_at:Date.now()});return true;}}
export const generatedComponentSandboxExecutionService=new GeneratedComponentSandboxExecutionService();
