import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
import { selfCodeSpaceService } from '../../core/services/selfCodeSpaceService';
import { isolatedCandidateWorkspaceService } from '../../core/services/isolatedCandidateWorkspaceService';
import { repositoryNamingConventionService } from './repositoryNamingConventionService';
import type { ItemFamilyExpansionPlan } from './itemFamilyExpansionPlannerService';
export interface ChangeResultManifest { manifestId:string; operation:'ITEM_EXPANSION'; addedItems:Array<{name:string;key:string}>; changedFiles:string[]; inspectedFiles:string[]; unchangedRelatedFiles:Array<{path:string;reason:string}>; checks:string[]; }
class ItemExpansionExecutorService {async execute(plan:ItemFamilyExpansionPlan,runId?:string){if(plan.reasons.length)throw new Error(plan.reasons.join('|'));const convention=repositoryNamingConventionService.infer([plan.familyName,...plan.proposedNames]);const items=plan.items.map(item=>({...item,key:repositoryNamingConventionService.format(item.name,convention)}));const source=selfCodeSpaceService.listSourceFiles();const changedFiles=[`src/generated/itemFamilies/${this.stem(plan.familyName)}Items.ts`,`src/generated/itemFamilies/${this.stem(plan.familyName)}Items.test.mjs`];const definition=`export interface GeneratedItemDefinition { name:string; key:string; attributes:Record<string,string|number|boolean>; }\nexport const generated${this.symbol(plan.familyName)}Items:GeneratedItemDefinition[]=${JSON.stringify(items,null,2)};\n`;
const test=`import assert from 'node:assert/strict';\nconst items=${JSON.stringify(items)};\nassert.equal(items.length,${items.length});\nassert.equal(new Set(items.map(item=>item.key)).size,items.length);\nconsole.log('item expansion verified');\n`;
const manifest:ChangeResultManifest={manifestId:`CHGM-${canonicalSha256({plan:plan.planId,items,changedFiles}).slice(0,24)}`,operation:'ITEM_EXPANSION',addedItems:items.map(({name,key})=>({name,key})),changedFiles,inspectedFiles:[...plan.affectedPaths],unchangedRelatedFiles:plan.affectedPaths.map(path=>({path,reason:'Safe generated registry used; direct mutation requires repository-specific anchor evidence'})),checks:[...plan.acceptanceChecks]};const workspace=await isolatedCandidateWorkspaceService.create(`item-expansion:${plan.planId}`,[{path:changedFiles[0],baselineContent:'',candidateContent:definition,evidenceIds:[plan.planId,manifest.manifestId]},{path:changedFiles[1],baselineContent:'',candidateContent:test,evidenceIds:[plan.planId,manifest.manifestId]},{path:'review/change_result_manifest.json',baselineContent:'',candidateContent:JSON.stringify(manifest,null,2),evidenceIds:[manifest.manifestId]}],runId);return {workspace,manifest,convention};}private stem(value:string){return value.replace(/[^A-Za-z0-9]+/g,'_').replace(/^_+|_+$/g,'').toLowerCase()||'generated';}private symbol(value:string){const stem=this.stem(value);return stem.split('_').map(value=>value[0]?.toUpperCase()+value.slice(1)).join('')||'Generated';}}
export const itemExpansionExecutorService=new ItemExpansionExecutorService();
