import { canonicalSha256 } from '../../core/services/canonicalSha256Service';import { capabilityProofRegistryService } from './capabilityProofRegistryService';
export interface BuildNode{nodeId:string;repositoryId:string;revision:string;dependencies:string[];command:string;artifactInputs:string[];artifactOutputs:string[];generatedCode:boolean;}
class ProductionScaleDevelopmentService{
 buildGraph(nodes:BuildNode[]){const order:string[]=[];const pending=new Map(nodes.map(n=>[n.nodeId,n]));while(pending.size){const ready=[...pending.values()].filter(n=>n.dependencies.every(d=>order.includes(d))).sort((a,b)=>a.nodeId.localeCompare(b.nodeId));if(!ready.length)return {accepted:false,reasons:['BUILD_GRAPH_CYCLE'],order:[],rollbackOrder:[]};for(const n of ready){order.push(n.nodeId);pending.delete(n.nodeId);}}return {accepted:true,graphId:`BG-${canonicalSha256(nodes).slice(0,22)}`,order,rollbackOrder:[...order].reverse(),parallelLayers:this.layers(nodes),atomicCompletionRequired:true,artifactHashRequired:true,repositoryManifests:nodes.map(n=>({repositoryId:n.repositoryId,revision:n.revision,nodeId:n.nodeId}))};}
 merge(input:{base:string;left:string;right:string;kind:'TS'|'JSON'|'YAML'|'LOCKFILE'|'MIGRATION';symbol?:string}){if(input.left===input.right)return {merged:input.left,conflict:false,evidence:['IDENTICAL_BRANCH']};if(input.left===input.base)return {merged:input.right,conflict:false,evidence:['LEFT_UNCHANGED']};if(input.right===input.base)return {merged:input.left,conflict:false,evidence:['RIGHT_UNCHANGED']};return {merged:undefined,conflict:true,evidence:[`THREE_WAY_CONFLICT:${input.kind}`,input.symbol?`SYMBOL:${input.symbol}`:'FILE_LEVEL'],requiresFullRevalidation:true};}
 cacheKey(input:{repositoryRevision:string;candidateSha256:string;environmentFingerprint:string;toolchainVersion:string;dependencyLockHash:string;commandHash:string;inputArtifactHashes:string[]}){return `CACHE-${canonicalSha256({...input,inputArtifactHashes:[...input.inputArtifactHashes].sort()})}`;}
 risk(input:{publicContract:boolean;coreAuthority:boolean;storageSchema:boolean;securityBoundary:boolean;repositoryCount:number;rollback:boolean;characterization:boolean;dynamicCalls:number;externalApi:boolean;deviceProof:boolean;staleEvidence:boolean;survivingMutations:number;largeMigration:boolean;singlePoint:boolean}){let score=0;for(const value of [input.publicContract,input.coreAuthority,input.storageSchema,input.securityBoundary,!input.rollback,!input.characterization,input.externalApi,!input.deviceProof,input.staleEvidence,input.largeMigration,input.singlePoint])if(value)score+=10;score+=Math.min(20,input.repositoryCount*2)+Math.min(10,input.dynamicCalls)+Math.min(20,input.survivingMutations*5);const level=score>=80?'CRITICAL':score>=55?'HIGH':score>=25?'MEDIUM':'LOW';const requiredProof=level==='CRITICAL'?['DEVICE_PROVEN','CANARY','HUMAN_REVIEW']:level==='HIGH'?['SANDBOX_PROVEN','FULL_BUILD','E2E','ROLLBACK']:level==='MEDIUM'?['SANDBOX_PROVEN','REGRESSION']:['STATICALLY_SUPPORTED','AFFECTED_TEST'];return {score,level,requiredProof};}
 proofGate(capability:string,environmentFingerprint:string,repositoryRevision:string,required:'STATIC_PROVEN'|'SANDBOX_PROVEN'|'DEVICE_PROVEN'){return capabilityProofRegistryService.gate(capability,environmentFingerprint,repositoryRevision,required);}
 cost(input:{files:number;symbols:number;repositories:number;buildMinutes:number;testMinutes:number;mutations:number;browserScenarios:number;dbGb:number;diskGb:number;networkGb:number;repairs:number;zipMb:number},budget:{minutes:number;diskGb:number;networkGb:number}){const minutes=input.buildMinutes+input.testMinutes+input.mutations*.1+input.browserScenarios*.2+input.repairs*5;const exceeded=minutes>budget.minutes||input.diskGb>budget.diskGb||input.networkGb>budget.networkGb;return {minutes,exceeded,actions:exceeded?['WAVE_SPLIT','AFFECTED_SCOPE','BACKGROUND_JOB','OFF_HOURS_FULL_TEST','REQUEST_ENVIRONMENT']:[]};}
 transformationCoverage(operation:string,stats:{generated:number;applied:number;parsePassed:number;typePassed:number;runtimePassed:number;rollbackPassed:number;unsupported:string[]}){const denominator=Math.max(1,stats.generated);const supported=stats.unsupported.length===0&&stats.rollbackPassed===stats.applied;return {operation,coverage:{apply:stats.applied/denominator,parse:stats.parsePassed/denominator,type:stats.typePassed/denominator,runtime:stats.runtimePassed/denominator,rollback:stats.rollbackPassed/denominator},supported,route:supported?'EXECUTE':'CAPABILITY_GAP'};}
 characterization(observations:Array<{inputHash:string;returnHash?:string;error?:string;logs:string[];dbHash?:string;fileHash?:string;events:string[];requests:string[];uiHash?:string;timingMs:number;cacheHash?:string;retryCount:number;externalCalls:string[]}>){return {suiteId:`CHAR-${canonicalSha256(observations).slice(0,22)}`,baselineHash:canonicalSha256(observations),cases:observations,requiresBaselinePass:true,allowedDifferencePolicy:'EXPLICIT_ONLY'};}
 private layers(nodes:BuildNode[]){const layers:string[][]=[];const done=new Set<string>();while(done.size<nodes.length){const layer=nodes.filter(n=>!done.has(n.nodeId)&&n.dependencies.every(d=>done.has(d))).map(n=>n.nodeId).sort();if(!layer.length)break;layers.push(layer);layer.forEach(id=>done.add(id));}return layers;}}
export const productionScaleDevelopmentService=new ProductionScaleDevelopmentService();
