import { canonicalSha256 } from '../../core/services/canonicalSha256Service';
export interface SemanticCondition{when:string;allow?:string;prohibit?:string;actor?:string;}
export interface SemanticReference{expression:string;antecedent?:string;resolved:boolean;}
export interface SemanticActionChain{segments:string[];separators:Array<':'|';'>;scope:'PREVIOUS_MUTATION_ROWS'|'ALL_MATCHED_ROWS'|'MIXED'|'SINGLE';source:string;}
export interface SemanticFrameV2{frameId:string;problem:string[];goals:string[];targets:string[];actors:string[];triggers:string[];conditions:SemanticCondition[];prohibitions:string[];exceptions:SemanticCondition[];priorities:string[];quantities:Array<{expression:string;resolved?:number;unit?:string;ambiguous:boolean}>;qualityAttributes:string[];successMetrics:string[];failureBehaviors:string[];compatibilityRequirements:string[];invariants:string[];unknowns:string[];targetSets:string[];exclusionSets:string[];evaluationOrder:string[];continuationConditions:string[];stopConditions:string[];confirmationConditions:string[];references:SemanticReference[];actionChains:SemanticActionChain[];conflicts:string[];conditionScopes:Array<{condition:string;continuation:string[];stops:string[];exclusions:string[]}>;}
class SemanticFrameV2Service{
 parse(text:string,entities:string[]=[]):SemanticFrameV2{
  const normalized=text.normalize('NFKC');const clauses=normalized.split(/[。\n;；]/).map(value=>value.trim()).filter(Boolean);const pick=(pattern:RegExp)=>clauses.filter(value=>pattern.test(value));
  const prohibitions=pick(/しない|変えず|禁止|不可|触らず|除外/);const exceptions=pick(/ただし|のみ|だけ|例外|管理者/).map(value=>({when:value,allow:value,actor:/管理者/.test(value)?'ADMIN':undefined}));const conditions=pick(/場合|とき|なら|中は|時は/).map(value=>({when:value,prohibit:/しない|不可/.test(value)?value:undefined,allow:/できる|許可/.test(value)?value:undefined}));
  const quantityExpressions=[...normalized.matchAll(/(\d+)\s*(件|個|回|%|ms|秒|分|種類)|もう少し|適度|十分|なるべく|大量|大規模/g)].map(match=>match[0]);const quantities=quantityExpressions.map(expression=>{const number=expression.match(/\d+/);return{expression,resolved:number?Number(number[0]):undefined,unit:expression.match(/件|個|回|%|ms|秒|分|種類/)?.[0],ambiguous:!number};});
  const qualityAttributes=pick(/性能|高速|安全|互換|可用|信頼|アクセシビリティ|安定|停止せず|分かりやす/);const successMetrics=clauses.filter(value=>/p95|中央値|以内|以下|以上|一致|成功|0件|tsc=0/i.test(value));const compatibilityRequirements=pick(/既存|後方互換|古い|旧|壊さず|互換/);const failureBehaviors=pick(/失敗|rollback|ロールバック|停止|復元|timeout|タイムアウト/i);const actors=[...new Set(['管理者','ユーザー','外部サービス','Worker'].filter(value=>normalized.includes(value)))];const priorities=clauses.filter(value=>/>|優先|最優先/.test(value));const goals=clauses.filter(value=>/追加|改善|修正|変更|移行|高速|守る|防ぐ|実装|検証/.test(value));const problem=clauses.filter(value=>/遅|不安定|壊|漏れ|不足|競合|失敗|重い|単調|問題/.test(value));const targets=[...new Set([...entities,...clauses.flatMap(value=>[...value.matchAll(/[A-Za-z_][A-Za-z0-9_.\/-]{2,}/g)].map(match=>match[0]))])].slice(0,80);
  const targetSets=pick(/対象|該当|一致|変更した行|行だけ/);const exclusionSets=pick(/ただし|除外|対象外|変更しない|しないで/);const evaluationOrder=pick(/最初|先に|前段|後段|優先|順序/);const continuationConditions=pick(/継続|続ける|次の条件|以降も評価/);const stopConditions=pick(/以降.*停止|後続.*行わない|評価を停止/);const confirmationConditions=pick(/確認.*後|確認してから|はい|いいえ/);
  const references=clauses.flatMap((value,index)=>[...value.matchAll(/それ|これ|その[^\s、。]*|前段|後段|該当行/g)].map(match=>{const antecedent=[...clauses.slice(0,index)].reverse().find(prior=>/対象|該当|一致|変更|条件/.test(prior));return{expression:match[0],antecedent,resolved:Boolean(antecedent)};}));
  const parseActionChain=(source:string):SemanticActionChain=>{const segments:string[]=[];const separators:Array<':'|';'>=[];let current='';let quote='';for(let index=0;index<source.length;index++){const character=source[index];if(quote){current+=character;if(character===quote&&source[index-1]!=='\\')quote='';continue;}if(character==='"'||character==="'"||character==='「'||character==='『'){quote=character==='「'?'」':character==='『'?'』':character;current+=character;continue;}const ascii=character==='：'?':':character==='；'?';':character;const before=source.slice(0,index);const urlStart=Math.max(before.lastIndexOf('http://'),before.lastIndexOf('https://'));const isSchemeColon=/https?$/i.test(before);const isUrl=isSchemeColon||(urlStart>=0&&!/\s/.test(source.slice(urlStart,index)));const around=source.slice(Math.max(0,index-8),index+6);const isTime=/\d{1,2}:\d{2}/.test(around);if((ascii===':'||ascii===';')&&!isUrl&&!isTime){segments.push(current.trim());separators.push(ascii);current='';}else current+=character;}segments.push(current.trim());const clean=segments.filter(Boolean);const kinds=new Set(separators);const scope=kinds.size>1?'MIXED':separators[0]===':'?'PREVIOUS_MUTATION_ROWS':separators[0]===';'?'ALL_MATCHED_ROWS':'SINGLE';return{segments:clean,separators,scope,source};};
  const actionChains=normalized.split(/[。\n]+/).map(value=>value.trim()).filter(Boolean).map(parseActionChain);
  const conditionScopes=clauses.filter(value=>/場合|とき|なら|条件/.test(value)).map((condition,index)=>{const scoped=[condition];return{condition,continuation:scoped.filter(value=>/継続|続ける|次の条件|以降も評価/.test(value)),stops:scoped.filter(value=>/以降.*停止|後続.*行わない|評価を停止/.test(value)),exclusions:scoped.filter(value=>/ただし|除外|対象外|変更しない/.test(value))};});
  const conflicts:string[]=[];for(const scope of conditionScopes)if(scope.continuation.length&&scope.stops.length&&!priorities.length)conflicts.push(`CONTINUE_STOP_PRIORITY_UNRESOLVED:${scope.condition}`);if(exclusionSets.length&&!targetSets.length)conflicts.push('EXCLUSION_TARGET_UNRESOLVED');for(const chain of actionChains)if(chain.separators.length&&chain.segments.length!==chain.separators.length+1)conflicts.push('ACTION_CHAIN_INCOMPLETE');
  const unknowns:string[]=[];if(!goals.length)unknowns.push('GOAL_UNRESOLVED');if(quantities.some(value=>value.ambiguous))unknowns.push('QUANTITY_AMBIGUOUS');if(exceptions.length&&!actors.length)unknowns.push('EXCEPTION_ACTOR_UNRESOLVED');for(const reference of references)if(!reference.resolved)unknowns.push(`REFERENCE_UNRESOLVED:${reference.expression}`);unknowns.push(...conflicts);
  return{frameId:`SF2-${canonicalSha256({normalized,entities}).slice(0,24)}`,problem,goals,targets,actors,triggers:pick(/クリック|入力|起動|保存|読込|受信|送信|実行したら/),conditions,prohibitions,exceptions,priorities,quantities,qualityAttributes,successMetrics,failureBehaviors,compatibilityRequirements,invariants:[...new Set([...prohibitions,...compatibilityRequirements])],unknowns:[...new Set(unknowns)],targetSets,exclusionSets,evaluationOrder,continuationConditions,stopConditions,confirmationConditions,references,actionChains,conflicts,conditionScopes};
 }
}
export const semanticFrameV2Service=new SemanticFrameV2Service();
