import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
import { unifiedCandidateLifecycleGraphService } from '../../core/services/unifiedCandidateLifecycleGraphService';
export interface CascadeInvalidationAdapter {name:string;priority:number;snapshot(candidateIds:string[]):unknown;invalidate(candidateIds:string[],reason:string,transactionId:string):string[];restore(snapshot:unknown,transactionId:string):void;}
export interface CascadeInvalidationReceipt {transactionId:string;rootCandidateId:string;invalidatedCandidateIds:string[];adapterReceipts:Record<string,string[]>;status:'COMMITTED'|'ROLLED_BACK';reason:string;startedAt:number;completedAt:number;error?:string;}
class PostAdoptionCascadeInvalidationTransactionService {
 private adapters=new Map<string,CascadeInvalidationAdapter>();private receipts=new Map<string,CascadeInvalidationReceipt>();
 registerAdapter(adapter:CascadeInvalidationAdapter){if(this.adapters.has(adapter.name))throw new Error(`CASCADE_ADAPTER_ALREADY_REGISTERED:${adapter.name}`);this.adapters.set(adapter.name,adapter);}
 unregisterAdapter(name:string){this.adapters.delete(name);}
 execute(rootCandidateId:string,reason:string):CascadeInvalidationReceipt {const root=unifiedCandidateLifecycleGraphService.get(rootCandidateId);if(!root)throw new Error(`CANDIDATE_NOT_FOUND:${rootCandidateId}`);if(root.state!=='ADOPTED')throw new Error(`CASCADE_REQUIRES_ADOPTED_ROOT:${root.state}`);const affected=[rootCandidateId,...unifiedCandidateLifecycleGraphService.listDescendants(rootCandidateId).filter(x=>!['INVALIDATED','REJECTED','ROLLED_BACK'].includes(x.state)).map(x=>x.candidateId)];const transactionId=canonicalSha256Object({rootCandidateId,reason,affected,startedAt:Date.now()});const startedAt=Date.now();const adapters=[...this.adapters.values()].sort((a,b)=>a.priority-b.priority||a.name.localeCompare(b.name));const snapshots=new Map<string,unknown>();const applied:CascadeInvalidationAdapter[]=[];const adapterReceipts:Record<string,string[]>={};try{for(const adapter of adapters)snapshots.set(adapter.name,adapter.snapshot(affected));for(const adapter of adapters){adapterReceipts[adapter.name]=adapter.invalidate(affected,reason,transactionId);applied.push(adapter);}for(const id of affected){const node=unifiedCandidateLifecycleGraphService.get(id);if(node&&node.state!=='INVALIDATED')unifiedCandidateLifecycleGraphService.transition(id,'INVALIDATED',reason,[],transactionId);}const receipt={transactionId,rootCandidateId,invalidatedCandidateIds:affected,adapterReceipts,status:'COMMITTED' as const,reason,startedAt,completedAt:Date.now()};this.receipts.set(transactionId,receipt);return receipt;}catch(error){for(const adapter of [...applied].reverse()){try{adapter.restore(snapshots.get(adapter.name),transactionId);}catch{}}const receipt={transactionId,rootCandidateId,invalidatedCandidateIds:[],adapterReceipts,status:'ROLLED_BACK' as const,reason,startedAt,completedAt:Date.now(),error:error instanceof Error?error.message:String(error)};this.receipts.set(transactionId,receipt);return receipt;}}
 getReceipt(id:string){return this.receipts.get(id);}
}
export const postAdoptionCascadeInvalidationTransactionService=new PostAdoptionCascadeInvalidationTransactionService();
