import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
export interface CandidateUtilityVector {performanceGain:number;memoryCost:number;safetyRisk:number;compatibilityRisk:number;changeSurface:number;rollbackCost:number;rustMigrationValue:number;validationConfidence:number;}
export interface CandidateSelectionInput {candidateId:string;vector:CandidateUtilityVector;eligible:boolean;rejectionReasons?:string[];}
export interface CandidateSelectionPolicy {weights:CandidateUtilityVector;hardLimits:Partial<Pick<CandidateUtilityVector,'memoryCost'|'safetyRisk'|'compatibilityRisk'|'changeSurface'|'rollbackCost'>>;}
export interface CandidateSelectionResult {selectedCandidateId?:string;paretoFront:string[];scores:Record<string,number>;rejected:Record<string,string[]>;decisionSha256:string;}
const DEFAULT_POLICY:CandidateSelectionPolicy={weights:{performanceGain:.2,memoryCost:.1,safetyRisk:.2,compatibilityRisk:.15,changeSurface:.1,rollbackCost:.1,rustMigrationValue:.05,validationConfidence:.1},hardLimits:{safetyRisk:.45,compatibilityRisk:.6,rollbackCost:.75}};
const benefit=(v:CandidateUtilityVector)=>[v.performanceGain,v.rustMigrationValue,v.validationConfidence];const cost=(v:CandidateUtilityVector)=>[v.memoryCost,v.safetyRisk,v.compatibilityRisk,v.changeSurface,v.rollbackCost];
function dominates(a:CandidateUtilityVector,b:CandidateUtilityVector){const av=[...benefit(a),...cost(a).map(x=>-x)],bv=[...benefit(b),...cost(b).map(x=>-x)];return av.every((x,i)=>x>=bv[i])&&av.some((x,i)=>x>bv[i]);}
class UnifiedMultiObjectiveCandidateSelectorService {
 select(inputs:CandidateSelectionInput[],policy:CandidateSelectionPolicy=DEFAULT_POLICY):CandidateSelectionResult {const ids=new Set<string>();const rejected:Record<string,string[]>={};const viable=inputs.filter(input=>{if(!input.candidateId||ids.has(input.candidateId))throw new Error(`DUPLICATE_OR_EMPTY_CANDIDATE:${input.candidateId}`);ids.add(input.candidateId);const reasons=[...(input.rejectionReasons||[])];if(!input.eligible)reasons.push('NOT_ELIGIBLE');for(const [key,limit] of Object.entries(policy.hardLimits) as [keyof CandidateUtilityVector,number][])if(input.vector[key]>limit)reasons.push(`HARD_LIMIT_${key}`);for(const [key,value] of Object.entries(input.vector))if(!Number.isFinite(value)||value<0||value>1)reasons.push(`INVALID_VECTOR_${key}`);if(reasons.length)rejected[input.candidateId]=[...new Set(reasons)];return reasons.length===0;});const pareto=viable.filter(candidate=>!viable.some(other=>other.candidateId!==candidate.candidateId&&dominates(other.vector,candidate.vector)));const scores:Record<string,number>={};for(const item of pareto){const v=item.vector,w=policy.weights;scores[item.candidateId]=v.performanceGain*w.performanceGain+v.rustMigrationValue*w.rustMigrationValue+v.validationConfidence*w.validationConfidence-v.memoryCost*w.memoryCost-v.safetyRisk*w.safetyRisk-v.compatibilityRisk*w.compatibilityRisk-v.changeSurface*w.changeSurface-v.rollbackCost*w.rollbackCost;}pareto.sort((a,b)=>(scores[b.candidateId]-scores[a.candidateId])||a.candidateId.localeCompare(b.candidateId));const body={selectedCandidateId:pareto[0]?.candidateId,paretoFront:pareto.map(x=>x.candidateId),scores,rejected};return {...body,decisionSha256:canonicalSha256Object(body)};}
}
export const unifiedMultiObjectiveCandidateSelectorService=new UnifiedMultiObjectiveCandidateSelectorService();
