import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const checks=[];const add=(name,ok)=>checks.push({name,passed:Boolean(ok)});
const assessment=read('src/miki/improvement/services/improvementAssessmentService.ts');
const planner=read('src/miki/core/services/adaptiveRoutePlannerService.ts');
const router=read('src/miki/core/services/domainRouterService.ts');
const bootstrap=read('src/miki/core/services/domainIntegrationBootstrapService.ts');
const core=read('src/miki/core/services/coreOrchestratorService.ts');
add('proposed operation union',assessment.includes('ProposedImprovementOperationType'));
add('proposal metadata',/priority: number/.test(assessment)&&/idempotencyKey: string/.test(assessment)&&/dedupeKey: string/.test(assessment));
add('source hash separated',assessment.includes('sourceArtifactHashes')&&!assessment.includes('pendingRuns.map((run) => String(run.sourceHash || \'\')).filter(Boolean);\n    const proposedOperations'));
add('real assessment evidence',assessment.includes('recordExecutionEvidence'));
add('legacy controller history removed',!assessment.includes('selfImprovementControllerService'));
add('task identity fail closed',assessment.includes('ASSESSMENT_WORKFLOW_IDENTITY_REQUIRED'));
add('domain commands defined',router.includes('PLAN_PENDING_IMPROVEMENT_RUN')&&router.includes('RESOLVE_CAPABILITY_GAPS')&&router.includes('DISCOVER_IMPROVEMENT_ISSUE'));
add('core consumes proposals',planner.includes('Assessment proposal adopted by core'));
add('handlers bound',bootstrap.includes("envelope.command==='PLAN_PENDING_IMPROVEMENT_RUN'")&&bootstrap.includes("envelope.command==='RESOLVE_CAPABILITY_GAPS'")&&bootstrap.includes("envelope.command==='DISCOVER_IMPROVEMENT_ISSUE'"));
add('core deduplicates accepted proposal',core.includes('proposedOperationSucceeded:${proposalKey}')&&core.includes("status:'OPERATION_SUCCEEDED'"));
const failed=checks.filter(x=>!x.passed);console.log(JSON.stringify({passed:failed.length===0,checks},null,2));process.exit(failed.length?1:0);
