import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const checks=[];const check=(name,ok)=>{checks.push({name,ok});console.log(`${ok?'PASS':'FAIL'} ${name}`)};
const loop=read('src/miki/core/services/autonomousSelfImprovementLoopService.ts');
const review=read('src/miki/core/services/reviewZipExportService.ts');
const discovery=read('src/miki/core/services/autonomousIssueDiscoveryService.ts');
check('preflight wired',loop.includes('selfImprovementPreflightService.evaluate'));
check('complexity gate wired',loop.includes('complexityCostGateService.evaluate'));
check('integrity auditor wired',loop.includes('runIntegrityAuditorService.audit'));
check('cumulative revalidation wired',loop.includes('cumulativeRevalidationService.run'));
check('completion after audit',loop.indexOf('runIntegrityAuditorService.audit')<loop.indexOf("status: 'COMPLETED'"));
check('review export does not complete early',!review.includes("status:'COMPLETED'"));
check('improvement debt discovery',discovery.includes("'IMPROVEMENT_DEBT'")&&discovery.includes('improvementDebtService.listOpen'));
check('environment router wired',read('src/miki/core/services/candidateValidationRunnerService.ts').includes('executionEnvironmentRouterService.route'));
check('all services exported',['selfImprovementPreflightService','runIntegrityAuditorService','improvementDebtService','executionEnvironmentRouterService','complexityCostGateService','cumulativeRevalidationService'].every(x=>read('src/miki/core.ts').includes(x)));
if(checks.some(x=>!x.ok))process.exit(1);
