import fs from 'node:fs';
const checks=[]; const add=(n,v)=>checks.push({name:n,passed:Boolean(v)});
const read=p=>fs.readFileSync(p,'utf8');
const gateway=read('src/miki/core/ui/typedCoreUiGatewayService.ts');
const ext=read('src/components/ExternalConnectionsScreen.tsx');
const ws=read('src/components/WorkspaceScreen.tsx');
const keys=read('src/components/GeminiKeyManagementPanel.tsx');
const path=read('src/miki/safety/services/workspacePathBoundaryService.ts');
const broker=read('src/miki/execution/services/workspaceExecutionBrokerService.ts');
add('typed gateway command/result/query contracts',gateway.includes('UiCommandResult')&&gateway.includes('sourceScreenId')&&gateway.includes('receiptIds'));
add('gateway delegates side effects to core ingress',gateway.includes('coreTaskIngressService.submit'));
add('external screen only uses typed gateway',ext.includes('typedCoreUiGatewayService')&&!ext.includes('externalConnectionUiService'));
add('workspace screen only uses typed gateway',ws.includes('typedCoreUiGatewayService')&&!ws.includes('generalWorkspaceService'));
add('gemini multiple key panel connected',ext.includes('<GeminiKeyManagementPanel/>')&&keys.includes('keyName')&&keys.includes('geminiKeyId'));
add('gemini duplicate normalized name rejected',keys.includes('toLocaleLowerCase()')&&keys.includes('同じキー名'));
add('gemini secret is password input',keys.includes('type="password"'));
add('workspace path traversal rejected',path.includes('PATH_TRAVERSAL_REJECTED')&&path.includes('ENCODED_TRAVERSAL_REJECTED'));
add('archive limits implemented',path.includes('FILE_COUNT_LIMIT')&&path.includes('TOTAL_SIZE_LIMIT')&&path.includes('SINGLE_FILE_SIZE_LIMIT'));
add('execution broker requires core decision and trust',broker.includes('CORE_DECISION_REQUIRED')&&broker.includes('WORKSPACE_TRUST_REQUIRED'));
add('execution broker rejects shell and secret env',broker.includes('SHELL_TRUE_FORBIDDEN')&&broker.includes('SECRET_ENVIRONMENT_FORBIDDEN'));
add('github actions preserved',fs.existsSync('.github/workflows/build-apk.yml'));
add('gradle wrapper preserved',fs.existsSync('android/gradle/wrapper/gradle-wrapper.jar'));
const failed=checks.filter(x=>!x.passed); console.log(JSON.stringify({schemaVersion:1,passed:failed.length===0,checks},null,2)); if(failed.length)process.exit(1);
