import fs from 'node:fs';
const root='src';
const ingress=fs.readFileSync(`${root}/miki/core/services/coreTaskIngressService.ts`,'utf8');
const settings=fs.readFileSync(`${root}/miki/core/services/coreCycleSettingsService.ts`,'utf8');
const gateway=fs.readFileSync(`${root}/miki/core/ui/typedCoreUiGatewayService.ts`,'utf8');
const panel=fs.readFileSync(`${root}/components/CoreCycleSettingsPanel.tsx`,'utf8');
const orch=fs.readFileSync(`${root}/miki/core/services/coreOrchestratorService.ts`,'utf8');
const checks={settingsService:settings.includes('conversationMaxCycles')&&settings.includes('selfImprovementMaxCycles'),conversationDefault3:settings.includes('conversationMaxCycles:3'),separateSelfImprovementCap:settings.includes('selfImprovementMaxCycles:64'),ingressUsesSettings:ingress.includes('coreCycleSettingsService.maxCyclesFor(request.kind)'),gatewaySettings:gateway.includes('saveCoreCycleSettings')&&gateway.includes('getCoreCycleSettings'),conversationNoHardcoded18:!gateway.match(/TYPED_CONVERSATION_UI_GATEWAY[^;]*maxCycles:18/),settingsUi:panel.includes('COREサイクル設定'),orchestratorSafety100:orch.includes('Math.min(maxCycles,100)')};
for(const [k,v] of Object.entries(checks)) console.log(`${v?'PASS':'FAIL'} ${k}`);
if(Object.values(checks).some(v=>!v))process.exit(1);
