import fs from 'node:fs';
const checks=[];
const check=(name,ok)=>{checks.push({name,ok});console.log(`${ok?'PASS':'FAIL'} ${name}`)};
const repo=fs.readFileSync('src/miki/research/services/queryPatternRepositoryService.ts','utf8');
const outcome=fs.readFileSync('src/miki/research/services/researchQueryOutcomeLearningService.ts','utf8');
const barrel=fs.readFileSync('src/miki/research.ts','utf8');
check('pattern lifecycle is staged', /CANDID.*TESTED.*ACTIVE.*SUSPENDED/s.test(repo));
check('single success cannot activate', /successCount >= 3/.test(repo));
check('independent plans required', /independentPlanIds\.length >= 3/.test(repo));
check('failure blocks activation', /failureCount === 0/.test(repo));
check('privacy and environment failures suspend', /PRIVACY_BLOCKED.*ENVIRONMENT_MISMATCH.*FAILED/s.test(repo));
check('query shape is normalized', /normalizeShape/.test(repo));
check('outcome persistence precedes learning', outcome.indexOf('QUERY_OUTCOME_PERSISTENCE_FAILED') < outcome.indexOf('queryPatternRepositoryService.observe'));
check('evidence is required for success observation', /outcome\.evidenceIds\.length > 0/.test(repo));
check('repository is exported', /queryPatternRepositoryService/.test(barrel));
check('canonical sha256 is used', /canonicalSha256Object/.test(repo));
if(checks.some(x=>!x.ok))process.exit(1);
