import fs from 'node:fs';
const files={router:fs.readFileSync('src/miki/core/services/domainRouterService.ts','utf8'),bootstrap:fs.readFileSync('src/miki/core/services/domainIntegrationBootstrapService.ts','utf8'),participation:fs.readFileSync('src/miki/core/services/domainParticipationService.ts','utf8'),sequential:fs.readFileSync('src/miki/core/services/domainSequentialConnectionService.ts','utf8')};
const domains=['core','autonomy','capability','conversation','data','execution','experience','improvement','learning','memory','promotion','research','safety','selfAwareness','selfDevelopment','strategy','unknown','verification'];
const checks=domains.map((domain,index)=>({order:index+1,domain,declared:files.sequential.includes(`'${domain}'`)}));
const contract=files.router.includes("'VERIFY_CONNECTION'")&&files.bootstrap.includes("'VERIFY_CONNECTION'")&&files.participation.includes("command: 'VERIFY_CONNECTION'");
const outbound=files.sequential.includes("crossDomainCirculationService.record(domain, 'core'");
const ordered=files.participation.includes('for (const domain of PARTICIPATING_DOMAINS)');
const passed=checks.every(x=>x.declared)&&contract&&outbound&&ordered;
const report={version:'v17',passed,contract,outbound,ordered,domains:checks};
fs.writeFileSync('DOMAIN_SEQUENTIAL_CONNECTION_AUDIT_V17.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
if(!passed)process.exitCode=1;
