import fs from 'fs';
const checks=[];
const read=(p)=>fs.readFileSync(p,'utf8');
const assert=(name,condition)=>{checks.push({name,passed:Boolean(condition)});if(!condition)process.exitCode=1;};
const server=read('server.ts');
const validation=read('src/miki/verification/services/unifiedValidationCoordinatorService.ts');
const teacher=read('src/miki/learning/services/teacherRequestService.ts');
const search=read('src/miki/research/services/autonomousSearchService.ts');
assert('unit-test-run reads current tsconfig',server.includes('ts.readConfigFile(tsconfigPath'));
assert('unit-test-run reports diagnostics',server.includes('tsconfigTypecheck'));
assert('unit-test-run blocks structural pass on typecheck failure',server.includes('const test1Passed = typecheckPassed'));
assert('validation requires environment identity',validation.includes('!input.environmentId'));
assert('validation requires artifact hash',validation.includes('!input.artifactHash'));
assert('passed validation requires actual command and log',validation.includes("input.exitCode!==0||!input.command||!input.logRef"));
assert('teacher evidence uses central identity service',teacher.includes("evidenceIdentityService.create('teacher'"));
assert('search evidence uses central identity service',search.includes("evidenceIdentityService.create('search'"));
assert('random evidence ids removed',!teacher.includes('ev_teacher_${Date.now()}_${Math.random')&&!search.includes('ev_search_${Date.now()}_${Math.random'));
for(const c of checks)console.log(`${c.passed?'PASS':'FAIL'} ${c.name}`);
