import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const checks=[];
const must=(name,ok)=>{checks.push([name,!!ok]); if(!ok) throw new Error(name)};
const svc=fs.readFileSync(path.join(root,'src/services/deterministicSelfImprovementLabService.ts'),'utf8');
const server=fs.readFileSync(path.join(root,'server.ts'),'utf8');
must('lab service exists', svc.includes('class DeterministicSelfImprovementLabService'));
must('web evidence stage', svc.includes("WEB_EVIDENCE"));
must('formal stage', svc.includes("FORMAL_VERIFIED"));
must('mutation stage', svc.includes("MUTATION_VERIFIED"));
must('canary stage', svc.includes("CANARY_VERIFIED"));
must('candidate only', svc.includes("CANDIDATE_READY") && svc.includes('USER_OR_PROTECTED_OPERATOR'));
must('no auto full release', !svc.includes('promoteToFullRelease'));
must('local llm explicitly denied', svc.includes('LOCAL_LLM_RUNTIME_REACTIVATION'));
must('production overwrite explicitly denied', svc.includes('DIRECT_PRODUCTION_OVERWRITE'));
must('dynamic tool has no retired local creator', !fs.readFileSync(path.join(root,'src/services/dynamicToolFactoryService.ts'),'utf8').includes("createdBy: 'QWEN_3B'"));
must('server tool has no retired local creator', !server.includes("createdBy: 'QWEN_3B'"));
must('route exists', server.includes("/api/miki/self-improvement-lab/run"));
must('contract route exists', server.includes("/api/miki/self-improvement-lab/contract"));
console.log(`${checks.filter(x=>x[1]).length}/${checks.length} PASS`);
