import fs from 'node:fs';
const checks=[];const check=(name,ok)=>{checks.push({name,passed:Boolean(ok)});if(!ok)process.exitCode=1;};
const svc=fs.readFileSync('src/miki/research/services/researchQueryPlanningService.ts','utf8');
const gw=fs.readFileSync('src/miki/core/ui/typedCoreUiGatewayService.ts','utf8');
const ui=fs.readFileSync('src/components/ResearchQueryPlanningPanel.tsx','utf8');
const screen=fs.readFileSync('src/components/ExternalConnectionsScreen.tsx','utf8');
check('query intent model',svc.includes("'OFFICIAL_SPECIFICATION'")&&svc.includes("'COUNTEREVIDENCE'"));
check('environment fingerprint',svc.includes("device:'Galaxy S25'")&&svc.includes("architecture:'arm64'"));
check('query plan persistence',svc.includes("miki_research_query_plans_v1"));
check('revision pair persistence',svc.includes("miki_research_query_revision_pairs_v1"));
check('privacy preflight',svc.includes('PRIVACY_BLOCKED'));
check('duplicate query prevention',svc.includes('const unique=new Map'));
check('web policy linkage',svc.includes('webResearchPolicyService.get()'));
check('typed gateway save',gw.includes('saveResearchQueryPlanningPolicy'));
check('typed gateway plan',gw.includes('buildResearchQueryPlan'));
check('ui plan preview',ui.includes('Planを作成')&&ui.includes('q.intentType'));
check('ui mounted',screen.includes('<ResearchQueryPlanningPanel/>'));
check('external ai not used',!svc.includes('/api/chat')&&!svc.includes('gemini'));
console.log(JSON.stringify({passed:checks.every(x=>x.passed),checks},null,2));
