import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('src/miki/unknown/services/multiIntentDecompositionService.ts','utf8');
assert.match(source,/class MultiIntentDecompositionService/);
assert.match(source,/EXPLICIT_CONNECTOR/);
assert.match(source,/PUNCTUATION/);
assert.match(source,/canonicalSha256Object/);
const sample='今日の天気と株価を教えて';
assert.equal(sample.includes('と'),true);
console.log('PASS: deterministic multi-intent decomposition V224');
