import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync('src/miki/conversation/services/runtimeConversationCompositionService.ts','utf8');
assert.match(source,/DETERMINISTIC_WEIGHTED_SELECTION_V1/);
assert.match(source,/selectionCriteria/);
assert.match(source,/weightedSelectionScore/);
assert.match(source,/deterministicTieBreak/);
assert.match(source,/inFlight/);
assert.doesNotMatch(source,/const result: RuntimeConversationCompositionResult = .* selection \};\n    if \(selection\)/s);
console.log('PASS: deterministic composition + concurrency guard V224');
