import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const checks = [];
const check = (name, pass, detail = '') => checks.push({ name, pass: Boolean(pass), detail });
const review = read('src/components/ReviewPackageLibrary.tsx');
const gateway = read('src/miki/core/ui/typedCoreUiGatewayService.ts');
check('review package UI uses typed gateway', review.includes('typedCoreUiGatewayService'));
check('review package UI has no review service import', !review.includes("../miki/core/services/reviewZipExportService") && !review.includes("../miki/core/services/externalReviewIntakeService"));
check('gateway owns review package query', gateway.includes('listReviewPackages()'));
check('gateway owns review regeneration', gateway.includes('regenerateReviewPackage'));
check('gateway owns external review import', gateway.includes('importExternalReview'));
check('gateway owns adoption decision', gateway.includes('submitExternalReviewDecision'));
check('ui command id contains no random', !gateway.includes('Math.random'));
check('core action status exists', fs.existsSync(path.join(root, 'src/components/common/CoreActionStatus.tsx')));
check('destructive confirmation exists', fs.existsSync(path.join(root, 'src/components/common/DestructiveActionConfirmDialog.tsx')));
check('github actions preserved', fs.existsSync(path.join(root, '.github/workflows/build-apk.yml')));
check('gradle wrapper preserved', fs.existsSync(path.join(root, 'android/gradle/wrapper/gradle-wrapper.jar')));
const failed = checks.filter(item => !item.pass);
const report = { passed: failed.length === 0, checks, generatedAt: new Date().toISOString() };
fs.writeFileSync(path.join(root, 'UI_MIGRATION_V73.json'), JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
process.exit(failed.length === 0 ? 0 : 1);
