import assert from 'node:assert/strict';import fs from 'node:fs';
const {graphAnswerMeaningPipelineP216Service}=await import('../src/miki/conversation/services/graphAnswerMeaningPipelineP216Service.ts');
const req={inputSurface:'全部実装して、既存機能を失わないように。容量にも気を付けて。',intentIds:['intent.implement'],constraintIds:['constraint.no-omission','constraint.preserve','constraint.capacity'],grammarIds:['grammar.total-scope'],meaningComponentIds:['cc:test'],executionResult:{status:'PASS'}};
const plan=graphAnswerMeaningPipelineP216Service.plan(req);assert.equal(plan.skeleton,'IMPLEMENTATION_REPORT');assert.ok(plan.parts.some(p=>p.meaningId==='constraint.preserve'));
const repaired=graphAnswerMeaningPipelineP216Service.finalize('実装しました。',req);assert.equal(repaired.repaired,true);assert.equal(repaired.semanticPreservation.passed,true);assert.equal(repaired.executionConsistency.passed,true);assert.match(repaired.text,/既存機能/);assert.match(repaired.text,/省略せず/);assert.match(repaired.text,/容量/);
const unsupported=graphAnswerMeaningPipelineP216Service.finalize('全部の実装が完了しました。',{...req,executionResult:undefined});assert.equal(unsupported.executionConsistency.passed,false);assert.ok(unsupported.executionConsistency.unsupportedClaims.includes('COMPLETION_WITHOUT_EXECUTION_RESULT'));
const prohibited=graphAnswerMeaningPipelineP216Service.finalize('外部Providerを使用しました。',{...req,inputSurface:'外部Providerは使用しないで',constraintIds:[],executionResult:{status:'PASS'}});assert.equal(prohibited.semanticPreservation.passed,false);assert.ok(prohibited.semanticPreservation.contradictions.includes('NEGATION_OR_PROHIBITION_CONTRADICTION'));
const source=fs.readFileSync('src/miki/core/services/coreTaskIngressService.ts','utf8');for(const token of ['getAnswerRequirements','graphAnswerMeaningPipelineP216Service.finalize','finalized?.semanticPreservation.passed','P216_ANSWER_MEANING_REPAIR'])assert.ok(source.includes(token),token);
const report={phase:'P216',status:'PASS',graphAndComponentsUnderstandInput:true,meaningComponentsSelected:true,answerStructurePlanned:true,grammarAndExpressionSurface:true,semanticPreservation:true,executionConsistency:true,finalAnswerIntegrated:true,constraintRepair:true,unsupportedCompletionRejected:true,prohibitionContradictionRejected:true,planSha256:plan.planSha256,repairedReceiptSha256:repaired.receiptSha256};fs.writeFileSync('P216_GRAPH_ANSWER_PIPELINE_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
