import{existsSync,readFileSync,readdirSync,writeFileSync}from'node:fs';
const failures=[];const retired=['instructionConstraintGraphService','conversationContinuityLedgerService','codeGenerationIntegrityPipelineService','understandingConversationCodeOrchestratorService'];
const frame=readFileSync('src/miki/selfDevelopment/services/semanticFrameV2Service.ts','utf8');for(const token of ['SemanticActionChain','PREVIOUS_MUTATION_ROWS','ALL_MATCHED_ROWS','CONTINUE_STOP_PRIORITY_UNRESOLVED','EXCLUSION_TARGET_UNRESOLVED','actionChains','conflicts'])if(!frame.includes(token))failures.push(`FRAME_STRENGTHENING_MISSING:${token}`);
const gate=readFileSync('src/miki/selfDevelopment/services/semanticClarificationGateService.ts','utf8');for(const token of ['REFERENCE_UNRESOLVED','CONTINUE_STOP_PRIORITY_UNRESOLVED','EXCLUSION_TARGET_UNRESOLVED'])if(!gate.includes(token))failures.push(`CLARIFICATION_MISSING:${token}`);
const orchestrator=readFileSync('src/miki/selfDevelopment/services/semanticUnderstandingV2OrchestratorService.ts','utf8');for(const token of ['executionPlan','actionChains','dependencies'])if(!orchestrator.includes(token))failures.push(`ORCHESTRATOR_MISSING:${token}`);
const taskboard=readFileSync('src/miki/conversation/services/conversationTaskboardService.ts','utf8');for(const token of ['taskFingerprint','findEquivalentTask','classifyWorkState','resolveContinuation'])if(!taskboard.includes(token))failures.push(`TASKBOARD_MISSING:${token}`);
const verifier=readFileSync('src/miki/verification/services/codeVerificationService.ts','utf8');for(const token of ['verifyContractEvolution','deletedPublicContracts','duplicateContracts','rust_unsafe','rust_unwrap','rust_expect','rust_panic'])if(!verifier.includes(token))failures.push(`VERIFIER_MISSING:${token}`);
const files=[];function walk(path){for(const entry of readdirSync(path,{withFileTypes:true})){if(['node_modules','dist','target','.git'].includes(entry.name))continue;const child=`${path}/${entry.name}`;if(entry.isDirectory())walk(child);else if(/\.tsx?$/.test(entry.name))files.push(child);}}walk('src');for(const file of files){const source=readFileSync(file,'utf8');for(const name of retired)if(source.includes(name))failures.push(`RETIRED_DUPLICATE_REFERENCE:${file}:${name}`);}
const report={passed:!failures.length,phase:'CANONICAL_SEMANTIC_CONVERSATION_CODEGEN_HARDENING_54',canonicalServicesEnhanced:5,retiredDuplicateReferences:failures.filter(x=>x.startsWith('RETIRED')).length,typescriptFilesScanned:files.length,failures};writeFileSync('CANONICAL_HARDENING_PHASE54_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
