import{readFileSync,readdirSync,writeFileSync,existsSync}from'node:fs';
const failures=[];const core=readFileSync('src/miki/core/services/coreOrchestratorService.ts','utf8');for(const token of ['decideSelfCodeImprovementNextAction','REPEATED_FAILURE_SIGNATURE','REPAIR_BUDGET_EXHAUSTED','WAIT_EXTERNAL_EVALUATION','PREPARE_ADOPTION','canMutateCanonical:false','requiresExternalEvaluation:true'])if(!core.includes(token))failures.push(`CORE_RULE_MISSING:${token}`);
const intake=readFileSync('src/miki/core/services/improvementIntakeRouterService.ts','utf8');if(!intake.includes('severity*b.frequency*b.confidence'))failures.push('CORE_INTAKE_PRIORITY_MISSING');
const repair=readFileSync('src/miki/selfDevelopment/services/candidateRepairRetryLoopService.ts','utf8');if(!repair.includes('MAX_REPAIR_ATTEMPTS_HARD_LIMIT'))failures.push('REPAIR_HARD_LIMIT_MISSING');
for(const retired of ['src/miki/improvement/services/adaptiveSelfCodeImprovementCoordinatorService.ts'])if(existsSync(retired))failures.push(`PARALLEL_AUTHORITY_REMAINS:${retired}`);
const roots=['src/miki/improvement','src/miki/selfDevelopment','src/miki/execution','src/miki/strategy','src/miki/verification'];const authorityFindings=[];for(const root of roots){const stack=[root];while(stack.length){const dir=stack.pop();for(const entry of readdirSync(dir,{withFileTypes:true})){const path=`${dir}/${entry.name}`;if(entry.isDirectory())stack.push(path);else if(/\.tsx?$/.test(entry.name)){const source=readFileSync(path,'utf8');if(/canonical authority|canMutateCanonical\s*:\s*true|public\s+decideSelfCodeImprovementNextAction/.test(source))authorityFindings.push(path);}}}}
if(authorityFindings.length)failures.push(...authorityFindings.map(path=>`NON_CORE_AUTHORITY:${path}`));
const controller=readFileSync('src/miki/improvement/services/selfImprovementControllerService.ts','utf8');if(!controller.includes('CORE_AUTHORITY_ONLY'))failures.push('CONTROLLER_CORE_AUTHORITY_GUARD_MISSING');
const report={passed:!failures.length,phase:'CORE_AUTHORITY_CONSOLIDATION_64',coreOwnsImprovementDecision:true,parallelAuthorities:authorityFindings.length,repairHardLimit:true,priorityOwnedByCoreIntake:true,failures};writeFileSync('CORE_AUTHORITY_CONSOLIDATION_PHASE64_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
