import{writeFileSync}from'node:fs';
import{storageService}from'../src/services/storageService.ts';
import{candidateGovernanceCoordinatorService}from'../src/miki/core/services/candidateGovernanceCoordinatorService.ts';
import{taskBlackboardService}from'../src/miki/core/services/taskBlackboardService.ts';
import{scopedVersionedMemoryService}from'../src/miki/memory/services/scopedVersionedMemoryService.ts';
import{candidateWriteGuardService}from'../src/miki/core/services/candidateWriteGuardService.ts';
import{unifiedCandidateLifecycleGraphService as graph}from'../src/miki/core/services/unifiedCandidateLifecycleGraphService.ts';
import{postAdoptionCascadeInvalidationTransactionService as cascade}from'../src/miki/improvement/services/postAdoptionCascadeInvalidationTransactionService.ts';
const checks=[];const failures=[];const check=(name,passed,detail={})=>{checks.push({name,passed,detail});if(!passed)failures.push(name);};
storageService.setItem('miki_self_code_space_v1',JSON.stringify({repository:'e2e/local',branch:'phase83',repoSha256:'seed',files:[{path:'src/e2e.ts',content:'export const e2e=true;',sha256:'c'.repeat(64)}],syncedAt:Date.now(),dirty:true,baseRepoSha256:'seed',source:'GITHUB'}));
const safe={candidateId:'existing-safe',eligible:true,vector:{performanceGain:.7,memoryCost:.2,safetyRisk:.1,compatibilityRisk:.1,changeSurface:.2,rollbackCost:.1,rustMigrationValue:.8,validationConfidence:.9}};
const unsafe={candidateId:'existing-unsafe',eligible:true,vector:{performanceGain:1,memoryCost:.1,safetyRisk:.9,compatibilityRisk:.1,changeSurface:.1,rollbackCost:.1,rustMigrationValue:.9,validationConfidence:.9}};
const task=taskBlackboardService.create('Phase83 existing implementation E2E','core',{kind:'SELF_IMPROVEMENT'});
const governance=candidateGovernanceCoordinatorService.preflight({candidates:[safe,unsafe],invariantChange:{paths:['src/miki/core/services/coreOrchestratorService.ts'],declaredPreservations:['CORE_ROUTE_AUTHORITY']}});
taskBlackboardService.append(task.taskId,'CHECKPOINT','core','CANDIDATE_GOVERNANCE_PREFLIGHT',governance,[]);
const persisted=taskBlackboardService.get(task.taskId);const preflight=persisted?.entries.find(x=>x.key==='CANDIDATE_GOVERNANCE_PREFLIGHT');
check('EXISTING_BLACKBOARD_AND_GOVERNANCE_PREFLIGHT',Boolean(preflight)&&governance.allowed&&governance.selection?.selectedCandidateId==='existing-safe',{taskId:task.taskId,governance,preflight});
const guard=await candidateWriteGuardService.stage('PHASE83-E2E',[{path:'src/miki/core/services/coreOrchestratorService.ts',baselineContent:'base',candidateContent:'candidate'}]);check('EXISTING_WRITE_GUARD_COMPATIBILITY',candidateWriteGuardService.verify(guard.guardId,'PHASE83-E2E',['src/miki/core/services/coreOrchestratorService.ts']),guard);
const mem=scopedVersionedMemoryService.propose({subject:'phase83-existing-candidate',content:'derived readiness evidence',kind:'EVIDENCE',scope:{type:'TASK',id:task.taskId},source:{turnIds:[],fileIds:[],evidenceIds:['existing-root']},confidence:1});
const memoryBefore=JSON.parse(JSON.stringify(mem));
graph.resetForTest();graph.register({candidateId:'existing-root',revision:1,parentCandidateIds:[],state:'ADOPTED',artifactSha256:'a'.repeat(64),metadata:{taskId:task.taskId}});graph.register({candidateId:'existing-child',revision:2,parentCandidateIds:['existing-root'],state:'VALIDATED',artifactSha256:'b'.repeat(64),metadata:{memoryId:mem.id}});
cascade.registerAdapter({name:'existing-scoped-memory',priority:10,snapshot:()=>({memoryId:mem.id,status:scopedVersionedMemoryService.list().find(x=>x.id===mem.id)?.status}),invalidate:(ids,reason)=>scopedVersionedMemoryService.invalidateBySource('existing-root',reason).map(x=>x.id),restore:()=>{}});
const receipt=cascade.execute('existing-root','E2E_EXISTING_INVALIDATION');const after=scopedVersionedMemoryService.list().find(x=>x.id===mem.id);check('CASCADE_TO_EXISTING_SCOPED_MEMORY',receipt.status==='COMMITTED'&&after?.status==='INVALIDATED',{receipt,memoryBefore,memoryAfter:after});cascade.unregisterAdapter('existing-scoped-memory');
check('LIFECYCLE_TO_EXISTING_TASK_ID',graph.get('existing-root')?.metadata.taskId===task.taskId,{root:graph.get('existing-root')});
const report={phase:'PHASE83_EXISTING_IMPLEMENTATION_E2E',passed:failures.length===0,executedAt:new Date().toISOString(),checks,failures};writeFileSync('PHASE83_EXISTING_IMPLEMENTATION_E2E_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
