import{readFileSync,readdirSync,writeFileSync,existsSync}from'node:fs';import{createHash}from'node:crypto';
const failures=[];const files=[];function walk(path){for(const entry of readdirSync(path,{withFileTypes:true})){if(['node_modules','dist','target','.git'].includes(entry.name))continue;const child=`${path}/${entry.name}`;if(entry.isDirectory())walk(child);else if(/\.tsx?$/.test(entry.name))files.push(child);}}walk('src/miki');
const sources=files.map(file=>({file,source:readFileSync(file,'utf8')}));const corpus=sources.map(value=>value.source).join('\n');
for(const retired of ['virtualTrainingService','virtualTrainingService.ts','addTrainingSample(','evaluateLoraTriggerCondition','runVirtualTrainingTrial','legacyResearchProviderMigrationService'])if(corpus.includes(retired))failures.push(`OLD_CODE_REMAINS:${retired}`);
for(const path of ['src/miki/learning/services/virtualTrainingService.ts','src/miki/research/services/legacyResearchProviderMigrationService.ts'])if(existsSync(path))failures.push(`OLD_FILE_REMAINS:${path}`);
const canonical='src/miki/learning/services/capabilityEvaluationService.ts';if(!existsSync(canonical))failures.push('CANONICAL_CAPABILITY_FILE_MISSING');
const worker=readFileSync('src/miki/execution/services/backgroundWorkerService.ts','utf8');for(const required of ['capabilityEvaluationService','capabilityEvaluationService','evaluateSufficiencyCondition','runCapabilityEvaluationTrial'])if(!worker.includes(required))failures.push(`CANONICAL_CAPABILITY_CALL_MISSING:${required}`);
const normalized=new Map();for(const {file,source}of sources){const body=source.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'').replace(/\s+/g,'');const hash=createHash('sha256').update(body).digest('hex');const group=normalized.get(hash)||[];group.push(file);normalized.set(hash,group);}const exact=[...normalized.values()].filter(group=>group.length>1);if(exact.length)failures.push(...exact.map(group=>`EXACT_DUPLICATE:${group.join('|')}`));
const report={passed:!failures.length,phase:'CANONICAL_NAMING_AND_OLD_CODE_CLEANUP_59',typescriptFilesScanned:files.length,canonicalFilesRenamed:1,deprecatedWrappersRemoved:1,oldFilesRemoved:2,exactDuplicateGroups:exact.length,failures};writeFileSync('CANONICAL_NAMING_OLD_CODE_PHASE59_REPORT.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
