import { canonicalSha256Object } from './canonicalSha256Service';
import type { RgbaImage } from './richVisualProductionRendererService';

export interface ImageAnalysis { width:number;height:number;meanLuma:number;contrast:number;edgeDensity:number;noiseEstimate:number;darkRatio:number;brightRatio:number;dominantChannels:[number,number,number];analysisSha256:string; }
export interface SuperResolutionOptions { scale:2|3|4; detail:number; denoise:number; sharpen:number; localContrast:number; preserveAlpha:boolean; }
export interface SuperResolutionResult extends RgbaImage { analysis:ImageAnalysis; options:SuperResolutionOptions; sourceSha256:string; outputSha256:string; provenance:'SOURCE_ANALYSIS_RECONSTRUCTION'; inventedIdentity:false; }
const clamp=(v:number)=>Math.max(0,Math.min(255,Math.round(v)));
const lum=(r:number,g:number,b:number)=>.2126*r+.7152*g+.0722*b;
class AnalyzedImageSuperResolutionService {
 analyze(image:RgbaImage):ImageAnalysis { let sum=0,sum2=0,dark=0,bright=0,edges=0,noise=0,rc=0,gc=0,bc=0,n=0; const p=image.rgba,w=image.width,h=image.height; for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;if(p[i+3]===0)continue;const l=lum(p[i],p[i+1],p[i+2]);sum+=l;sum2+=l*l;rc+=p[i];gc+=p[i+1];bc+=p[i+2];dark+=l<48?1:0;bright+=l>208?1:0;n++;if(x+1<w){const j=i+4;const d=Math.abs(l-lum(p[j],p[j+1],p[j+2]));edges+=d>24?1:0;noise+=d;}if(y+1<h){const j=i+w*4;const d=Math.abs(l-lum(p[j],p[j+1],p[j+2]));edges+=d>24?1:0;noise+=d;}} const mean=n?sum/n:0,variance=n?sum2/n-mean*mean:0,totalPairs=Math.max(1,n*2);const seed={width:w,height:h,meanLuma:mean,contrast:Math.sqrt(Math.max(0,variance)),edgeDensity:edges/totalPairs,noiseEstimate:noise/totalPairs,darkRatio:n?dark/n:0,brightRatio:n?bright/n:0,dominantChannels:[n?rc/n:0,n?gc/n:0,n?bc/n:0] as [number,number,number]};return{...seed,analysisSha256:canonicalSha256Object(seed)}; }
 async enhance(image:RgbaImage,options:SuperResolutionOptions):Promise<SuperResolutionResult>{this.validate(image,options);const analysis=this.analyze(image),w=image.width*options.scale,h=image.height*options.scale;let rgba=this.bicubic(image,w,h);if(options.denoise>0)rgba=this.edgeAwareDenoise(rgba,w,h,options.denoise,analysis);if(options.localContrast>0)rgba=this.localContrast(rgba,w,h,options.localContrast);if(options.detail>0||options.sharpen>0)rgba=this.detailReconstruct(rgba,w,h,options,analysis);if(options.preserveAlpha)this.restoreAlpha(image,rgba,w,h,options.scale);const sourceSha256=await this.sha(image.rgba),outputSha256=await this.sha(rgba);return{width:w,height:h,rgba,analysis,options,sourceSha256,outputSha256,provenance:'SOURCE_ANALYSIS_RECONSTRUCTION',inventedIdentity:false};}
 private validate(image:RgbaImage,o:SuperResolutionOptions){if(image.width<2||image.height<2||image.rgba.length!==image.width*image.height*4)throw new Error('INVALID_RGBA_IMAGE');for(const v of [o.detail,o.denoise,o.sharpen,o.localContrast])if(v<0||v>1)throw new Error('SUPER_RESOLUTION_PARAMETER_OUT_OF_RANGE');}
 private bicubic(src:RgbaImage,w:number,h:number){const out=new Uint8Array(w*h*4),sx=src.width/w,sy=src.height/h;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const fx=(x+.5)*sx-.5,fy=(y+.5)*sy-.5,ix=Math.floor(fx),iy=Math.floor(fy);for(let c=0;c<4;c++){let sum=0,ws=0;for(let yy=-1;yy<=2;yy++)for(let xx=-1;xx<=2;xx++){const px=Math.max(0,Math.min(src.width-1,ix+xx)),py=Math.max(0,Math.min(src.height-1,iy+yy)),wt=this.cubic(fx-(ix+xx))*this.cubic(fy-(iy+yy));sum+=src.rgba[(py*src.width+px)*4+c]*wt;ws+=wt;}out[(y*w+x)*4+c]=clamp(sum/ws);}}return out;}
 private cubic(x:number){x=Math.abs(x);return x<=1?1.5*x*x*x-2.5*x*x+1:x<2?-.5*x*x*x+2.5*x*x-4*x+2:0;}
 private edgeAwareDenoise(src:Uint8Array,w:number,h:number,a:number,analysis:ImageAnalysis){const out=src.slice(),range=10+analysis.noiseEstimate*1.5;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++){let sum=0,ws=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const j=((y+yy)*w+x+xx)*4+c,d=Math.abs(src[j]-src[i]),wt=Math.exp(-(xx*xx+yy*yy)/2)*Math.exp(-(d*d)/(2*range*range));sum+=src[j]*wt;ws+=wt;}out[i+c]=clamp(src[i+c]*(1-a)+sum/ws*a);}}return out;}
 private localContrast(src:Uint8Array,w:number,h:number,a:number){const out=src.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;let avg=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const j=((y+yy)*w+x+xx)*4;avg+=lum(src[j],src[j+1],src[j+2]);}avg/=9;const l=lum(src[i],src[i+1],src[i+2]),gain=1+(l-avg)/255*a*.8;for(let c=0;c<3;c++)out[i+c]=clamp((src[i+c]-128)*gain+128);}return out;}
 private detailReconstruct(src:Uint8Array,w:number,h:number,o:SuperResolutionOptions,analysis:ImageAnalysis){const out=src.slice(),strength=o.sharpen*(.6+analysis.edgeDensity)+o.detail*.45;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++){const blur=(src[i-4+c]+src[i+4+c]+src[i-w*4+c]+src[i+w*4+c]+src[i+c]*4)/8;const high=src[i+c]-blur;out[i+c]=clamp(src[i+c]+high*strength);}}return out;}
 private restoreAlpha(src:RgbaImage,out:Uint8Array,w:number,h:number,scale:number){for(let y=0;y<h;y++)for(let x=0;x<w;x++)out[(y*w+x)*4+3]=src.rgba[(Math.min(src.height-1,Math.floor(y/scale))*src.width+Math.min(src.width-1,Math.floor(x/scale)))*4+3];}
 private async sha(data:Uint8Array){const b=await crypto.subtle.digest('SHA-256',data.slice().buffer);return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');}
}
export const analyzedImageSuperResolutionService=new AnalyzedImageSuperResolutionService();
