import { canonicalSha256Object } from './canonicalSha256Service';
export interface BodyTypeObservation{shoulderToHeight:number;waistToHeight:number;hipToHeight:number;torsoToHeight:number;legToHeight:number;limbThickness:number;muscleDefinition:number;softness:number;postureCurve:number;garmentBulk:number;sampleSha256:string;}
export interface BodyTypeTrend{sampleCount:number;means:Omit<BodyTypeObservation,'sampleSha256'>;ranges:Record<keyof Omit<BodyTypeObservation,'sampleSha256'>,{min:number;max:number}>;clusters:Array<{id:string;centroid:Omit<BodyTypeObservation,'sampleSha256'>;sampleCount:number}>;sourceSha256List:string[];trendSha256:string;}
const keys=['shoulderToHeight','waistToHeight','hipToHeight','torsoToHeight','legToHeight','limbThickness','muscleDefinition','softness','postureCurve','garmentBulk'] as const;
class BodyTypeTrendService{
 learn(values:BodyTypeObservation[],clusterCount=3):BodyTypeTrend{if(!values.length)throw new Error('BODY_TYPE_SAMPLES_REQUIRED');values.forEach(value=>this.validate(value));const means=this.average(values);const ranges=Object.fromEntries(keys.map(key=>[key,{min:Math.min(...values.map(value=>value[key])),max:Math.max(...values.map(value=>value[key]))}])) as BodyTypeTrend['ranges'];const count=Math.max(1,Math.min(clusterCount,values.length));let centroids=values.slice(0,count).map(value=>this.numeric(value));for(let round=0;round<8;round+=1){const groups=centroids.map(()=>[] as BodyTypeObservation[]);for(const value of values){let best=0;let distance=Infinity;centroids.forEach((center,index)=>{const next=this.distance(value,center);if(next<distance){distance=next;best=index;}});groups[best].push(value);}centroids=centroids.map((center,index)=>groups[index].length?this.average(groups[index]):center);}const clusters=centroids.map((centroid,index)=>({id:`BODY_CLUSTER_${index+1}`,centroid,sampleCount:values.filter(value=>this.nearest(value,centroids)===index).length}));const seed={sampleCount:values.length,means,ranges,clusters,sourceSha256List:values.map(value=>value.sampleSha256).sort()};return{...seed,trendSha256:canonicalSha256Object(seed)};}
 interpolate(left:BodyTypeTrend['means'],right:BodyTypeTrend['means'],ratio:number){const t=Math.max(0,Math.min(1,ratio));return Object.fromEntries(keys.map(key=>[key,left[key]+(right[key]-left[key])*t])) as BodyTypeTrend['means'];}
 private validate(value:BodyTypeObservation){for(const key of keys)if(!Number.isFinite(value[key])||value[key]<0||value[key]>1)throw new Error(`INVALID_BODY_TYPE_VALUE:${key}`);if(!value.sampleSha256)throw new Error('BODY_TYPE_SOURCE_HASH_REQUIRED');}
 private numeric(value:BodyTypeObservation){return Object.fromEntries(keys.map(key=>[key,value[key]])) as BodyTypeTrend['means'];}
 private average(values:BodyTypeObservation[]){return Object.fromEntries(keys.map(key=>[key,values.reduce((sum,value)=>sum+value[key],0)/values.length])) as BodyTypeTrend['means'];}
 private distance(value:BodyTypeObservation,center:BodyTypeTrend['means']){return Math.sqrt(keys.reduce((sum,key)=>sum+(value[key]-center[key])**2,0));}
 private nearest(value:BodyTypeObservation,centers:BodyTypeTrend['means'][]){let best=0;let distance=Infinity;centers.forEach((center,index)=>{const next=this.distance(value,center);if(next<distance){distance=next;best=index;}});return best;}
}
export const bodyTypeTrendService=new BodyTypeTrendService();
