import { isolatedCandidateWorkspaceService } from './isolatedCandidateWorkspaceService';
import { improvementIntakeRouterService } from './improvementIntakeRouterService';
import { semanticUnderstandingV2OrchestratorService } from '../../selfDevelopment/services/semanticUnderstandingV2OrchestratorService';
export interface ConstraintValidationResult { passed:boolean; workspaceId:string; reasons:string[]; checkedAt:number; }
class CandidateConstraintValidationService {
 validate(runId:string,workspaceId:string):ConstraintValidationResult{const run=improvementIntakeRouterService.get(runId);const workspace=isolatedCandidateWorkspaceService.get(workspaceId);const reasons:string[]=[];if(!run)reasons.push('IMPROVEMENT_RUN_NOT_FOUND');if(!workspace)reasons.push('CANDIDATE_WORKSPACE_NOT_FOUND');if(run&&workspace){const instruction=typeof run.payload.instruction==='string'?run.payload.instruction:typeof run.payload.request==='string'?run.payload.request:'';if(instruction){const semantic=semanticUnderstandingV2OrchestratorService.analyze(instruction);if(!semantic.ready)reasons.push(...semantic.clarification.reasons.map(reason=>`SEMANTIC_NOT_READY:${reason}`));for(const mutation of semantic.executionPlan.mutations){if(mutation.operation==='UNKNOWN')reasons.push(`UNKNOWN_MUTATION:${mutation.actionId}`);if(mutation.targetSet==='PREVIOUS_MUTATION_ROWS'&&!mutation.dependsOn.length)reasons.push(`MISSING_MUTATION_DEPENDENCY:${mutation.actionId}`);if(mutation.operation==='UPDATE'&&!mutation.field)reasons.push(`UPDATE_FIELD_UNRESOLVED:${mutation.actionId}`);}}const plannedTargets=run.implementationPlan&&Array.isArray(run.implementationPlan.targetPaths)?run.implementationPlan.targetPaths:undefined;const requestedTargets=plannedTargets|| (Array.isArray(run.payload.targetFiles)?run.payload.targetFiles.filter((x):x is string=>typeof x==='string'):workspace.files.map(file=>file.path));if(new Set(requestedTargets).size!==requestedTargets.length)reasons.push('DUPLICATE_TARGET_PATH');const permitted=new Set(requestedTargets);if(plannedTargets&&workspace.files.length>plannedTargets.length)reasons.push('IMPLEMENTATION_PLAN_SCOPE_EXCEEDED');for(const file of workspace.files){if(!permitted.has(file.path))reasons.push(`UNPERMITTED_FILE:${file.path}`);if(file.baselineContent===file.candidateContent)reasons.push(`UNCHANGED_FILE:${file.path}`);if(!file.candidateContent.trim())reasons.push(`EMPTY_FILE:${file.path}`);if(!file.evidenceIds.length)reasons.push(`IMPLEMENTATION_EVIDENCE_MISSING:${file.path}`);}for(const text of this.strings(run.payload.prohibitions)){for(const file of workspace.files){if(text&&file.candidateContent.includes(text))reasons.push(`PROHIBITION_TEXT_PRESENT:${text}`);}}}return {passed:reasons.length===0,workspaceId,reasons,checkedAt:Date.now()};}
 private strings(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];}
}
export const candidateConstraintValidationService=new CandidateConstraintValidationService();
