import { improvementIntakeRouterService } from './improvementIntakeRouterService';
import { autonomousCandidatePreparationService } from './autonomousCandidatePreparationService';
import { apiUrl, getCustomApiHeaders } from '../../../services/api';
import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from './canonicalSha256Service';
import { reviewLearningArtifactService } from './reviewLearningArtifactService';
import { reusableComponentFactoryService } from './reusableComponentFactoryService';
import { candidateUnknownResolutionService } from './candidateUnknownResolutionService';
export interface CandidateGenerationFile { path:string; candidateContent:string; evidenceIds:string[]; }
export interface CandidateGenerationOutcome { accepted:boolean; runId:string; workspaceId?:string; files:CandidateGenerationFile[]; reasons:string[]; responseHash?:string; attemptCount?:number; learningLineage?:{usedLearningArtifactIds:string[];ignoredLearningArtifactIds:string[];appliedFailurePatternIds:string[];appliedCorrectionPairIds:string[];appliedComponentPatternIds:string[];learningContextSha256:string;componentPackId?:string;usedKnowledgeComponentIds?:string[];usedCodeComponentIds?:string[];usedConversationComponentIds?:string[];excludedComponentIds?:string[];componentContextSha256?:string}; }
class CandidateCodeGenerationService {
 async generate(runId:string):Promise<CandidateGenerationOutcome>{
  const run=improvementIntakeRouterService.get(runId);if(!run)return {accepted:false,runId,files:[],reasons:['IMPROVEMENT_RUN_NOT_FOUND']};
  const probe=await autonomousCandidatePreparationService.prepareForRun(runId,[]);const targetPaths=probe.targetPaths;
  if(targetPaths.length===0)return {accepted:false,runId,files:[],reasons:[probe.reason||'TARGET_FILES_NOT_RESOLVED']};
  const sources=new Map(autonomousCandidatePreparationService.getSourceFiles().map(file=>[file.path,file]));const targetFiles=targetPaths.map(path=>sources.get(path)).filter((value):value is NonNullable<typeof value>=>Boolean(value));
  if(targetFiles.length!==targetPaths.length)return {accepted:false,runId,files:[],reasons:['SOURCE_SNAPSHOT_INCOMPLETE']};
  const unknownContext=await candidateUnknownResolutionService.resolve({runId:run.runId,taskId:run.taskId||run.runId,objective:run.objective,environmentFingerprint:typeof run.payload.environmentFingerprint==='string'?run.payload.environmentFingerprint:'unknown',targetPaths,sourcePaths:targetFiles.map(file=>file.path),requirements:this.strings(run.payload.requirements),validationRequirements:this.strings(run.payload.validationRequirements)});
  const learningContext=reviewLearningArtifactService.retrieve({objective:run.objective,packageId:typeof run.payload.packageId==='string'?run.payload.packageId:undefined});
  const componentPack=reusableComponentFactoryService.plan({taskId:run.taskId||run.runId,purpose:run.objective,environmentFingerprint:typeof run.payload.environmentFingerprint==='string'?run.payload.environmentFingerprint:'unknown',requiredKinds:['KNOWLEDGE','CODE']});
  const contract={formatVersion:3,unknownContext,runId:run.runId,runType:run.runType,objective:run.objective,learningContext,componentPack,targets:targetFiles.map(file=>({path:file.path,language:file.language,baselineContent:file.content})),requirements:this.strings(run.payload.requirements),prohibitions:this.strings(run.payload.prohibitions),invariants:this.strings(run.payload.invariants),validationRequirements:this.strings(run.payload.validationRequirements),responseContract:{files:[{path:'must equal one requested target path',candidateContent:'complete file content without markdown fences',evidenceIds:['optional evidence ids']}],summary:'short description'}};
  const prompt=['You are a code candidate generator operating in an isolated workspace.','Return JSON only. Do not use markdown fences. Do not omit file content. Do not claim tests were run. Preserve all invariants and prohibitions. Use resolved unknown context where verified. Keep unverified items explicit and do not invent missing facts.',JSON.stringify(contract)].join('\n');
  let responseText='';let parsed:CandidateGenerationFile[]|undefined;let attemptCount=0;let lastReason='CODE_GENERATION_NOT_STARTED';
  while(attemptCount<2&&!parsed){attemptCount+=1;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const response=await fetch(apiUrl('/api/chat'),{method:'POST',headers:getCustomApiHeaders(),signal:controller.signal,body:JSON.stringify({prompt:attemptCount===1?prompt:`${prompt}\nPrevious response was rejected: ${lastReason}. Return corrected JSON only.`,history:[],useSearch:false,engineMode:'cloud',speakerMode:false,workspaceFiles:targetFiles.map(file=>({path:file.path,name:file.path.split('/').pop()||file.path,content:file.content,language:file.language})),attachedFiles:[],memories:[],activeGameCode:''})});if(!response.ok){lastReason=`CODE_GENERATION_HTTP_${response.status}`;continue;}const body=await response.json();responseText=this.extractResponseText(body);if(!responseText.trim()){lastReason='CODE_GENERATION_EMPTY_RESPONSE';continue;}parsed=this.parse(responseText);if(!parsed)lastReason='CODE_GENERATION_RESPONSE_INVALID_JSON';}catch(error){lastReason=error instanceof Error&&error.name==='AbortError'?'CODE_GENERATION_TIMEOUT':`CODE_GENERATION_REQUEST_FAILED:${error instanceof Error?error.message:String(error)}`;}finally{clearTimeout(timer);}}
  this.record(runId,{attemptCount,status:parsed?'PARSED':'FAILED',reason:parsed?undefined:lastReason,responseHash:responseText?canonicalSha256(responseText):undefined,updatedAt:Date.now()});
  if(!parsed)return {accepted:false,runId,files:[],reasons:[lastReason],responseHash:responseText?canonicalSha256(responseText):undefined,attemptCount};
  const targetSet=new Set(targetPaths);const reasons:string[]=[];const files:CandidateGenerationFile[]=[];
  for(const item of parsed){if(!targetSet.has(item.path)){reasons.push(`UNEXPECTED_TARGET:${item.path}`);continue;}const baseline=sources.get(item.path)?.content||'';if(!item.candidateContent.trim()||item.candidateContent.trim()===baseline.trim()){reasons.push(`UNCHANGED_OR_EMPTY:${item.path}`);continue;}for(const prohibition of this.strings(run.payload.prohibitions)){if(prohibition&&item.candidateContent.includes(prohibition))reasons.push(`PROHIBITION_TEXT_PRESENT:${prohibition}`);}files.push({path:item.path,candidateContent:item.candidateContent,evidenceIds:item.evidenceIds});}
  if(reasons.length>0||files.length===0)return {accepted:false,runId,files:[],reasons:reasons.length?reasons:['NO_VALID_CANDIDATE_FILES'],responseHash:canonicalSha256(responseText),attemptCount};
  const prepared=await autonomousCandidatePreparationService.prepareForRun(runId,files);if(!prepared.workspaceId)return {accepted:false,runId,files:[],reasons:[prepared.reason||'CANDIDATE_WORKSPACE_NOT_CREATED'],responseHash:canonicalSha256(responseText),attemptCount};
  return {accepted:true,runId,workspaceId:prepared.workspaceId,files,reasons:[],responseHash:canonicalSha256(responseText),attemptCount,learningLineage:{usedLearningArtifactIds:learningContext.usedLearningArtifactIds,ignoredLearningArtifactIds:learningContext.ignoredArtifactIds,appliedFailurePatternIds:learningContext.appliedFailurePatternIds,appliedCorrectionPairIds:learningContext.appliedCorrectionPairIds,appliedComponentPatternIds:learningContext.appliedComponentPatternIds,learningContextSha256:learningContext.learningContextSha256,componentPackId:componentPack.componentPackId,usedKnowledgeComponentIds:componentPack.usedKnowledgeComponentIds,usedCodeComponentIds:componentPack.usedCodeComponentIds,usedConversationComponentIds:componentPack.usedConversationComponentIds,excludedComponentIds:componentPack.excludedComponentIds,componentContextSha256:componentPack.componentContextSha256}};
 }
 private extractResponseText(body:unknown):string{if(typeof body==='string')return body;if(!body||typeof body!=='object')return '';const object=body as Record<string,unknown>;for(const key of ['response','text','content','message','answer']){const value=object[key];if(typeof value==='string')return value;if(value&&typeof value==='object'){const nested=value as Record<string,unknown>;if(typeof nested.content==='string')return nested.content;if(typeof nested.text==='string')return nested.text;}}return '';}
 private parse(text:string):CandidateGenerationFile[]|undefined{const cleaned=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const start=cleaned.indexOf('{');const end=cleaned.lastIndexOf('}');const options=[cleaned,start>=0&&end>start?cleaned.slice(start,end+1):''];for(const option of options){if(!option)continue;try{const value=JSON.parse(option);if(!value||!Array.isArray(value.files))continue;const files:CandidateGenerationFile[]=[];for(const row of value.files){if(typeof row?.path!=='string'||typeof row?.candidateContent!=='string')return undefined;files.push({path:row.path,candidateContent:row.candidateContent,evidenceIds:Array.isArray(row.evidenceIds)?row.evidenceIds.filter((x:unknown):x is string=>typeof x==='string'):[]});}return files;}catch{continue;}}return undefined;}
 private record(runId:string,value:Record<string,unknown>):void{const key='miki_candidate_generation_ledger_v2';let ledger:Record<string,unknown>;try{const raw=storageService.getItem(key);const parsed:unknown=raw?JSON.parse(raw):{};ledger=parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch(error){throw new Error(`PERSISTENCE_FAILED:CANDIDATE_LEDGER_READ:${error instanceof Error?error.message:String(error)}`);}const record={runId,...value};try{storageService.setItem(key,JSON.stringify({...ledger,[runId]:record}));const reloadedRaw=storageService.getItem(key);const reloaded:unknown=reloadedRaw?JSON.parse(reloadedRaw):undefined;if(!reloaded||typeof reloaded!=='object'||Array.isArray(reloaded)||(reloaded as Record<string,unknown>)[runId]===undefined)throw new Error('RELOAD_MISSING');const expected=canonicalSha256(record);const actual=canonicalSha256((reloaded as Record<string,unknown>)[runId]);if(actual!==expected)throw new Error('RELOAD_HASH_MISMATCH');}catch(error){throw new Error(`PERSISTENCE_FAILED:CANDIDATE_LEDGER_WRITE:${error instanceof Error?error.message:String(error)}`);}}
 private strings(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];}
}
export const candidateCodeGenerationService=new CandidateCodeGenerationService();
