import { apiUrl, getCustomApiHeaders } from '../../../services/api';
import { autonomousCandidatePreparationService } from './autonomousCandidatePreparationService';
import { isolatedCandidateWorkspaceService } from './isolatedCandidateWorkspaceService';
import { candidateValidationEvidenceService, type ValidationStage } from './candidateValidationEvidenceService';
import { shadowEvaluationService } from './shadowEvaluationService';
export interface ValidationRunnerResult { passed:boolean; workspaceId:string; reasons:string[]; }
class CandidateValidationRunnerService {
 async run(workspaceId:string):Promise<ValidationRunnerResult>{const workspace=isolatedCandidateWorkspaceService.get(workspaceId);if(!workspace)return {passed:false,workspaceId,reasons:['WORKSPACE_NOT_FOUND']};const candidateSha256=workspace.files[0]?.candidateSha256||'';if(!candidateSha256)return {passed:false,workspaceId,reasons:['CANDIDATE_HASH_MISSING']};const sourceFiles=autonomousCandidatePreparationService.getSourceFiles();let response:Response;try{response=await fetch(apiUrl('/api/candidate-validation/run'),{method:'POST',headers:getCustomApiHeaders(),body:JSON.stringify({workspaceId,candidateSha256,sourceFiles,candidateFiles:workspace.files.map(file=>({path:file.path,baselineContent:file.baselineContent,candidateContent:file.candidateContent,baselineSha256:file.baselineSha256,candidateSha256:file.candidateSha256}))})});}catch(error){return {passed:false,workspaceId,reasons:[error instanceof Error?`VALIDATION_REQUEST_FAILED:${error.message}`:'VALIDATION_REQUEST_FAILED']};}if(!response.ok)return {passed:false,workspaceId,reasons:[`VALIDATION_HTTP_${response.status}`]};const body=await response.json();const stages=Array.isArray(body.stages)?body.stages:[];for(const row of stages){candidateValidationEvidenceService.record({workspaceId,candidateSha256,stage:row.stage as ValidationStage,passed:Boolean(row.passed),command:String(row.command||''),exitCode:Number(row.exitCode??1),startedAt:Number(row.startedAt||Date.now()),completedAt:Number(row.completedAt||Date.now()),logRef:String(row.logRef||'')});}if(body.shadow?.baseline&&body.shadow?.candidate)shadowEvaluationService.compare(workspaceId,body.shadow.baseline,body.shadow.candidate);const evaluation=candidateValidationEvidenceService.evaluate(workspaceId,candidateSha256);return {passed:evaluation.passed&&Boolean(body.shadow?.passed),workspaceId,reasons:[...evaluation.missing.map(value=>`MISSING_${value}`),...evaluation.failed.map(value=>`FAILED_${value}`),...(Array.isArray(body.reasons)?body.reasons:[])]};}
}
export const candidateValidationRunnerService=new CandidateValidationRunnerService();
