import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from './canonicalSha256Service';
import { reusableComponentFactoryService } from './reusableComponentFactoryService';
import { researchQueryPlanningService } from '../../research/services/researchQueryPlanningService';
import { unifiedUnknownResolutionCoordinatorService } from '../../unknown/services/unifiedUnknownResolutionCoordinatorService';

export type CandidateUnknownKind='MISSING_KNOWLEDGE'|'MISSING_REPOSITORY_CONTEXT'|'MISSING_IMPLEMENTATION_PATTERN'|'MISSING_TEST_ORACLE';
export type CandidateUnknownStatus='RESOLVED'|'PARTIAL'|'EXTERNAL_QUESTION_REQUIRED';
export interface CandidateUnknownInput{runId:string;taskId:string;objective:string;environmentFingerprint:string;targetPaths:string[];sourcePaths:string[];requirements:string[];validationRequirements:string[];}
export interface CandidateUnknownItem{unknownId:string;kind:CandidateUnknownKind;question:string;status:CandidateUnknownStatus;queryPlanId:string;queryPlanSha256:string;effectiveText:string;evidenceCount:number;verificationStatus:'VERIFIED'|'UNVERIFIED';componentDecision:'REUSE'|'ADAPT'|'CREATE'|'DEFER';componentPackId?:string;candidateNote:string;externalQuestion?:string;}
export interface CandidateUnknownContext{contextId:string;runId:string;items:CandidateUnknownItem[];candidateNotes:string[];externalQuestions:string[];contextSha256:string;createdAt:number;}
const KEY='miki_candidate_unknown_context_v1';
class CandidateUnknownResolutionService{
 async resolve(input:CandidateUnknownInput):Promise<CandidateUnknownContext>{const questions=this.detect(input);const items:CandidateUnknownItem[]=[];for(const entry of questions){const plan=researchQueryPlanningService.buildPlan(entry.question);const resolution=await unifiedUnknownResolutionCoordinatorService.resolveForChat({question:entry.question,useSearch:true,unknownTerms:[entry.question],hasAttachments:input.sourcePaths.length>0});const verified=resolution.status==='REUSED_SUPPORTED'||resolution.status==='LOCAL_EVIDENCE';const componentPack=reusableComponentFactoryService.plan({taskId:input.taskId,purpose:entry.question,environmentFingerprint:input.environmentFingerprint,requiredKinds:entry.kind==='MISSING_IMPLEMENTATION_PATTERN'?['CODE']:['KNOWLEDGE','CODE']});const hasReusable=componentPack.usedKnowledgeComponentIds.length+componentPack.usedCodeComponentIds.length>0;const componentDecision=hasReusable?'REUSE':entry.kind==='MISSING_IMPLEMENTATION_PATTERN'?'CREATE':entry.kind==='MISSING_REPOSITORY_CONTEXT'?'DEFER':'ADAPT';const status:CandidateUnknownStatus=verified?'RESOLVED':resolution.evidenceCount>0?'PARTIAL':'EXTERNAL_QUESTION_REQUIRED';const unknownId=`CUNK-${canonicalSha256({runId:input.runId,kind:entry.kind,question:entry.question}).slice(0,20)}`;items.push({unknownId,kind:entry.kind,question:entry.question,status,queryPlanId:plan.queryPlanId,queryPlanSha256:plan.planSha256,effectiveText:resolution.effectiveText,evidenceCount:resolution.evidenceCount,verificationStatus:verified?'VERIFIED':'UNVERIFIED',componentDecision,componentPackId:componentPack.componentPackId,candidateNote:status==='RESOLVED'?`Resolved ${entry.kind}: ${entry.question}`:`Unverified ${entry.kind}: ${entry.question}`,externalQuestion:status==='EXTERNAL_QUESTION_REQUIRED'?`External reviewer question [${entry.kind}]: ${entry.question}`:undefined});}const body={runId:input.runId,items,candidateNotes:items.filter(item=>item.status!=='RESOLVED').map(item=>item.candidateNote),externalQuestions:items.map(item=>item.externalQuestion).filter((value):value is string=>Boolean(value)),createdAt:Date.now()};const contextSha256=canonicalSha256(body);const context={contextId:`CUC-${contextSha256.slice(0,20)}`,...body,contextSha256};this.save(context);return context;}
 get(runId:string):CandidateUnknownContext|undefined{return this.list().filter(item=>item.runId===runId).sort((a,b)=>b.createdAt-a.createdAt)[0];}
 list():CandidateUnknownContext[]{try{const raw=storageService.getItem(KEY),parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return[]}}
 private detect(input:CandidateUnknownInput):Array<{kind:CandidateUnknownKind;question:string}>{const rows:Array<{kind:CandidateUnknownKind;question:string}>=[];if(input.sourcePaths.length<input.targetPaths.length)rows.push({kind:'MISSING_REPOSITORY_CONTEXT',question:`Repository context is incomplete for targets: ${input.targetPaths.filter(path=>!input.sourcePaths.includes(path)).join(', ')}`});if(input.requirements.some(value=>/unknown|未確認|不明/i.test(value)))rows.push({kind:'MISSING_KNOWLEDGE',question:`Resolve requirement knowledge for ${input.objective}: ${input.requirements.join(' / ')}`});if(input.validationRequirements.length===0)rows.push({kind:'MISSING_TEST_ORACLE',question:`Define test oracle and expected validation for ${input.objective}`});if(input.requirements.some(value=>/component|pattern|実装|部品/i.test(value)))rows.push({kind:'MISSING_IMPLEMENTATION_PATTERN',question:`Select reusable, adaptable, or new implementation component for ${input.objective}`});return rows;}
 private save(value:CandidateUnknownContext){const values=this.list().filter(item=>item.contextId!==value.contextId);values.push(value);storageService.setItem(KEY,JSON.stringify(values.slice(-500)));}
}
export const candidateUnknownResolutionService=new CandidateUnknownResolutionService();
