import { canonicalSha256Object } from './canonicalSha256Service';
import { persistentVisualMemoryStoreService, type PersistentVisualMemoryRecord } from './persistentVisualMemoryStoreService';
import { visualProjectLearningCompositionService, type VisualKnowledgeMemory } from './visualProjectLearningCompositionService';
import type { VisualMemoryScope } from './visualConversationProjectGatewayService';

export type EvidenceState='OBSERVED'|'MULTI_VIEW_DERIVED'|'INFERRED'|'LEARNED_COMPLETION'|'USER_DEFINED'|'UNKNOWN'|'CONFLICTING'|'OCCLUDED'|'GARMENT_AFFECTED';
export interface VisualFact<T>{value:T|null;state:EvidenceState;confidence:number;sourceSha256List:string[];view?:'FRONT'|'SIDE'|'BACK'|'THREE_QUARTER'|'VIDEO'|'UNKNOWN';notes?:string[];}
export interface Point3Fact{ x:VisualFact<number>;y:VisualFact<number>;z:VisualFact<number>; }
export interface CrossSectionFact{normalizedY:number;leftWidth:VisualFact<number>;rightWidth:VisualFact<number>;frontDepth:VisualFact<number>;backDepth:VisualFact<number>;visibleWidth:VisualFact<number>;garmentOffset:VisualFact<number>;bodyWidth:VisualFact<number>;}
export interface ComprehensiveVisualProfile {
 profileId:string; revision:number; subject:string; sourceSha256List:string[]; createdAt:number; updatedAt:number;
 head:{headToHeight:VisualFact<number>;headWidthToHeight:VisualFact<number>;faceWidthToHeight:VisualFact<number>;faceHeightToHeight:VisualFact<number>;jawWidthToFace:VisualFact<number>;foreheadToFace:VisualFact<number>;chinToFace:VisualFact<number>;eyeLine:VisualFact<number>;eyeSpacing:VisualFact<number>;noseLength:VisualFact<number>;mouthWidth:VisualFact<number>;earPosition:VisualFact<number>;headYaw:VisualFact<number>;headPitch:VisualFact<number>;headRoll:VisualFact<number>;};
 hair:{length:VisualFact<number>;width:VisualFact<number>;volume:VisualFact<number>;frontContour:VisualFact<number[]>;sideContour:VisualFact<number[]>;backContour:VisualFact<number[]>;flowDirection:VisualFact<number>;strandDensity:VisualFact<number>;};
 neckShoulders:{neckLength:VisualFact<number>;neckWidth:VisualFact<number>;neckDepth:VisualFact<number>;shoulderWidth:VisualFact<number>;shoulderSlopeLeft:VisualFact<number>;shoulderSlopeRight:VisualFact<number>;clavicleLine:VisualFact<number>;};
 ribcage:{upperWidth:VisualFact<number>;middleWidth:VisualFact<number>;lowerWidth:VisualFact<number>;height:VisualFact<number>;depth:VisualFact<number>;tilt:VisualFact<number>;};
 chestSurface:{totalWidth:VisualFact<number>;totalHeight:VisualFact<number>;forwardProjection:VisualFact<number>;leftContour:VisualFact<number[]>;rightContour:VisualFact<number[]>;verticalPosition:VisualFact<number>;spacing:VisualFact<number>;relativeToRibcage:VisualFact<number>;};
 abdomen:{upperWidth:VisualFact<number>;middleWidth:VisualFact<number>;lowerWidth:VisualFact<number>;upperProjection:VisualFact<number>;middleProjection:VisualFact<number>;lowerProjection:VisualFact<number>;leftContour:VisualFact<number[]>;rightContour:VisualFact<number[]>;roundness:VisualFact<number>;};
 waistPelvis:{waistWidth:VisualFact<number>;waistHeight:VisualFact<number>;pelvisWidth:VisualFact<number>;pelvisHeight:VisualFact<number>;pelvisDepth:VisualFact<number>;pelvisTilt:VisualFact<number>;backCurve:VisualFact<number[]>;centerLine:VisualFact<number[]>;};
 arms:{upperArmLengthLeft:VisualFact<number>;upperArmLengthRight:VisualFact<number>;forearmLengthLeft:VisualFact<number>;forearmLengthRight:VisualFact<number>;upperArmWidthLeft:VisualFact<number>;upperArmWidthRight:VisualFact<number>;elbowWidthLeft:VisualFact<number>;elbowWidthRight:VisualFact<number>;forearmWidthLeft:VisualFact<number>;forearmWidthRight:VisualFact<number>;wristWidthLeft:VisualFact<number>;wristWidthRight:VisualFact<number>;handLengthLeft:VisualFact<number>;handLengthRight:VisualFact<number>;};
 legs:{thighLengthLeft:VisualFact<number>;thighLengthRight:VisualFact<number>;lowerLegLengthLeft:VisualFact<number>;lowerLegLengthRight:VisualFact<number>;upperThighWidthLeft:VisualFact<number>;upperThighWidthRight:VisualFact<number>;midThighWidthLeft:VisualFact<number>;midThighWidthRight:VisualFact<number>;kneeWidthLeft:VisualFact<number>;kneeWidthRight:VisualFact<number>;calfWidthLeft:VisualFact<number>;calfWidthRight:VisualFact<number>;ankleWidthLeft:VisualFact<number>;ankleWidthRight:VisualFact<number>;footLengthLeft:VisualFact<number>;footLengthRight:VisualFact<number>;};
 skeleton:Record<string,Point3Fact>;
 crossSections:CrossSectionFact[];
 garment:{regions:Record<string,{visibleWidth:VisualFact<number>;estimatedThickness:VisualFact<number>;estimatedBodyWidth:VisualFact<number>;compression:VisualFact<number>}>;material:VisualFact<string>;stiffness:VisualFact<number>;shine:VisualFact<number>;wrinkleDensity:VisualFact<number>;};
 appearance:{palette:VisualFact<string[]>;skinPalette:VisualFact<string[]>;hairPalette:VisualFact<string[]>;garmentPalettes:Record<string,VisualFact<string[]>>;outlineStrength:VisualFact<number>;shadowLevels:VisualFact<number>;textureGrain:VisualFact<number>;localContrast:VisualFact<number>;detailDensity:VisualFact<number>;};
 motion:{poseConfidence:VisualFact<number>;walkCycle:VisualFact<number[]>;armSwing:VisualFact<number>;legStride:VisualFact<number>;bodyBounce:VisualFact<number>;hairDelay:VisualFact<number>;garmentDelay:VisualFact<number>;turnTiming:VisualFact<number>;};
 scene:{depthAvailable:VisualFact<boolean>;relativeDepth:VisualFact<number[]>;cameraAngle:VisualFact<number>;lightDirection:VisualFact<number>;backgroundPalette:VisualFact<string[]>;};
 unknownPaths:string[]; conflictingPaths:string[]; completeness:number; profileSha256:string;
}
export interface ComprehensiveProfileContext{subject:string;sourceSha256List:string[];scope:VisualMemoryScope;projectId?:string;familyId?:string;confidence:number;status?:'PROVISIONAL'|'GROWING'|'STABLE';profileId?:string;revision?:number;}

const fact=<T>(value:T|null=null,state:EvidenceState='UNKNOWN',confidence=0,sources:string[]=[]):VisualFact<T>=>({value,state,confidence,sourceSha256List:sources});
class ComprehensiveVisualProfileService {
 create(context:ComprehensiveProfileContext,partial?:Partial<ComprehensiveVisualProfile>):ComprehensiveVisualProfile {if(!context.subject.trim()||!context.sourceSha256List.length)throw new Error('VISUAL_PROFILE_SOURCE_REQUIRED');const now=Date.now(),s=context.sourceSha256List;const f=<T>()=>fact<T>(null,'UNKNOWN',0,s);const profile:any={profileId:context.profileId??`VP-${canonicalSha256Object({subject:context.subject,sources:[...s].sort()}).slice(0,24)}`,revision:context.revision??1,subject:context.subject,sourceSha256List:[...new Set(s)].sort(),createdAt:now,updatedAt:now,
 head:{headToHeight:f(),headWidthToHeight:f(),faceWidthToHeight:f(),faceHeightToHeight:f(),jawWidthToFace:f(),foreheadToFace:f(),chinToFace:f(),eyeLine:f(),eyeSpacing:f(),noseLength:f(),mouthWidth:f(),earPosition:f(),headYaw:f(),headPitch:f(),headRoll:f()},
 hair:{length:f(),width:f(),volume:f(),frontContour:f(),sideContour:f(),backContour:f(),flowDirection:f(),strandDensity:f()},neckShoulders:{neckLength:f(),neckWidth:f(),neckDepth:f(),shoulderWidth:f(),shoulderSlopeLeft:f(),shoulderSlopeRight:f(),clavicleLine:f()},ribcage:{upperWidth:f(),middleWidth:f(),lowerWidth:f(),height:f(),depth:f(),tilt:f()},chestSurface:{totalWidth:f(),totalHeight:f(),forwardProjection:f(),leftContour:f(),rightContour:f(),verticalPosition:f(),spacing:f(),relativeToRibcage:f()},abdomen:{upperWidth:f(),middleWidth:f(),lowerWidth:f(),upperProjection:f(),middleProjection:f(),lowerProjection:f(),leftContour:f(),rightContour:f(),roundness:f()},waistPelvis:{waistWidth:f(),waistHeight:f(),pelvisWidth:f(),pelvisHeight:f(),pelvisDepth:f(),pelvisTilt:f(),backCurve:f(),centerLine:f()},arms:{upperArmLengthLeft:f(),upperArmLengthRight:f(),forearmLengthLeft:f(),forearmLengthRight:f(),upperArmWidthLeft:f(),upperArmWidthRight:f(),elbowWidthLeft:f(),elbowWidthRight:f(),forearmWidthLeft:f(),forearmWidthRight:f(),wristWidthLeft:f(),wristWidthRight:f(),handLengthLeft:f(),handLengthRight:f()},legs:{thighLengthLeft:f(),thighLengthRight:f(),lowerLegLengthLeft:f(),lowerLegLengthRight:f(),upperThighWidthLeft:f(),upperThighWidthRight:f(),midThighWidthLeft:f(),midThighWidthRight:f(),kneeWidthLeft:f(),kneeWidthRight:f(),calfWidthLeft:f(),calfWidthRight:f(),ankleWidthLeft:f(),ankleWidthRight:f(),footLengthLeft:f(),footLengthRight:f()},skeleton:{},crossSections:[],garment:{regions:{},material:f(),stiffness:f(),shine:f(),wrinkleDensity:f()},appearance:{palette:f(),skinPalette:f(),hairPalette:f(),garmentPalettes:{},outlineStrength:f(),shadowLevels:f(),textureGrain:f(),localContrast:f(),detailDensity:f()},motion:{poseConfidence:f(),walkCycle:f(),armSwing:f(),legStride:f(),bodyBounce:f(),hairDelay:f(),garmentDelay:f(),turnTiming:f()},scene:{depthAvailable:f(),relativeDepth:f(),cameraAngle:f(),lightDirection:f(),backgroundPalette:f()},unknownPaths:[],conflictingPaths:[],completeness:0,profileSha256:''};this.merge(profile,partial??{});return this.finalize(profile);}
 save(profile:ComprehensiveVisualProfile,context:ComprehensiveProfileContext):PersistentVisualMemoryRecord {this.validate(profile);const memory=visualProjectLearningCompositionService.createMemory({kind:'VISUAL_PROFILE',subject:profile.subject,payload:{profile,representation:'COMPREHENSIVE_VISUAL_PROFILE',rawImageStored:false,identityMatching:false,notMedicalAssessment:true},confidence:context.confidence,status:context.status??(context.confidence>=.88?'STABLE':context.confidence>=.68?'GROWING':'PROVISIONAL'),sourceSha256List:profile.sourceSha256List});return persistentVisualMemoryStoreService.save(memory,context.scope,context);}
 load(subject:string,context:{projectId?:string;familyId?:string;minConfidence?:number}={}):ComprehensiveVisualProfile[]{const records=persistentVisualMemoryStoreService.query({...context,subject,kinds:['VISUAL_PROFILE'],limit:12});persistentVisualMemoryStoreService.markUsed(records.map(x=>x.memory.memoryId),context);return records.map(x=>(x.memory.payload as any).profile as ComprehensiveVisualProfile);}
 revise(previous:ComprehensiveVisualProfile,patch:Partial<ComprehensiveVisualProfile>,sources:string[]):ComprehensiveVisualProfile {const next=structuredClone(previous) as any;next.revision=previous.revision+1;next.updatedAt=Date.now();next.sourceSha256List=[...new Set([...previous.sourceSha256List,...sources])].sort();this.merge(next,patch);return this.finalize(next);}
 private finalize(profile:any):ComprehensiveVisualProfile {const paths:{path:string;fact:VisualFact<unknown>}[]=[];const walk=(v:any,p:string)=>{if(v&&typeof v==='object'&&'state'in v&&'confidence'in v&&'sourceSha256List'in v)paths.push({path:p,fact:v});else if(Array.isArray(v))v.forEach((x,i)=>walk(x,`${p}[${i}]`));else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v))if(!['profileSha256','unknownPaths','conflictingPaths','completeness'].includes(k))walk(x,p?`${p}.${k}`:k);};walk(profile,'');profile.unknownPaths=paths.filter(x=>['UNKNOWN','OCCLUDED'].includes(x.fact.state)).map(x=>x.path);profile.conflictingPaths=paths.filter(x=>x.fact.state==='CONFLICTING').map(x=>x.path);const known=paths.filter(x=>!['UNKNOWN','OCCLUDED'].includes(x.fact.state)&&x.fact.value!==null);profile.completeness=paths.length?known.reduce((n,x)=>n+x.fact.confidence,0)/paths.length:0;profile.profileSha256='';profile.profileSha256=canonicalSha256Object(profile);return profile;}
 private validate(profile:ComprehensiveVisualProfile){const copy=structuredClone(profile);copy.profileSha256='';if(canonicalSha256Object(copy)!==profile.profileSha256)throw new Error('VISUAL_PROFILE_SHA_MISMATCH');if(profile.completeness<0||profile.completeness>1)throw new Error('VISUAL_PROFILE_COMPLETENESS_INVALID');}
 private merge(target:any,patch:any){for(const [key,value]of Object.entries(patch)){if(value===undefined||['profileSha256','unknownPaths','conflictingPaths','completeness'].includes(key))continue;if(value&&typeof value==='object'&&!Array.isArray(value)&&target[key]&&typeof target[key]==='object'&&!('state'in value))this.merge(target[key],value);else target[key]=structuredClone(value);}}
}
export const comprehensiveVisualProfileService=new ComprehensiveVisualProfileService();
export { fact as visualFact };
