export interface ComplexCapabilityContract{capability:string;inputSource:string;requiredEvidence:string[];workspaceRequired:boolean;candidateShaRequired:boolean;rollbackTarget:string;consumer:string;coreEvidenceEvent:string;invalidationTargets:string[];execution:'EXPLICIT'|'UI_ONLY'|'DIAGNOSTIC'|'BLOCKED_REMOTE';canonical?:string;}
const contracts:ComplexCapabilityContract[]=[
{capability:'multiIntentAstMergeService',inputSource:'core SELF_IMPROVEMENT payload.multiIntentAstMerge',requiredEvidence:['SEMANTIC_FRAME','BASELINE_SHA','INTENT_EVIDENCE'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'baseline content',consumer:'multiIntentWorkspaceTransactionService',coreEvidenceEvent:'MULTI_INTENT_AST_MERGE',invalidationTargets:['merged candidate','workspace','review package'],execution:'EXPLICIT'},
{capability:'multiIntentWorkspaceTransactionService',inputSource:'core SELF_IMPROVEMENT payload.workspaceFragments',requiredEvidence:['FRAGMENT_EVIDENCE','BASELINE_SHA'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'fragment parent workspaces',consumer:'candidateConstraintValidationService',coreEvidenceEvent:'MULTI_INTENT_WORKSPACE_TRANSACTION',invalidationTargets:['merged workspace','validation evidence','review package'],execution:'EXPLICIT'},
{capability:'multiRepositoryAtomicCandidateService',inputSource:'core SELF_IMPROVEMENT payload.repositoryChanges',requiredEvidence:['REPOSITORY_REVISION','CHANGE_EVIDENCE','BASELINE_SHA'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'per-repository baseline snapshot',consumer:'cumulativeRevalidationService',coreEvidenceEvent:'MULTI_REPOSITORY_ATOMIC_CANDIDATE',invalidationTargets:['all repository candidates','combined review package'],execution:'EXPLICIT'},
{capability:'productionScaleE2EOrchestratorService',inputSource:'core SELF_IMPROVEMENT payload.productionScaleE2E',requiredEvidence:['CANDIDATE_VALIDATION','RESOURCE_PREFLIGHT'],workspaceRequired:true,candidateShaRequired:true,rollbackTarget:'runtime adapter rollback token',consumer:'runtimeProofOrchestratorService',coreEvidenceEvent:'PRODUCTION_SCALE_E2E',invalidationTargets:['runtime proof','canary','adoption readiness'],execution:'EXPLICIT'},
{capability:'realE2EProofSuiteService',inputSource:'core SELF_IMPROVEMENT payload.runRealE2EProof',requiredEvidence:['CANDIDATE_VALIDATION'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'isolated proof workspace',consumer:'acceptanceEvidenceMatrixService',coreEvidenceEvent:'REAL_E2E_PROOF_SUITE',invalidationTargets:['proof evidence','acceptance matrix'],execution:'DIAGNOSTIC'},
{capability:'remoteExecutionAgentProtocolService',inputSource:'core SELF_IMPROVEMENT payload.remoteExecution',requiredEvidence:['SIGNED_MANIFEST','PAYLOAD_HASH','AGENT_ATTESTATION','PERMISSION'],workspaceRequired:true,candidateShaRequired:true,rollbackTarget:'remote job cancellation and local workspace baseline',consumer:'runIntegrityAuditorService',coreEvidenceEvent:'REMOTE_EXECUTION_PROTOCOL',invalidationTargets:['remote result','attestation','candidate evidence','review package'],execution:'BLOCKED_REMOTE'},
{capability:'runtimeProofOrchestratorService',inputSource:'productionScaleE2EOrchestratorService result',requiredEvidence:['RUNTIME_JOB','CANDIDATE_SHA','ENVIRONMENT_FINGERPRINT'],workspaceRequired:true,candidateShaRequired:true,rollbackTarget:'candidate workspace baseline',consumer:'runtimeCoverageGraphService',coreEvidenceEvent:'RUNTIME_PROOF',invalidationTargets:['coverage evidence','acceptance evidence','adoption readiness'],execution:'EXPLICIT'},
{capability:'runtimeCoverageGraphService',inputSource:'runtime proof result payload.coverageEdges',requiredEvidence:['TEST_ID','SYMBOL_ID','REPOSITORY_REVISION','ENVIRONMENT_FINGERPRINT'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'remove coverage record by evidence lineage',consumer:'core cognitive evidence',coreEvidenceEvent:'RUNTIME_COVERAGE_GRAPH',invalidationTargets:['coverage status','task completion','adoption readiness'],execution:'EXPLICIT'},
{capability:'selfDevelopmentArchitectureAuditService',inputSource:'core SELF_IMPROVEMENT preflight',requiredEvidence:['SOURCE_SNAPSHOT'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'none read-only',consumer:'advancedPipelineHandoffAuditService',coreEvidenceEvent:'SELF_DEVELOPMENT_ARCHITECTURE_AUDIT',invalidationTargets:['architecture audit evidence'],execution:'EXPLICIT'},
{capability:'stages41To50GovernanceGateService',inputSource:'core PREPARE_ADOPTION',requiredEvidence:['GOAL_REVISION','CHANGED_SYMBOLS','TEST_CRITERIA','TEST_RESULTS','SUPPLY_CHAIN_GATE'],workspaceRequired:false,candidateShaRequired:true,rollbackTarget:'stop adoption and preserve candidate',consumer:'core adoption decision',coreEvidenceEvent:'STAGES_41_50_GOVERNANCE_GATE',invalidationTargets:['adoption readiness'],execution:'EXPLICIT'},
{capability:'runIntegrityAuditorService',inputSource:'core SELF_IMPROVEMENT payload runId/workspaceId',requiredEvidence:['RUN_ID','WORKSPACE_ID','VALIDATION','SHADOW_EVALUATION'],workspaceRequired:true,candidateShaRequired:false,rollbackTarget:'workspace baseline',consumer:'core improvement decision',coreEvidenceEvent:'RUN_INTEGRITY_AUDIT',invalidationTargets:['completion','review package','adoption readiness'],execution:'EXPLICIT'},
{capability:'migrationRepositoryIntegrationService',inputSource:'explicit migration request',requiredEvidence:['MIGRATION_ID','ROUND_TRIP_TEST','ROLLBACK_TEST'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'pre-migration repository snapshot',consumer:'candidate workspace builder',coreEvidenceEvent:'MIGRATION_REPOSITORY_PLAN',invalidationTargets:['migration workspace','round-trip evidence'],execution:'EXPLICIT'},
{capability:'relevantCausalAnalysisService',inputSource:'semantic frame plus target paths',requiredEvidence:['SEMANTIC_FRAME','TARGET_PATHS'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'none read-only',consumer:'repair planning evidence',coreEvidenceEvent:'RELEVANT_CAUSAL_ANALYSIS',invalidationTargets:['causal hypothesis','repair plan'],execution:'EXPLICIT'},
{capability:'memoryPromotionService',inputSource:'validated task case completion',requiredEvidence:['TASK_CASE','TESTED_OR_ADOPTED'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'remove promoted memory',consumer:'longTermMemoryService',coreEvidenceEvent:'MEMORY_PROMOTION',invalidationTargets:['promoted memory','retrieval cache'],execution:'EXPLICIT'},
{capability:'mikiAutonomousDevStudioService',inputSource:'explicit local studio operation',requiredEvidence:['USER_INTENT','ISOLATED_PROJECT'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'studio project snapshot',consumer:'candidate intake only',coreEvidenceEvent:'AUTONOMOUS_DEV_STUDIO',invalidationTargets:['studio candidate'],execution:'UI_ONLY'},
{capability:'mikiBrainCapsuleService',inputSource:'explicit export/import operation',requiredEvidence:['CAPSULE_MANIFEST','SHA256'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'pre-import memory snapshot',consumer:'memory import gate',coreEvidenceEvent:'BRAIN_CAPSULE',invalidationTargets:['imported memory batch'],execution:'UI_ONLY'},
{capability:'priority12ArtifactWorkspaceService',inputSource:'explicit artifact workspace request',requiredEvidence:['ARTIFACT_ID','SOURCE_SHA'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'artifact workspace baseline',consumer:'review package builder',coreEvidenceEvent:'PRIORITY12_ARTIFACT_WORKSPACE',invalidationTargets:['artifact workspace','review package'],execution:'EXPLICIT'},
{capability:'selfImprovementSuiteService',inputSource:'explicit diagnostic suite request',requiredEvidence:['SOURCE_SNAPSHOT'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'isolated test state',consumer:'core diagnostic evidence',coreEvidenceEvent:'SELF_IMPROVEMENT_SUITE',invalidationTargets:['suite evidence'],execution:'DIAGNOSTIC'},
{capability:'semanticContextBudgetService',inputSource:'conversation and core context selection',requiredEvidence:['QUERY','CONTEXT_ITEMS'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'none read-only',consumer:'semantic understanding',coreEvidenceEvent:'SEMANTIC_CONTEXT_BUDGET',invalidationTargets:['selected context cache'],execution:'EXPLICIT'},
{capability:'surfaceVariationGrowthService',inputSource:'conversation evaluation weaknesses',requiredEvidence:['EVALUATION_EVIDENCE','WEAKNESS_CATEGORY'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'discard variation candidate',consumer:'offline conversation evaluation',coreEvidenceEvent:'SURFACE_VARIATION_GROWTH',invalidationTargets:['variation candidate'],execution:'DIAGNOSTIC'},
{capability:'typedCoreUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'operation-specific',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_CORE_UI',invalidationTargets:['UI operation result'],execution:'UI_ONLY'},
{capability:'typedGitHubUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND','USER_PERMISSION'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'Git operation-specific',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_GITHUB_UI',invalidationTargets:['Git operation result'],execution:'UI_ONLY'},
{capability:'typedImprovementUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'candidate baseline',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_IMPROVEMENT_UI',invalidationTargets:['candidate result'],execution:'UI_ONLY'},
{capability:'typedMemoryUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'memory snapshot',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_MEMORY_UI',invalidationTargets:['memory mutation'],execution:'UI_ONLY'},
{capability:'typedPersonaUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'persona prior state',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_PERSONA_UI',invalidationTargets:['persona state'],execution:'UI_ONLY'},
{capability:'typedResearchUiGatewayService',inputSource:'typed UI command',requiredEvidence:['UI_COMMAND'],workspaceRequired:false,candidateShaRequired:false,rollbackTarget:'cancel research task',consumer:'coreTaskIngressService',coreEvidenceEvent:'TYPED_RESEARCH_UI',invalidationTargets:['research result'],execution:'UI_ONLY'}
];
class ComplexCapabilityContractService{
 list(){return contracts.map(contract=>({...contract,requiredEvidence:[...contract.requiredEvidence],invalidationTargets:[...contract.invalidationTargets]}));}
 validate(capability:string,input:Record<string,unknown>){const contract=contracts.find(item=>item.capability===capability);if(!contract)return{accepted:false,reasons:['UNKNOWN_COMPLEX_CAPABILITY'],contract:undefined};const evidenceIds=Array.isArray(input.evidenceIds)?input.evidenceIds.filter((x):x is string=>typeof x==='string'):[];const reasons:string[]=[];if(contract.workspaceRequired&&typeof input.workspaceId!=='string')reasons.push('WORKSPACE_ID_REQUIRED');if(contract.candidateShaRequired&&typeof input.candidateSha256!=='string')reasons.push('CANDIDATE_SHA_REQUIRED');if(contract.requiredEvidence.length&&!evidenceIds.length)reasons.push('EVIDENCE_IDS_REQUIRED');if(contract.execution==='BLOCKED_REMOTE'&&input.userApproved!==true)reasons.push('REMOTE_USER_APPROVAL_REQUIRED');return{accepted:reasons.length===0,reasons,contract,evidenceIds};}
}
export const complexCapabilityContractService=new ComplexCapabilityContractService();
