import { canonicalSha256Object } from './canonicalSha256Service';
import { conversationComponentPipelineService } from '../../conversation/services/conversationComponentPipelineService';

export type P207NodeKind='CONVERSATION_TURN'|'INTENT'|'CAPABILITY'|'COMPONENT'|'COMPOSITION_PLAN'|'COMPONENT_RUN'|'RESEARCH_TASK'|'CLAIM'|'EVIDENCE'|'POSITIVE_EXAMPLE'|'COUNTEREXAMPLE'|'FAILURE_PATTERN'|'REPAIR_ACTION'|'REUSE_CONDITION'|'VALIDATION'|'ANSWER_ARTIFACT';
export interface P207Node{nodeId:string;kind:P207NodeKind;label:string;payload:Record<string,unknown>;confidence:number;createdAt:number;sha256:string}
export interface P207Edge{edgeId:string;from:string;to:string;type:'EXPRESSES'|'REQUIRES'|'SELECTS'|'USES'|'PRODUCES'|'SUPPORTED_BY'|'CONTRADICTED_BY'|'FAILED_ON'|'FAILED_BECAUSE'|'REPAIRED_BY'|'VALID_WHEN'|'EVALUATED_BY'|'DERIVED_FROM'|'TRIGGERS';sha256:string}
export interface P207Graph{nodes:P207Node[];edges:P207Edge[];graphSha256:string}
export interface P207Case{caseId:string;input:string;expected:string;actual:string;passed:boolean;scope:string;severity:'LOW'|'MEDIUM'|'HIGH';confidence:number}
export interface P207Plan{planId:string;intentId:string;capabilityIds:string[];componentIds:string[];decision:'REUSE'|'COMPOSE'|'EXTEND'|'NEW'|'REJECT';reason:string;planSha256:string}
export interface P207LearningResult{graph:P207Graph;plan:P207Plan;positiveCases:P207Case[];counterExamples:P207Case[];researchTasks:string[];candidateComponents:string[];mutations:Array<{semanticKind:string;ownerDomain:string;participantDomains:string[];subjectId:string;payload:Record<string,unknown>}>;receiptSha256:string}

class ConversationResearchComponentGraphP207Service{
 analyze(text:string,cases:P207Case[]):P207LearningResult{const analysis=conversationComponentPipelineService.analyzeSync(text),nodes:P207Node[]=[],edges:P207Edge[]=[],now=Date.now(),turn=this.node('turn', 'CONVERSATION_TURN',text,{text,usedComponentIds:analysis.usedComponentIds,mode:analysis.mode},1,now),intent=this.node('intent','INTENT',this.intent(text),{sourceTurnId:turn.nodeId},.88,now),capability=this.node('capability','CAPABILITY','会話意図解析と根拠付き応答構成',{language:'ja',requiresCounterExamples:true},.9,now);nodes.push(turn,intent,capability);edges.push(this.edge(turn,intent,'EXPRESSES'),this.edge(intent,capability,'REQUIRES'));
 const componentNodes=analysis.components.map((c,i)=>this.node(`component-${i}`,'COMPONENT',c.componentId,{componentId:c.componentId,available:c.available,verified:c.verified,reason:c.reason},c.verified?1:.35,now));nodes.push(...componentNodes);for(const c of componentNodes)edges.push(this.edge(capability,c,'SELECTS'));
 const positives=cases.filter(x=>x.passed),negatives=cases.filter(x=>!x.passed),decision:P207Plan['decision']=componentNodes.filter(x=>x.payload.available).length>1?'COMPOSE':'REUSE',planCore={planId:`plan:${intent.nodeId}`,intentId:intent.nodeId,capabilityIds:[capability.nodeId],componentIds:componentNodes.filter(x=>x.payload.available).map(x=>String(x.payload.componentId)),decision,reason:negatives.length?'反例を保持し、既存部品を条件付き合成する':'検証済み部品を再利用する'},plan:P207Plan={...planCore,planSha256:canonicalSha256Object(planCore)},planNode=this.node('plan','COMPOSITION_PLAN',plan.decision,plan as any,.9,now);nodes.push(planNode);edges.push(this.edge(intent,planNode,'TRIGGERS'));for(const c of componentNodes.filter(x=>plan.componentIds.includes(String(x.payload.componentId))))edges.push(this.edge(planNode,c,'USES'));
 const researchTasks:string[]=[],candidateComponents:string[]=[];for(const c of positives){const n=this.node(`positive-${c.caseId}`,'POSITIVE_EXAMPLE',c.scope,c as any,c.confidence,now);nodes.push(n);edges.push(this.edge(planNode,n,'PRODUCES'))}for(const c of negatives){const bad=this.node(`counter-${c.caseId}`,'COUNTEREXAMPLE',c.scope,c as any,c.confidence,now),failure=this.node(`failure-${c.caseId}`,'FAILURE_PATTERN',this.failure(c),{caseId:c.caseId,severity:c.severity,expected:c.expected,actual:c.actual},c.confidence,now),repair=this.node(`repair-${c.caseId}`,'REPAIR_ACTION',this.repair(c),{caseId:c.caseId,action:'ADD_GUARD_OR_COMPOSE_VERIFIED_COMPONENT'},.82,now),reuse=this.node(`reuse-${c.caseId}`,'REUSE_CONDITION',`反例 ${c.caseId} に該当しない、または修復部品を併用する`,{caseId:c.caseId},.86,now);nodes.push(bad,failure,repair,reuse);edges.push(this.edge(planNode,bad,'FAILED_ON'),this.edge(bad,failure,'FAILED_BECAUSE'),this.edge(failure,repair,'REPAIRED_BY'),this.edge(planNode,reuse,'VALID_WHEN'));researchTasks.push(`反例 ${c.caseId} の原因・再現条件・代替部品を調査`);candidateComponents.push(`conversation.guard.${c.caseId.toLowerCase().replace(/[^a-z0-9]+/g,'_')}`)}
 const validation=this.node('validation','VALIDATION',negatives.length?'CONDITIONAL_PASS':'PASS',{positiveCount:positives.length,counterExampleCount:negatives.length,failClosed:true},negatives.length?.78:.98,now);nodes.push(validation);edges.push(this.edge(planNode,validation,'EVALUATED_BY'));const graphCore={nodes,edges,graphSha256:''},graph:P207Graph={...graphCore,graphSha256:canonicalSha256Object(graphCore)},mutations=this.mutations(turn,intent,plan,positives,negatives,researchTasks,candidateComponents),receiptSha256=canonicalSha256Object({graphSha256:graph.graphSha256,planSha256:plan.planSha256,mutations});return{graph,plan,positiveCases:positives,counterExamples:negatives,researchTasks,candidateComponents,mutations,receiptSha256}}
 private node(suffix:string,kind:P207NodeKind,label:string,payload:Record<string,unknown>,confidence:number,createdAt:number):P207Node{const core={nodeId:`p207:${suffix}:${canonicalSha256Object({kind,label,payload}).slice(0,18)}`,kind,label,payload,confidence,createdAt};return{...core,sha256:canonicalSha256Object(core)}}
 private edge(a:P207Node,b:P207Node,type:P207Edge['type']):P207Edge{const core={edgeId:`p207e:${canonicalSha256Object({a:a.nodeId,b:b.nodeId,type}).slice(0,20)}`,from:a.nodeId,to:b.nodeId,type};return{...core,sha256:canonicalSha256Object(core)}}
 private intent(text:string){if(/調べ|リサーチ|根拠/u.test(text))return'RESEARCH_AND_ANSWER';if(/作|生成|部品/u.test(text))return'CREATE_OR_COMPOSE_COMPONENT';return'CONVERSATION_RESPONSE'}
 private failure(c:P207Case){return `${c.scope}: expected=${c.expected}; actual=${c.actual}`}
 private repair(c:P207Case){return c.severity==='HIGH'?'単独利用を禁止し、検証済み部品との合成を必須化':'反例条件をGuardへ追加して再検証'}
 private mutations(turn:P207Node,intent:P207Node,plan:P207Plan,pos:P207Case[],neg:P207Case[],research:string[],candidates:string[]){return[{semanticKind:'OBSERVATION',ownerDomain:'conversation',participantDomains:['learning','memory','research'],subjectId:turn.nodeId,payload:{turnSha256:turn.sha256,intent:intent.label}},{semanticKind:'KNOWLEDGE',ownerDomain:'learning',participantDomains:['conversation','memory','research','verification'],subjectId:plan.planId,payload:{plan,positiveCases:pos.map(x=>x.caseId),counterExamples:neg.map(x=>x.caseId)}},{semanticKind:'RESEARCH',ownerDomain:'research',participantDomains:['conversation','learning','memory'],subjectId:plan.planId,payload:{tasks:research,status:research.length?'OPEN':'NOT_REQUIRED'}},{semanticKind:'CAPABILITY',ownerDomain:'capability',participantDomains:['conversation','learning','verification','improvement'],subjectId:plan.planId,payload:{candidateComponents:candidates,decision:plan.decision}},{semanticKind:'VALIDATION',ownerDomain:'verification',participantDomains:['conversation','learning','memory','improvement'],subjectId:plan.planId,payload:{passed:neg.length===0,conditional:neg.length>0,failClosed:true}}]}
}
export const conversationResearchComponentGraphP207Service=new ConversationResearchComponentGraphP207Service();
