import { canonicalSha256Object } from './canonicalSha256Service';
import { coreTaskIngressService } from './coreTaskIngressService';
export interface P206ConversationIntent { operation:'GENERATE_SOFT25D_CHARACTER'; prompt:string; seed:number; yaw:number; pitch:number; pose:'SEATED'; style:'SOFT_25D'; intentSha256:string }
class ConversationPersonGenerationP206Service {
 parse(text:string):P206ConversationIntent|undefined {if(!/(人物|キャラクター|人).*(生成|作|描)|(?:生成|作|描).*(人物|キャラクター|人)/u.test(text))return undefined;const yaw=/右(?:向き)?/u.test(text)?22:/左(?:向き)?/u.test(text)?-22:0,pitch=/俯瞰|上から/u.test(text)?12:/煽り|下から/u.test(text)?-12:0,seed=this.seed(text),base:any={operation:'GENERATE_SOFT25D_CHARACTER',prompt:text,seed,yaw,pitch,pose:'SEATED',style:'SOFT_25D',intentSha256:''};base.intentSha256=canonicalSha256Object({...base,intentSha256:''});return base}
 async submit(text:string){const intent=this.parse(text);if(!intent)throw new Error('P206_PERSON_GENERATION_INTENT_REQUIRED');return coreTaskIngressService.submit({kind:'USER_REQUEST',goal:'会話要求からSOFT_25D創作人物を端末内生成する',source:'conversation',payload:{...intent,networkForbidden:true,graphDomains:['conversation','learning','memory','verification','experience'],renderer:'P206_SPLINE_RIBBON_HAND_GARMENT'},maxCycles:24})}
 graphMutations(intent:P206ConversationIntent,result:{renderSha256:string;qualityScore:number;passed:boolean}){return[{semanticKind:'OBSERVATION',ownerDomain:'conversation',participantDomains:['learning','memory'],subjectId:`conversation-person:${intent.intentSha256}`,payload:{prompt:intent.prompt,intentSha256:intent.intentSha256,seed:intent.seed,view:{yaw:intent.yaw,pitch:intent.pitch}}},{semanticKind:'EXPERIENCE',ownerDomain:'experience',participantDomains:['conversation','learning','memory','verification','improvement'],subjectId:`character:${intent.seed}`,payload:{renderSha256:result.renderSha256,qualityScore:result.qualityScore,passed:result.passed,style:intent.style,pose:intent.pose}},{semanticKind:'VALIDATION',ownerDomain:'verification',participantDomains:['conversation','learning','memory'],subjectId:`character:${intent.seed}`,payload:{passed:result.passed,renderSha256:result.renderSha256}}]}
 private seed(t:string){let h=2166136261;for(const c of t)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
}
export const conversationPersonGenerationP206Service=new ConversationPersonGenerationP206Service();
