import { canonicalSha256Object } from './canonicalSha256Service';
import { isMikiDomain,MIKI_WORKER_DOMAINS } from './domainCatalogService';
import type { MikiDomain } from './crossDomainCirculationService';
import { unifiedKnowledgeGraphP151Service as graph,type P151Graph,type P151Node,type P151Edge } from './unifiedKnowledgeGraphP151Service';
export type P155SemanticKind='DATA'|'OBSERVATION'|'MEMORY'|'EXPERIENCE'|'KNOWLEDGE'|'CORRECTION'|'HYPOTHESIS'|'DECISION'|'ACTION'|'RESULT'|'VALIDATION'|'UNKNOWN';
export interface P155CognitiveNodeInput{semanticKind:P155SemanticKind;ownerDomain:MikiDomain;participantDomains:MikiDomain[];subjectId:string;payload:Record<string,unknown>;confidence:number;uncertainty:number;sourceRefs:string[];}
export interface P155MutationCandidate{candidateId:string;proposerDomain:MikiDomain;operation:'ADD_NODE'|'ADD_EDGE';node?:P155CognitiveNodeInput;edge?:{from:string;to:string;type:string;confidence:number;sourceRefs:string[]};requiresVerification:boolean;candidateSha256:string;}
export interface P155CommitReceipt{commitId:string;acceptedCandidateIds:string[];rejected:{candidateId:string;reasons:string[]}[];graphSha256:string;semanticCounts:Record<string,number>;ownerCounts:Record<string,number>;commitSha256:string;}
export interface P155CognitiveContext{taskId:string;seedNodeIds:string[];activeSubjectIds:string[];nodeIdsBySemanticKind:Record<string,string[]>;conflicts:string[];unknowns:string[];participantDomains:MikiDomain[];contextSha256:string;}
class CoreCognitiveGraphP155Service{
 propose(proposerDomain:MikiDomain,input:Omit<P155MutationCandidate,'candidateId'|'proposerDomain'|'candidateSha256'>):P155MutationCandidate{if(proposerDomain==='core')throw new Error('P155_CORE_IS_COMMIT_AUTHORITY_NOT_WORKER');if(!MIKI_WORKER_DOMAINS.includes(proposerDomain))throw new Error('P155_INVALID_PROPOSER');const base={proposerDomain,...input},candidateSha256=canonicalSha256Object(base);return{candidateId:`MC-${candidateSha256.slice(0,24)}`,...base,candidateSha256};}
 commit(existing:P151Graph,candidates:P155MutationCandidate[]):{graph:P151Graph;receipt:P155CommitReceipt}{const nodes=[...existing.nodes],edges=[...existing.edges],accepted:string[]=[],rejected:P155CommitReceipt['rejected']=[];for(const c of candidates){const reasons=this.validate(c,nodes,edges);if(reasons.length){rejected.push({candidateId:c.candidateId,reasons});continue;}if(c.operation==='ADD_NODE'&&c.node){const n=c.node,payload={...n.payload,semanticKind:n.semanticKind,ownerDomain:n.ownerDomain,participantDomains:[...new Set(n.participantDomains)].sort()};nodes.push(graph.node({domain:this.legacyDomain(n.semanticKind),kind:`COGNITIVE_${n.semanticKind}`,subjectId:n.subjectId,payload,confidence:n.confidence,uncertainty:n.uncertainty,sourceRefs:n.sourceRefs}));accepted.push(c.candidateId);}if(c.operation==='ADD_EDGE'&&c.edge){edges.push(graph.edge(c.edge));accepted.push(c.candidateId);}}
 const g=graph.build([...new Map(nodes.map(n=>[n.nodeId,n])).values()],[...new Map(edges.map(e=>[e.edgeId,e])).values()]),semanticCounts=this.count(g.nodes,n=>String((n.payload as any).semanticKind||'LEGACY')),ownerCounts=this.count(g.nodes,n=>String((n.payload as any).ownerDomain||'legacy')),seed:any={acceptedCandidateIds:accepted,rejected,graphSha256:g.graphSha256,semanticCounts,ownerCounts,commitSha256:''};seed.commitSha256=canonicalSha256Object({...seed,commitSha256:''});return{graph:g,receipt:{commitId:`GC-${seed.commitSha256.slice(0,24)}`,...seed}};}
 context(taskId:string,g:P151Graph,seedNodeIds:string[],maxNodes=64):P155CognitiveContext{const selected=new Set(seedNodeIds),queue=[...seedNodeIds];while(queue.length&&selected.size<maxNodes){const id=queue.shift()!;for(const e of g.edges)if(e.from===id||e.to===id){const next=e.from===id?e.to:e.from;if(!selected.has(next)){selected.add(next);queue.push(next);if(selected.size>=maxNodes)break;}}}const nodes=g.nodes.filter(n=>selected.has(n.nodeId)),byKind:Record<string,string[]>={};for(const n of nodes)(byKind[String((n.payload as any).semanticKind||'LEGACY')]??=[]).push(n.nodeId);const core:any={taskId,seedNodeIds,activeSubjectIds:[...new Set(nodes.map(n=>n.subjectId))],nodeIdsBySemanticKind:byKind,conflicts:nodes.filter(n=>(n.payload as any).semanticKind==='CORRECTION').map(n=>n.nodeId),unknowns:nodes.filter(n=>(n.payload as any).semanticKind==='UNKNOWN').map(n=>n.nodeId),participantDomains:[...new Set(nodes.flatMap(n=>((n.payload as any).participantDomains||[])))].filter(isMikiDomain).sort(),contextSha256:''};core.contextSha256=canonicalSha256Object({...core,contextSha256:''});return core;}
 private validate(c:P155MutationCandidate,nodes:P151Node[],edges:P151Edge[]):string[]{const r:string[]=[];if(c.operation==='ADD_NODE'){if(!c.node)r.push('NODE_REQUIRED');else{if(c.node.ownerDomain==='core')r.push('CORE_CANNOT_OWN_SEMANTIC_CONTENT');if(c.node.ownerDomain!==c.proposerDomain&&!c.node.participantDomains.includes(c.proposerDomain))r.push('PROPOSER_NOT_PARTICIPANT');if(c.node.participantDomains.some(d=>!isMikiDomain(d)))r.push('INVALID_PARTICIPANT');if(!c.node.sourceRefs.length&&c.node.semanticKind!=='UNKNOWN')r.push('PROVENANCE_REQUIRED');if(c.requiresVerification&&c.node.semanticKind!=='VALIDATION'&&!c.node.participantDomains.includes('verification'))r.push('VERIFICATION_PARTICIPANT_REQUIRED');}}else{if(!c.edge)r.push('EDGE_REQUIRED');else{const ids=new Set(nodes.map(n=>n.nodeId));if(!ids.has(c.edge.from)||!ids.has(c.edge.to))r.push('DANGLING_EDGE');if(c.edge.from===c.edge.to)r.push('SELF_EDGE_FORBIDDEN');if(edges.some(e=>e.from===c.edge!.from&&e.to===c.edge!.to&&e.type===c.edge!.type))r.push('DUPLICATE_EDGE');}}return r;}
 private legacyDomain(k:P155SemanticKind):any{return({DATA:'VISUAL',OBSERVATION:'VISUAL',MEMORY:'MEMORY',EXPERIENCE:'EXPERIENCE',KNOWLEDGE:'MEMORY',CORRECTION:'EXPERIENCE',HYPOTHESIS:'VISUAL',DECISION:'REQUIREMENT',ACTION:'CODE',RESULT:'VALIDATION',VALIDATION:'VALIDATION',UNKNOWN:'VALIDATION'} as any)[k];}
 private count(nodes:P151Node[],key:(n:P151Node)=>string){return nodes.reduce((o,n)=>(o[key(n)]=(o[key(n)]||0)+1,o),{} as Record<string,number>);}}
export const coreCognitiveGraphP155Service=new CoreCognitiveGraphP155Service();
