import { canonicalSha256Object } from './canonicalSha256Service';
import { MIKI_DOMAINS } from './domainCatalogService';
import type { MikiDomain } from './crossDomainCirculationService';
import type { P151Edge,P151Node } from './unifiedKnowledgeGraphP151Service';
export interface P153Shard{shardId:string;domain:MikiDomain;bucket:string;nodeIds:string[];edgeIds:string[];byteLength:number;sha256:string;}
export interface P153BlobReference{blobId:string;contentSha256:string;mediaType:string;byteLength:number;storageKey:string;}
export interface P153Manifest{format:'MIKI_CORE_GRAPH_SHARDS_V1';domains:readonly MikiDomain[];shards:P153Shard[];nodeIndex:Record<string,string>;edgeIndex:Record<string,string>;subjectIndex:Record<string,string[]>;blobIndex:Record<string,P153BlobReference>;journalSequence:number;manifestSha256:string;}
export interface P153WorkingSet{nodes:P151Node[];edges:P151Edge[];loadedShardIds:string[];estimatedBytes:number;evictedShardIds:string[];}
class CoreUnifiedGraphManagerP153Service{
 createManifest():P153Manifest{const core:any={format:'MIKI_CORE_GRAPH_SHARDS_V1',domains:MIKI_DOMAINS,shards:[],nodeIndex:{},edgeIndex:{},subjectIndex:{},blobIndex:{},journalSequence:0,manifestSha256:''};core.manifestSha256=canonicalSha256Object({...core,manifestSha256:''});return core;}
 partition(nodes:P151Node[],edges:P151Edge[],maxBytes=64*1024):{manifest:P153Manifest;records:Record<string,{nodes:P151Node[];edges:P151Edge[]}>}{const manifest=this.createManifest(),records:Record<string,{nodes:P151Node[];edges:P151Edge[]}>={};const domainOf=(n:P151Node):MikiDomain=>this.mapDomain(n.domain);for(const n of nodes){const domain=domainOf(n),bucket=n.nodeId.slice(2,4),base=`${domain}/${bucket}`,body=records[base]||{nodes:[],edges:[]};body.nodes.push(n);records[base]=body;}for(const e of edges){const from=nodes.find(n=>n.nodeId===e.from);if(!from)continue;const domain=domainOf(from),bucket=from.nodeId.slice(2,4),base=`${domain}/${bucket}`,body=records[base]||{nodes:[],edges:[]};body.edges.push(e);records[base]=body;}for(const [base,body] of Object.entries(records)){const raw=JSON.stringify(body),[domain,bucket]=base.split('/') as [MikiDomain,string];if(new TextEncoder().encode(raw).byteLength>maxBytes&&body.nodes.length>1)throw new Error('P153_SHARD_LIMIT_REQUIRES_REPARTITION');const sha256=canonicalSha256Object(body),shardId=`S-${sha256.slice(0,24)}`,byteLength=new TextEncoder().encode(raw).byteLength,shard={shardId,domain,bucket,nodeIds:body.nodes.map(x=>x.nodeId),edgeIds:body.edges.map(x=>x.edgeId),byteLength,sha256};manifest.shards.push(shard);for(const id of shard.nodeIds)manifest.nodeIndex[id]=shardId;for(const id of shard.edgeIds)manifest.edgeIndex[id]=shardId;for(const n of body.nodes)(manifest.subjectIndex[n.subjectId]??=[]).push(n.nodeId);records[shardId]=body;delete records[base];}manifest.shards.sort((a,b)=>a.shardId.localeCompare(b.shardId));manifest.journalSequence=nodes.length+edges.length;manifest.manifestSha256=canonicalSha256Object({...manifest,manifestSha256:''});return{manifest,records};}
 loadWorkingSet(manifest:P153Manifest,records:Record<string,{nodes:P151Node[];edges:P151Edge[]}>,seedNodeIds:string[],maxBytes:number):P153WorkingSet{const wanted=new Set(seedNodeIds.map(id=>manifest.nodeIndex[id]).filter(Boolean)),loaded:P153Shard[]=[],evicted:string[]=[];let bytes=0;for(const shard of manifest.shards.filter(s=>wanted.has(s.shardId)).sort((a,b)=>a.byteLength-b.byteLength)){if(bytes+shard.byteLength>maxBytes){evicted.push(shard.shardId);continue;}loaded.push(shard);bytes+=shard.byteLength;}return{nodes:loaded.flatMap(s=>records[s.shardId]?.nodes||[]),edges:loaded.flatMap(s=>records[s.shardId]?.edges||[]),loadedShardIds:loaded.map(s=>s.shardId),estimatedBytes:bytes,evictedShardIds:evicted};}
 registerBlob(m:P153Manifest,b:Omit<P153BlobReference,'blobId'>):P153Manifest{const blobId=`B-${b.contentSha256.slice(0,24)}`,next={...m,blobIndex:{...m.blobIndex,[blobId]:{blobId,...b}},manifestSha256:''};next.manifestSha256=canonicalSha256Object({...next,manifestSha256:''});return next;}
 private mapDomain(d:string):MikiDomain{const map:Record<string,MikiDomain>={CONVERSATION:'conversation',MEMORY:'memory',EXPERIENCE:'experience',VISUAL:'data',PERSON:'selfAwareness',CODE:'selfDevelopment',REQUIREMENT:'strategy',VALIDATION:'verification'};return map[d]||'unknown';}}
export const coreUnifiedGraphManagerP153Service=new CoreUnifiedGraphManagerP153Service();
