import { canonicalSha256Object } from './canonicalSha256Service';
export interface P194SubjectObservation { subjectId:string; sourceSha256:string; face:Record<string,number>; body:Record<string,number>; skin:{meanRgb:number[];stdRgb:number[];spatialLowFrequency:number;microContrast:number}; hair:Record<string,number>; garment:Record<string,number>; lighting:Record<string,number>; hands:Record<string,number>; view:Record<string,number>; }
export interface P194FeatureRule { path:string; mean:number; stdDev:number; min:number; max:number; median:number; q25:number; q75:number; confidence:number; }
export interface P194RuleBook { featureRules:P194FeatureRule[]; correlations:Array<{a:string;b:string;r:number}>; constraints:Array<{kind:string;expression:string;tolerance:number}>; occlusionRules:Array<{near:string;far:string;condition:string}>; sourceSha256List:string[]; ruleBookSha256:string; }
class DetailedHumanRuleLearningP194Service {
 learn(subjects:P194SubjectObservation[]):P194RuleBook { if(new Set(subjects.map(x=>x.subjectId)).size<10)throw new Error('P194_TEN_DISTINCT_SUBJECTS_REQUIRED');const flat=subjects.map(x=>this.flatten(x)),paths=[...new Set(flat.flatMap(x=>Object.keys(x)))].filter(x=>!x.endsWith('subjectId')&&!x.endsWith('sourceSha256')),featureRules=paths.map(path=>this.rule(path,flat.map(x=>Number(x[path])).filter(Number.isFinite))),pairs=[['face.eyeSpacingRatio','face.noseWidthRatio'],['face.noseLengthRatio','face.mouthWidthRatio'],['face.widthRatio','face.jawTaper'],['body.shoulderRatio','body.hipRatio'],['body.torsoRatio','body.legLengthRatio'],['skin.microContrast','lighting.shadowContrast'],['hair.density','hair.strandVariance'],['garment.wrinkleDensity','garment.roughnessProxy'],['view.yawProxy','view.selfOcclusion'],['hands.palmWidthRatio','hands.fingerLengthRatio']],correlations=pairs.map(([a,b])=>({a,b,r:this.corr(flat.map(x=>Number(x[a])),flat.map(x=>Number(x[b])))})),constraints=[{kind:'FACE_TOPOLOGY',expression:'eyeSpacingRatio > noseWidthRatio',tolerance:.08},{kind:'FACE_VERTICAL',expression:'noseLengthRatio + mouthWidthRatio < 0.75',tolerance:.12},{kind:'BODY_PROPORTION',expression:'shoulderRatio and hipRatio co-vary',tolerance:.15},{kind:'HAND',expression:'five finger surfaces attach to palm surface',tolerance:.04},{kind:'CONTACT',expression:'pelvis-seat and feet-floor distances within learned range',tolerance:.06},{kind:'VIEW_CONSISTENCY',expression:'identity ratios invariant under yaw and pitch',tolerance:.05}],occlusionRules=[{near:'nose.tip',far:'far.cheek',condition:'abs(yaw)>0.18'},{near:'near.eyelid',far:'far.eyelid',condition:'abs(yaw)>0.35'},{near:'front.hair',far:'forehead',condition:'hair.lengthRatio>0.25'},{near:'hand',far:'torso',condition:'hand.depth<torso.depth'},{near:'thigh',far:'chair.seat',condition:'seated=true'},{near:'chair.front',far:'lower.leg',condition:'legBehindChair=true'}],core:any={featureRules,correlations,constraints,occlusionRules,sourceSha256List:subjects.map(x=>x.sourceSha256).sort(),ruleBookSha256:''};core.ruleBookSha256=canonicalSha256Object({...core,ruleBookSha256:''});return core }
 private flatten(value:any,prefix='',out:Record<string,unknown>={}){for(const [k,v] of Object.entries(value)){const p=prefix?`${prefix}.${k}`:k;if(v&&typeof v==='object'&&!Array.isArray(v))this.flatten(v,p,out);else if(Array.isArray(v))v.forEach((n,i)=>out[`${p}.${i}`]=n);else out[p]=v}return out}
 private rule(path:string,a:number[]):P194FeatureRule{const s=[...a].sort((x,y)=>x-y),q=(p:number)=>s[Math.min(s.length-1,Math.max(0,Math.floor((s.length-1)*p)))],mean=s.reduce((x,y)=>x+y,0)/s.length,stdDev=Math.sqrt(s.reduce((x,y)=>x+(y-mean)**2,0)/s.length);return{path,mean,stdDev,min:s[0],max:s[s.length-1],median:q(.5),q25:q(.25),q75:q(.75),confidence:Math.min(.96,.62+s.length*.028)}}
 private corr(a:number[],b:number[]){const ma=a.reduce((s,v)=>s+v,0)/a.length,mb=b.reduce((s,v)=>s+v,0)/b.length,n=a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0),d=Math.sqrt(a.reduce((s,v)=>s+(v-ma)**2,0)*b.reduce((s,v)=>s+(v-mb)**2,0));return d?n/d:0}
}
export const detailedHumanRuleLearningP194Service=new DetailedHumanRuleLearningP194Service();
