import { canonicalSha256Object } from './canonicalSha256Service';
import { MIKI_WORKER_DOMAINS } from './domainCatalogService';
import type { MikiDomain } from './crossDomainCirculationService';
import type { P151Graph,P151Node } from './unifiedKnowledgeGraphP151Service';
import type { P155CognitiveContext,P155MutationCandidate } from './coreCognitiveGraphP155Service';
export interface P156DomainProjection{domain:MikiDomain;taskId:string;nodeIds:string[];semanticKinds:string[];activeSubjectIds:string[];conflictIds:string[];unknownIds:string[];maxNodes:number;projectionSha256:string;}
export interface P156DispatchReceipt{taskId:string;projections:Record<string,P156DomainProjection>;candidateIds:string[];missingDomains:MikiDomain[];receiptSha256:string;}
const POLICY:Record<string,string[]>={autonomy:['DECISION','ACTION','RESULT','VALIDATION','UNKNOWN'],capability:['KNOWLEDGE','ACTION','RESULT','VALIDATION'],conversation:['DATA','OBSERVATION','MEMORY','EXPERIENCE','KNOWLEDGE','CORRECTION','UNKNOWN'],data:['DATA','OBSERVATION','VALIDATION','UNKNOWN'],execution:['DECISION','ACTION','RESULT','VALIDATION'],experience:['OBSERVATION','EXPERIENCE','CORRECTION','RESULT','VALIDATION'],improvement:['EXPERIENCE','KNOWLEDGE','CORRECTION','RESULT','VALIDATION'],learning:['OBSERVATION','EXPERIENCE','KNOWLEDGE','CORRECTION','HYPOTHESIS','VALIDATION'],memory:['MEMORY','EXPERIENCE','KNOWLEDGE','CORRECTION','UNKNOWN'],promotion:['KNOWLEDGE','RESULT','VALIDATION'],research:['DATA','OBSERVATION','KNOWLEDGE','HYPOTHESIS','VALIDATION','UNKNOWN'],safety:['DATA','OBSERVATION','DECISION','ACTION','VALIDATION','UNKNOWN'],selfAwareness:['MEMORY','EXPERIENCE','KNOWLEDGE','DECISION','RESULT'],selfDevelopment:['EXPERIENCE','KNOWLEDGE','ACTION','RESULT','VALIDATION'],strategy:['MEMORY','KNOWLEDGE','DECISION','RESULT','UNKNOWN'],unknown:['UNKNOWN','HYPOTHESIS','OBSERVATION'],verification:['DATA','OBSERVATION','EXPERIENCE','KNOWLEDGE','CORRECTION','HYPOTHESIS','DECISION','ACTION','RESULT','VALIDATION','UNKNOWN']};
class DomainContextProjectionP156Service{
 project(domain:MikiDomain,context:P155CognitiveContext,g:P151Graph,maxNodes=24):P156DomainProjection{if(domain==='core')throw new Error('P156_CORE_DOES_NOT_RECEIVE_WORKER_PROJECTION');const allowed=new Set(POLICY[domain]||['UNKNOWN']),contextIds=new Set(Object.values(context.nodeIdsBySemanticKind).flat()),rank=(n:P151Node)=>{const p=n.payload as any;let score=n.confidence*(1-n.uncertainty*.4);if(p.ownerDomain===domain)score+=2;if((p.participantDomains||[]).includes(domain))score+=1;if(context.seedNodeIds.includes(n.nodeId))score+=3;return score;},nodes=g.nodes.filter(n=>contextIds.has(n.nodeId)&&allowed.has(String((n.payload as any).semanticKind||'UNKNOWN'))).sort((a,b)=>rank(b)-rank(a)||a.nodeId.localeCompare(b.nodeId)).slice(0,maxNodes),core:any={domain,taskId:context.taskId,nodeIds:nodes.map(n=>n.nodeId),semanticKinds:[...new Set(nodes.map(n=>String((n.payload as any).semanticKind||'UNKNOWN')))].sort(),activeSubjectIds:[...new Set(nodes.map(n=>n.subjectId))],conflictIds:context.conflicts.filter(id=>nodes.some(n=>n.nodeId===id)),unknownIds:context.unknowns.filter(id=>nodes.some(n=>n.nodeId===id)),maxNodes,projectionSha256:''};core.projectionSha256=canonicalSha256Object({...core,projectionSha256:''});return core;}
 dispatch(context:P155CognitiveContext,g:P151Graph,candidates:P155MutationCandidate[]):P156DispatchReceipt{const projections:Record<string,P156DomainProjection>={};for(const d of MIKI_WORKER_DOMAINS)projections[d]=this.project(d,context,g);const missingDomains=MIKI_WORKER_DOMAINS.filter(d=>!projections[d]),core:any={taskId:context.taskId,projections,candidateIds:candidates.map(c=>c.candidateId).sort(),missingDomains,receiptSha256:''};core.receiptSha256=canonicalSha256Object({...core,receiptSha256:''});return core;}}
export const domainContextProjectionP156Service=new DomainContextProjectionP156Service();
