import { storageService } from '../../../services/storageService';
import { improvementIntakeRouterService, type ImprovementIntakeRun } from './improvementIntakeRouterService';
export type ExternalDirectiveStatus='RECEIVED'|'PARSED'|'VALIDATED'|'QUEUED'|'IN_PROGRESS'|'CANDIDATE_READY'|'VALIDATION_FAILED'|'REVIEW_READY'|'REJECTED';
export interface ExternalDirective { directiveId:string; sourceFileName:string; sourceHash:string; rawText:string; objective:string; targetFiles:string[]; requirements:string[]; prohibitions:string[]; invariants:string[]; validationRequirements:string[]; deliveryRequirements:string[]; relatedIssueIds:string[]; status:ExternalDirectiveStatus; receivedAt:number; runId?:string; }
const KEY='miki_external_directives_v1';
class ExternalDirectiveIntakeService{
 private rows=new Map<string,ExternalDirective>();private sequence=0;constructor(){this.load();}
 async receive(input:{sourceFileName:string;rawText:string;objective:string;targetFiles?:string[];requirements?:string[];prohibitions?:string[];invariants?:string[];validationRequirements?:string[];deliveryRequirements?:string[];relatedIssueIds?:string[]}):Promise<{directive:ExternalDirective;run:ImprovementIntakeRun}>{if(!input.rawText.trim()||!input.objective.trim())throw new Error('EXTERNAL_DIRECTIVE_REQUIRED_FIELDS_MISSING');const sourceHash=await this.sha(input.rawText);const existing=[...this.rows.values()].find(x=>x.sourceHash===sourceHash&&x.status!=='REJECTED');if(existing&&existing.runId){const run=improvementIntakeRouterService.get(existing.runId);if(run)return {directive:this.clone(existing),run};}const now=Date.now();this.sequence+=1;const directive:ExternalDirective={directiveId:`DIR-${now}-${String(this.sequence).padStart(6,'0')}`,sourceFileName:input.sourceFileName,sourceHash,rawText:input.rawText,objective:input.objective,targetFiles:[...(input.targetFiles||[])],requirements:[...(input.requirements||[])],prohibitions:[...(input.prohibitions||[])],invariants:[...(input.invariants||[])],validationRequirements:[...(input.validationRequirements||[])],deliveryRequirements:[...(input.deliveryRequirements||[])],relatedIssueIds:[...(input.relatedIssueIds||[])],status:'VALIDATED',receivedAt:now};const run=await improvementIntakeRouterService.receive({runType:'EXTERNAL_DIRECTIVE',sourceId:directive.directiveId,objective:directive.objective,priority:100,payload:{directiveId:directive.directiveId,sourceHash,targetFiles:directive.targetFiles,requirements:directive.requirements,prohibitions:directive.prohibitions,invariants:directive.invariants,validationRequirements:directive.validationRequirements,deliveryRequirements:directive.deliveryRequirements,relatedIssueIds:directive.relatedIssueIds}});directive.runId=run.runId;directive.status='QUEUED';this.rows.set(directive.directiveId,directive);this.save();return {directive:this.clone(directive),run};}

 async receiveTextFile(sourceFileName:string,rawText:string):Promise<{directive:ExternalDirective;run:ImprovementIntakeRun}>{
  const lines=rawText.replace(/\r\n/g,'\n').split('\n').map(line=>line.trim()).filter(Boolean);const section=(names:string[])=>lines.filter(line=>names.some(name=>line.toLowerCase().startsWith(name.toLowerCase()))).map(line=>line.replace(/^[^:=：]+[:=：]\s*/,''));
  const targetFiles=[...new Set([...section(['TARGET_FILE','TARGET_FILES','対象ファイル']),...lines.filter(line=>/^(src|android|scripts|docs|reference)\//.test(line)).map(line=>line.replace(/^[-*]\s*/,''))])];
  const objective=section(['OBJECTIVE','目的'])[0]||lines.find(line=>!/^([\[【]|[-*]|#)/.test(line))||sourceFileName;
  return this.receive({sourceFileName,rawText,objective,targetFiles,requirements:section(['REQUIREMENT','REQUIREMENTS','要件']),prohibitions:section(['PROHIBITION','PROHIBITIONS','禁止']),invariants:section(['INVARIANT','INVARIANTS','不変条件']),validationRequirements:section(['VALIDATION','検証条件']),deliveryRequirements:section(['DELIVERY','納品条件'])});
 }

 get(id:string){const row=this.rows.get(id);return row?this.clone(row):undefined;}list(){return [...this.rows.values()].sort((a,b)=>b.receivedAt-a.receivedAt).map(x=>this.clone(x));}
 private clone(x:ExternalDirective):ExternalDirective{return {...x,targetFiles:[...x.targetFiles],requirements:[...x.requirements],prohibitions:[...x.prohibitions],invariants:[...x.invariants],validationRequirements:[...x.validationRequirements],deliveryRequirements:[...x.deliveryRequirements],relatedIssueIds:[...x.relatedIssueIds]};}
 private async sha(text:string){const data=new TextEncoder().encode(text);if(typeof crypto!=='undefined'&&crypto.subtle){const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('');}let h=2166136261;for(const v of data){h^=v;h=Math.imul(h,16777619);}return `fallback-${(h>>>0).toString(16).padStart(8,'0')}`;}
 private save(){storageService.setItem(KEY,JSON.stringify(this.list().slice(0,200)));}private load(){try{const raw=storageService.getItem(KEY);const rows=raw?JSON.parse(raw):[];if(Array.isArray(rows))for(const row of rows)this.rows.set(row.directiveId,row);}catch{this.rows.clear();}}
}
export const externalDirectiveIntakeService=new ExternalDirectiveIntakeService();
