import { canonicalSha256Object } from './canonicalSha256Service';
export interface FailureTraceEvent{id:string;kind:string;dependsOn:string[];payloadSha256:string;}
export interface FailureTraceMinimizationResult{originalEventIds:string[];minimalEventIds:string[];removedEventIds:string[];reproductionRuns:number;reproductionPasses:number;reproductionRate:number;threshold:number;reproduced:boolean;resultSha256:string;}
class FailureTraceMinimizationService{
 async minimize(events:FailureTraceEvent[],reproduce:(projected:FailureTraceEvent[])=>boolean|Promise<boolean>,options:{runs?:number;threshold?:number}={}):Promise<FailureTraceMinimizationResult>{const runs=Math.max(1,Math.floor(options.runs??3));const threshold=Math.min(1,Math.max(0.5,options.threshold??1));this.validate(events);let current=[...events];if(!(await this.reproduces(current,reproduce,runs,threshold)).reproduced)throw new Error('FAILURE_NOT_REPRODUCED_FROM_FULL_TRACE');let granularity=2;while(current.length>=2){const size=Math.ceil(current.length/granularity);let reduced=false;for(let start=0;start<current.length;start+=size){const removed=new Set(current.slice(start,start+size).map(event=>event.id));const candidate=this.dependencyClosure(current.filter(event=>!removed.has(event.id)),events);if(candidate.length===current.length||candidate.length===0)continue;const verdict=await this.reproduces(candidate,reproduce,runs,threshold);if(verdict.reproduced){current=candidate;granularity=Math.max(2,granularity-1);reduced=true;break;}}if(!reduced){if(granularity>=current.length)break;granularity=Math.min(current.length,granularity*2);}}const final=await this.reproduces(current,reproduce,runs,threshold);const originalEventIds=events.map(event=>event.id);const minimalEventIds=current.map(event=>event.id);const seed={originalEventIds,minimalEventIds,reproductionRuns:runs,reproductionPasses:final.passes,reproductionRate:final.rate,threshold,reproduced:final.reproduced};return{...seed,removedEventIds:originalEventIds.filter(id=>!minimalEventIds.includes(id)),resultSha256:canonicalSha256Object(seed)};}
 private async reproduces(events:FailureTraceEvent[],fn:(events:FailureTraceEvent[])=>boolean|Promise<boolean>,runs:number,threshold:number){let passes=0;for(let index=0;index<runs;index+=1)if(await fn(events))passes+=1;const rate=passes/runs;return{passes,rate,reproduced:rate>=threshold};}
 private dependencyClosure(selected:FailureTraceEvent[],all:FailureTraceEvent[]){const byId=new Map(all.map(event=>[event.id,event]));const ids=new Set(selected.map(event=>event.id));let changed=true;while(changed){changed=false;for(const id of [...ids])for(const dependency of byId.get(id)?.dependsOn||[])if(!ids.has(dependency)){ids.add(dependency);changed=true;}}return all.filter(event=>ids.has(event.id));}
 private validate(events:FailureTraceEvent[]){const ids=new Set(events.map(event=>event.id));if(ids.size!==events.length)throw new Error('DUPLICATE_TRACE_EVENT_ID');for(const event of events)for(const dependency of event.dependsOn)if(!ids.has(dependency))throw new Error(`TRACE_DEPENDENCY_MISSING:${event.id}:${dependency}`);}
}
export const failureTraceMinimizationService=new FailureTraceMinimizationService();
