import { canonicalSha256Object } from './canonicalSha256Service';
import type { P194DetailedModel } from './detailedFaceSurfaceP194Service';
import type { P193Synthesis } from './proceduralPersonRuleSynthesizerP193Service';

export interface P197PixelEvidence { part:string; label:number; pixels:number; components:number; edgePixels:number; depthOrdered:boolean; passed:boolean; }
export interface P197Result extends P193Synthesis { partLabels:Uint16Array; pixelEvidence:P197PixelEvidence[]; anatomyScore:number; opticalScore:number; finalScore:number; passed:boolean; failures:string[]; refinementSha256:string; }

class FinalPixelQualityP197Service {
 refine(model:P194DetailedModel,input:P193Synthesis):P197Result {
  const rgba=input.rgba.slice(),normal=input.normal.slice(),material=input.material.slice(),depth=input.depth.slice(),labels=new Uint16Array(input.width*input.height),cp=new Map(model.controlPoints.map(x=>[x.id,x]));
  const parts=[
   {name:'left-eye',label:11,ids:['eyeballL'],color:[34,31,29],scale:1.0,depth:.08},
   {name:'right-eye',label:12,ids:['eyeballR'],color:[34,31,29],scale:1.0,depth:.08},
   {name:'left-upper-lid',label:13,ids:['upperLidL'],color:[133,91,78],scale:1.15,depth:.07},
   {name:'right-upper-lid',label:14,ids:['upperLidR'],color:[133,91,78],scale:1.15,depth:.07},
   {name:'nose-bridge',label:21,ids:['noseRoot','noseBridge','noseTip'],color:[187,139,119],scale:.75,depth:.06},
   {name:'left-nostril',label:22,ids:['nostrilL'],color:[69,43,39],scale:1.0,depth:.045},
   {name:'right-nostril',label:23,ids:['nostrilR'],color:[69,43,39],scale:1.0,depth:.045},
   {name:'upper-lip',label:31,ids:['upperLip'],color:[145,79,80],scale:1.05,depth:.05},
   {name:'lower-lip',label:32,ids:['lowerLip'],color:[173,102,101],scale:1.1,depth:.045},
   {name:'left-ear',label:41,ids:['earL'],color:[191,143,124],scale:1.0,depth:.12},
   {name:'right-ear',label:42,ids:['earR'],color:[191,143,124],scale:1.0,depth:.12},
   {name:'neck-blend',label:51,ids:['neckBlendL','neckBlendR','chin'],color:[193,148,128],scale:1.25,depth:.18}
  ];
  for(const p of parts)this.strokePart(p,cp,input.width,input.height,rgba,normal,material,depth,labels);
  this.refineFingers(model,input.width,input.height,rgba,normal,material,depth,labels);
  this.skinOptics(model,input.width,input.height,rgba,normal,material,depth,labels);
  this.hairOcclusion(model,input.width,input.height,rgba,normal,depth,labels);
  this.garmentTension(model,input.width,input.height,rgba,normal,material,depth,labels);
  this.antialias(input.width,input.height,rgba,labels);
  const evidence=this.inspect(input.width,input.height,labels,depth),failures=evidence.filter(x=>!x.passed).map(x=>`${x.part.toUpperCase().replaceAll('-','_')}_RASTER_FAILURE`),anatomyScore=evidence.filter(x=>x.passed).length/evidence.length,opticalScore=this.optical(rgba,normal,material,labels),finalScore=anatomyScore*.72+opticalScore*.28,passed=failures.length===0&&finalScore>=.78;
  const refinementSha256=canonicalSha256Object({modelSha256:model.modelSha256,inputSha256:input.synthesisSha256,evidence,anatomyScore,opticalScore,finalScore,head:Array.from(rgba.slice(0,2048)),tail:Array.from(rgba.slice(-2048)),labelHead:Array.from(labels.slice(0,1024)),labelTail:Array.from(labels.slice(-1024))});
  return{...input,rgba,normal,material,depth,partLabels:labels,pixelEvidence:evidence,anatomyScore,opticalScore,finalScore,passed,failures,refinementSha256};
 }
 private strokePart(p:any,cp:Map<string,any>,w:number,h:number,rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,depth:Float32Array,labels:Uint16Array){const pts=p.ids.map((id:string)=>cp.get(id)).filter(Boolean);for(let k=0;k<pts.length;k++){const a=pts[k],b=pts[Math.min(k+1,pts.length-1)],steps=Math.max(1,Math.ceil(Math.hypot((b.x-a.x)*w,(b.y-a.y)*h)));for(let s=0;s<=steps;s++){const t=s/steps,x=(a.x+(b.x-a.x)*t)*w,y=(a.y+(b.y-a.y)*t)*h,r=Math.max(2,Math.round((a.radius+(b.radius-a.radius)*t)*Math.min(w,h)*p.scale));this.disc(x,y,r,p.depth,p.label,p.color,w,h,rgba,normal,material,depth,labels)}}}
 private refineFingers(model:P194DetailedModel,w:number,h:number,rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,depth:Float32Array,labels:Uint16Array){for(let side=0;side<2;side++)for(let f=1;f<=5;f++){const ids=[1,2,3].map(j=>model.controlPoints.find(x=>x.id===`${side?'handR':'handL'}-finger-${f}-joint-${j}`)).filter(Boolean) as any[];for(let j=0;j<ids.length;j++){const q=ids[j],label=100+side*10+f,r=Math.max(4,Math.round(q.radius*Math.min(w,h)*2.25));this.disc(q.x*w,q.y*h,r,.018+f*.001,label,[196,149,128],w,h,rgba,normal,material,depth,labels);if(j===2)this.disc(q.x*w,q.y*h-r*.45,Math.max(1,Math.round(r*.55)),.012+f*.001,label,[218,186,174],w,h,rgba,normal,material,depth,labels)}}}
 private skinOptics(model:P194DetailedModel,w:number,h:number,rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,depth:Float32Array,labels:Uint16Array){const head=model.controlPoints.find(x=>x.id==='head');if(!head)return;const rr=head.radius*Math.min(w,h)*1.25;for(let y=Math.max(0,Math.floor(head.y*h-rr));y<Math.min(h,Math.ceil(head.y*h+rr));y++)for(let x=Math.max(0,Math.floor(head.x*w-rr));x<Math.min(w,Math.ceil(head.x*w+rr));x++){const i=y*w+x;if(depth[i]>.5)continue;const dx=(x-head.x*w)/rr,dy=(y-head.y*h)/rr,d=Math.sqrt(dx*dx+dy*dy);if(d>1)continue;const subsurface=Math.max(0,1-d)*.06,micro=(((x*73856093)^(y*19349663)^(model.seed*83492791))>>>0)%997/997-.5;rgba[i*4]=this.clamp(rgba[i*4]*(1+subsurface)+micro*5);rgba[i*4+1]=this.clamp(rgba[i*4+1]*(1+subsurface*.45)+micro*3);rgba[i*4+2]=this.clamp(rgba[i*4+2]*(1+subsurface*.25)+micro*2);material[i*4]=Math.min(255,material[i*4]+Math.round(d*18));material[i*4+1]=Math.min(255,material[i*4+1]+Math.round((1-d)*16));normal[i*4+2]=Math.max(normal[i*4+2],200)}}
 private hairOcclusion(model:P194DetailedModel,w:number,h:number,rgba:Uint8Array,normal:Uint8Array,depth:Float32Array,labels:Uint16Array){const head=model.controlPoints.find(x=>x.id==='head');if(!head)return;for(let n=0;n<160;n++){const u=n/159,a=(u-.5)*Math.PI*1.04,x0=head.x*w+Math.sin(a)*head.radius*w*.92,y0=head.y*h-Math.cos(a)*head.radius*h*.92,len=h*(.025+(n%17)/420);for(let t=0;t<=1;t+=.018){const x=Math.round(x0+Math.sin(a)*len*t+Math.sin(t*11+n)*.8),y=Math.round(y0+len*t);if(x<0||y<0||x>=w||y>=h)continue;const i=y*w+x,z=.035+(n%7)*.002;if(z>=depth[i])continue;depth[i]=z;labels[i]=200;const shine=(n%11===0?22:0)+Math.round((1-t)*10);rgba[i*4]=43+shine;rgba[i*4+1]=34+Math.round(shine*.65);rgba[i*4+2]=30+Math.round(shine*.45);rgba[i*4+3]=255;normal[i*4]=128;normal[i*4+1]=105;normal[i*4+2]=238;normal[i*4+3]=255}}}
 private garmentTension(model:P194DetailedModel,w:number,h:number,rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,depth:Float32Array,labels:Uint16Array){const pelvis=model.controlPoints.find(x=>x.id==='pelvis');if(!pelvis)return;for(let k=-10;k<=10;k++)for(let t=0;t<=1;t+=.004){const x=Math.round((pelvis.x+k*.012+Math.sin(t*9+k*.7)*.005)*w),y=Math.round((pelvis.y+.02+t*.23)*h);if(x<0||y<0||x>=w||y>=h)continue;const i=y*w+x;if(depth[i]>.75)continue;labels[i]=300;const shade=8+Math.round(Math.abs(Math.sin(t*18+k))*14);rgba[i*4]=Math.max(0,rgba[i*4]-shade);rgba[i*4+1]=Math.max(0,rgba[i*4+1]-shade);rgba[i*4+2]=Math.max(0,rgba[i*4+2]-shade);normal[i*4]=110+k*2;normal[i*4+1]=150;normal[i*4+2]=220;material[i*4]=Math.min(255,material[i*4]+18)}}
 private disc(cx:number,cy:number,r:number,z:number,label:number,color:number[],w:number,h:number,rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,depth:Float32Array,labels:Uint16Array){for(let y=Math.max(0,Math.floor(cy-r));y<=Math.min(h-1,Math.ceil(cy+r));y++)for(let x=Math.max(0,Math.floor(cx-r));x<=Math.min(w-1,Math.ceil(cx+r));x++){const dx=(x-cx)/r,dy=(y-cy)/r,d=dx*dx+dy*dy;if(d>1)continue;const i=y*w+x,zz=z-d*.008;if(zz>=depth[i])continue;depth[i]=zz;labels[i]=label;const light=.72+.28*Math.sqrt(Math.max(0,1-d));rgba[i*4]=Math.round(color[0]*light);rgba[i*4+1]=Math.round(color[1]*light);rgba[i*4+2]=Math.round(color[2]*light);rgba[i*4+3]=255;normal[i*4]=this.clamp((dx*.5+.5)*255);normal[i*4+1]=this.clamp((dy*.5+.5)*255);normal[i*4+2]=this.clamp(Math.sqrt(Math.max(0,1-d))*255);normal[i*4+3]=255;material[i*4]=145;material[i*4+1]=48;material[i*4+3]=255}}
 private antialias(w:number,h:number,rgba:Uint8Array,labels:Uint16Array){const src=rgba.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,l=labels[i];if(!l)continue;let boundary=false;for(const n of [i-1,i+1,i-w,i+w])if(labels[n]!==l){boundary=true;break}if(!boundary)continue;for(let c=0;c<3;c++)rgba[i*4+c]=Math.round((src[i*4+c]*4+src[(i-1)*4+c]+src[(i+1)*4+c]+src[(i-w)*4+c]+src[(i+w)*4+c])/8)}}
 private inspect(w:number,h:number,labels:Uint16Array,depth:Float32Array){const defs=[['left-eye',[11,13],20],['right-eye',[12,14],20],['nose',[21,22,23],28],['lips',[31,32],24],['ears',[41,42],20],['neck',[51],30],['fingers',Array.from({length:15},(_,i)=>101+i).filter(x=>x<106||x>110),50],['hair',[200],80],['garment-wrinkles',[300],80]] as any[];return defs.map(([part,codes,min])=>{const set=new Set<number>(codes as number[]),idx=[] as number[];for(let i=0;i<labels.length;i++)if(set.has(labels[i]))idx.push(i);let edges=0;for(const i of idx)if(i%w===0||i%w===w-1||i<w||i>=w*(h-1)||[i-1,i+1,i-w,i+w].some(n=>!set.has(labels[n])))edges++;const components=this.components(w,h,labels,set),ds=idx.map(i=>depth[i]);return{part,label:codes[0],pixels:idx.length,components,edgePixels:edges,depthOrdered:ds.every(Number.isFinite)&&Math.max(...ds)<9,passed:idx.length>=min&&components>=1&&edges>0&&ds.every(Number.isFinite)}})}
 private components(w:number,h:number,labels:Uint16Array,set:Set<number>){const seen=new Uint8Array(labels.length);let count=0;for(let i=0;i<labels.length;i++){if(seen[i]||!set.has(labels[i]))continue;count++;const q=[i];seen[i]=1;while(q.length){const v=q.pop()!;for(const n of [v-1,v+1,v-w,v+w])if(n>=0&&n<labels.length&&!seen[n]&&set.has(labels[n])&&Math.abs(n%w-v%w)<=1){seen[n]=1;q.push(n)}}}return count}
 private optical(rgba:Uint8Array,normal:Uint8Array,material:Uint8Array,labels:Uint16Array){const colors=new Set<string>(),normals=new Set<string>(),mats=new Set<string>();for(let i=0;i<labels.length;i+=11){if(!labels[i])continue;colors.add(`${rgba[i*4]>>3},${rgba[i*4+1]>>3},${rgba[i*4+2]>>3}`);normals.add(`${normal[i*4]>>4},${normal[i*4+1]>>4},${normal[i*4+2]>>4}`);mats.add(`${material[i*4]>>4},${material[i*4+1]>>4}`)}return Math.min(1,colors.size/45)*.45+Math.min(1,normals.size/35)*.35+Math.min(1,mats.size/12)*.2}
 private clamp(v:number){return Math.max(0,Math.min(255,Math.round(v)))}
}
export const finalPixelQualityP197Service=new FinalPixelQualityP197Service();
