import { canonicalSha256Object } from './canonicalSha256Service';

export type GarmentPresence='GARMENT_PRESENT'|'GARMENT_ABSENT'|'GARMENT_AMBIGUOUS'|'GARMENT_OCCLUDED'|'GARMENT_CONFIRMATION_REQUIRED';
export type GarmentLayer='INNER'|'TOP'|'BOTTOM'|'OUTER'|'FOOTWEAR'|'HEADWEAR'|'ACCESSORY'|'UNKNOWN';
export type GarmentKind='SHIRT'|'COAT'|'JACKET'|'PANTS'|'SKIRT'|'DRESS'|'SWEATER'|'SPORTSWEAR'|'FOOTWEAR'|'OTHER'|'UNKNOWN';
export interface NormalizedPoint{x:number;y:number;}
export interface GarmentGapEvidence{kind:'NECK_OPENING'|'FRONT_OPENING'|'SLEEVE_OPENING'|'HEM_GAP'|'WAIST_GAP'|'LAYER_GAP'|'VENT'|'UNKNOWN';contour:NormalizedPoint[];widthRatio:number;depthHint:number;confidence:number;}
export interface GarmentEvidenceInput{regionId:string;sourceSha256:string;appearancePalette:string[];garmentPalette:string[];boundaryConfidence:number;textureDifference:number;seamConfidence:number;wrinkleConfidence:number;layerOverlapConfidence:number;motionLagConfidence:number;coverageRatio:number;occlusionRatio:number;kindCandidates:{kind:GarmentKind;confidence:number}[];layerCandidates:{layer:GarmentLayer;confidence:number}[];gaps:GarmentGapEvidence[];gapObservationComplete:boolean;zeroGapConfidence:number;userDecision?:'PRESENT'|'ABSENT'|'UNKNOWN';}
export type GarmentGapState='GAPS_OBSERVED'|'ZERO_GAPS_CONFIRMED'|'GAP_OBSERVATION_INCOMPLETE';
export interface GarmentLearningProfile{regionId:string;presence:GarmentPresence;confirmationRequired:boolean;confirmationReason:string[];absenceDecisionAllowed:false;confirmationContract?:{questionId:string;regionId:string;sourceSha256:string;profileSha256BeforeAnswer:string;consumed:boolean;};appearanceGarmentColorDistance:number;appearanceGarmentSimilarity:number;nonColorEvidenceScore:number;kind:GarmentKind;layer:GarmentLayer;coverageRatio:number;occlusionRatio:number;gapState:GarmentGapState;gapObservationComplete:boolean;zeroGapConfidence:number;gaps:GarmentGapEvidence[];learnedDifferences:{paletteDistance:number;boundaryConfidence:number;textureDifference:number;seamConfidence:number;wrinkleConfidence:number;layerOverlapConfidence:number;motionLagConfidence:number;gapCount:number;meanGapWidthRatio:number;zeroGapConfirmed:boolean;};sourceSha256:string;profileSha256:string;}

class GarmentEvidenceLearningService {
 analyze(input:GarmentEvidenceInput):GarmentLearningProfile {this.validate(input);const distance=this.paletteDistance(input.appearancePalette,input.garmentPalette);const similarity=1-Math.min(1,distance/441.673);const nonColor=this.clamp((input.boundaryConfidence*1.4+input.textureDifference+input.seamConfidence*1.2+input.wrinkleConfidence+input.layerOverlapConfidence*1.2+input.motionLagConfidence*.8)/6.6);const reasons:string[]=[];const similar=similarity>=.82;if(similar)reasons.push('APPEARANCE_GARMENT_COLOR_SIMILAR');if(input.boundaryConfidence<.48)reasons.push('WEAK_BOUNDARY');if(input.occlusionRatio>.58)reasons.push('HIGH_OCCLUSION');if(nonColor<.52)reasons.push('INSUFFICIENT_NON_COLOR_EVIDENCE');let presence:GarmentPresence;
 if(input.userDecision==='PRESENT')presence='GARMENT_PRESENT';else if(input.userDecision==='ABSENT')presence='GARMENT_CONFIRMATION_REQUIRED';else if(input.userDecision==='UNKNOWN')presence='GARMENT_AMBIGUOUS';else if(input.occlusionRatio>.82)presence='GARMENT_OCCLUDED';else if(similar||nonColor<.52)presence='GARMENT_CONFIRMATION_REQUIRED';else if(nonColor>=.68)presence='GARMENT_PRESENT';else presence='GARMENT_AMBIGUOUS';
 if(input.userDecision==='ABSENT')reasons.push('ABSENCE_REQUIRES_EXPLICIT_CONFIRMATION_CONTRACT');
 const confirmationRequired=presence==='GARMENT_CONFIRMATION_REQUIRED';const kind=this.best(input.kindCandidates,'kind') as GarmentKind;const layer=this.best(input.layerCandidates,'layer') as GarmentLayer;const meanGap=input.gaps.length?input.gaps.reduce((n,g)=>n+g.widthRatio,0)/input.gaps.length:0;const gapState:GarmentGapState=input.gaps.length?'GAPS_OBSERVED':input.gapObservationComplete&&input.zeroGapConfidence>=.6?'ZERO_GAPS_CONFIRMED':'GAP_OBSERVATION_INCOMPLETE';if(gapState==='GAP_OBSERVATION_INCOMPLETE')reasons.push('GAP_OBSERVATION_INCOMPLETE');const core={regionId:input.regionId,presence,confirmationRequired,confirmationReason:reasons,absenceDecisionAllowed:false as const,appearanceGarmentColorDistance:distance,appearanceGarmentSimilarity:similarity,nonColorEvidenceScore:nonColor,kind,layer,coverageRatio:input.coverageRatio,occlusionRatio:input.occlusionRatio,gapState,gapObservationComplete:input.gapObservationComplete,zeroGapConfidence:input.zeroGapConfidence,gaps:structuredClone(input.gaps),learnedDifferences:{paletteDistance:distance,boundaryConfidence:input.boundaryConfidence,textureDifference:input.textureDifference,seamConfidence:input.seamConfidence,wrinkleConfidence:input.wrinkleConfidence,layerOverlapConfidence:input.layerOverlapConfidence,motionLagConfidence:input.motionLagConfidence,gapCount:input.gaps.length,meanGapWidthRatio:meanGap,zeroGapConfirmed:gapState==='ZERO_GAPS_CONFIRMED'},sourceSha256:input.sourceSha256};return{...core,profileSha256:canonicalSha256Object(core)};}
 issueConfirmation(profile:GarmentLearningProfile):GarmentLearningProfile {if(profile.presence!=='GARMENT_CONFIRMATION_REQUIRED')throw new Error('GARMENT_CONFIRMATION_NOT_REQUIRED');const questionId=`GARMENT-${canonicalSha256Object({regionId:profile.regionId,sourceSha256:profile.sourceSha256,profileSha256:profile.profileSha256}).slice(0,24)}`;const contract={questionId,regionId:profile.regionId,sourceSha256:profile.sourceSha256,profileSha256BeforeAnswer:profile.profileSha256,consumed:false};const core={...profile,confirmationContract:contract};delete (core as Partial<GarmentLearningProfile>).profileSha256;return{...core,profileSha256:canonicalSha256Object(core)};}
 resolve(profile:GarmentLearningProfile,answer:{decision:'PRESENT'|'ABSENT'|'UNKNOWN';questionId:string;regionId:string;sourceSha256:string;profileSha256BeforeAnswer:string}):GarmentLearningProfile {const contract=profile.confirmationContract;if(!contract||contract.consumed)throw new Error('GARMENT_CONFIRMATION_CONTRACT_INVALID');if(profile.presence!=='GARMENT_CONFIRMATION_REQUIRED'||answer.questionId!==contract.questionId||answer.regionId!==contract.regionId||answer.sourceSha256!==contract.sourceSha256||answer.profileSha256BeforeAnswer!==contract.profileSha256BeforeAnswer)throw new Error('GARMENT_CONFIRMATION_CONTEXT_MISMATCH');const presence:GarmentPresence=answer.decision==='PRESENT'?'GARMENT_PRESENT':answer.decision==='ABSENT'?'GARMENT_ABSENT':'GARMENT_AMBIGUOUS';const core={...profile,presence,confirmationRequired:false,confirmationReason:[...profile.confirmationReason,'USER_CONFIRMED'],absenceDecisionAllowed:false as const,confirmationContract:{...contract,consumed:true}};delete (core as Partial<GarmentLearningProfile>).profileSha256;return{...core,profileSha256:canonicalSha256Object(core)};}
 private paletteDistance(a:string[],b:string[]){if(!a.length||!b.length)return 441.673;const rgb=(x:string)=>[parseInt(x.slice(1,3),16),parseInt(x.slice(3,5),16),parseInt(x.slice(5,7),16)];let total=0;for(const x of a){const p=rgb(x);let min=Infinity;for(const y of b){const q=rgb(y);min=Math.min(min,Math.hypot(p[0]-q[0],p[1]-q[1],p[2]-q[2]));}total+=min;}return total/a.length;}
 private best<T extends Record<string,unknown>>(items:T[],key:keyof T){return items.length?[...items].sort((a,b)=>Number(b.confidence)-Number(a.confidence))[0][key]:'UNKNOWN';}
 private clamp(v:number){return Math.max(0,Math.min(1,v));}
 private validate(i:GarmentEvidenceInput){if(!i.regionId||!/^[a-f0-9]{64}$/i.test(i.sourceSha256))throw new Error('GARMENT_EVIDENCE_ID_REQUIRED');for(const c of [...i.appearancePalette,...i.garmentPalette])if(!/^#[0-9a-f]{6}$/i.test(c))throw new Error('GARMENT_PALETTE_INVALID');for(const n of [i.boundaryConfidence,i.textureDifference,i.seamConfidence,i.wrinkleConfidence,i.layerOverlapConfidence,i.motionLagConfidence,i.coverageRatio,i.occlusionRatio,i.zeroGapConfidence])if(!Number.isFinite(n)||n<0||n>1)throw new Error('GARMENT_EVIDENCE_RANGE_INVALID');for(const g of i.gaps)if(g.widthRatio<0||g.widthRatio>1||g.depthHint<0||g.depthHint>1||g.confidence<0||g.confidence>1)throw new Error('GARMENT_GAP_RANGE_INVALID');}
}
export const garmentEvidenceLearningService=new GarmentEvidenceLearningService();
