import { canonicalSha256Object } from './canonicalSha256Service';
import type { GarmentLearningProfile } from './garmentEvidenceLearningService';

export type GarmentBoundaryMode='NO_ARTIFICIAL_BOUNDARY'|'OBSERVED_BOUNDARY_ONLY'|'MATERIAL_BOUNDARY'|'STRUCTURAL_BOUNDARY';
export interface GarmentBoundaryRenderingInput{profile:GarmentLearningProfile;appearancePalette:string[];garmentPalette:string[];observedBoundaryConfidence:number;observedSeamConfidence:number;observedShadowConfidence:number;observedTextureDifference:number;garmentThickness:number;userRequestedOutline?:boolean;}
export interface GarmentBoundaryRenderingPolicy{mode:GarmentBoundaryMode;drawBlackOutline:false;drawBoundary:boolean;boundaryColor:string|null;boundaryOpacity:number;allowedSignals:('OBSERVED_SEAM'|'OBSERVED_SHADOW'|'OBSERVED_TEXTURE'|'OBSERVED_THICKNESS'|'USER_REQUESTED_OUTLINE')[];reason:string[];policySha256:string;}
class GarmentBoundaryRenderingPolicyService{
 resolve(input:GarmentBoundaryRenderingInput):GarmentBoundaryRenderingPolicy{this.validate(input);const exactColor=this.samePalette(input.appearancePalette,input.garmentPalette);const zeroGap=input.profile.gapState==='ZERO_GAPS_CONFIRMED';const weakStructure=input.observedBoundaryConfidence<.3&&input.observedSeamConfidence<.3&&input.observedShadowConfidence<.3&&input.observedTextureDifference<.3&&input.garmentThickness<.02;const allowed:GarmentBoundaryRenderingPolicy['allowedSignals']=[];if(input.observedSeamConfidence>=.3)allowed.push('OBSERVED_SEAM');if(input.observedShadowConfidence>=.3)allowed.push('OBSERVED_SHADOW');if(input.observedTextureDifference>=.3)allowed.push('OBSERVED_TEXTURE');if(input.garmentThickness>=.02)allowed.push('OBSERVED_THICKNESS');if(input.userRequestedOutline)allowed.push('USER_REQUESTED_OUTLINE');let mode:GarmentBoundaryMode='STRUCTURAL_BOUNDARY',drawBoundary=true,boundaryColor:string|null='#000000',boundaryOpacity=.8;const reason:string[]=[];if(exactColor&&zeroGap&&weakStructure&&!input.userRequestedOutline){mode='NO_ARTIFICIAL_BOUNDARY';drawBoundary=false;boundaryColor=null;boundaryOpacity=0;reason.push('EXACT_COLOR_MATCH','ZERO_GAPS_CONFIRMED','NO_OBSERVED_BOUNDARY_SIGNAL');}else if(!input.userRequestedOutline){mode=allowed.length?'OBSERVED_BOUNDARY_ONLY':'NO_ARTIFICIAL_BOUNDARY';drawBoundary=allowed.length>0;boundaryColor=drawBoundary?this.derivedBoundary(input.garmentPalette):null;boundaryOpacity=drawBoundary?Math.max(input.observedBoundaryConfidence,input.observedSeamConfidence,input.observedShadowConfidence,input.observedTextureDifference):0;reason.push(drawBoundary?'OBSERVED_SIGNAL_ONLY':'NO_OBSERVED_BOUNDARY_SIGNAL');}else{reason.push('USER_REQUESTED_OUTLINE');}
 const core={mode,drawBlackOutline:false as const,drawBoundary,boundaryColor,boundaryOpacity,allowedSignals:allowed,reason};return{...core,policySha256:canonicalSha256Object(core)};}
 private samePalette(a:string[],b:string[]){return a.length===b.length&&[...a].sort().every((x,i)=>x.toLowerCase()===[...b].sort()[i].toLowerCase());}
 private derivedBoundary(colors:string[]){const c=colors[0]??'#808080';const n=parseInt(c.slice(1),16);const r=Math.max(0,((n>>16)&255)-12),g=Math.max(0,((n>>8)&255)-12),b=Math.max(0,(n&255)-12);return`#${[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
 private validate(i:GarmentBoundaryRenderingInput){for(const n of [i.observedBoundaryConfidence,i.observedSeamConfidence,i.observedShadowConfidence,i.observedTextureDifference,i.garmentThickness])if(!Number.isFinite(n)||n<0||n>1)throw new Error('GARMENT_BOUNDARY_VALUE_INVALID');}
}
export const garmentBoundaryRenderingPolicyService=new GarmentBoundaryRenderingPolicyService();
