import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from './canonicalSha256Service';
import { coreTaskIngressService } from './coreTaskIngressService';
export type WorkspaceMode='SELF_CODE'|'SOURCE_REPOSITORY'|'VBA_WORKBOOK'|'VBA_TEXT'|'STATIC_WEB'|'APPLICATION_PROJECT'|'DOCUMENT_OR_CONFIG';
export type WorkspaceTrust='UNTRUSTED'|'RESTRICTED'|'REVIEWED'|'TRUSTED_FOR_BUILD'|'TRUSTED_FOR_PREVIEW'|'QUARANTINED';
export type PreviewCapability='SOURCE_VIEW'|'DIFF_VIEW'|'STRUCTURE_VIEW'|'DEPENDENCY_VIEW'|'WEB_RUNTIME_PREVIEW'|'DEVICE_VIEWPORT_PREVIEW'|'DOCUMENT_PREVIEW'|'DATA_PREVIEW'|'VBA_VALIDATION_PREVIEW'|'RUNTIME_EVIDENCE_PREVIEW';
export interface WorkspaceRecord {workspaceId:string;name:string;workspaceMode:WorkspaceMode;assetKind:string;sourceLocator:string;baseSnapshotId:string;baseContent:string;baseSha256:string;candidateRevisionId?:string;candidateContent?:string;candidateSha256?:string;trustStatus:WorkspaceTrust;previewCapabilities:PreviewCapability[];validationCapabilities:string[];exportCapabilities:string[];targetEnvironment:string;coreTaskId:string;createdAt:number;updatedAt:number;}
export interface VbaProcedureIndex {name:string;visibility:'Public'|'Private'|'Friend'|'Default';kind:'Sub'|'Function'|'Property';startLine:number;endLine?:number;}
export interface VbaWorkspaceAnalysis {procedures:VbaProcedureIndex[];dependencies:{sheets:string[];ranges:string[];calls:string[]};violations:string[];runtimeStatus:'NOT_EXECUTED'|'EXECUTED';baseSha256:string;candidateSha256?:string;}
const KEY='miki_general_workspace_v1';
class GeneralWorkspaceService{
 async create(input:{name:string;workspaceMode:WorkspaceMode;assetKind:string;sourceLocator:string;baseContent:string;trustStatus?:WorkspaceTrust;targetEnvironment?:string}):Promise<WorkspaceRecord>{if(!input.name.trim()||!input.baseContent)throw new Error('WORKSPACE_REQUIRED_FIELDS_MISSING');const baseSha256=canonicalSha256(input.baseContent);const result=await coreTaskIngressService.submit({kind:'USER_REQUEST',goal:`Workspace ${input.name}を隔離作成する`,source:'conversation',payload:{operation:'CREATE_GENERAL_WORKSPACE',workspaceMode:input.workspaceMode,assetKind:input.assetKind,sourceLocator:input.sourceLocator,baseSha256,destructive:false}});if(result.task.status!=='COMPLETED')throw new Error('CORE_WORKSPACE_CREATE_NOT_COMPLETED');const workspaceId=`WS-${canonicalSha256({name:input.name,baseSha256,at:Date.now()}).slice(0,20)}`;const now=Date.now();const row:WorkspaceRecord={workspaceId,name:input.name.trim(),workspaceMode:input.workspaceMode,assetKind:input.assetKind,sourceLocator:input.sourceLocator,baseSnapshotId:`BASE-${baseSha256.slice(0,20)}`,baseContent:input.baseContent,baseSha256,trustStatus:input.trustStatus||'UNTRUSTED',previewCapabilities:this.capabilities(input.workspaceMode),validationCapabilities:input.workspaceMode==='VBA_TEXT'||input.workspaceMode==='VBA_WORKBOOK'?['VBA_STATIC_VALIDATION']:['STATIC_VALIDATION'],exportCapabilities:input.workspaceMode==='VBA_TEXT'||input.workspaceMode==='VBA_WORKBOOK'?['VBE_CODE_TXT','VBE_VALIDATION_LOG','REVIEW_ZIP']:['REVIEW_ZIP'],targetEnvironment:input.targetEnvironment||'unknown',coreTaskId:result.task.taskId,createdAt:now,updatedAt:now};const rows=this.list();storageService.setItem(KEY,JSON.stringify([row,...rows.filter(x=>x.workspaceId!==workspaceId)].slice(0,100)));return this.clone(row);}
 async setCandidate(workspaceId:string,content:string):Promise<WorkspaceRecord>{const rows=this.list();const row=rows.find(x=>x.workspaceId===workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');if(!content.trim())throw new Error('CANDIDATE_CONTENT_REQUIRED');const candidateSha256=canonicalSha256(content);const result=await coreTaskIngressService.submit({kind:'SELF_IMPROVEMENT',goal:`${workspaceId}のCandidate Revisionを隔離保存する`,source:'conversation',payload:{operation:'SAVE_WORKSPACE_CANDIDATE',workspaceId,parentRevision:row.candidateRevisionId||row.baseSnapshotId,baseSha256:row.baseSha256,candidateSha256}});if(result.task.status!=='COMPLETED')throw new Error('CORE_CANDIDATE_SAVE_NOT_COMPLETED');row.candidateRevisionId=`REV-${candidateSha256.slice(0,20)}`;row.candidateContent=content;row.candidateSha256=candidateSha256;row.coreTaskId=result.task.taskId;row.updatedAt=Date.now();storageService.setItem(KEY,JSON.stringify(rows));return this.clone(row);}
 analyzeVba(workspaceId:string):VbaWorkspaceAnalysis{const row=this.list().find(x=>x.workspaceId===workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');const code=row.candidateContent||row.baseContent;const lines=code.replace(/\r\n?/g,'\n').split('\n');const procedures:VbaProcedureIndex[]=[];const starts:Array<{index:number;proc:VbaProcedureIndex}>=[];lines.forEach((line,index)=>{const match=line.match(/^\s*(?:(Public|Private|Friend)\s+)?(?:Static\s+)?(Sub|Function|Property\s+(?:Get|Let|Set))\s+([A-Za-z_][A-Za-z0-9_]*)/i);if(match){const proc:VbaProcedureIndex={name:match[3],visibility:(match[1]||'Default') as VbaProcedureIndex['visibility'],kind:/^Sub$/i.test(match[2])?'Sub':/^Function$/i.test(match[2])?'Function':'Property',startLine:index+1};procedures.push(proc);starts.push({index,proc});}});for(const item of starts){const endPattern=item.proc.kind==='Sub'?/^\s*End\s+Sub\b/i:item.proc.kind==='Function'?/^\s*End\s+Function\b/i:/^\s*End\s+Property\b/i;for(let i=item.index+1;i<lines.length;i+=1){if(endPattern.test(lines[i])){item.proc.endLine=i+1;break;}}}const sheets=[...code.matchAll(/(?:Worksheets|Sheets)\s*\(\s*"([^"]+)"/gi)].map(x=>x[1]);const ranges=[...code.matchAll(/Range\s*\(\s*"([^"]+)"/gi)].map(x=>x[1]);const calls=[...code.matchAll(/\bCall\s+([A-Za-z_][A-Za-z0-9_]*)/gi)].map(x=>x[1]);const violations:string[]=[];if(!/^\s*Option\s+Explicit\b/im.test(code))violations.push('OPTION_EXPLICIT_REQUIRED');if(/\bGoTo\b/i.test(code))violations.push('GOTO_FORBIDDEN');if(/^\s*[A-Za-z_][A-Za-z0-9_]*:\s*$/m.test(code))violations.push('LABEL_FORBIDDEN');if(/^\s*If\b[^\n]*\bThen\s+[^'\s].+$/im.test(code))violations.push('SINGLE_LINE_IF_FORBIDDEN');if(/^\s*Attribute\s+VB_Name\b/im.test(code))violations.push('ATTRIBUTE_VB_NAME_FORBIDDEN');if(procedures.some(x=>!x.endLine))violations.push('PROCEDURE_END_MISSING');return {procedures,dependencies:{sheets:[...new Set(sheets)],ranges:[...new Set(ranges)],calls:[...new Set(calls)]},violations,runtimeStatus:'NOT_EXECUTED',baseSha256:row.baseSha256,candidateSha256:row.candidateSha256};}
 exportVbaCode(workspaceId:string):Blob{const row=this.list().find(x=>x.workspaceId===workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');const code=row.candidateContent||row.baseContent;const analysis=this.analyzeVba(workspaceId);if(analysis.violations.length)throw new Error(`VBA_VALIDATION_FAILED:${analysis.violations.join('|')}`);return new Blob([code],{type:'text/plain;charset=utf-8'});}
 list():WorkspaceRecord[]{return this.read().map(x=>this.clone(x));}
 private capabilities(mode:WorkspaceMode):PreviewCapability[]{if(mode==='VBA_TEXT'||mode==='VBA_WORKBOOK')return ['SOURCE_VIEW','DIFF_VIEW','STRUCTURE_VIEW','DEPENDENCY_VIEW','VBA_VALIDATION_PREVIEW'];if(mode==='STATIC_WEB')return ['SOURCE_VIEW','DIFF_VIEW','STRUCTURE_VIEW','WEB_RUNTIME_PREVIEW','DEVICE_VIEWPORT_PREVIEW'];return ['SOURCE_VIEW','DIFF_VIEW','STRUCTURE_VIEW'];}
 private read():WorkspaceRecord[]{try{const raw=storageService.getItem(KEY);const value=raw?JSON.parse(raw):[];return Array.isArray(value)?value:[];}catch{return [];}}
 private clone(row:WorkspaceRecord):WorkspaceRecord{return {...row,previewCapabilities:[...row.previewCapabilities],validationCapabilities:[...row.validationCapabilities],exportCapabilities:[...row.exportCapabilities]};}
}
export const generalWorkspaceService=new GeneralWorkspaceService();
