import { canonicalSha256Object } from './canonicalSha256Service';
import type { P151Edge,P151Graph,P151Node } from './unifiedKnowledgeGraphP151Service';
export type P154TruthStatus='ASSERTED'|'SUPPORTED'|'CONTRADICTED'|'SUPERSEDED'|'UNKNOWN';
export interface P154Claim{claimId:string;subjectId:string;predicate:string;value:unknown;validFrom:number;validTo?:number;recordedAt:number;status:P154TruthStatus;confidence:number;uncertainty:number;sourceNodeIds:string[];supersedesClaimId?:string;claimSha256:string;}
export interface P154EdgeRule{type:string;fromDomains:string[];toDomains:string[];transitive:boolean;maxDepth:number;allowCycles:boolean;}
export interface P154Ontology{nodeKinds:string[];edgeRules:P154EdgeRule[];ontologySha256:string;}
export interface P154Conflict{conflictId:string;subjectId:string;predicate:string;claimIds:string[];resolution:'KEEP_BOTH'|'LATEST_VALIDATED'|'HIGHEST_CONFIDENCE'|'USER_CORRECTION';winnerClaimId?:string;conflictSha256:string;}
export interface P154Path{nodeIds:string[];edgeIds:string[];score:number;provenanceComplete:boolean;}
export interface P154ReasoningResult{claims:P154Claim[];conflicts:P154Conflict[];paths:P154Path[];selectedNodeIds:string[];resultSha256:string;}
class GraphReasoningP154Service{
 ontology(nodes:P151Node[],edges:P151Edge[]):P154Ontology{const nodeKinds=[...new Set(nodes.map(n=>`${n.domain}:${n.kind}`))].sort(),types=[...new Set(edges.map(e=>e.type))].sort(),edgeRules=types.map(type=>({type,fromDomains:[...new Set(edges.filter(e=>e.type===type).map(e=>nodes.find(n=>n.nodeId===e.from)?.domain||'UNKNOWN'))].sort(),toDomains:[...new Set(edges.filter(e=>e.type===type).map(e=>nodes.find(n=>n.nodeId===e.to)?.domain||'UNKNOWN'))].sort(),transitive:['SUPPORTS_COMPLETION','DERIVED_FROM','UPDATES'].includes(type),maxDepth:['SUPPORTS_COMPLETION','DERIVED_FROM'].includes(type)?6:3,allowCycles:false}));const core:any={nodeKinds,edgeRules,ontologySha256:''};core.ontologySha256=canonicalSha256Object({...core,ontologySha256:''});return core;}
 claim(input:Omit<P154Claim,'claimId'|'claimSha256'>):P154Claim{if(input.validTo!==undefined&&input.validTo<input.validFrom)throw new Error('P154_INVALID_INTERVAL');const claimSha256=canonicalSha256Object(input);return{claimId:`C-${claimSha256.slice(0,24)}`,...input,claimSha256};}
 resolve(claims:P154Claim[]):P154Conflict[]{const groups=new Map<string,P154Claim[]>();for(const c of claims){const key=`${c.subjectId}|${c.predicate}`;(groups.get(key)||groups.set(key,[]).get(key)!).push(c);}const out:P154Conflict[]=[];for(const [key,items] of groups)if(new Set(items.map(x=>JSON.stringify(x.value))).size>1){const corrected=items.filter(x=>x.status==='SUPPORTED'&&x.supersedesClaimId),validated=items.filter(x=>x.status==='SUPPORTED'),winner=(corrected.sort((a,b)=>b.recordedAt-a.recordedAt)[0]||validated.sort((a,b)=>b.confidence-a.confidence||b.recordedAt-a.recordedAt)[0]||items.sort((a,b)=>b.confidence-a.confidence)[0]),resolution=corrected.length?'USER_CORRECTION':validated.length?'LATEST_VALIDATED':'HIGHEST_CONFIDENCE',[subjectId,predicate]=key.split('|'),seed:any={subjectId,predicate,claimIds:items.map(x=>x.claimId).sort(),resolution,winnerClaimId:winner?.claimId,conflictSha256:''};seed.conflictSha256=canonicalSha256Object({...seed,conflictSha256:''});out.push({conflictId:`X-${seed.conflictSha256.slice(0,24)}`,...seed});}return out;}
 traverse(g:P151Graph,startIds:string[],goal:(n:P151Node)=>boolean,maxDepth=6,limit=32):P154Path[]{const byId=new Map(g.nodes.map(n=>[n.nodeId,n])),adj=new Map<string,P151Edge[]>();for(const e of g.edges){(adj.get(e.from)||adj.set(e.from,[]).get(e.from)!).push(e);(adj.get(e.to)||adj.set(e.to,[]).get(e.to)!).push(e);}const q=startIds.map(id=>({id,nodes:[id],edges:[] as string[],score:1})),paths:P154Path[]=[];while(q.length&&paths.length<limit){const cur=q.shift()!;const node=byId.get(cur.id);if(node&&goal(node)&&cur.nodes.length>1)paths.push({nodeIds:cur.nodes,edgeIds:cur.edges,score:cur.score,provenanceComplete:cur.nodes.every(id=>(byId.get(id)?.sourceRefs.length||0)>0||id===cur.nodes[0])});if(cur.edges.length>=maxDepth)continue;for(const e of adj.get(cur.id)||[]){const next=e.from===cur.id?e.to:e.from;if(cur.nodes.includes(next))continue;const n=byId.get(next);if(!n)continue;q.push({id:next,nodes:[...cur.nodes,next],edges:[...cur.edges,e.edgeId],score:cur.score*e.confidence*n.confidence*(1-n.uncertainty*.35)});}}return paths.sort((a,b)=>b.score-a.score);}
 reason(g:P151Graph,claims:P154Claim[],startIds:string[]):P154ReasoningResult{const paths=this.traverse(g,startIds,n=>['MEMORY','EXPERIENCE','VISUAL','VALIDATION'].includes(n.domain)),conflicts=this.resolve(claims),selectedNodeIds=[...new Set(paths.slice(0,12).flatMap(p=>p.nodeIds))],core:any={claims,conflicts,paths,selectedNodeIds,resultSha256:''};core.resultSha256=canonicalSha256Object({...core,resultSha256:''});return core;}}
export const graphReasoningP154Service=new GraphReasoningP154Service();
