import { storageService } from '../../../services/storageService';
import { candidateWriteGuardService } from './candidateWriteGuardService';
import { candidateCommitTransactionService, type CandidateCommitTransaction } from './candidateCommitTransactionService';
export type CandidateWorkspaceStatus='ISOLATED'|'VALIDATING'|'SHADOW_PASSED'|'PROMOTABLE'|'EXPORTED'|'REJECTED';
export interface CandidateFile { path:string; baselineContent:string; candidateContent:string; baselineSha256:string; candidateSha256:string; evidenceIds:string[]; }
export interface CandidateWorkspace { workspaceId:string; runId?:string; issueId:string; writeGuardId:string; transactionId?:string; committedRevision?:number; persistenceReceiptId?:string; baseSnapshotSha256:string; candidateRevisionSha256:string; status:CandidateWorkspaceStatus; files:CandidateFile[]; createdAt:number; updatedAt:number; }
const KEY='miki_isolated_candidate_workspaces_v1';
class IsolatedCandidateWorkspaceService{
 private items=new Map<string,CandidateWorkspace>();private sequence=0;
 constructor(){this.load();this.reconcileRestoredWorkspaces();}
 async create(issueId:string,files:Array<{path:string;baselineContent:string;candidateContent:string;evidenceIds?:string[]}>,runId?:string):Promise<CandidateWorkspace>{const guard=await candidateWriteGuardService.stage(issueId,files);try{candidateWriteGuardService.consume(guard.guardId,issueId,files.map(file=>file.path));const now=Date.now();this.sequence+=1;const workspaceId=`CWS-${now}-${String(this.sequence).padStart(6,'0')}`;const mapped:CandidateFile[]=[];for(const file of files)mapped.push({...file,evidenceIds:[...(file.evidenceIds||[])],baselineSha256:await this.sha(file.baselineContent),candidateSha256:await this.sha(file.candidateContent)});const item={workspaceId,issueId,runId,writeGuardId:guard.guardId,baseSnapshotSha256:guard.baseSnapshotSha256,candidateRevisionSha256:guard.candidateRevisionSha256,status:'ISOLATED' as const,files:mapped,createdAt:now,updatedAt:now};this.items.set(workspaceId,item);this.save();return this.clone(item);}catch(error){candidateWriteGuardService.rollback(guard.guardId);throw error;}}
 async commitWithReceipt(id:string,persistenceReceiptId:string,operationInstanceId:string):Promise<{workspace:CandidateWorkspace;transaction:CandidateCommitTransaction}>{const item=this.items.get(id);if(!item)throw new Error('CANDIDATE_WORKSPACE_NOT_FOUND');if(item.status!=='ISOLATED'&&item.status!=='SHADOW_PASSED'&&item.status!=='EXPORTED')throw new Error('CANDIDATE_WORKSPACE_NOT_COMMITTABLE');if(!candidateWriteGuardService.verify(item.writeGuardId,item.issueId,item.files.map(file=>file.path)))throw new Error('CANDIDATE_WRITE_GUARD_INVALID');const previous=candidateCommitTransactionService.latestCommitted(item.issueId);try{const transaction=await candidateCommitTransactionService.commit({issueId:item.issueId,workspaceId:item.workspaceId,guardId:item.writeGuardId,files:item.files.map(file=>({...file,evidenceIds:[...file.evidenceIds]})),receiptId:persistenceReceiptId,previousTransactionId:previous?.transactionId,operationInstanceId});item.transactionId=transaction.transactionId;item.committedRevision=transaction.revision;item.persistenceReceiptId=persistenceReceiptId;item.status='PROMOTABLE';item.updatedAt=Date.now();try{this.save();}catch(error){candidateCommitTransactionService.markRecoveryRequired(transaction.transactionId,'WORKSPACE_SAVE_AFTER_COMMIT_FAILED');item.status='REJECTED';throw error;}return {workspace:this.clone(item),transaction};}catch(error){candidateWriteGuardService.rollback(item.writeGuardId);item.status='REJECTED';item.updatedAt=Date.now();this.save();throw error;}}
 async restorePreviousCommitted(transactionId:string):Promise<CandidateWorkspace>{const previous=candidateCommitTransactionService.restorePrevious(transactionId);if(!previous)throw new Error('PREVIOUS_COMMITTED_TRANSACTION_NOT_FOUND');const existing=this.items.get(previous.workspaceId);const restoredFiles=previous.files.map(file=>({...file,candidateContent:file.candidateContent,evidenceIds:[...file.evidenceIds]}));if(existing){existing.files=restoredFiles;existing.transactionId=previous.transactionId;existing.committedRevision=previous.revision;existing.persistenceReceiptId=previous.receiptId;existing.status='PROMOTABLE';existing.updatedAt=Date.now();this.save();return this.clone(existing);}const restored=await this.create(previous.issueId,restoredFiles.map(file=>({path:file.path,baselineContent:file.baselineContent,candidateContent:file.candidateContent,evidenceIds:file.evidenceIds})));const item=this.items.get(restored.workspaceId);if(!item)throw new Error('RESTORED_WORKSPACE_NOT_FOUND');item.transactionId=previous.transactionId;item.committedRevision=previous.revision;item.persistenceReceiptId=previous.receiptId;item.status='PROMOTABLE';item.updatedAt=Date.now();this.save();return this.clone(item);}
 recover(transactionId:string,action:'RESUME'|'ROLLBACK'):CandidateWorkspace|undefined{const transaction=candidateCommitTransactionService.get(transactionId);if(!transaction||transaction.status!=='RECOVERY_REQUIRED')return undefined;const item=this.items.get(transaction.workspaceId);if(action==='ROLLBACK'){candidateCommitTransactionService.rollback(transactionId,'RECOVERY_ROLLBACK');if(item){candidateWriteGuardService.rollback(item.writeGuardId);item.status='REJECTED';item.updatedAt=Date.now();this.save();return this.clone(item);}return undefined;}if(!item)return undefined;item.transactionId=transaction.transactionId;item.committedRevision=transaction.revision;item.persistenceReceiptId=transaction.receiptId;item.status='PROMOTABLE';item.updatedAt=Date.now();this.save();return this.clone(item);}

 setStatus(id:string,status:CandidateWorkspaceStatus){const item=this.items.get(id);if(!item)return undefined;item.status=status;item.updatedAt=Date.now();this.save();return this.clone(item);}
 get(id:string){const item=this.items.get(id);return item?this.clone(item):undefined;}
 list(){return [...this.items.values()].sort((a,b)=>b.updatedAt-a.updatedAt).map(x=>this.clone(x));}
 private reconcileRestoredWorkspaces():void{for(const workspace of this.items.values()){const targets=workspace.files.map(file=>file.path);const valid=candidateWriteGuardService.verify(workspace.writeGuardId,workspace.issueId,targets);if(!valid){workspace.status='REJECTED';workspace.updatedAt=Date.now();continue;}const guard=candidateWriteGuardService.get(workspace.writeGuardId);if(!guard||guard.baseSnapshotSha256!==workspace.baseSnapshotSha256||guard.candidateRevisionSha256!==workspace.candidateRevisionSha256){workspace.status='REJECTED';workspace.updatedAt=Date.now();}}this.save();}
 private clone(x:CandidateWorkspace):CandidateWorkspace{return {...x,files:x.files.map(f=>({...f,evidenceIds:[...f.evidenceIds]}))};}
 private async sha(text:string):Promise<string>{const data=new TextEncoder().encode(text);if(typeof crypto!=='undefined'&&crypto.subtle){const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('');}let h=2166136261;for(const value of data){h^=value;h=Math.imul(h,16777619);}return `fallback-${(h>>>0).toString(16).padStart(8,'0')}`;}
 private save(){storageService.setItem(KEY,JSON.stringify(this.list().slice(0,100)));}
 private load(){try{const raw=storageService.getItem(KEY);const all=raw?JSON.parse(raw):[];if(Array.isArray(all))for(const x of all)this.items.set(x.workspaceId,x);}catch{this.items.clear();}}
}
export const isolatedCandidateWorkspaceService=new IsolatedCandidateWorkspaceService();
