import { canonicalSha256Object } from './canonicalSha256Service';
export interface P181Image{width:number;height:number;rgba:Uint8Array;sourceSha256:string}
export interface P181FaceBox{x:number;y:number;width:number;height:number}
export interface P181Candidate{candidateId:string;width:number;height:number;rgba:Uint8Array;metrics:{sourceColorSimilarity:number;edgeRetention:number;foregroundContinuity:number;observedPixelRatio:number;artifactPenalty:number;borderLeakage:number;qualityScore:number};parameters:{yaw:number;pitch:number;feather:number;saturation:number};candidateSha256:string}
class IterativePersonQualityP181Service{
 generate(source:P181Image,face:P181FaceBox,yaw:number,pitch:number):P181Candidate{const candidates:P181Candidate[]=[];for(const feather of[4,8,14])for(const saturation of[.92,1,1.08])candidates.push(this.render(source,face,yaw,pitch,feather,saturation));return candidates.sort((a,b)=>b.metrics.qualityScore-a.metrics.qualityScore)[0]}
 private render(src:P181Image,face:P181FaceBox,yaw:number,pitch:number,feather:number,saturation:number):P181Candidate{const width=1024,height=1024,rgba=new Uint8Array(width*height*4),bg=this.borderMedian(src),mask=this.foregroundMask(src,bg,face),angle=yaw*Math.PI/180,compress=Math.max(.55,Math.cos(angle)),shift=Math.sin(angle)*.10,pitchShift=pitch/90*.08;let observed=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const nx=x/width,ny=y/height,ux=(nx-.5-shift)/(compress*.82)+.5,uy=(ny-.5)/.82+.5-pitchShift*(ny-.5);if(ux<0||uy<0||ux>1||uy>1)continue;const sx=ux*(src.width-1),sy=uy*(src.height-1),m=this.sampleMask(mask,src.width,src.height,sx,sy),edge=Math.min(1,m*feather),a=Math.max(0,Math.min(1,(m-.05)*feather));if(a<=0)continue;const c=this.sample(src,sx,sy),gray=.2126*c[0]+.7152*c[1]+.0722*c[2],shade=.94+.08*Math.cos((nx-.5)*Math.PI)+.06*Math.sin(angle)*(nx-.5);const di=(y*width+x)*4;for(let k=0;k<3;k++)rgba[di+k]=Math.max(0,Math.min(255,Math.round((gray+(c[k]-gray)*saturation)*shade)));rgba[di+3]=Math.round(255*a*edge);observed++;}this.fillSmallHoles(rgba,width,height);const metrics=this.metrics(src,rgba,width,height,observed),parameters={yaw,pitch,feather,saturation},seed={sourceSha256:src.sourceSha256,face,parameters,metrics},candidateSha256=canonicalSha256Object(seed);return{candidateId:`P181-${candidateSha256.slice(0,20)}`,width,height,rgba,metrics,parameters,candidateSha256}}
 private borderMedian(i:P181Image){const v:number[][]=[];for(let x=0;x<i.width;x+=8)for(const y of[0,i.height-1]){const p=(y*i.width+x)*4;v.push([i.rgba[p],i.rgba[p+1],i.rgba[p+2]])}for(let y=0;y<i.height;y+=8)for(const x of[0,i.width-1]){const p=(y*i.width+x)*4;v.push([i.rgba[p],i.rgba[p+1],i.rgba[p+2]])}return[0,1,2].map(k=>v.map(x=>x[k]).sort((a,b)=>a-b)[Math.floor(v.length/2)])}
 private foregroundMask(i:P181Image,bg:number[],face:P181FaceBox){
  const m=new Float32Array(i.width*i.height);
  const fx=(face.x+face.width*.5)/i.width,fy=(face.y+face.height*.52)/i.height,frx=Math.max(.10,face.width/i.width*.72),fry=Math.max(.12,face.height/i.height*.78);
  const tx=fx,ty=Math.min(.72,fy+face.height/i.height*2.0),trx=Math.min(.46,frx*2.35),try0=Math.min(.46,fry*2.2);
  for(let y=0;y<i.height;y++)for(let x=0;x<i.width;x++){
   const p=(y*i.width+x)*4,d=Math.hypot(i.rgba[p]-bg[0],i.rgba[p+1]-bg[1],i.rgba[p+2]-bg[2]);
   const nx=x/i.width,ny=y/i.height,head=1-((nx-fx)/frx)**2-((ny-fy)/fry)**2,torso=1-((nx-tx)/trx)**2-((ny-ty)/try0)**2;
   const anatomy=Math.max(head,torso);
   const boundary=Math.max(0,Math.min(1,anatomy*3.2));
   const contrast=Math.max(.18,Math.min(1,(d-8)/42));
   m[y*i.width+x]=boundary*contrast;
  }
  return m;
 }
 private sample(i:P181Image,x:number,y:number){const x0=Math.floor(x),y0=Math.floor(y),x1=Math.min(i.width-1,x0+1),y1=Math.min(i.height-1,y0+1),fx=x-x0,fy=y-y0,out=[0,0,0,0];for(const[xx,yy,w]of[[x0,y0,(1-fx)*(1-fy)],[x1,y0,fx*(1-fy)],[x0,y1,(1-fx)*fy],[x1,y1,fx*fy]] as number[][]){const p=(yy*i.width+xx)*4;for(let k=0;k<4;k++)out[k]+=i.rgba[p+k]*w}return out}
 private sampleMask(m:Float32Array,w:number,h:number,x:number,y:number){const xx=Math.max(0,Math.min(w-1,Math.round(x))),yy=Math.max(0,Math.min(h-1,Math.round(y)));return m[yy*w+xx]}
 private fillSmallHoles(r:Uint8Array,w:number,h:number){const copy=r.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;if(copy[i+3]>0)continue;let n=0,rr=0,g=0,b=0,a=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){const q=((y+yy)*w+x+xx)*4;if(copy[q+3]>180){n++;rr+=copy[q];g+=copy[q+1];b+=copy[q+2];a+=copy[q+3]}}if(n>=7){r[i]=rr/n;r[i+1]=g/n;r[i+2]=b/n;r[i+3]=a/n}}}
 private borderLeakage(out:Uint8Array,w:number,h:number){let opaque=0,total=0;const band=Math.max(4,Math.floor(Math.min(w,h)*.03));for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(x<band||y<band||x>=w-band||y>=h-band){total++;if(out[(y*w+x)*4+3]>32)opaque++;}return opaque/Math.max(1,total)}

 private metrics(src:P181Image,out:Uint8Array,w:number,h:number,observed:number){const hs=new Array(48).fill(0),ho=new Array(48).fill(0);let se=0,oe=0,oc=0,adj=0;for(let y=0;y<src.height;y+=4)for(let x=0;x<src.width;x+=4){const p=(y*src.width+x)*4;for(let k=0;k<3;k++)hs[k*16+(src.rgba[p+k]>>4)]++;if(x+4<src.width){const q=p+16;if(Math.abs(src.rgba[p]-src.rgba[q])+Math.abs(src.rgba[p+1]-src.rgba[q+1])+Math.abs(src.rgba[p+2]-src.rgba[q+2])>60)se++}}for(let y=0;y<h;y+=4)for(let x=0;x<w;x+=4){const p=(y*w+x)*4;if(out[p+3]<32)continue;oc++;for(let k=0;k<3;k++)ho[k*16+(out[p+k]>>4)]++;if(x+4<w){const q=p+16;if(out[q+3]>32&&Math.abs(out[p]-out[q])+Math.abs(out[p+1]-out[q+1])+Math.abs(out[p+2]-out[q+2])>60)oe++;adj++}}const ns=hs.reduce((a,b)=>a+b,0)||1,no=ho.reduce((a,b)=>a+b,0)||1;let l1=0;for(let i=0;i<48;i++)l1+=Math.abs(hs[i]/ns-ho[i]/no);const sourceColorSimilarity=Math.max(0,1-l1/2),edgeRetention=Math.min(1,oe/Math.max(1,se)*.3),observedPixelRatio=observed/(w*h),foregroundContinuity=Math.min(1,oc/Math.max(1,observed/16)),borderLeakage=this.borderLeakage(out,w,h),artifactPenalty=Math.max(0,.18-observedPixelRatio)*1.5+borderLeakage*.8,qualityScore=Math.max(0,Math.min(1,sourceColorSimilarity*.38+edgeRetention*.18+foregroundContinuity*.16+Math.min(1,observedPixelRatio/.42)*.18+(1-borderLeakage)*.10-artifactPenalty));return{sourceColorSimilarity,edgeRetention,foregroundContinuity,observedPixelRatio,artifactPenalty,borderLeakage,qualityScore}}
}
export const iterativePersonQualityP181Service=new IterativePersonQualityP181Service();
