import { canonicalSha256Object } from './canonicalSha256Service';
import type { LearnedPersonProfileP139 } from './multiPhotoPersonLearningP139Service';
export interface LearnedPersonP139Artifact{width:number;height:number;rgba:Uint8Array;png:Uint8Array;profileSha256:string;sourceSha256List:string[];appliedFields:string[];unresolvedFields:string[];renderReceiptSha256:string;pngSha256:string;}
const parse=(h:string)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];const shade=(h:string,n:number)=>'#'+parse(h).map(v=>Math.max(0,Math.min(255,Math.round(v+n))).toString(16).padStart(2,'0')).join('');
class Raster{rgba:Uint8Array;constructor(readonly width:number,readonly height:number){this.rgba=new Uint8Array(width*height*4);}px(x:number,y:number,c:string,a=1){x=Math.round(x);y=Math.round(y);if(x<0||y<0||x>=this.width||y>=this.height)return;const i=(y*this.width+x)*4,q=parse(c),ia=Math.max(0,Math.min(1,a));for(let k=0;k<3;k++)this.rgba[i+k]=Math.round(q[k]*ia+this.rgba[i+k]*(1-ia));this.rgba[i+3]=Math.max(this.rgba[i+3],Math.round(255*ia));}ellipse(cx:number,cy:number,rx:number,ry:number,c:string,a=1){for(let y=Math.floor(cy-ry);y<=cy+ry;y++)for(let x=Math.floor(cx-rx);x<=cx+rx;x++)if(((x-cx)/rx)**2+((y-cy)/ry)**2<=1)this.px(x,y,c,a);}softEllipse(cx:number,cy:number,rx:number,ry:number,c:string,a=1){for(let y=Math.floor(cy-ry*1.25);y<=cy+ry*1.25;y++)for(let x=Math.floor(cx-rx*1.25);x<=cx+rx*1.25;x++){const d=Math.sqrt(((x-cx)/rx)**2+((y-cy)/ry)**2);if(d<1.25)this.px(x,y,c,a*Math.max(0,Math.min(1,(1.25-d)*4)));}}poly(p:number[][],c:string,a=1){const ys=p.map(q=>q[1]);for(let y=Math.floor(Math.min(...ys));y<=Math.ceil(Math.max(...ys));y++){const xs=[] as number[];for(let i=0,j=p.length-1;i<p.length;j=i++){const u=p[i],v=p[j];if((u[1]>y)!==(v[1]>y))xs.push(u[0]+(y-u[1])*(v[0]-u[0])/(v[1]-u[1]));}xs.sort((u,v)=>u-v);for(let i=0;i+1<xs.length;i+=2)for(let x=Math.ceil(xs[i]);x<=Math.floor(xs[i+1]);x++)this.px(x,y,c,a);}}line(x0:number,y0:number,x1:number,y1:number,c:string,a=1,w=1){const n=Math.max(Math.abs(x1-x0),Math.abs(y1-y0),1);for(let i=0;i<=n;i++)this.ellipse(x0+(x1-x0)*i/n,y0+(y1-y0)*i/n,w/2,w/2,c,a);}}
class LearnedPersonRendererP139Service{
 async render(profile:LearnedPersonProfileP139,width=768,height=1152):Promise<LearnedPersonP139Artifact>{this.verify(profile);const n=(x:{value:number|null},d:number)=>x.value??d,s=(x:{value:string|null},d:string)=>x.value??d;const faceW=n(profile.face.widthRatio,.72),faceH=n(profile.face.heightRatio,.92),jaw=n(profile.face.jawTaper,.35),eyeGap=n(profile.face.eyeSpacing,.42),eyeSize=n(profile.face.eyeSize,.08),nose=n(profile.face.noseLength,.21),mouth=n(profile.face.mouthWidth,.34),hairVol=n(profile.hair.volume,.25),hairLen=n(profile.hair.length,.32),part=n(profile.hair.parting,.5),wave=n(profile.hair.wave,.15),heads=n(profile.body.headToBody,.14),shoulders=n(profile.body.shoulderRatio,.33),torso=n(profile.body.torsoRatio,.31),arms=n(profile.body.armRatio,.31),legs=n(profile.body.legRatio,.43);const skin=s(profile.appearance.surfaceColor,'#d5aa8b'),hair=s(profile.hair.baseColor,'#302a2a'),hairHi=s(profile.hair.highlightColor,shade(hair,38)),cloth=s(profile.appearance.garmentColor,'#526b83'),pants=s(profile.appearance.pantsColor,'#333e4d'),shoe=s(profile.appearance.shoeColor,'#22252b'),r=new Raster(width,height),cx=width*.5,headH=height*heads,headW=headH*faceW,top=height*.055,neckY=top+headH*.92,shoulderY=neckY+height*.065,hipY=shoulderY+height*torso,footY=Math.min(height*.94,hipY+height*legs),shoulderW=width*shoulders*.52;
 r.softEllipse(cx+width*.025,footY-height*.015,width*.19,height*.025,'#000000',.28);r.softEllipse(cx+width*.03,(shoulderY+hipY)/2,shoulderW*.62,(hipY-shoulderY)*.6,'#000000',.12);
 const hairRy=headH*(.55+hairVol*.18);r.ellipse(cx,top+headH*.48,headW*(.55+hairVol*.12),hairRy,hair);for(let i=0;i<9;i++){const t=i/8,x=cx-headW*.44+t*headW*.88,y=top+headH*(.08+.08*Math.sin(t*Math.PI*(2+wave*2)));r.line(cx+headW*(part-.5)*.5,top+headH*.08,x,y+headH*hairLen*.55,hairHi,.28,width/300);}
 const faceCy=top+headH*.5;r.ellipse(cx,faceCy,headW*.50,headH*.46,skin);r.ellipse(cx-headW*.35,faceCy+headH*.06,headW*.055,headH*.12,shade(skin,-12));r.ellipse(cx+headW*.35,faceCy+headH*.06,headW*.055,headH*.12,shade(skin,-12));r.softEllipse(cx+headW*.17,faceCy-headH*.03,headW*.20,headH*.32,'#ffffff',.10);
 const ey=faceCy-headH*.08,eg=headW*eyeGap*.5,esz=headW*eyeSize;r.ellipse(cx-eg,ey,esz*1.6,esz,'#f4f2ec');r.ellipse(cx+eg,ey,esz*1.6,esz,'#f4f2ec');r.ellipse(cx-eg,ey,esz*.58,esz*.72,'#3b322c');r.ellipse(cx+eg,ey,esz*.58,esz*.72,'#3b322c');r.line(cx-eg-esz*1.8,ey-headH*.055,cx-eg+esz*1.8,ey-headH*.06,hair,.8,width/420);r.line(cx+eg-esz*1.8,ey-headH*.06,cx+eg+esz*1.8,ey-headH*.055,hair,.8,width/420);r.line(cx,ey+headH*.06,cx-headW*.025,ey+headH*nose,shade(skin,-42),.55,width/500);r.line(cx-headW*mouth/2,faceCy+headH*.26,cx+headW*mouth/2,faceCy+headH*.26,shade(skin,-58),.8,width/450);
 const neckW=headW*(.25+jaw*.08);r.poly([[cx-neckW,neckY-headH*.06],[cx+neckW,neckY-headH*.06],[cx+neckW*.8,shoulderY],[cx-neckW*.8,shoulderY]],skin);r.poly([[cx-shoulderW,shoulderY],[cx+shoulderW,shoulderY],[cx+shoulderW*.72,hipY],[cx-shoulderW*.72,hipY]],cloth);for(let i=0;i<7;i++){const t=i/6;r.poly([[cx-shoulderW+t*shoulderW*2,shoulderY],[cx-shoulderW+(t+.16)*shoulderW*2,shoulderY],[cx-shoulderW*.72+(t+.16)*shoulderW*1.44,hipY],[cx-shoulderW*.72+t*shoulderW*1.44,hipY]],shade(cloth,Math.round((t-.5)*55)),.55);}
 const handY=shoulderY+height*arms;r.poly([[cx-shoulderW,shoulderY+10],[cx-shoulderW*.72,shoulderY+height*.035],[cx-shoulderW*1.18,handY],[cx-shoulderW*1.42,handY-height*.02]],cloth);r.poly([[cx+shoulderW,shoulderY+10],[cx+shoulderW*.72,shoulderY+height*.035],[cx+shoulderW*1.18,handY],[cx+shoulderW*1.42,handY-height*.02]],cloth);r.ellipse(cx-shoulderW*1.30,handY,headW*.09,headH*.11,skin);r.ellipse(cx+shoulderW*1.30,handY,headW*.09,headH*.11,skin);
 const gap=width*.022,legW=shoulderW*.43;r.poly([[cx-gap-legW,hipY],[cx-gap,hipY],[cx-gap*.8,footY],[cx-gap-legW*.9,footY]],pants);r.poly([[cx+gap,hipY],[cx+gap+legW,hipY],[cx+gap+legW*.9,footY],[cx+gap*.8,footY]],shade(pants,12));r.ellipse(cx-gap-legW*.42,footY+height*.012,legW*.62,height*.025,shoe);r.ellipse(cx+gap+legW*.42,footY+height*.012,legW*.62,height*.025,shoe);r.line(cx-shoulderW*.7,hipY,cx+shoulderW*.7,hipY,shade(cloth,-55),.45,width/260);
 const applied=['face.widthRatio','face.heightRatio','face.jawTaper','face.eyeSpacing','face.eyeSize','face.noseLength','face.mouthWidth','hair.volume','hair.length','hair.parting','hair.wave','hair.baseColor','hair.highlightColor','body.headToBody','body.shoulderRatio','body.torsoRatio','body.armRatio','body.legRatio','appearance.surfaceColor','appearance.garmentColor','appearance.pantsColor','appearance.shoeColor'].filter(x=>!profile.unresolvedFeatures.includes(x));const sourceSha256List=profile.sourceObservations.map(x=>x.sourceSha256);const receipt={profileSha256:profile.profileSha256,sourceSha256List,appliedFields:applied,unresolvedFields:profile.unresolvedFeatures,width,height};const png=await this.png(r);return{width,height,rgba:r.rgba,png,profileSha256:profile.profileSha256,sourceSha256List,appliedFields:applied,unresolvedFields:profile.unresolvedFeatures,renderReceiptSha256:canonicalSha256Object(receipt),pngSha256:await this.sha(png)};}
 private verify(p:LearnedPersonProfileP139){const c=structuredClone(p);c.profileSha256='';if(canonicalSha256Object(c)!==p.profileSha256)throw new Error('P139_PROFILE_SHA_MISMATCH');}private async png(r:Raster){const raw=new Uint8Array((r.width*4+1)*r.height);for(let y=0;y<r.height;y++){const o=y*(r.width*4+1);raw[o]=0;raw.set(r.rgba.subarray(y*r.width*4,(y+1)*r.width*4),o+1);}const cs=new CompressionStream('deflate'),w=cs.writable.getWriter();await w.write(raw.slice().buffer);await w.close();const d=new Uint8Array(await new Response(cs.readable).arrayBuffer()),sig=Uint8Array.from([137,80,78,71,13,10,26,10]),ih=new Uint8Array(13),v=new DataView(ih.buffer);v.setUint32(0,r.width);v.setUint32(4,r.height);ih.set([8,6,0,0,0],8);return this.cat(sig,this.chunk('IHDR',ih),this.chunk('IDAT',d),this.chunk('IEND',new Uint8Array()));}private chunk(t:string,d:Uint8Array){const b=new TextEncoder().encode(t),o=new Uint8Array(12+d.length),v=new DataView(o.buffer);v.setUint32(0,d.length);o.set(b,4);o.set(d,8);v.setUint32(8+d.length,this.crc(this.cat(b,d)));return o;}private crc(d:Uint8Array){let c=0xffffffff;for(const b of d){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}private cat(...a:Uint8Array[]){const o=new Uint8Array(a.reduce((n,x)=>n+x.length,0));let p=0;for(const x of a){o.set(x,p);p+=x.length;}return o;}private async sha(d:Uint8Array){const h=await crypto.subtle.digest('SHA-256',d.slice().buffer);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}}
export const learnedPersonRendererP139Service=new LearnedPersonRendererP139Service();
