import { canonicalSha256Object } from './canonicalSha256Service';
import type { RgbaImage } from './richVisualProductionRendererService';
import type { BodyGeometryEstimate, Scene25D } from './visualLearningBody25dService';
import type { VisualKnowledgeMemory } from './visualProjectLearningCompositionService';

export interface LearnedGenerationRequest { width:number; height:number; body?:BodyGeometryEstimate; scene?:Scene25D; memories:VisualKnowledgeMemory[]; preserveSource:number; creativity:number; }
export interface LearnedGenerationPlan { bodyScale:{shoulder:number;waist:number;hip:number;torso:number;leg:number}; palette:string[]; texture:{grain:number;contrast:number;detail:number}; depthEnabled:boolean; memoryIds:string[]; confidence:number; planSha256:string; }
export interface LayerImage25D { layerId:string; image:RgbaImage; parallax:number; occlusionOrder:number; }
export interface Render25DResult extends RgbaImage { cameraX:number;cameraY:number;sourceLayerSha256List:string[];renderSha256:string; }
const clamp=(v:number)=>Math.max(0,Math.min(255,Math.round(v)));
class LearnedVisualGeneration25dService {
 plan(request:LearnedGenerationRequest):LearnedGenerationPlan { if(request.width<1||request.height<1)throw new Error('INVALID_GENERATION_SIZE');if(request.preserveSource<0||request.preserveSource>1||request.creativity<0||request.creativity>1)throw new Error('GENERATION_WEIGHT_OUT_OF_RANGE');const usable=request.memories.filter(m=>m.status!=='PROVISIONAL'||m.confidence>=.72).sort((a,b)=>b.confidence-a.confidence);const body=request.body;const defaults={shoulder:.24,waist:.18,hip:.2,torso:.31,leg:.48};const bodyScale={shoulder:body?body.shoulderToHeight:defaults.shoulder,waist:body?body.waistToHeight:defaults.waist,hip:body?body.hipToHeight:defaults.hip,torso:body?body.torsoToHeight:defaults.torso,leg:body?body.legToHeight:defaults.leg};const colors:string[]=[];let grain=.08,contrast=.45,detail=.5;for(const memory of usable){const palette=memory.payload.palette;if(Array.isArray(palette))for(const value of palette)if(typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)&&!colors.includes(value))colors.push(value);if(typeof memory.payload.grain==='number')grain=Math.max(grain,Math.min(1,memory.payload.grain));if(typeof memory.payload.contrast==='number')contrast=Math.max(contrast,Math.min(1,memory.payload.contrast));if(typeof memory.payload.detail==='number')detail=Math.max(detail,Math.min(1,memory.payload.detail));}const confidence=usable.length?usable.reduce((n,m)=>n+m.confidence,0)/usable.length:0;const seed={bodyScale,palette:colors.slice(0,16),texture:{grain,contrast,detail},depthEnabled:Boolean(request.scene),memoryIds:usable.map(m=>m.memoryId),confidence};return{...seed,planSha256:canonicalSha256Object({...seed,width:request.width,height:request.height,preserveSource:request.preserveSource,creativity:request.creativity})}; }
 render25D(layers:LayerImage25D[],width:number,height:number,cameraX:number,cameraY:number):Render25DResult {if(!layers.length)throw new Error('LAYERS_REQUIRED');if(width<1||height<1)throw new Error('INVALID_RENDER_SIZE');const out=new Uint8Array(width*height*4);const ordered=[...layers].sort((a,b)=>a.occlusionOrder-b.occlusionOrder);const hashes:string[]=[];for(const layer of ordered){this.validateImage(layer.image);hashes.push(canonicalSha256Object({layerId:layer.layerId,width:layer.image.width,height:layer.image.height,rgbaLength:layer.image.rgba.length,parallax:layer.parallax}));const ox=Math.round(cameraX*layer.parallax),oy=Math.round(cameraY*layer.parallax);this.composite(out,width,height,layer.image,ox,oy);}const seed={width,height,cameraX,cameraY,sourceLayerSha256List:hashes};return{width,height,rgba:out,cameraX,cameraY,sourceLayerSha256List:hashes,renderSha256:canonicalSha256Object(seed)}; }
 applyLearnedTexture(image:RgbaImage,plan:LearnedGenerationPlan,seed=1):RgbaImage {this.validateImage(image);const out=image.rgba.slice();let state=seed>>>0;const random=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296;};const strength=plan.texture.grain*12;for(let i=0;i<out.length;i+=4){const n=(random()-.5)*strength;for(let c=0;c<3;c++)out[i+c]=clamp((out[i+c]-128)*(1+plan.texture.contrast*.08)+128+n);}return{width:image.width,height:image.height,rgba:out}; }
 private composite(dst:Uint8Array,dw:number,dh:number,src:RgbaImage,ox:number,oy:number){for(let y=0;y<src.height;y++){const dy=y+oy;if(dy<0||dy>=dh)continue;for(let x=0;x<src.width;x++){const dx=x+ox;if(dx<0||dx>=dw)continue;const si=(y*src.width+x)*4,di=(dy*dw+dx)*4,a=src.rgba[si+3]/255;if(a<=0)continue;const da=dst[di+3]/255,oa=a+da*(1-a);for(let c=0;c<3;c++)dst[di+c]=oa?clamp((src.rgba[si+c]*a+dst[di+c]*da*(1-a))/oa):0;dst[di+3]=clamp(oa*255);}}}
 private validateImage(image:RgbaImage){if(image.width<1||image.height<1||image.rgba.length!==image.width*image.height*4)throw new Error('INVALID_RGBA_IMAGE');}
}
export const learnedVisualGeneration25dService=new LearnedVisualGeneration25dService();
