import { canonicalSha256 } from './canonicalSha256Service';
import { reviewerReliabilityService } from './reviewerReliabilityService';
export type ConsensusVerdict='ACCEPT'|'REJECT'|'REQUEST_CHANGES'|'HOLD';
export interface ReviewerOpinion{externalReviewId:string;reviewerId:string;domain:string;candidateManifestSha256:string;verdict:ConsensusVerdict;reasons:string[];requestedChanges:string[];}
export interface ReviewConsensus{consensusId:string;candidateManifestSha256:string;verdict:ConsensusVerdict;confidence:number;quorumReached:boolean;reviewCount:number;weightedScores:Record<ConsensusVerdict,number>;conflicts:string[];mergedReasons:string[];mergedRequestedChanges:string[];sourceReviewIds:string[];}
class MultiReviewerConsensusService{
 build(input:{candidateManifestSha256:string;opinions:ReviewerOpinion[];minimumReviewers?:number}):ReviewConsensus{const valid=input.opinions.filter(row=>row.candidateManifestSha256===input.candidateManifestSha256);const reviewers=new Set(valid.map(row=>row.reviewerId));const scores:Record<ConsensusVerdict,number>={ACCEPT:0,REJECT:0,REQUEST_CHANGES:0,HOLD:0};for(const opinion of valid)scores[opinion.verdict]+=reviewerReliabilityService.get(opinion.reviewerId,opinion.domain).reliability;const ranked=(Object.entries(scores) as Array<[ConsensusVerdict,number]>).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));const total=ranked.reduce((sum,row)=>sum+row[1],0);const minimum=input.minimumReviewers??2;const quorumReached=reviewers.size>=minimum;const margin=ranked[0][1]-(ranked[1]?.[1]||0);let verdict:ConsensusVerdict=ranked[0][0];if(!quorumReached||total===0||margin<0.25)verdict='HOLD';const conflicts=valid.length>1&&new Set(valid.map(row=>row.verdict)).size>1?[...new Set(valid.map(row=>row.verdict))].sort():[];const base={candidateManifestSha256:input.candidateManifestSha256,verdict,confidence:total?ranked[0][1]/total:0,quorumReached,reviewCount:valid.length,weightedScores:scores,conflicts,mergedReasons:[...new Set(valid.flatMap(row=>row.reasons))],mergedRequestedChanges:[...new Set(valid.flatMap(row=>row.requestedChanges))],sourceReviewIds:valid.map(row=>row.externalReviewId).sort()};return{consensusId:`CONSENSUS-${canonicalSha256(base).slice(0,24)}`,...base};}
}
export const multiReviewerConsensusService=new MultiReviewerConsensusService();
