import { canonicalSha256Object } from './canonicalSha256Service';
export type PhotoView='FRONT'|'LEFT'|'RIGHT'|'BACK'|'THREE_QUARTER'|'FULL_BODY'|'DETAIL';
export interface ObservedValue<T>{value:T;confidence:number;observed:boolean;sourceSha256:string;}
export interface PersonPhotoObservation{observationId:string;sourceSha256:string;view:PhotoView;width:number;height:number;quality:number;occlusion:number;lightingBias:[number,number,number];face:{widthRatio:ObservedValue<number>;heightRatio:ObservedValue<number>;jawTaper:ObservedValue<number>;eyeSpacing:ObservedValue<number>;eyeSize:ObservedValue<number>;noseLength:ObservedValue<number>;mouthWidth:ObservedValue<number>};hair:{volume:ObservedValue<number>;length:ObservedValue<number>;parting:ObservedValue<number>;wave:ObservedValue<number>;baseColor:ObservedValue<string>;highlightColor:ObservedValue<string>};body:{headToBody:ObservedValue<number>;shoulderRatio:ObservedValue<number>;torsoRatio:ObservedValue<number>;armRatio:ObservedValue<number>;legRatio:ObservedValue<number>};appearance:{surfaceColor:ObservedValue<string>;garmentColor:ObservedValue<string>;pantsColor:ObservedValue<string>;shoeColor:ObservedValue<string>};observationSha256:string;}
export interface FusedField<T>{value:T|null;confidence:number;sources:string[];state:'OBSERVED'|'CONFLICTING'|'UNKNOWN';spread:number;}
export interface LearnedPersonProfileP139{profileId:string;subject:string;revision:number;sourceObservations:PersonPhotoObservation[];face:Record<keyof PersonPhotoObservation['face'],FusedField<number>>;hair:{volume:FusedField<number>;length:FusedField<number>;parting:FusedField<number>;wave:FusedField<number>;baseColor:FusedField<string>;highlightColor:FusedField<string>};body:Record<keyof PersonPhotoObservation['body'],FusedField<number>>;appearance:Record<keyof PersonPhotoObservation['appearance'],FusedField<string>>;unresolvedFeatures:string[];evidenceCoverage:number;createdAt:number;updatedAt:number;profileSha256:string;}
const clamp=(v:number)=>Math.max(0,Math.min(1,v));
class MultiPhotoPersonLearningP139Service{
 createObservation(input:Omit<PersonPhotoObservation,'observationSha256'>):PersonPhotoObservation{this.validateObservation(input);return{...structuredClone(input),observationSha256:canonicalSha256Object(input)};}
 learn(subject:string,observations:PersonPhotoObservation[],previous?:LearnedPersonProfileP139):LearnedPersonProfileP139{if(!subject.trim()||!observations.length)throw new Error('P139_PHOTO_OBSERVATIONS_REQUIRED');for(const o of observations)this.verifyObservation(o);const all=previous?[...previous.sourceObservations,...observations]:observations;const unique=[...new Map(all.map(x=>[x.sourceSha256,x])).values()];const num=(path:'face'|'body',key:string)=>this.fuseNumber(unique.map(o=>(o as any)[path][key]),unique);const color=(path:'hair'|'appearance',key:string)=>this.fuseColor(unique.map(o=>(o as any)[path][key]),unique);const face:any={},body:any={};for(const k of ['widthRatio','heightRatio','jawTaper','eyeSpacing','eyeSize','noseLength','mouthWidth'])face[k]=num('face',k);for(const k of ['headToBody','shoulderRatio','torsoRatio','armRatio','legRatio'])body[k]=num('body',k);const hair={volume:numAny(unique,'hair','volume'),length:numAny(unique,'hair','length'),parting:numAny(unique,'hair','parting'),wave:numAny(unique,'hair','wave'),baseColor:color('hair','baseColor'),highlightColor:color('hair','highlightColor')};const appearance:any={};for(const k of ['surfaceColor','garmentColor','pantsColor','shoeColor'])appearance[k]=color('appearance',k);const fields=[...Object.entries(face).map(([k,v])=>[`face.${k}`,v]),...Object.entries(hair).map(([k,v])=>[`hair.${k}`,v]),...Object.entries(body).map(([k,v])=>[`body.${k}`,v]),...Object.entries(appearance).map(([k,v])=>[`appearance.${k}`,v])] as [string,FusedField<unknown>][];const unresolvedFeatures=fields.filter(([,v])=>v.state!=='OBSERVED').map(([k])=>k);const evidenceCoverage=fields.reduce((n,[,v])=>n+v.confidence,0)/fields.length;const now=Date.now();const p:LearnedPersonProfileP139={profileId:previous?.profileId??`PERSON-${canonicalSha256Object({subject}).slice(0,20)}`,subject,revision:(previous?.revision??0)+1,sourceObservations:unique,face,hair,body,appearance,unresolvedFeatures,evidenceCoverage,createdAt:previous?.createdAt??now,updatedAt:now,profileSha256:''};return this.seal(p);}
 serialize(profile:LearnedPersonProfileP139){this.verify(profile);const record={format:'MIKI_PERSON_PROFILE_P139',profile,recordSha256:canonicalSha256Object(profile)};return JSON.stringify({...record,envelopeSha256:canonicalSha256Object(record)});}
 deserialize(raw:string){const e=JSON.parse(raw);if(e.format!=='MIKI_PERSON_PROFILE_P139'||canonicalSha256Object({format:e.format,profile:e.profile,recordSha256:e.recordSha256})!==e.envelopeSha256||canonicalSha256Object(e.profile)!==e.recordSha256)throw new Error('P139_PERSISTENT_PROFILE_TAMPERED');this.verify(e.profile);return e.profile as LearnedPersonProfileP139;}
 private fuseNumber(values:ObservedValue<number>[],obs:PersonPhotoObservation[]):FusedField<number>{const a=values.map((v,i)=>({v:v.value,w:v.observed?clamp(v.confidence)*clamp(obs[i].quality)*(1-clamp(obs[i].occlusion)):0,s:v.sourceSha256})).filter(x=>x.w>0);if(!a.length)return{value:null,confidence:0,sources:[],state:'UNKNOWN',spread:0};const sw=a.reduce((n,x)=>n+x.w,0),m=a.reduce((n,x)=>n+x.v*x.w,0)/sw,spread=Math.sqrt(a.reduce((n,x)=>n+(x.v-m)**2*x.w,0)/sw);return{value:m,confidence:clamp(sw/a.length*(1-Math.min(1,spread/.2))),sources:a.map(x=>x.s),state:spread>.18?'CONFLICTING':'OBSERVED',spread};}
 private fuseColor(values:ObservedValue<string>[],obs:PersonPhotoObservation[]):FusedField<string>{const a=values.map((v,i)=>({v:v.value,w:v.observed?clamp(v.confidence)*clamp(obs[i].quality)*(1-clamp(obs[i].occlusion)):0,s:v.sourceSha256})).filter(x=>x.w>0);if(!a.length)return{value:null,confidence:0,sources:[],state:'UNKNOWN',spread:0};const parse=(h:string)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];const sw=a.reduce((n,x)=>n+x.w,0),rgb=[0,1,2].map(i=>Math.round(a.reduce((n,x)=>n+parse(x.v)[i]*x.w,0)/sw)),value='#'+rgb.map(x=>x.toString(16).padStart(2,'0')).join('');const spread=a.reduce((n,x)=>n+Math.hypot(...parse(x.v).map((y,i)=>y-rgb[i]))*x.w,0)/sw/441.67;return{value,confidence:clamp(sw/a.length*(1-spread)),sources:a.map(x=>x.s),state:spread>.24?'CONFLICTING':'OBSERVED',spread};}
 private seal(p:LearnedPersonProfileP139){p.profileSha256='';p.profileSha256=canonicalSha256Object(p);return p;}private verify(p:LearnedPersonProfileP139){const c=structuredClone(p);c.profileSha256='';if(canonicalSha256Object(c)!==p.profileSha256)throw new Error('P139_PROFILE_SHA_MISMATCH');}private verifyObservation(o:PersonPhotoObservation){const c={...o} as any;delete c.observationSha256;if(canonicalSha256Object(c)!==o.observationSha256)throw new Error('P139_OBSERVATION_SHA_MISMATCH');}private validateObservation(o:any){if(!/^[a-f0-9]{64}$/i.test(o.sourceSha256)||o.width<1||o.height<1||o.quality<0||o.quality>1||o.occlusion<0||o.occlusion>1)throw new Error('P139_OBSERVATION_INVALID');}
}
const numAny=(obs:PersonPhotoObservation[],path:'hair',key:string)=>{const values=obs.map(o=>(o as any)[path][key]) as ObservedValue<number>[];const s=new MultiPhotoPersonLearningP139Service() as any;return s.fuseNumber(values,obs) as FusedField<number>;};
export const multiPhotoPersonLearningP139Service=new MultiPhotoPersonLearningP139Service();
