import { canonicalSha256Object } from './canonicalSha256Service';
import type { FaceFeatureEvidenceP146 } from './realPhotoFaceFeatureP146Service';
import type { ObservedOnlyProfileP146 } from './observedOnlyProfileP146Service';

export interface P147Artifact {
  width:number; height:number; png:Uint8Array; pngSha256:string;
  evidenceSha256:string; observedProfileSha256:string; receiptSha256:string;
  connectedFields:string[]; suppressedRegions:string[];
}
const rgb=(h:string)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
const mix=(a:string,b:string,t:number)=>'#'+rgb(a).map((v,i)=>Math.round(v*(1-t)+rgb(b)[i]*t).toString(16).padStart(2,'0')).join('');
class Raster{p:Uint8Array;constructor(readonly w:number,readonly h:number){this.p=new Uint8Array(w*h*4);}dot(x:number,y:number,c:string,a=1,r=1){const q=rgb(c);for(let yy=Math.floor(y-r);yy<=y+r;yy++)for(let xx=Math.floor(x-r);xx<=x+r;xx++){if(xx<0||yy<0||xx>=this.w||yy>=this.h||Math.hypot(xx-x,yy-y)>r)continue;const i=(yy*this.w+xx)*4;for(let k=0;k<3;k++)this.p[i+k]=Math.round(q[k]*a+this.p[i+k]*(1-a));this.p[i+3]=Math.max(this.p[i+3],Math.round(255*a));}}ellipse(cx:number,cy:number,rx:number,ry:number,c:string,a=1){for(let y=cy-ry;y<=cy+ry;y++)for(let x=cx-rx;x<=cx+rx;x++)if(((x-cx)/rx)**2+((y-cy)/ry)**2<=1)this.dot(x,y,c,a,.7);}poly(q:{x:number;y:number}[],c:string,a=1){const ys=q.map(v=>v.y);for(let y=Math.floor(Math.min(...ys));y<=Math.ceil(Math.max(...ys));y++){const xs:number[]=[];for(let i=0,j=q.length-1;i<q.length;j=i++){const u=q[i],v=q[j];if((u.y>y)!==(v.y>y))xs.push(u.x+(y-u.y)*(v.x-u.x)/(v.y-u.y));}xs.sort((a,b)=>a-b);for(let i=0;i+1<xs.length;i+=2)for(let x=Math.ceil(xs[i]);x<=xs[i+1];x++)this.dot(x,y,c,a,.7);}}line(a:{x:number;y:number},b:{x:number;y:number},c:string,r:number,alpha=1){const n=Math.max(2,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)));for(let i=0;i<=n;i++){const t=i/n;this.dot(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,c,alpha,r);}}}
class ObservedFaceConnectedRendererP147Service{
 async render(profile:ObservedOnlyProfileP146,e:FaceFeatureEvidenceP146):Promise<P147Artifact>{this.verify(profile,e);const w=768,h=768,r=new Raster(w,h),skin=profile.palette.surface,hair=profile.palette.hair,garment=profile.palette.garment,skinS=mix(skin,'#3a241b',.23),skinH=mix(skin,'#ffffff',.20),hairS=mix(hair,'#111111',.18),garmentS=mix(garment,'#201b20',.22),garmentH=mix(garment,'#ffffff',.18);const fw=w*.30,fh=h*.38,cx=w*.50,cy=h*.28,jaw=e.ratios.jawTaper,eyeGap=fw*e.ratios.eyeSpacing*.46,eyeR=Math.max(4,fw*e.ratios.eyeSize*.35),noseLen=fh*e.ratios.noseLength,mouthW=fw*e.ratios.mouthWidth;
 r.ellipse(cx,h*.72,w*.25,h*.025,'#000000',.20);r.poly([{x:w*.25,y:h*.50},{x:w*.75,y:h*.50},{x:w*.69,y:h*.98},{x:w*.31,y:h*.98}],garment);for(let i=0;i<8;i++){const x=w*(.31+i*.048);r.poly([{x,y:h*.52},{x:x+w*.04,y:h*.52},{x:x+w*.02,y:h*.96},{x:x-w*.005,y:h*.96}],i%2?garmentH:garmentS,.15);}r.poly([{x:w*.40,y:h*.49},{x:w*.50,y:h*.59},{x:w*.60,y:h*.49},{x:w*.55,y:h*.46},{x:w*.50,y:h*.54},{x:w*.45,y:h*.46}],garmentH,.55);
 r.ellipse(cx-w*.19,h*.67,w*.06,h*.22,garmentS);r.ellipse(cx+w*.19,h*.67,w*.06,h*.22,garmentH,.85);
 r.poly([{x:cx-fw*.48,y:cy-fh*.18},{x:cx-fw*.40,y:cy+fh*.31},{x:cx-fw*jaw,y:cy+fh*.48},{x:cx,y:cy+fh*.57},{x:cx+fw*jaw,y:cy+fh*.48},{x:cx+fw*.40,y:cy+fh*.31},{x:cx+fw*.48,y:cy-fh*.18},{x:cx+fw*.28,y:cy-fh*.48},{x:cx-fw*.28,y:cy-fh*.48}],skin);r.ellipse(cx-fw*.28,cy,fw*.23,fh*.37,skinS,.12);r.ellipse(cx+fw*.22,cy-fh*.04,fw*.18,fh*.29,skinH,.13);r.ellipse(cx-fw*.49,cy,fw*.07,fh*.16,skinS);r.ellipse(cx+fw*.49,cy,fw*.07,fh*.16,skinS);
 const ey=cy-fh*.10;for(const side of [-1,1]){const ex=cx+side*eyeGap;r.ellipse(ex,ey,eyeR*1.8,eyeR,'#f2eee8');r.ellipse(ex,ey,eyeR*.58,eyeR*.76,mix(hair,'#5a3d2b',.35));r.ellipse(ex,ey,eyeR*.24,eyeR*.38,'#171413');r.line({x:ex-eyeR*2,y:ey-eyeR*2.5},{x:ex+eyeR*2,y:ey-eyeR*2.8},hairS,Math.max(2,eyeR*.32),.85);}
 const noseY=ey+noseLen;r.line({x:cx,y:ey+eyeR},{x:cx-fw*.025,y:noseY},skinS,Math.max(2,fw*.009),.5);r.line({x:cx-fw*.055,y:noseY},{x:cx+fw*.045,y:noseY+fh*.012},skinS,Math.max(1,fw*.006),.45);const mouthY=cy+fh*.28;r.line({x:cx-mouthW*.5,y:mouthY},{x:cx+mouthW*.5,y:mouthY},mix(skinS,'#9a4855',.55),Math.max(2,fw*.009),.8);r.line({x:cx-mouthW*.38,y:mouthY+fh*.018},{x:cx+mouthW*.38,y:mouthY+fh*.018},mix(skin,'#c66e77',.52),Math.max(2,fw*.010),.66);
 r.ellipse(cx,cy-fh*.46,fw*.54,fh*.18,hair);r.poly([{x:cx-fw*.53,y:cy-fh*.42},{x:cx-fw*.12,y:cy-fh*.49},{x:cx-fw*.28,y:cy+fh*.31},{x:cx-fw*.49,y:cy+fh*.17}],hair);r.poly([{x:cx+fw*.53,y:cy-fh*.42},{x:cx+fw*.12,y:cy-fh*.49},{x:cx+fw*.28,y:cy+fh*.31},{x:cx+fw*.49,y:cy+fh*.17}],hair);for(let i=0;i<8;i++){const side=i<4?-1:1,t=(i%4)/3;r.line({x:cx+side*fw*.04,y:cy-fh*.45},{x:cx+side*fw*(.18+.24*t),y:cy+fh*(.02+.33*t)},i%2?hairS:mix(hair,'#ffffff',.12),Math.max(2,fw*.012),.5);}
 const connectedFields=['face.eyeSpacing','face.eyeSize','face.noseLength','face.mouthWidth','face.jawTaper','palette.hair','palette.surface','palette.garment','scope.UPPER_BODY','suppressed.lower-arms','suppressed.hands','suppressed.legs','suppressed.feet'];const png=await this.png(w,h,r.p),receipt={evidenceSha256:e.evidenceSha256,observedProfileSha256:profile.profileSha256,sourceSha256:e.sourceSha256,connectedFields,suppressedRegions:profile.suppressedRegions,width:w,height:h};return{width:w,height:h,png,pngSha256:await this.sha(png),evidenceSha256:e.evidenceSha256,observedProfileSha256:profile.profileSha256,receiptSha256:canonicalSha256Object(receipt),connectedFields,suppressedRegions:profile.suppressedRegions};}
 private verify(p:ObservedOnlyProfileP146,e:FaceFeatureEvidenceP146){const pc=structuredClone(p);pc.profileSha256='';if(canonicalSha256Object(pc)!==p.profileSha256)throw new Error('P147_PROFILE_SHA_MISMATCH');const ec=structuredClone(e);ec.evidenceSha256='';if(canonicalSha256Object(ec)!==e.evidenceSha256||p.evidenceSha256!==e.evidenceSha256)throw new Error('P147_EVIDENCE_SHA_MISMATCH');}
 private async png(w:number,h:number,p:Uint8Array){const raw=new Uint8Array((w*4+1)*h);for(let y=0;y<h;y++){const o=y*(w*4+1);raw[o]=0;raw.set(p.subarray(y*w*4,(y+1)*w*4),o+1);}const cs=new CompressionStream('deflate'),wr=cs.writable.getWriter();await wr.write(raw.slice().buffer);await wr.close();const d=new Uint8Array(await new Response(cs.readable).arrayBuffer()),sig=Uint8Array.from([137,80,78,71,13,10,26,10]),ih=new Uint8Array(13),v=new DataView(ih.buffer);v.setUint32(0,w);v.setUint32(4,h);ih.set([8,6,0,0,0],8);return this.cat(sig,this.chunk('IHDR',ih),this.chunk('IDAT',d),this.chunk('IEND',new Uint8Array()));}private chunk(t:string,d:Uint8Array){const b=new TextEncoder().encode(t),o=new Uint8Array(12+d.length),v=new DataView(o.buffer);v.setUint32(0,d.length);o.set(b,4);o.set(d,8);v.setUint32(8+d.length,this.crc(this.cat(b,d)));return o;}private crc(d:Uint8Array){let c=0xffffffff;for(const b of d){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}private cat(...a:Uint8Array[]){const o=new Uint8Array(a.reduce((n,x)=>n+x.length,0));let p=0;for(const x of a){o.set(x,p);p+=x.length;}return o;}private async sha(d:Uint8Array){const h=await crypto.subtle.digest('SHA-256',d.slice().buffer);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}}
export const observedFaceConnectedRendererP147Service=new ObservedFaceConnectedRendererP147Service();
