import { storageService } from '../../../services/storageService';
import { canonicalSha256Object } from './canonicalSha256Service';
import type { VisualKnowledgeKind, VisualKnowledgeMemory } from './visualProjectLearningCompositionService';
import type { VisualMemoryScope } from './visualConversationProjectGatewayService';

export interface VisualMemoryStorage { getItem(key:string):string|null; setItem(key:string,value:string):void; removeItem(key:string):void; }
export interface PersistentVisualMemoryRecord { memory:VisualKnowledgeMemory;scope:VisualMemoryScope;projectId?:string;familyId?:string;createdAt:number;updatedAt:number;lastUsedAt?:number;useCount:number;status:'ACTIVE'|'SUPERSEDED'|'REVOKED';supersededBy?:string;recordSha256:string; }
interface VisualMemoryEnvelope {formatVersion:1;records:PersistentVisualMemoryRecord[];savedAt:number;recordsSha256:string;envelopeSha256:string;}
export interface VisualMemoryQuery {projectId?:string;familyId?:string;kinds?:VisualKnowledgeKind[];subject?:string;minConfidence?:number;limit?:number;}
export interface VisualMemoryLoadResult {records:PersistentVisualMemoryRecord[];valid:boolean;reason?:string;}
const STORE_KEY='miki_visual_memory_store_v1';
export class PersistentVisualMemoryStoreService {
 constructor(private readonly storage:VisualMemoryStorage=storageService){}
 save(memory:VisualKnowledgeMemory,scope:VisualMemoryScope,context:{projectId?:string;familyId?:string}={}):PersistentVisualMemoryRecord {this.validateMemory(memory);this.validateScope(scope,context);const loaded=this.load();if(!loaded.valid&&loaded.reason!=='EMPTY')throw new Error(`VISUAL_MEMORY_STORE_INVALID:${loaded.reason}`);const now=Date.now();const duplicate=loaded.records.find(x=>x.status==='ACTIVE'&&x.memory.memorySha256===memory.memorySha256&&x.scope===scope&&(x.projectId||'')===(context.projectId||'')&&(x.familyId||'')===(context.familyId||''));if(duplicate){const updated=this.record({...duplicate,updatedAt:now});this.persist(loaded.records.map(x=>x.recordSha256===duplicate.recordSha256?updated:x));return updated;}const record=this.record({memory,scope,projectId:context.projectId,familyId:context.familyId,createdAt:now,updatedAt:now,useCount:0,status:'ACTIVE'});this.persist([...loaded.records,record]);return record;}
 load():VisualMemoryLoadResult {const raw=this.storage.getItem(STORE_KEY);if(!raw)return{records:[],valid:true,reason:'EMPTY'};try{const envelope=JSON.parse(raw) as VisualMemoryEnvelope;if(envelope.formatVersion!==1||!Array.isArray(envelope.records))return{records:[],valid:false,reason:'FORMAT'};const seed={formatVersion:envelope.formatVersion,records:envelope.records,savedAt:envelope.savedAt,recordsSha256:envelope.recordsSha256};if(canonicalSha256Object(seed)!==envelope.envelopeSha256)return{records:[],valid:false,reason:'ENVELOPE_SHA'};if(canonicalSha256Object(envelope.records.map(x=>x.recordSha256).sort())!==envelope.recordsSha256)return{records:[],valid:false,reason:'RECORDS_SHA'};for(const record of envelope.records){this.validateMemory(record.memory);const {recordSha256,...body}=record;if(canonicalSha256Object(body)!==recordSha256)return{records:[],valid:false,reason:`RECORD_SHA:${record.memory.memoryId}`};}return{records:envelope.records,valid:true};}catch{return{records:[],valid:false,reason:'PARSE'};}}
 query(query:VisualMemoryQuery={}):PersistentVisualMemoryRecord[]{const loaded=this.load();if(!loaded.valid)throw new Error(`VISUAL_MEMORY_STORE_INVALID:${loaded.reason}`);const min=query.minConfidence??0;return loaded.records.filter(x=>x.status==='ACTIVE'&&x.memory.confidence>=min&&this.inScope(x,query)&&(!query.kinds?.length||query.kinds.includes(x.memory.kind))&&(!query.subject||x.memory.subject.toLowerCase().includes(query.subject.toLowerCase()))).sort((a,b)=>b.memory.confidence-a.memory.confidence||(b.lastUsedAt||0)-(a.lastUsedAt||0)||b.updatedAt-a.updatedAt).slice(0,query.limit??100);}
 memories(query:VisualMemoryQuery={}):VisualKnowledgeMemory[]{return this.query(query).map(x=>x.memory);}
 markUsed(memoryIds:string[],context:{projectId?:string;familyId?:string}={}):PersistentVisualMemoryRecord[]{const ids=new Set(memoryIds);const loaded=this.load();if(!loaded.valid)throw new Error(`VISUAL_MEMORY_STORE_INVALID:${loaded.reason}`);const now=Date.now();const updated=loaded.records.map(x=>ids.has(x.memory.memoryId)&&x.status==='ACTIVE'&&this.inScope(x,context)?this.record({...x,lastUsedAt:now,useCount:x.useCount+1,updatedAt:now}):x);this.persist(updated);return updated.filter(x=>ids.has(x.memory.memoryId));}
 supersede(memoryId:string,replacement:VisualKnowledgeMemory,scope:VisualMemoryScope,context:{projectId?:string;familyId?:string}={}):PersistentVisualMemoryRecord {const newRecord=this.save(replacement,scope,context);const loaded=this.load();const old=loaded.records.find(x=>x.memory.memoryId===memoryId&&x.status==='ACTIVE');if(!old)throw new Error('VISUAL_MEMORY_NOT_FOUND');const changed=this.record({...old,status:'SUPERSEDED',supersededBy:newRecord.memory.memoryId,updatedAt:Date.now()});this.persist(loaded.records.map(x=>x.memory.memoryId===memoryId?changed:x));return newRecord;}
 revoke(memoryId:string):void {const loaded=this.load();if(!loaded.valid)throw new Error(`VISUAL_MEMORY_STORE_INVALID:${loaded.reason}`);let found=false;const updated=loaded.records.map(x=>{if(x.memory.memoryId!==memoryId||x.status!=='ACTIVE')return x;found=true;return this.record({...x,status:'REVOKED',updatedAt:Date.now()});});if(!found)throw new Error('VISUAL_MEMORY_NOT_FOUND');this.persist(updated);}
 clear():void {this.storage.removeItem(STORE_KEY);}
 private persist(records:PersistentVisualMemoryRecord[]):void {const savedAt=Date.now();const recordsSha256=canonicalSha256Object(records.map(x=>x.recordSha256).sort());const seed={formatVersion:1 as const,records,savedAt,recordsSha256};const envelope={...seed,envelopeSha256:canonicalSha256Object(seed)};this.storage.setItem(STORE_KEY,JSON.stringify(envelope));const verified=this.load();if(!verified.valid||verified.records.length!==records.length)throw new Error(`VISUAL_MEMORY_WRITE_VERIFY_FAILED:${verified.reason}`);}
 private record(input:Omit<PersistentVisualMemoryRecord,'recordSha256'>|PersistentVisualMemoryRecord):PersistentVisualMemoryRecord {const {recordSha256:_ignored,...body}=input as PersistentVisualMemoryRecord;return{...body,recordSha256:canonicalSha256Object(body)};}
 private inScope(record:PersistentVisualMemoryRecord,context:{projectId?:string;familyId?:string}):boolean{return record.scope==='GLOBAL_TREND'||record.scope==='VISUAL_LIBRARY'||(record.scope==='PROJECT_LOCAL'&&record.projectId===context.projectId)||(record.scope==='PROJECT_FAMILY'&&record.familyId===context.familyId);}
 private validateScope(scope:VisualMemoryScope,context:{projectId?:string;familyId?:string}):void {if(scope==='PROJECT_LOCAL'&&!context.projectId)throw new Error('PROJECT_LOCAL_MEMORY_REQUIRES_PROJECT');if(scope==='PROJECT_FAMILY'&&!context.familyId)throw new Error('PROJECT_FAMILY_MEMORY_REQUIRES_FAMILY');}
 private validateMemory(memory:VisualKnowledgeMemory):void {if(!memory.memoryId||memory.confidence<0||memory.confidence>1||!memory.sourceSha256List?.length)throw new Error('INVALID_VISUAL_MEMORY');const {memoryId:_id,memorySha256:_sha,...seed}=memory;if(canonicalSha256Object(seed)!==memory.memorySha256)throw new Error('VISUAL_MEMORY_SHA_MISMATCH');}
}
export const persistentVisualMemoryStoreService=new PersistentVisualMemoryStoreService();
