import { canonicalSha256Object } from './canonicalSha256Service';
export type P171Origin='PERSON_OBSERVED'|'SAME_PERSON_FUSED'|'CROSS_PERSON_LEARNED_PRIOR'|'STRUCTURAL_PRIOR'|'EXPERIENCE_CORRECTED_PRIOR';
export interface P171VisualKnowledgeNode{nodeId:string;personScope:string;feature:string;value:unknown;origin:P171Origin;poseBucket:string;sourceSha256:string;confidence:number;uncertainty:number;validated:boolean;createdAt:number;nodeSha256:string;}
export interface P171VisualKnowledgeEdge{edgeId:string;from:string;to:string;type:'DERIVED_FROM'|'SUPPORTS'|'CORRECTS'|'GENERALIZES_TO';confidence:number;edgeSha256:string;}
export interface P171LearningGraph{nodes:P171VisualKnowledgeNode[];edges:P171VisualKnowledgeEdge[];featureIndex:Record<string,string[]>;poseIndex:Record<string,string[]>;graphSha256:string;}
const id=(p:string,h:string)=>`${p}-${h.slice(0,24)}`;
class PersonLearningGraphP171Service{
 empty():P171LearningGraph{return{nodes:[],edges:[],featureIndex:{},poseIndex:{},graphSha256:canonicalSha256Object({nodes:[],edges:[],featureIndex:{},poseIndex:{}})}}
 ingest(g:P171LearningGraph,input:Omit<P171VisualKnowledgeNode,'nodeId'|'nodeSha256'>):P171LearningGraph{const nodeSha256=canonicalSha256Object(input),node={nodeId:id('VKN',nodeSha256),...input,nodeSha256};const nodes=[...new Map([...g.nodes,node].map(n=>[n.nodeId,n])).values()],featureIndex=this.index(nodes,n=>n.feature),poseIndex=this.index(nodes,n=>n.poseBucket),core:any={nodes,edges:g.edges,featureIndex,poseIndex,graphSha256:''};core.graphSha256=canonicalSha256Object({...core,graphSha256:''});return core;}
 generalize(g:P171LearningGraph,feature:string,poseBucket:string,minSources=3):P171LearningGraph{const eligible=g.nodes.filter(n=>n.feature===feature&&n.poseBucket===poseBucket&&n.validated&&n.confidence>=.55&&n.origin==='PERSON_OBSERVED'),persons=new Set(eligible.map(n=>n.personScope));if(persons.size<minSources)throw new Error('P171_INSUFFICIENT_DIVERSE_SOURCES');const numeric=eligible.filter(n=>typeof n.value==='number');if(numeric.length!==eligible.length)throw new Error('P171_GENERALIZATION_REQUIRES_NUMERIC');const weight=eligible.reduce((s,n)=>s+n.confidence,0),value=eligible.reduce((s,n)=>s+Number(n.value)*n.confidence,0)/weight,spread=Math.sqrt(eligible.reduce((s,n)=>s+(Number(n.value)-value)**2,0)/eligible.length),base={personScope:'GENERAL',feature,value,origin:'CROSS_PERSON_LEARNED_PRIOR' as const,poseBucket,sourceSha256:canonicalSha256Object(eligible.map(n=>n.sourceSha256).sort()),confidence:Math.min(.88,weight/eligible.length),uncertainty:Math.min(1,.12+spread),validated:true,createdAt:Math.max(...eligible.map(n=>n.createdAt))};let next=this.ingest(g,base),general=next.nodes.find(n=>n.nodeSha256===canonicalSha256Object(base))!;for(const n of eligible){const seed={from:n.nodeId,to:general.nodeId,type:'GENERALIZES_TO' as const,confidence:n.confidence},edgeSha256=canonicalSha256Object(seed);next={...next,edges:[...new Map([...next.edges,{edgeId:id('VKE',edgeSha256),...seed,edgeSha256}].map(e=>[e.edgeId,e])).values()]};}next.graphSha256=canonicalSha256Object({...next,graphSha256:''});return next;}
 query(g:P171LearningGraph,feature:string,poseBucket:string,limit=16){return(g.featureIndex[feature]||[]).map(id=>g.nodes.find(n=>n.nodeId===id)!).filter(n=>n&&n.poseBucket===poseBucket&&n.validated).sort((a,b)=>b.confidence-a.confidence||a.uncertainty-b.uncertainty).slice(0,limit)}
 private index(nodes:P171VisualKnowledgeNode[],key:(n:P171VisualKnowledgeNode)=>string){const out:Record<string,string[]>={};for(const n of nodes)(out[key(n)]??=[]).push(n.nodeId);for(const k of Object.keys(out))out[k].sort();return out}}
export const personLearningGraphP171Service=new PersonLearningGraphP171Service();
