import { canonicalSha256Object } from './canonicalSha256Service';
import { detailedHumanRuleLearningP194Service, type P194SubjectObservation, type P194RuleBook } from './detailedHumanRuleLearningP194Service';
import { layeredPerson25DModelP192Service, type P192ControlPoint } from './layeredPerson25DModelP192Service';
import { detailedFaceSurfaceP194Service, type P194DetailedModel } from './detailedFaceSurfaceP194Service';
import { proceduralPersonRuleSynthesizerP193Service, type P193RuleSet, type P193Synthesis } from './proceduralPersonRuleSynthesizerP193Service';
import type { P190Graph } from './fictionalPersonGraphLearningP190Service';
export interface P196View{yaw:number;pitch:number;roll:number}
export interface P196Expression{eyeOpenLeft:number;eyeOpenRight:number;browRaiseLeft:number;browRaiseRight:number;mouthOpen:number;lipCornerLeft:number;lipCornerRight:number;jawOpen:number;cheekRaiseLeft:number;cheekRaiseRight:number}
export interface P196Request{requestId:string;seed:number;view:P196View;expression:P196Expression;maxRepairPasses:number}
export interface P196PartEvidence{part:string;controlPoints:number;patches:number;visiblePixels:number;depthMin:number;depthMax:number;passed:boolean}
export interface P196Quality{score:number;passed:boolean;failures:string[];parts:P196PartEvidence[];repairPasses:number}
export interface P196Result{request:P196Request;model:P194DetailedModel;synthesis:P193Synthesis;quality:P196Quality;route:'CORE_LOCAL_PERSON_GENERATION_P196';receiptSha256:string}
class PersonGenerationCoreRouteP196Service{
 generate(graph:P190Graph,subjects:P194SubjectObservation[],request:P196Request):P196Result{const book=detailedHumanRuleLearningP194Service.learn(subjects);let model=this.fingers(detailedFaceSurfaceP194Service.enhance(layeredPerson25DModelP192Service.build(graph,request.seed),book));model=this.project(this.express(model,request.expression),request.view);let pass=0,synthesis:P193Synthesis,quality:P196Quality;const rule=this.rules(book);do{synthesis=proceduralPersonRuleSynthesizerP193Service.synthesize(model,rule);quality=this.inspect(model,synthesis,pass);if(quality.passed)break;model=this.repair(model,quality.failures,pass);pass++}while(pass<=request.maxRepairPasses);quality={...quality,repairPasses:pass};const core:any={request,model,synthesis,quality,route:'CORE_LOCAL_PERSON_GENERATION_P196',receiptSha256:''};core.receiptSha256=canonicalSha256Object({...core,synthesis:{...synthesis,rgba:[],normal:[],material:[],depth:[]},receiptSha256:''});return core}
 private rules(book:P194RuleBook):P193RuleSet{const v=(p:string,f:number)=>book.featureRules.find(x=>x.path===p)?.mean??f,rgb:[number,number,number]=[v('skin.meanRgb.0',.8)*255,v('skin.meanRgb.1',.64)*255,v('skin.meanRgb.2',.55)*255] as any;const base:any={rules:book.featureRules.slice(0,5).map((x,i)=>({ruleId:`P196-${i}`,feature:x.path,mean:x.mean,stdDev:x.stdDev,min:x.min,max:x.max,sourceCount:book.sourceSha256List.length,confidence:x.confidence,ruleSha256:canonicalSha256Object(x)})),correlations:Object.fromEntries(book.correlations.map(x=>[`${x.a}:${x.b}`,x.r])),materials:{SKIN:{base:rgb.map(x=>Math.max(0,Math.min(255,Math.round(x)))) as any,variation:Math.max(.04,v('skin.microContrast',.1)),roughness:.55,specular:.2,microScale:Math.max(.008,v('skin.spatialLowFrequency',.02))},HAIR:{base:[42,33,29],variation:Math.max(.08,v('hair.strandVariance',.15)),roughness:.4,specular:.32,microScale:.01},GARMENT:{base:[76,102,112],variation:Math.max(.08,v('garment.wrinkleDensity',.14)),roughness:Math.max(.4,v('garment.roughnessProxy',.7)),specular:.08,microScale:.025},WOOD:{base:[103,64,39],variation:.12,roughness:.64,specular:.12,microScale:.032},BACKGROUND:{base:[224,220,214],variation:.025,roughness:.9,specular:.02,microScale:.05},SHADOW:{base:[24,21,19],variation:.04,roughness:.95,specular:0,microScale:.04}},sourceSha256List:book.sourceSha256List,ruleSetSha256:''};base.ruleSetSha256=canonicalSha256Object({...base,ruleSetSha256:''});return base}
 private express(m:P194DetailedModel,e:P196Expression){const c=m.controlPoints.map(p=>({...p})),by=new Map(c.map(p=>[p.id,p]));const mv=(id:string,dx:number,dy:number)=>{const p=by.get(id);if(p){p.x+=dx;p.y+=dy}};mv('upperLidL',0,(1-e.eyeOpenLeft)*.008);mv('lowerLidL',0,-(1-e.eyeOpenLeft)*.006);mv('upperLidR',0,(1-e.eyeOpenRight)*.008);mv('lowerLidR',0,-(1-e.eyeOpenRight)*.006);mv('upperLip',0,-e.mouthOpen*.006);mv('lowerLip',0,e.mouthOpen*.010);mv('chin',0,e.jawOpen*.012);mv('cheekL',0,-e.cheekRaiseLeft*.006);mv('cheekR',0,-e.cheekRaiseRight*.006);mv('upperLip',e.lipCornerRight*.002-e.lipCornerLeft*.002,0);return this.hash({...m,controlPoints:c})}
 private project(m:P194DetailedModel,v:P196View){const yaw=v.yaw*Math.PI/180,pitch=v.pitch*Math.PI/180,roll=v.roll*Math.PI/180,cx=.5,cy=.45,c=m.controlPoints.map(p=>{let x=p.x-cx,y=p.y-cy,z=p.depth-.5;const x1=x*Math.cos(yaw)+z*Math.sin(yaw),z1=-x*Math.sin(yaw)+z*Math.cos(yaw),y1=y*Math.cos(pitch)-z1*Math.sin(pitch),z2=y*Math.sin(pitch)+z1*Math.cos(pitch),xr=x1*Math.cos(roll)-y1*Math.sin(roll),yr=x1*Math.sin(roll)+y1*Math.cos(roll);return{...p,x:cx+xr*(1-z2*.18),y:cy+yr*(1-z2*.12),depth:.5+z2}});return this.hash({...m,controlPoints:c})}
 private fingers(m:P194DetailedModel){const c=m.controlPoints.filter(x=>!x.id.includes('Finger')).map(x=>({...x})),p=m.patches.filter(x=>!x.patchId.includes('-finger-')).map(x=>({...x,controlPointIds:[...x.controlPointIds]}));for(const side of ['handL','handR']){const hand=c.find(x=>x.id===side)!;for(let f=0;f<5;f++){let prev=side;for(let j=1;j<=3;j++){const id=`${side}-finger-${f+1}-joint-${j}`,dir=side==='handL'?-1:1;c.push({id,x:hand.x+dir*(f-2)*.006+dir*j*.004,y:hand.y+j*.010+Math.abs(f-2)*.001,depth:.14+f*.004,radius:.0038});p.push({patchId:`${side}-finger-${f+1}-${j}`,kind:'HANDS',depth:.14+f*.004,opacity:1,color:[205,164,142,255],controlPointIds:[prev,id],curvature:.72,material:'SKIN'});prev=id}}}return this.hash({...m,controlPoints:c,patches:p,fingerControlPoints:c.filter(x=>x.id.includes('-finger-')).map(x=>x.id)})}
 private inspect(m:P194DetailedModel,s:P193Synthesis,pass:number):P196Quality{const groups:any={eyes:['orbit','eyeball','Lid'],nose:['nose'],lips:['Lip'],ears:['ear'],fingers:['-finger-'],neck:['neckBlend']};const parts:P196PartEvidence[]=Object.entries(groups).map(([part,tokens]:any)=>{const ids=m.controlPoints.filter(p=>tokens.some((t:string)=>p.id.includes(t))),patches=m.patches.filter(p=>p.controlPointIds.some(id=>ids.some(x=>x.id===id))),visiblePixels=Math.max(0,Math.round(ids.reduce((a,p)=>a+p.radius*p.radius,0)*s.width*s.height*3.2)),depths=ids.map(x=>x.depth),minimum=part==='fingers'?120:part==='eyes'?80:40;return{part,controlPoints:ids.length,patches:patches.length,visiblePixels,depthMin:Math.min(...depths),depthMax:Math.max(...depths),passed:ids.length>0&&patches.length>0&&visiblePixels>=minimum}});const failures=parts.filter(x=>!x.passed).map(x=>`${x.part.toUpperCase()}_PIXEL_EVIDENCE_FAILURE`);if(s.colorCount<80)failures.push('MATERIAL_FLATNESS_FAILURE');if(s.surfaceCoverage<.99)failures.push('SURFACE_COVERAGE_FAILURE');const score=(parts.filter(x=>x.passed).length/parts.length)*.75+Math.min(1,s.colorCount/120)*.15+Math.min(1,s.surfaceCoverage)*.1;return{score,passed:failures.length===0&&score>=.83,failures,parts,repairPasses:pass}}
 private repair(m:P194DetailedModel,fail:string[],pass:number){const keys=fail.map(x=>x.split('_')[0].toLowerCase()),c=m.controlPoints.map(p=>({...p,radius:keys.some(k=>p.id.toLowerCase().includes(k))?p.radius*(1.18+pass*.04):p.radius}));return this.hash({...m,controlPoints:c})}
 private hash(v:any){const core:any={...v,modelSha256:''};core.modelSha256=canonicalSha256Object(core);return core}
}
export const personGenerationCoreRouteP196Service=new PersonGenerationCoreRouteP196Service();
