import { canonicalSha256Object } from './canonicalSha256Service';
import { garmentEvidenceLearningService, type GarmentEvidenceInput, type GarmentLearningProfile } from './garmentEvidenceLearningService';
import { garmentBoundaryRenderingPolicyService, type GarmentBoundaryRenderingPolicy } from './garmentBoundaryRenderingPolicyService';

export type PersonRenderQuality='PIXEL_NATIVE'|'PIXEL_ILLUSTRATION'|'ILLUSTRATION_2D'|'ILLUSTRATION_25D';
export interface P138ConfirmationAnswer{questionId:string;regionId:string;sourceSha256:string;profileSha256BeforeAnswer:string;decision:'PRESENT'|'ABSENT'|'UNKNOWN';}
export interface P138GarmentRecord{garmentId:string;regionId:string;kind:string;layer:string;evidenceProfile:GarmentLearningProfile;presence:string;gapState:string;gapObservationComplete:boolean;zeroGapConfidence:number;gaps:GarmentLearningProfile['gaps'];confirmationContract?:GarmentLearningProfile['confirmationContract'];boundaryRenderingPolicy:GarmentBoundaryRenderingPolicy;sourceSha256:string;evidenceProfileSha256:string;boundaryPolicySha256:string;revision:number;status:'PROVISIONAL'|'CONFIRMED';}
export interface P138VisualProfile{profileId:string;revision:number;subject:string;garments:P138GarmentRecord[];confirmationHistory:Array<{questionId:string;regionId:string;sourceSha256:string;profileSha256BeforeAnswer:string;profileSha256AfterAnswer:string;answer:string;answeredAt:number;consumed:boolean}>;profileSha256:string;}
export interface P138PngArtifact{quality:PersonRenderQuality;width:number;height:number;rgba:Uint8Array;png:Uint8Array;sha256:string;profileSha256:string;boundaryPolicySha256:string;}

const rgb=(h:string)=>{const x=h.replace('#','');return [parseInt(x.slice(0,2),16),parseInt(x.slice(2,4),16),parseInt(x.slice(4,6),16),255] as const;};
class Canvas{rgba:Uint8Array;constructor(readonly width:number,readonly height:number){this.rgba=new Uint8Array(width*height*4);}px(x:number,y:number,c:string,a=1){if(x<0||y<0||x>=this.width||y>=this.height)return;const i=(Math.floor(y)*this.width+Math.floor(x))*4,q=rgb(c),ia=Math.max(0,Math.min(1,a));this.rgba[i]=Math.round(q[0]*ia+this.rgba[i]*(1-ia));this.rgba[i+1]=Math.round(q[1]*ia+this.rgba[i+1]*(1-ia));this.rgba[i+2]=Math.round(q[2]*ia+this.rgba[i+2]*(1-ia));this.rgba[i+3]=255;}ellipse(cx:number,cy:number,rx:number,ry:number,c:string,a=1){for(let y=Math.floor(cy-ry);y<=cy+ry;y++)for(let x=Math.floor(cx-rx);x<=cx+rx;x++)if(((x-cx)/rx)**2+((y-cy)/ry)**2<=1)this.px(x,y,c,a);}poly(points:number[][],c:string){const ys=points.map(p=>p[1]);for(let y=Math.floor(Math.min(...ys));y<=Math.ceil(Math.max(...ys));y++){const xs:number[]=[];for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>y)!==(b[1]>y))xs.push(a[0]+(y-a[1])*(b[0]-a[0])/(b[1]-a[1]));}xs.sort((a,b)=>a-b);for(let i=0;i+1<xs.length;i+=2)for(let x=Math.ceil(xs[i]);x<=Math.floor(xs[i+1]);x++)this.px(x,y,c);}}line(x0:number,y0:number,x1:number,y1:number,c:string,a=1,w=1){const n=Math.max(Math.abs(x1-x0),Math.abs(y1-y0),1);for(let i=0;i<=n;i++){const x=x0+(x1-x0)*i/n,y=y0+(y1-y0)*i/n;this.ellipse(x,y,w/2,w/2,c,a);}}}

class PersonVisualProductionP138Service{
 analyzeAndCreateProfile(subject:string,input:GarmentEvidenceInput):P138VisualProfile{const analyzed=garmentEvidenceLearningService.analyze(input);const evidence=analyzed.confirmationRequired&&!analyzed.confirmationContract?garmentEvidenceLearningService.issueConfirmation(analyzed):analyzed;const policy=garmentBoundaryRenderingPolicyService.resolve({profile:evidence,appearancePalette:input.appearancePalette,garmentPalette:input.garmentPalette,observedBoundaryConfidence:input.boundaryConfidence,observedSeamConfidence:input.seamConfidence,observedShadowConfidence:input.wrinkleConfidence,observedTextureDifference:input.textureDifference,garmentThickness:input.layerOverlapConfidence*.03});const garment:P138GarmentRecord={garmentId:`GAR-${input.regionId}`,regionId:input.regionId,kind:evidence.kind,layer:evidence.layer,evidenceProfile:evidence,presence:evidence.presence,gapState:evidence.gapState,gapObservationComplete:evidence.gapObservationComplete,zeroGapConfidence:evidence.zeroGapConfidence,gaps:evidence.gaps,confirmationContract:evidence.confirmationContract,boundaryRenderingPolicy:policy,sourceSha256:input.sourceSha256,evidenceProfileSha256:evidence.profileSha256,boundaryPolicySha256:policy.policySha256,revision:1,status:evidence.confirmationRequired?'PROVISIONAL':'CONFIRMED'};return this.seal({profileId:`P138-${input.regionId}`,revision:1,subject,garments:[garment],confirmationHistory:[],profileSha256:''});}
 consumeConfirmation(profile:P138VisualProfile,answer:P138ConfirmationAnswer):P138VisualProfile{this.verify(profile);const g=profile.garments.find(x=>x.regionId===answer.regionId);if(!g||!g.confirmationContract)throw new Error('GARMENT_CONFIRMATION_NOT_FOUND');const updated=garmentEvidenceLearningService.resolve(g.evidenceProfile,answer);const next=structuredClone(profile);const ng=next.garments.find(x=>x.regionId===answer.regionId)!;ng.evidenceProfile=updated;ng.presence=updated.presence;ng.confirmationContract=updated.confirmationContract;ng.evidenceProfileSha256=updated.profileSha256;ng.revision++;ng.status='CONFIRMED';next.revision++;next.confirmationHistory.push({questionId:answer.questionId,regionId:answer.regionId,sourceSha256:answer.sourceSha256,profileSha256BeforeAnswer:answer.profileSha256BeforeAnswer,profileSha256AfterAnswer:updated.profileSha256,answer:answer.decision,answeredAt:Date.now(),consumed:true});return this.seal(next);}
 confirmationQuestion(profile:P138VisualProfile):string|null{return profile.garments.some(g=>g.presence==='GARMENT_CONFIRMATION_REQUIRED')?'対象領域では外観と衣服候補の差を確定できません。衣服あり、衣服なし、不明のまま、のどれとして扱いますか？':null;}
 async render(profile:P138VisualProfile,quality:PersonRenderQuality):Promise<P138PngArtifact>{this.verify(profile);const policy=profile.garments[0].boundaryRenderingPolicy;const dims:Record<PersonRenderQuality,[number,number]>={PIXEL_NATIVE:[64,96],PIXEL_ILLUSTRATION:[256,384],ILLUSTRATION_2D:[512,768],ILLUSTRATION_25D:[768,1152]};const [w,h]=dims[quality],c=new Canvas(w,h),s=w/256;const skin='#f2c6a8',hair='#302333',cloth='#ececec',shadow='#b8bdc8',deep='#777f91',light='#ffffff',shoe='#34333a';
  if(quality==='ILLUSTRATION_25D'){c.ellipse(w*.52,h*.91,w*.18,h*.025,'#000000',.28);c.ellipse(w*.54,h*.52,w*.20,h*.38,'#000000',.10);}
  c.ellipse(w*.5,h*.15,w*.105,h*.105,hair);c.ellipse(w*.5,h*.165,w*.088,h*.092,skin);c.ellipse(w*.468,h*.158,w*.008,h*.006,'#332f36');c.ellipse(w*.532,h*.158,w*.008,h*.006,'#332f36');c.line(w*.49,h*.19,w*.51,h*.19,'#9c5d60',1,Math.max(1,s));
  c.poly([[w*.42,h*.25],[w*.58,h*.25],[w*.64,h*.58],[w*.36,h*.58]],cloth);c.poly([[w*.42,h*.25],[w*.50,h*.25],[w*.47,h*.58],[w*.36,h*.58]],shadow);c.poly([[w*.50,h*.25],[w*.58,h*.25],[w*.64,h*.58],[w*.47,h*.58]],light);
  c.poly([[w*.42,h*.27],[w*.33,h*.31],[w*.28,h*.55],[w*.34,h*.57],[w*.43,h*.39]],cloth);c.poly([[w*.58,h*.27],[w*.67,h*.31],[w*.72,h*.55],[w*.66,h*.57],[w*.57,h*.39]],cloth);c.ellipse(w*.30,h*.58,w*.028,h*.04,skin);c.ellipse(w*.70,h*.58,w*.028,h*.04,skin);
  c.poly([[w*.40,h*.58],[w*.49,h*.58],[w*.47,h*.88],[w*.37,h*.88]],deep);c.poly([[w*.51,h*.58],[w*.60,h*.58],[w*.63,h*.88],[w*.53,h*.88]],'#687185');c.ellipse(w*.40,h*.90,w*.07,h*.025,shoe);c.ellipse(w*.60,h*.90,w*.07,h*.025,shoe);
  if(quality!=='PIXEL_NATIVE'){for(let i=0;i<5;i++)c.line(w*(.405+i*.045),h*.31,w*(.39+i*.05),h*.55,i%2?light:shadow,.22,Math.max(1,s));c.line(w*.43,h*.255,w*.50,h*.30,shadow,.65,Math.max(1,s));c.line(w*.57,h*.255,w*.50,h*.30,shadow,.65,Math.max(1,s));}
  if(policy.drawBoundary&&policy.boundaryColor){const col=policy.boundaryColor;c.line(w*.42,h*.25,w*.36,h*.58,col,policy.boundaryOpacity,Math.max(1,s));c.line(w*.58,h*.25,w*.64,h*.58,col,policy.boundaryOpacity,Math.max(1,s));}
  if(quality==='ILLUSTRATION_25D'){c.ellipse(w*.68,h*.36,w*.025,h*.20,'#ffffff',.25);c.line(w*.38,h*.58,w*.62,h*.58,'#000000',.18,Math.max(2,s*2));c.line(w*.37,h*.88,w*.47,h*.88,'#000000',.18,Math.max(2,s));}
  const png=await this.png(c);return{quality,width:w,height:h,rgba:c.rgba,png,sha256:await this.sha(png),profileSha256:profile.profileSha256,boundaryPolicySha256:policy.policySha256};}
 private seal(p:P138VisualProfile){p.profileSha256='';p.profileSha256=canonicalSha256Object(p);return p;}private verify(p:P138VisualProfile){const c=structuredClone(p);c.profileSha256='';if(canonicalSha256Object(c)!==p.profileSha256)throw new Error('P138_PROFILE_SHA_MISMATCH');}
 private async png(c:Canvas){const raw=new Uint8Array((c.width*4+1)*c.height);for(let y=0;y<c.height;y++){const o=y*(c.width*4+1);raw[o]=0;raw.set(c.rgba.subarray(y*c.width*4,(y+1)*c.width*4),o+1);}const cs=new CompressionStream('deflate'),wr=cs.writable.getWriter();await wr.write(raw);await wr.close();const data=new Uint8Array(await new Response(cs.readable).arrayBuffer()),sig=Uint8Array.from([137,80,78,71,13,10,26,10]),ih=new Uint8Array(13),v=new DataView(ih.buffer);v.setUint32(0,c.width);v.setUint32(4,c.height);ih.set([8,6,0,0,0],8);return this.concat(sig,this.chunk('IHDR',ih),this.chunk('IDAT',data),this.chunk('IEND',new Uint8Array()));}
 private chunk(t:string,d:Uint8Array){const b=new TextEncoder().encode(t),o=new Uint8Array(12+d.length),v=new DataView(o.buffer);v.setUint32(0,d.length);o.set(b,4);o.set(d,8);v.setUint32(8+d.length,this.crc(this.concat(b,d)));return o;}private crc(d:Uint8Array){let c=0xffffffff;for(const b of d){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}private concat(...a:Uint8Array[]){const o=new Uint8Array(a.reduce((n,x)=>n+x.length,0));let p=0;for(const x of a){o.set(x,p);p+=x.length;}return o;}private async sha(d:Uint8Array){const h=await crypto.subtle.digest('SHA-256',d.slice().buffer);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}
}
export const personVisualProductionP138Service=new PersonVisualProductionP138Service();
