import JSZip from 'jszip';
import { storageService } from '../../../services/storageService';
import { canonicalSha256 } from './canonicalSha256Service';

export type Priority12ArtifactKind='FILE'|'ZIP'|'ZIPTXT'|'GIT_REPOSITORY'|'XLSM'|'XLSB';
export type Priority12SnapshotRole='BASE'|'CANDIDATE'|'EVIDENCE'|'REVIEW_PACKAGE';
export interface Priority12File {path:string;contentBase64:string;sha256:string;size:number;binary:boolean;}
export interface Priority12Snapshot {snapshotId:string;role:Priority12SnapshotRole;files:Priority12File[];sha256:string;createdAt:number;}
export interface Priority12Workspace {workspaceId:string;name:string;kind:Priority12ArtifactKind;snapshots:Priority12Snapshot[];createdAt:number;updatedAt:number;}
export interface Priority12Diff {path:string;status:'ADDED'|'MODIFIED'|'DELETED'|'UNCHANGED';baseSha256?:string;candidateSha256?:string;}
export interface Priority12VbaValidation {valid:boolean;lineCount:number;procedures:{name:string;kind:string;startLine:number;endLine:number}[];violations:{code:string;line:number}[];codeSha256:string;}
export interface Priority12CompileReceipt {status:'NOT_RUN'|'PASSED'|'FAILED';compiler:'EXCEL_VBE';message:string;checkedAt:number;codeSha256:string;}
export interface Priority12RollbackReceipt {restored:boolean;fromSha256:string;toSha256:string;checkedAt:number;}
const KEY='miki_priority12_artifact_workspaces_v1';
const textEncoder=new TextEncoder();
const textDecoder=new TextDecoder();
const bytesToBase64=(bytes:Uint8Array):string=>{let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(out);};
const base64ToBytes=(value:string):Uint8Array=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
const normalizePath=(path:string):string=>{const normalized=path.replace(/\\/g,'/').replace(/^\.\//,'');if(!normalized||normalized.startsWith('/')||normalized.split('/').includes('..'))throw new Error('UNSAFE_ARTIFACT_PATH');return normalized;};
class Priority12ArtifactWorkspaceService{
 async importArtifact(input:{name:string;fileName:string;bytes:Uint8Array;kind?:Priority12ArtifactKind}):Promise<Priority12Workspace>{
  const kind=input.kind||this.detectKind(input.fileName,input.bytes);const files=kind==='ZIP'||kind==='ZIPTXT'||kind==='XLSM'||kind==='XLSB'?await this.readZip(input.bytes):[this.makeFile(input.fileName,input.bytes)];
  if(files.length===0)throw new Error('ARTIFACT_EMPTY');const now=Date.now();const base=this.snapshot('BASE',files,now);const row:Priority12Workspace={workspaceId:`p12-${now}-${canonicalSha256(input.name).slice(0,10)}`,name:input.name.trim()||input.fileName,kind,snapshots:[base],createdAt:now,updatedAt:now};this.save([...this.read().filter(item=>item.workspaceId!==row.workspaceId),row]);return this.clone(row);
 }
 saveSnapshot(workspaceId:string,role:Priority12SnapshotRole,files:{path:string;bytes:Uint8Array}[]):Priority12Snapshot{const rows=this.read();const row=rows.find(item=>item.workspaceId===workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');const snapshot=this.snapshot(role,files.map(file=>this.makeFile(file.path,file.bytes)),Date.now());row.snapshots=[...row.snapshots.filter(item=>item.role!==role),snapshot];row.updatedAt=Date.now();this.save(rows);return {...snapshot,files:snapshot.files.map(file=>({...file}))};}
 list():Priority12Workspace[]{return this.read().map(row=>this.clone(row));}
 restore(workspaceId:string):Priority12Workspace|undefined{return this.list().find(row=>row.workspaceId===workspaceId);}
 preview(workspaceId:string):{diff:Priority12Diff[];structure:string[];dependencies:Record<string,string[]>;screenshots:{path:string;sha256:string}[]}{const row=this.restore(workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');const base=this.byRole(row,'BASE');const candidate=this.byRole(row,'CANDIDATE')||base;const baseMap=new Map(base.files.map(file=>[file.path,file]));const candidateMap=new Map(candidate.files.map(file=>[file.path,file]));const paths=[...new Set([...baseMap.keys(),...candidateMap.keys()])].sort();const diff=paths.map(path=>{const left=baseMap.get(path);const right=candidateMap.get(path);return {path,status:!left?'ADDED':!right?'DELETED':left.sha256===right.sha256?'UNCHANGED':'MODIFIED',baseSha256:left?.sha256,candidateSha256:right?.sha256} as Priority12Diff;});const dependencies:Record<string,string[]>={};for(const file of candidate.files){if(file.binary)continue;const text=textDecoder.decode(base64ToBytes(file.contentBase64));dependencies[file.path]=[...text.matchAll(/(?:from\s+|require\()['"]([^'"]+)['"]/g)].map(match=>match[1]);}return {diff,structure:candidate.files.map(file=>file.path).sort(),dependencies,screenshots:candidate.files.filter(file=>/\.(png|jpe?g|webp)$/i.test(file.path)).map(file=>({path:file.path,sha256:file.sha256}))};}
 validateVba(code:string):Priority12VbaValidation{const lines=code.replace(/\r\n?/g,'\n').split('\n');const violations:{code:string;line:number}[]=[];const procedures:{name:string;kind:string;startLine:number;endLine:number}[]=[];if(!lines.some(line=>/^\s*Option\s+Explicit\s*$/i.test(line)))violations.push({code:'OPTION_EXPLICIT_REQUIRED',line:1});const stack:{name:string;kind:string;startLine:number}[]=[];lines.forEach((raw,index)=>{const line=raw.replace(/'.*$/,'');if(/^\s*GoTo\b/i.test(line)||/\bGoTo\s+\w+/i.test(line))violations.push({code:'GOTO_FORBIDDEN',line:index+1});if(/^\s*Attribute\s+VB_Name/i.test(line))violations.push({code:'ATTRIBUTE_VB_NAME_FORBIDDEN',line:index+1});if(/^\s*\w+\s*:\s*(?:'.*)?$/i.test(raw))violations.push({code:'LABEL_FORBIDDEN',line:index+1});if(/^\s*If\b.+\bThen\s+\S+/i.test(line))violations.push({code:'SINGLE_LINE_IF_FORBIDDEN',line:index+1});const start=line.match(/^\s*(?:(Public|Private|Friend)\s+)?(Sub|Function|Property\s+(?:Get|Let|Set))\s+([A-Za-z_]\w*)/i);if(start)stack.push({name:start[3],kind:start[2],startLine:index+1});if(/^\s*End\s+(Sub|Function|Property)\s*$/i.test(line)){const item=stack.pop();if(item)procedures.push({...item,endLine:index+1});else violations.push({code:'UNEXPECTED_PROCEDURE_END',line:index+1});}});stack.forEach(item=>violations.push({code:'PROCEDURE_END_MISSING',line:item.startLine}));return {valid:violations.length===0,lineCount:lines.length,procedures:procedures.sort((a,b)=>a.startLine-b.startLine),violations,codeSha256:canonicalSha256(code)};}
 exportVba(code:string,mode:'VBE_CODE_TXT'|'VBE_VALIDATION_LOG'|'AUTO_APPLY_TXT'):string{const result=this.validateVba(code);if(!result.valid)throw new Error(`VBA_SECONDARY_VALIDATION_FAILED:${result.violations.map(item=>item.code).join(',')}`);if(mode==='VBE_CODE_TXT')return code;if(mode==='VBE_VALIDATION_LOG')return JSON.stringify(result,null,2);return `[DELIVERY]\nFORMAT_VERSION=2\nDELIVERY_TYPE=FULL_MODULE\nCODE_LENGTH=${code.length}\nCODE_LINE_COUNT=${result.lineCount}\nCODE_SHA256=${result.codeSha256}\n[/DELIVERY]\n\n[CODE]\n${code}\n[/CODE]\n\n[VALIDATION]\n${JSON.stringify(result)}\n[/VALIDATION]`;}
 recordCompile(code:string,status:'PASSED'|'FAILED',message:string):Priority12CompileReceipt{return {status,compiler:'EXCEL_VBE',message,checkedAt:Date.now(),codeSha256:canonicalSha256(code)};}
 rollback(candidate:string,base:string):{content:string;receipt:Priority12RollbackReceipt}{return {content:base,receipt:{restored:true,fromSha256:canonicalSha256(candidate),toSha256:canonicalSha256(base),checkedAt:Date.now()}};}
 async exportZip(workspaceId:string,role:Priority12SnapshotRole):Promise<Uint8Array>{const row=this.restore(workspaceId);if(!row)throw new Error('WORKSPACE_NOT_FOUND');const snapshot=this.byRole(row,role);if(!snapshot)throw new Error('SNAPSHOT_NOT_FOUND');const zip=new JSZip();snapshot.files.forEach(file=>zip.file(file.path,base64ToBytes(file.contentBase64)));zip.file('priority12-manifest.json',JSON.stringify({workspaceId,rowName:row.name,kind:row.kind,role,snapshotSha256:snapshot.sha256,files:snapshot.files.map(file=>({path:file.path,sha256:file.sha256,size:file.size}))},null,2));const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE'});const verification=await this.readZip(bytes);if(!verification.some(file=>file.path==='priority12-manifest.json'))throw new Error('EXPORT_RELOAD_VERIFICATION_FAILED');return bytes;}
 private detectKind(fileName:string,bytes:Uint8Array):Priority12ArtifactKind{const lower=fileName.toLowerCase();if(lower.endsWith('.zip.txt'))return 'ZIPTXT';if(lower.endsWith('.zip'))return 'ZIP';if(lower.endsWith('.xlsm'))return 'XLSM';if(lower.endsWith('.xlsb'))return 'XLSB';if(bytes[0]===0x50&&bytes[1]===0x4b)return 'ZIP';return 'FILE';}
 private async readZip(bytes:Uint8Array):Promise<Priority12File[]>{const archive=await JSZip.loadAsync(bytes,{checkCRC32:true});const files:Priority12File[]=[];for(const [path,entry] of Object.entries(archive.files)){if(entry.dir)continue;const safe=normalizePath(path);const content=await entry.async('uint8array');files.push(this.makeFile(safe,content));}return files;}
 private makeFile(path:string,bytes:Uint8Array):Priority12File{const safe=normalizePath(path);const binary=bytes.some(byte=>byte===0)||(textDecoder.decode(bytes).includes('\uFFFD'));return {path:safe,contentBase64:bytesToBase64(bytes),sha256:canonicalSha256(Array.from(bytes)),size:bytes.length,binary};}
 private snapshot(role:Priority12SnapshotRole,files:Priority12File[],createdAt:number):Priority12Snapshot{const stable=[...files].sort((a,b)=>a.path.localeCompare(b.path));const sha256=canonicalSha256(stable.map(file=>({path:file.path,sha256:file.sha256})));return {snapshotId:`${role.toLowerCase()}-${createdAt}-${sha256.slice(0,12)}`,role,files:stable,sha256,createdAt};}
 private byRole(row:Priority12Workspace,role:Priority12SnapshotRole):Priority12Snapshot|undefined{return row.snapshots.find(item=>item.role===role);}
 private read():Priority12Workspace[]{try{const parsed=JSON.parse(storageService.getItem(KEY)||'[]');return Array.isArray(parsed)?parsed:[];}catch{return [];}}
 private save(rows:Priority12Workspace[]):void{storageService.setItem(KEY,JSON.stringify(rows));}
 private clone(row:Priority12Workspace):Priority12Workspace{return {...row,snapshots:row.snapshots.map(snapshot=>({...snapshot,files:snapshot.files.map(file=>({...file}))}))};}
}
export const priority12ArtifactWorkspaceService=new Priority12ArtifactWorkspaceService();
