import { canonicalSha256Object } from './canonicalSha256Service';
import type { P192Person25DModel,P192SurfacePatch,P192ControlPoint } from './layeredPerson25DModelP192Service';
export interface P193Observation{subjectId:string;foregroundRatio:number;seatBandOccupancy:number;floorContactOccupancy:number;leftRightBalance:number;luminanceMean:number;sourceSha256:string}
export interface P193Rule{ruleId:string;feature:string;mean:number;stdDev:number;min:number;max:number;sourceCount:number;confidence:number;ruleSha256:string}
export interface P193RuleSet{rules:P193Rule[];correlations:Record<string,number>;materials:Record<string,{base:[number,number,number];variation:number;roughness:number;specular:number;microScale:number}>;sourceSha256List:string[];ruleSetSha256:string}
export interface P193Synthesis{width:number;height:number;rgba:Uint8Array;normal:Uint8Array;material:Uint8Array;depth:Float32Array;newPixelRatio:number;colorCount:number;surfaceCoverage:number;ruleSetSha256:string;modelSha256:string;synthesisSha256:string}
class ProceduralPersonRuleSynthesizerP193Service{
 learn(obs:P193Observation[]):P193RuleSet{if(new Set(obs.map(x=>x.subjectId)).size<10)throw new Error('P193_TEN_SUBJECTS_REQUIRED');const fs=['foregroundRatio','seatBandOccupancy','floorContactOccupancy','leftRightBalance','luminanceMean'] as const,rules=fs.map(feature=>{const a=obs.map(o=>o[feature]),mean=a.reduce((x,y)=>x+y,0)/a.length,stdDev=Math.sqrt(a.reduce((s,v)=>s+(v-mean)**2,0)/a.length),seed={feature,mean,stdDev,min:Math.min(...a),max:Math.max(...a),sourceCount:a.length,confidence:Math.min(.92,.62+a.length*.025)},ruleSha256=canonicalSha256Object(seed);return{ruleId:`P193R-${ruleSha256.slice(0,20)}`,...seed,ruleSha256}}),corr=(a:keyof P193Observation,b:keyof P193Observation)=>{const x=obs.map(o=>Number(o[a])),y=obs.map(o=>Number(o[b])),mx=x.reduce((s,v)=>s+v,0)/x.length,my=y.reduce((s,v)=>s+v,0)/y.length,n=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0),d=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)*y.reduce((s,v)=>s+(v-my)**2,0));return d?n/d:0},core:any={rules,correlations:{seatFloor:corr('seatBandOccupancy','floorContactOccupancy'),balanceForeground:corr('leftRightBalance','foregroundRatio'),luminanceForeground:corr('luminanceMean','foregroundRatio')},materials:{SKIN:{base:[205,164,142],variation:.11,roughness:.58,specular:.18,microScale:.018},HAIR:{base:[43,33,29],variation:.16,roughness:.42,specular:.30,microScale:.010},GARMENT:{base:[76,102,112],variation:.14,roughness:.72,specular:.08,microScale:.026},WOOD:{base:[103,64,39],variation:.12,roughness:.64,specular:.12,microScale:.032},BACKGROUND:{base:[224,220,214],variation:.025,roughness:.9,specular:.02,microScale:.05},SHADOW:{base:[24,21,19],variation:.04,roughness:.95,specular:0,microScale:.04}},sourceSha256List:obs.map(o=>o.sourceSha256).sort(),ruleSetSha256:''};core.ruleSetSha256=canonicalSha256Object({...core,ruleSetSha256:''});return core}
 synthesize(model:P192Person25DModel,rules:P193RuleSet,scale=1):P193Synthesis{const w=Math.round(model.width*scale),h=Math.round(model.height*scale),rgba=new Uint8Array(w*h*4),normal=new Uint8Array(w*h*4),material=new Uint8Array(w*h*4),depth=new Float32Array(w*h);depth.fill(9);const cps=new Map(model.controlPoints.map(x=>[x.id,x])),sorted=[...model.patches].sort((a,b)=>b.depth-a.depth);for(const p of sorted)this.patch(p,cps,w,h,model.seed,rules,rgba,normal,material,depth);this.faceDetails(model,cps,w,h,rgba,normal,material,depth);this.hairFibers(model,cps,w,h,rgba,depth);this.garmentWrinkles(model,cps,w,h,rgba,normal,depth);this.ambientOcclusion(w,h,rgba,depth);let occupied=0;const colors=new Set<string>();for(let i=0;i<w*h;i++){if(rgba[i*4+3])occupied++;if(i%17===0)colors.add(`${rgba[i*4]>>3},${rgba[i*4+1]>>3},${rgba[i*4+2]>>3}`)}const core={width:w,height:h,ruleSetSha256:rules.ruleSetSha256,modelSha256:model.modelSha256,occupied,colorCount:colors.size,head:Array.from(rgba.slice(0,1024)),tail:Array.from(rgba.slice(-1024))},synthesisSha256=canonicalSha256Object(core);return{width:w,height:h,rgba,normal,material,depth,newPixelRatio:1,colorCount:colors.size,surfaceCoverage:occupied/(w*h),ruleSetSha256:rules.ruleSetSha256,modelSha256:model.modelSha256,synthesisSha256}}
 private patch(p:P192SurfacePatch,cps:Map<string,P192ControlPoint>,w:number,h:number,seed:number,rules:P193RuleSet,rgba:Uint8Array,norm:Uint8Array,mat:Uint8Array,depth:Float32Array){if(p.kind==='BACKGROUND'){for(let i=0;i<w*h;i++)this.write(i,p.depth,.5,.5,p.material,seed,rules,rgba,norm,mat,depth);return}const pts=p.controlPointIds.map(id=>cps.get(id)!).filter(Boolean);if(!pts.length)return;const rr=Math.max(...pts.map(q=>q.radius))*Math.min(w,h)*(p.kind==='GARMENT'||p.kind==='THIGHS'?2.2:1.55),xs=pts.map(q=>q.x*w),ys=pts.map(q=>q.y*h);for(let y=Math.max(0,Math.floor(Math.min(...ys)-rr));y<Math.min(h,Math.ceil(Math.max(...ys)+rr));y++)for(let x=Math.max(0,Math.floor(Math.min(...xs)-rr));x<Math.min(w,Math.ceil(Math.max(...xs)+rr));x++){let f=0;for(let j=0;j<pts.length;j++){const q=pts[j],r=Math.max(8,q.radius*Math.min(w,h)*(p.kind==='GARMENT'||p.kind==='THIGHS'?2.2:1.55));f=Math.max(f,1-((x-q.x*w)**2+(y-q.y*h)**2)/(r*r));if(j){const a=pts[j-1],vx=(q.x-a.x)*w,vy=(q.y-a.y)*h,l=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((x-a.x*w)*vx+(y-a.y*h)*vy)/l)),px=a.x*w+vx*t,py=a.y*h+vy*t;f=Math.max(f,1-((x-px)**2+(y-py)**2)/(r*r));}}if(f>0)this.write(y*w+x,p.depth-p.curvature*f*.06,f,(x/w+y/h)*.5,p.material,seed,rules,rgba,norm,mat,depth)}}
 private write(i:number,z:number,f:number,v:number,k:string,seed:number,r:P193RuleSet,rgba:Uint8Array,norm:Uint8Array,mat:Uint8Array,depth:Float32Array){if(z>=depth[i])return;depth[i]=z;const m=r.materials[k]||r.materials.GARMENT,n=this.noise(i,seed,m.microScale),nx=(this.noise(i+19,seed,1)-.5)*m.variation,ny=(this.noise(i+43,seed,1)-.5)*m.variation,nz=Math.sqrt(Math.max(0,1-nx*nx-ny*ny)),light=Math.max(.18,.28+.72*(nx*-.25+ny*-.35+nz*.90)),ao=.82+.18*f;for(let c=0;c<3;c++)rgba[i*4+c]=Math.max(0,Math.min(255,Math.round(m.base[c]*(1+(n-.5)*m.variation)*light*ao)));rgba[i*4+3]=255;norm[i*4]=Math.round((nx*.5+.5)*255);norm[i*4+1]=Math.round((ny*.5+.5)*255);norm[i*4+2]=Math.round(nz*255);norm[i*4+3]=255;mat[i*4]=Math.round(m.roughness*255);mat[i*4+1]=Math.round(m.specular*255);mat[i*4+2]=Math.round(v*255);mat[i*4+3]=255}
 private faceDetails(model:P192Person25DModel,cps:Map<string,P192ControlPoint>,w:number,h:number,rgba:Uint8Array,norm:Uint8Array,mat:Uint8Array,depth:Float32Array){const q=cps.get('head')!;for(const [dx,dy,rx,ry,c] of [[-.028,-.012,.012,.006,[36,30,28]],[.028,-.012,.012,.006,[36,30,28]],[0,.012,.010,.020,[176,125,105]],[0,.045,.026,.006,[156,80,82]]] as any[]){const cx=(q.x+dx)*w,cy=(q.y+dy)*h;for(let y=cy-ry*h;y<=cy+ry*h;y++)for(let x=cx-rx*w;x<=cx+rx*w;x++){const e=((x-cx)/(rx*w))**2+((y-cy)/(ry*h))**2;if(e>1||x<0||y<0||x>=w||y>=h)continue;const i=Math.floor(y)*w+Math.floor(x);if(.16<depth[i]){depth[i]=.16;rgba[i*4]=c[0];rgba[i*4+1]=c[1];rgba[i*4+2]=c[2];rgba[i*4+3]=255;norm[i*4]=128;norm[i*4+1]=128;norm[i*4+2]=255;norm[i*4+3]=255;mat[i*4]=145;mat[i*4+1]=60;mat[i*4+3]=255}}}}
 private hairFibers(model:P192Person25DModel,cps:Map<string,P192ControlPoint>,w:number,h:number,rgba:Uint8Array,depth:Float32Array){const q=cps.get('head')!;for(let s=0;s<80;s++){const a=(s/79-.5)*Math.PI*.90,x0=q.x*w+Math.sin(a)*q.radius*w*.95,y0=q.y*h-Math.cos(a)*q.radius*h*.88,len=h*(.035+(s%9)/360);for(let t=0;t<1;t+=.02){const x=Math.round(x0+Math.sin(a)*len*t+Math.sin(t*8+s)*1.2),y=Math.round(y0+len*t);if(x<0||y<0||x>=w||y>=h)continue;const i=y*w+x;if(.12<depth[i]){depth[i]=.12;const g=26+Math.round(22*(1-t));rgba[i*4]=g+8;rgba[i*4+1]=g;rgba[i*4+2]=g-2;rgba[i*4+3]=255}}}}
 private garmentWrinkles(model:P192Person25DModel,cps:Map<string,P192ControlPoint>,w:number,h:number,rgba:Uint8Array,norm:Uint8Array,depth:Float32Array){const p=cps.get('pelvis')!;for(let k=-5;k<=5;k++){for(let t=0;t<1;t+=.005){const x=Math.round((p.x+k*.018+Math.sin(t*8+k)*.006)*w),y=Math.round((p.y+t*.17)*h);if(x<0||y<0||x>=w||y>=h)continue;const i=y*w+x;if(depth[i]<.7){rgba[i*4]=Math.max(0,rgba[i*4]-12);rgba[i*4+1]=Math.max(0,rgba[i*4+1]-12);rgba[i*4+2]=Math.max(0,rgba[i*4+2]-12);norm[i*4]=110+k;norm[i*4+1]=145;}}}}
 private ambientOcclusion(w:number,h:number,rgba:Uint8Array,depth:Float32Array){const d=depth.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;if(d[i]>=9)continue;const delta=Math.max(0,d[i]-Math.min(d[i-1],d[i+1],d[i-w],d[i+w])),ao=Math.max(.65,1-delta*2.2);for(let c=0;c<3;c++)rgba[i*4+c]=Math.round(rgba[i*4+c]*ao)}}
 private noise(i:number,seed:number,scale:number){let x=(i^(seed*374761393))>>>0;x=Math.imul(x^(x>>>13),1274126177);x=(x^(x>>>16))>>>0;return((x&65535)/65535*(1-scale)+((x>>>16)&65535)/65535*scale)}
}
export const proceduralPersonRuleSynthesizerP193Service=new ProceduralPersonRuleSynthesizerP193Service();
