import { canonicalSha256Object } from './canonicalSha256Service';
import type { RgbaFrame } from './visualStyleLearningService';
export interface PoseLandmarkFrame{timestampMs:number;landmarks:Array<{name:string;x:number;y:number;z:number;visibility:number}>;sourceSha256:string;}
export interface VisualRepositoryAdoptionReceipt{adoptedConcepts:string[];rejectedConcepts:string[];licenses:string[];localOnly:boolean;receiptSha256:string;}
class RepositoryBackedVisualLearningService{
 recoverPixelGrid(frame:RgbaFrame,maxCell=32){let best={cellSize:1,error:Number.POSITIVE_INFINITY};for(let cell=1;cell<=Math.min(maxCell,frame.width,frame.height);cell+=1){let error=0;let count=0;for(let y=0;y<frame.height;y+=cell)for(let x=0;x<frame.width;x+=cell){const colors:number[][]=[];for(let yy=y;yy<Math.min(y+cell,frame.height);yy+=1)for(let xx=x;xx<Math.min(x+cell,frame.width);xx+=1){const offset=(yy*frame.width+xx)*4;colors.push(frame.rgba.slice(offset,offset+3));}const mean=[0,1,2].map(channel=>colors.reduce((sum,color)=>sum+color[channel],0)/colors.length);error+=colors.reduce((sum,color)=>sum+color.reduce((s,value,index)=>s+(value-mean[index])**2,0),0);count+=colors.length;}const score=count?error/count:Number.POSITIVE_INFINITY;if(score<best.error)best={cellSize:cell,error:score};}const seed={...best,sourceSha256:frame.provenance.contentSha256};return{...seed,receiptSha256:canonicalSha256Object(seed)};}
 oklabPalette(frame:RgbaFrame,colorCount=16,rounds=8){const pixels:number[][]=[];for(let i=0;i<frame.rgba.length;i+=4)if(frame.rgba[i+3]>0)pixels.push(this.rgbToOklab(frame.rgba[i],frame.rgba[i+1],frame.rgba[i+2]));if(!pixels.length)throw new Error('OPAQUE_PIXELS_REQUIRED');const count=Math.max(2,Math.min(colorCount,pixels.length));let centers=Array.from({length:count},(_,index)=>pixels[Math.floor(index*pixels.length/count)]);for(let round=0;round<rounds;round+=1){const groups=centers.map(()=>[] as number[][]);for(const pixel of pixels)groups[this.nearest(pixel,centers)].push(pixel);centers=centers.map((center,index)=>groups[index].length?[0,1,2].map(axis=>groups[index].reduce((sum,pixel)=>sum+pixel[axis],0)/groups[index].length):center);}const palette=centers.map(center=>this.oklabToHex(center));const seed={palette,sourceSha256:frame.provenance.contentSha256,colorSpace:'OKLAB'};return{...seed,paletteSha256:canonicalSha256Object(seed)};}
 learnMotion(frames:PoseLandmarkFrame[]){if(frames.length<2)throw new Error('POSE_SEQUENCE_REQUIRED');const names=[...new Set(frames.flatMap(frame=>frame.landmarks.map(point=>point.name)))].sort();const tracks=names.map(name=>{const points=frames.map(frame=>frame.landmarks.find(point=>point.name===name)).filter((point):point is NonNullable<typeof point>=>Boolean(point)&&point.visibility>=.5);let distance=0;for(let i=1;i<points.length;i+=1)distance+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y,points[i].z-points[i-1].z);return{name,visibleFrames:points.length,totalMotion:distance,averageMotion:points.length>1?distance/(points.length-1):0};});const durationMs=frames[frames.length-1].timestampMs-frames[0].timestampMs;const seed={durationMs,tracks,sourceSha256List:frames.map(frame=>frame.sourceSha256)};return{...seed,motionSha256:canonicalSha256Object(seed)};}
 adoptionReceipt():VisualRepositoryAdoptionReceipt{const seed={adoptedConcepts:['proper-pixel-art:grid-recovery-not-code-copy','quantette:perceptual-oklab-quantization','image-q:alpha-aware-indexed-palette','mediapipe-pose:landmark-trajectory-contract','video-to-pixel-art:canvas-frame-pipeline'],rejectedConcepts:['external-model-training','cloud-upload','source-image-output','GPL-libimagequant-linking','heavy-clothing-model-bundling'],licenses:['MIT-concept-review','Apache-2.0-documentation-review','repository-specific-license-gate'],localOnly:true};return{...seed,receiptSha256:canonicalSha256Object(seed)};}
 private nearest(pixel:number[],centers:number[][]){let best=0;let distance=Infinity;centers.forEach((center,index)=>{const value=pixel.reduce((sum,item,axis)=>sum+(item-center[axis])**2,0);if(value<distance){distance=value;best=index;}});return best;}
 private rgbToOklab(r:number,g:number,b:number){const linear=(value:number)=>{const x=value/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;};const R=linear(r),G=linear(g),B=linear(b);const l=Math.cbrt(.4122214708*R+.5363325363*G+.0514459929*B),m=Math.cbrt(.2119034982*R+.6806995451*G+.1073969566*B),s=Math.cbrt(.0883024619*R+.2817188376*G+.6299787005*B);return[.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s];}
 private oklabToHex(v:number[]){const l=v[0]+.3963377774*v[1]+.2158037573*v[2],m=v[0]-.1055613458*v[1]-.0638541728*v[2],s=v[0]-.0894841775*v[1]-1.291485548*v[2],L=l**3,M=m**3,S=s**3;const linear=[4.0767416621*L-3.3077115913*M+.2309699292*S,-1.2684380046*L+2.6097574011*M-.3413193965*S,-.0041960863*L-.7034186147*M+1.707614701*S];const encode=(x:number)=>Math.round(255*Math.max(0,Math.min(1,x<=.0031308?12.92*x:1.055*x**(1/2.4)-.055)));return'#'+linear.map(encode).map(x=>x.toString(16).padStart(2,'0')).join('');}
}
export const repositoryBackedVisualLearningService=new RepositoryBackedVisualLearningService();
