import { storageService } from '../../../services/storageService';
import { canonicalSha256Object } from './canonicalSha256Service';
import type { ReviewLearningEpisode } from './reviewDecisionLearningService';
import { persistenceReceiptLedgerService, type PersistenceReceipt } from './persistenceReceiptLedgerService';

export type LearningArtifactLifecycle='CANDIDATE'|'USER_APPROVED'|'ACTIVE'|'CONFLICT'|'SUSPENDED'|'SUPERSEDED'|'ARCHIVED'|'PENDING_AFTER_ARTIFACT';
export type LearningArtifactType='FAILURE_PATTERN'|'CORRECTION_PAIR'|'ACCEPTED_PATTERN'|'HOLD_CONDITION';
interface ArtifactLineage {artifactId:string;artifactType:LearningArtifactType;sourceEpisodeIds:string[];packageId:string;packageRevision:number;candidateManifestSha256:string;externalReviewId:string;userDecisionId:string;canonicalSha256:string;lifecycleStatus:LearningArtifactLifecycle;createdAt:number;supersededBy?:string;}
export interface FailurePattern extends ArtifactLineage {artifactType:'FAILURE_PATTERN';symptom:string;rootCause:string;rejectedApproach:string;preferredAlternative:string;scope:'THIS_PACKAGE_ONLY';appliesWhen:string[];doesNotApplyWhen:string[];}
export interface CorrectionPair extends ArtifactLineage {artifactType:'CORRECTION_PAIR';beforeCandidateRef:string;externalRequestedChanges:string[];correctedCandidateRef?:string;correctionReason:string;finalUserDecision:'ACCEPT'|'REJECT'|'REQUEST_CHANGES'|'PARTIAL_ACCEPT'|'PARTIAL_REJECT'|'HOLD';sourceEpisodeId:string;}
export interface AcceptedPattern extends ArtifactLineage {artifactType:'ACCEPTED_PATTERN';acceptedApproach:string;applicableContext:string[];requiredDependencies:string[];preservedInvariants:string[];confidenceEvidence:string[];scope:'THIS_PACKAGE_ONLY'|'GENERALIZED';generalizationEvidencePackageIds:string[];} 
export interface HoldCondition extends ArtifactLineage {artifactType:'HOLD_CONDITION';reconsiderWhen:string[];generalizationAllowed:false;}
export type ReviewLearningArtifact=FailurePattern|CorrectionPair|AcceptedPattern|HoldCondition;
export interface CandidateLearningContext {acceptedPatterns:AcceptedPattern[];rejectedFailurePatterns:FailurePattern[];correctionPairs:CorrectionPair[];componentPatterns:unknown[];teacherMaterials:unknown[];responseSkeletons:unknown[];unresolvedConflicts:string[];ignoredArtifactIds:string[];ignoreReasons:Record<string,string>;usedLearningArtifactIds:string[];appliedFailurePatternIds:string[];appliedCorrectionPairIds:string[];appliedComponentPatternIds:string[];learningContextSha256:string;}
const KEY='miki_review_learning_artifacts_v1';
const RECEIPT_KEY='miki_review_learning_artifact_receipts_v1' as const;
class ReviewLearningArtifactService{
 deriveAndPersist(episode:ReviewLearningEpisode,userDecisionId:string):{artifacts:ReviewLearningArtifact[];receipts:PersistenceReceipt[]}{
  const payload=this.derive(episode,userDecisionId);const existing=this.list();const merged=[...payload,...existing.filter(item=>!payload.some(next=>next.canonicalSha256===item.canonicalSha256))].slice(0,500);storageService.setItem(KEY,JSON.stringify(merged));const loaded=this.list();const receipts=payload.map(item=>{const reloaded=loaded.some(value=>value.artifactId===item.artifactId&&value.canonicalSha256===item.canonicalSha256);if(!reloaded)throw new Error('LEARNING_ARTIFACT_PERSISTENCE_FAILED');return {receiptId:`PR-${canonicalSha256Object({id:item.artifactId,at:item.createdAt}).slice(0,20)}`,entityType:'REVIEW_LEARNING_ARTIFACT' as const,entityId:item.artifactId,entitySha256:item.canonicalSha256,storageKey:KEY,persistedAt:Date.now(),reloaded};});persistenceReceiptLedgerService.registerMany(receipts,RECEIPT_KEY);return {artifacts:payload,receipts};
 }
 retrieve(input:{objective:string;packageId?:string}):CandidateLearningContext{const objective=input.objective.toLowerCase();const ignoredArtifactIds:string[]=[];const ignoreReasons:Record<string,string>={};const usable=this.list().filter(item=>{if(item.lifecycleStatus==='CONFLICT'||item.lifecycleStatus==='SUSPENDED'){ignoredArtifactIds.push(item.artifactId);ignoreReasons[item.artifactId]=item.lifecycleStatus;return false;}if(item.packageId===input.packageId)return true;const terms=this.terms(item);const matched=terms.some(term=>term.length>=4&&objective.includes(term.toLowerCase()));if(!matched){ignoredArtifactIds.push(item.artifactId);ignoreReasons[item.artifactId]='SCOPE_OR_CONTEXT_NOT_MATCHED';}return matched;});const acceptedPatterns=usable.filter((x):x is AcceptedPattern=>x.artifactType==='ACCEPTED_PATTERN');const rejectedFailurePatterns=usable.filter((x):x is FailurePattern=>x.artifactType==='FAILURE_PATTERN');const correctionPairs=usable.filter((x):x is CorrectionPair=>x.artifactType==='CORRECTION_PAIR');const usedLearningArtifactIds=usable.filter(x=>x.artifactType!=='HOLD_CONDITION').map(x=>x.artifactId);const base={acceptedPatterns,rejectedFailurePatterns,correctionPairs,componentPatterns:[],teacherMaterials:[],responseSkeletons:[],unresolvedConflicts:this.list().filter(x=>x.lifecycleStatus==='CONFLICT').map(x=>x.artifactId),ignoredArtifactIds,ignoreReasons,usedLearningArtifactIds,appliedFailurePatternIds:rejectedFailurePatterns.map(x=>x.artifactId),appliedCorrectionPairIds:correctionPairs.map(x=>x.artifactId),appliedComponentPatternIds:[]};return {...base,learningContextSha256:canonicalSha256Object(base)};}
 compareLearningImpact(objective:string,packageId?:string){const withLearning=this.retrieve({objective,packageId});const withoutLearning={acceptedPatterns:[],rejectedFailurePatterns:[],correctionPairs:[],usedLearningArtifactIds:[]};return {withLearning,withoutLearning,usedEpisodeOrArtifactCount:withLearning.usedLearningArtifactIds.length,rejectedMethodRecurrenceBlockIds:withLearning.appliedFailurePatternIds,correctionReuseIds:withLearning.appliedCorrectionPairIds};}
 generalizeAcceptedPatterns():string[]{const rows=this.list();const accepted=rows.filter((x):x is AcceptedPattern=>x.artifactType==='ACCEPTED_PATTERN'&&x.lifecycleStatus!=='SUSPENDED'&&x.lifecycleStatus!=='CONFLICT');const groups=new Map<string,AcceptedPattern[]>();for(const item of accepted){const key=this.normalize(item.acceptedApproach);const group=groups.get(key)||[];group.push(item);groups.set(key,group);}const ids:string[]=[];for(const group of groups.values()){const packages=[...new Set(group.map(x=>x.packageId))];if(packages.length<2)continue;for(const item of group){item.scope='GENERALIZED';item.generalizationEvidencePackageIds=packages;item.lifecycleStatus='ACTIVE';ids.push(item.artifactId);}}if(ids.length)storageService.setItem(KEY,JSON.stringify(rows));return [...new Set(ids)];}
 private normalize(value:string):string{return value.toLowerCase().replace(/[^a-z0-9\\u3040-\\u30ff\\u3400-\\u9fff]+/g,).slice(0,160);}
 generalizeAcceptedPatterns(){const rows=this.list();const accepted=rows.filter((x):x is AcceptedPattern=>x.artifactType==='ACCEPTED_PATTERN'&&x.lifecycleStatus==='CANDIDATE');const groups=new Map<string,AcceptedPattern[]>();for(const item of accepted){const key=item.acceptedApproach.trim().toLowerCase();const group=groups.get(key)||[];group.push(item);groups.set(key,group);}const promoted:AcceptedPattern[]=[];for(const group of groups.values()){const packages=[...new Set(group.map(x=>x.packageId))];if(packages.length<2)continue;for(const item of group)item.lifecycleStatus='SUPERSEDED';const base={...group[0],artifactId:'TEMP',canonicalSha256:'TEMP',lifecycleStatus:'ACTIVE',scope:'GENERALIZED',generalizationEvidencePackageIds:packages,applicableContext:packages};const canonicalSha256=canonicalSha256Object({...base,artifactId:undefined,canonicalSha256:undefined});const promotedItem={...base,canonicalSha256,artifactId:`LART-${canonicalSha256.slice(0,20)}`};promoted.push(promotedItem);}if(promoted.length)storageService.setItem(KEY,JSON.stringify([...promoted,...rows]));return promoted;}
 suspendArtifact(artifactId:string){const rows=this.list();const item=rows.find(row=>row.artifactId===artifactId);if(!item)return undefined;item.lifecycleStatus='SUSPENDED';storageService.setItem(KEY,JSON.stringify(rows));return item;}
 list():ReviewLearningArtifact[]{return this.read<ReviewLearningArtifact>(KEY);}
 private derive(e:ReviewLearningEpisode,userDecisionId:string):ReviewLearningArtifact[]{const createdAt=Date.now();const common={sourceEpisodeIds:[e.episodeId],packageId:e.packageId,packageRevision:e.packageRevision,candidateManifestSha256:e.candidateManifestSha256,externalReviewId:e.externalReviewId,userDecisionId,createdAt,supersededBy:undefined};let body:Omit<ReviewLearningArtifact,keyof ArtifactLineage>|Record<string,unknown>;let artifactType:LearningArtifactType;let lifecycleStatus:LearningArtifactLifecycle='CANDIDATE';if(e.decision==='REJECT'){artifactType='FAILURE_PATTERN';body={symptom:e.risks[0]||e.reason,rootCause:e.reason,rejectedApproach:e.reason,preferredAlternative:e.requestedChanges[0]||'Alternative requires review',scope:'THIS_PACKAGE_ONLY',appliesWhen:[e.packageId],doesNotApplyWhen:[]};}else if(e.decision==='REQUEST_CHANGES'||e.decision==='PARTIAL_ACCEPT'||e.decision==='PARTIAL_REJECT'){artifactType='CORRECTION_PAIR';lifecycleStatus='PENDING_AFTER_ARTIFACT';body={beforeCandidateRef:e.candidateManifestSha256,externalRequestedChanges:[...e.requestedChanges],correctedCandidateRef:undefined,correctionReason:e.reason,finalUserDecision:e.decision,sourceEpisodeId:e.episodeId};}else if(e.decision==='ACCEPT'){artifactType='ACCEPTED_PATTERN';body={acceptedApproach:e.reason,applicableContext:[e.packageId],requiredDependencies:[],preservedInvariants:[],confidenceEvidence:[...e.strengths],scope:'THIS_PACKAGE_ONLY',generalizationEvidencePackageIds:[]};}else{artifactType='HOLD_CONDITION';body={reconsiderWhen:[e.reason],generalizationAllowed:false};}const digestBase={artifactType,...common,lifecycleStatus,...body};const canonicalSha256=canonicalSha256Object(digestBase);return [{artifactId:`LART-${canonicalSha256.slice(0,20)}`,canonicalSha256,...digestBase} as ReviewLearningArtifact];}
 private terms(item:ReviewLearningArtifact):string[]{if(item.artifactType==='FAILURE_PATTERN')return [item.symptom,item.rootCause,...item.appliesWhen];if(item.artifactType==='ACCEPTED_PATTERN')return [item.acceptedApproach,...item.applicableContext];if(item.artifactType==='CORRECTION_PAIR')return [...item.externalRequestedChanges,item.correctionReason];return [];}
 private read<T>(key:string):T[]{try{const raw=storageService.getItem(key);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[];}catch{return [];}}
}
export const reviewLearningArtifactService=new ReviewLearningArtifactService();
