import JSZip from 'jszip';
import { isolatedCandidateWorkspaceService } from './isolatedCandidateWorkspaceService';
import { improvementIntakeRouterService } from './improvementIntakeRouterService';
import { candidateValidationEvidenceService } from './candidateValidationEvidenceService';
import { shadowEvaluationService } from './shadowEvaluationService';
import { singlePromotionGateService } from './singlePromotionGateService';
export interface ReviewZipArtifact { workspaceId:string; fileName:string; sha256:string; blob:Blob; createdAt:number; }
class ReviewZipExportService {private artifacts=new Map<string,ReviewZipArtifact>();
 async create(runId:string,workspaceId:string):Promise<ReviewZipArtifact|undefined>{const run=improvementIntakeRouterService.get(runId);const workspace=isolatedCandidateWorkspaceService.get(workspaceId);if(!run||!workspace)return undefined;const decision=singlePromotionGateService.evaluate(workspaceId);if(!decision.allowed)return undefined;const zip=new JSZip();for(const file of workspace.files)zip.file(`candidate/${file.path}`,file.candidateContent);const manifest={formatVersion:1,run,workspace:{workspaceId:workspace.workspaceId,issueId:workspace.issueId,status:workspace.status,files:workspace.files.map(file=>({path:file.path,baselineSha256:file.baselineSha256,candidateSha256:file.candidateSha256,evidenceIds:file.evidenceIds}))},validationEvidence:candidateValidationEvidenceService.list(workspaceId),shadow:shadowEvaluationService.latest(workspaceId),promotion:decision,generatedAt:Date.now()};zip.file('manifest.json',JSON.stringify(manifest,null,2));zip.file('README_REVIEW.txt','This package is an isolated review candidate. It has not been applied to the running application. Review all candidate files, hashes, validation evidence, and shadow results before manual deployment.');const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const sha256=await this.sha(blob);const artifact={workspaceId,fileName:`MIKI-AI_review_${run.runId}_${workspaceId}.zip`,sha256,blob,createdAt:Date.now()};this.artifacts.set(workspaceId,artifact);isolatedCandidateWorkspaceService.setStatus(workspaceId,'EXPORTED');improvementIntakeRouterService.update(runId,{status:'COMPLETED',workspaceId});return artifact;}
 get(workspaceId:string){return this.artifacts.get(workspaceId);}download(workspaceId:string):boolean{const artifact=this.artifacts.get(workspaceId);if(!artifact)return false;const url=URL.createObjectURL(artifact.blob);const link=document.createElement('a');link.href=url;link.download=artifact.fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}
 private async sha(blob:Blob){const bytes=await blob.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('');}}
export const reviewZipExportService=new ReviewZipExportService();
