import { canonicalSha256Object } from './canonicalSha256Service';

export type SemanticAssetKind='LEXEME'|'CONCEPT'|'INTENT_PATTERN'|'CONSTRAINT_PATTERN'|'DISCOURSE_PATTERN'|'COMPONENT_CONDITION'|'RESEARCH_TRIGGER'|'POSITIVE_EXAMPLE'|'COUNTEREXAMPLE'|'FAILURE_PATTERN'|'REPAIR_RULE';
export interface SemanticAsset{assetId:string;kind:SemanticAssetKind;surface:string;normalized:string;conceptId:string;domain:string;confidence:number;version:number;enabled:boolean;conditions:string[];evidenceIds:string[];counterexampleIds:string[];sha256:string}
export interface SemanticCandidate{conceptId:string;score:number;matchedAssetIds:string[];evidenceIds:string[];counterexampleIds:string[];requiredComponentIds:string[];decision:'ACCEPT'|'CONDITIONAL'|'REJECT'}
export interface SemanticGraphState{generation:number;assets:SemanticAsset[];sha256:string}
export interface SemanticCommit{transactionId:string;expectedGeneration:number;assets:Omit<SemanticAsset,'sha256'>[]}
export interface SemanticUnderstandingResult{input:string;candidates:SemanticCandidate[];selected?:SemanticCandidate;requiresResearch:boolean;mutationCandidates:Array<{semanticKind:string;ownerDomain:string;participantDomains:string[];subjectId:string;payload:Record<string,unknown>}>;receiptSha256:string}

const normalize=(value:string)=>value.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();
class SemanticGraphCoreP208Service{
 bootstrap():SemanticGraphState{const definitions:Array<Omit<SemanticAsset,'sha256'>>=[
 {assetId:'lexeme.continue',kind:'LEXEME',surface:'続き',normalized:'続き',conceptId:'intent.continue',domain:'conversation',confidence:.82,version:1,enabled:true,conditions:['ACTIVE_GOAL_REQUIRED'],evidenceIds:['ev.continue.general'],counterexampleIds:['cx.continue.multiple-open']},
 {assetId:'lexeme.research',kind:'LEXEME',surface:'調べて',normalized:'調べて',conceptId:'intent.research',domain:'research',confidence:.94,version:1,enabled:true,conditions:[],evidenceIds:['ev.research.explicit'],counterexampleIds:[]},
 {assetId:'lexeme.implement',kind:'LEXEME',surface:'実装',normalized:'実装',conceptId:'intent.implement',domain:'capability',confidence:.93,version:1,enabled:true,conditions:[],evidenceIds:['ev.implement.explicit'],counterexampleIds:[]},
 {assetId:'constraint.keep',kind:'CONSTRAINT_PATTERN',surface:'失わない',normalized:'失わない',conceptId:'constraint.preserve',domain:'memory',confidence:.98,version:1,enabled:true,conditions:[],evidenceIds:['ev.preserve.explicit'],counterexampleIds:[]},
 {assetId:'cx.continue.multiple-open',kind:'COUNTEREXAMPLE',surface:'複数の未完了タスクがある状態の「続き」',normalized:'複数の未完了タスクがある状態の「続き」',conceptId:'intent.continue',domain:'conversation',confidence:.99,version:1,enabled:true,conditions:['MULTIPLE_OPEN_GOALS'],evidenceIds:['ev.ambiguity'],counterexampleIds:[]},
 {assetId:'repair.continue.guard',kind:'REPAIR_RULE',surface:'ActiveGoalと直前Topicで参照を限定',normalized:'activegoalと直前topicで参照を限定',conceptId:'intent.continue',domain:'conversation',confidence:.97,version:1,enabled:true,conditions:['ACTIVE_GOAL_REQUIRED'],evidenceIds:['ev.repair.regression'],counterexampleIds:[]},
 {assetId:'component.semantic.graph',kind:'COMPONENT_CONDITION',surface:'意味候補はGraph根拠と反例を共同評価',normalized:'意味候補はgraph根拠と反例を共同評価',conceptId:'capability.semantic-understanding',domain:'capability',confidence:1,version:1,enabled:true,conditions:['GRAPH_COMMIT_REQUIRED'],evidenceIds:['ev.p208.e2e'],counterexampleIds:[]}
 ];return this.state(0,definitions.map(asset=>({...asset,sha256:canonicalSha256Object(asset)})))}
 commit(state:SemanticGraphState,input:SemanticCommit):SemanticGraphState{if(input.expectedGeneration!==state.generation)throw new Error('SEMANTIC_GRAPH_GENERATION_CONFLICT');const byId=new Map(state.assets.map(asset=>[asset.assetId,asset]));for(const raw of input.assets){if(!raw.assetId||!raw.conceptId||raw.confidence<0||raw.confidence>1)throw new Error('SEMANTIC_GRAPH_INVALID_ASSET');byId.set(raw.assetId,{...raw,normalized:normalize(raw.normalized||raw.surface),sha256:canonicalSha256Object(raw)})}return this.state(state.generation+1,[...byId.values()])}
 understand(text:string,state:SemanticGraphState,context:{activeGoalIds:string[];openGoalIds:string[]}):SemanticUnderstandingResult{const value=normalize(text),groups=new Map<string,SemanticAsset[]>();for(const asset of state.assets){if(!asset.enabled||asset.kind==='COUNTEREXAMPLE'||asset.kind==='REPAIR_RULE')continue;if(value.includes(asset.normalized)){const list=groups.get(asset.conceptId)||[];list.push(asset);groups.set(asset.conceptId,list)}}const candidates=[...groups].map(([conceptId,assets])=>{let score=assets.reduce((sum,a)=>sum+a.confidence,0)/assets.length;const counter=state.assets.filter(a=>a.kind==='COUNTEREXAMPLE'&&a.conceptId===conceptId&&a.conditions.includes('MULTIPLE_OPEN_GOALS')&&context.openGoalIds.length>1);score-=counter.length*.45;const missingActive=assets.some(a=>a.conditions.includes('ACTIVE_GOAL_REQUIRED'))&&context.activeGoalIds.length===0;score-=missingActive?.5:0;const decision=score>=.75&&!counter.length?'ACCEPT':score>=.35?'CONDITIONAL':'REJECT';return{conceptId,score:Math.max(0,Math.min(1,score)),matchedAssetIds:assets.map(a=>a.assetId),evidenceIds:assets.flatMap(a=>a.evidenceIds),counterexampleIds:counter.map(a=>a.assetId),requiredComponentIds:decision==='ACCEPT'?['conversation.analysis.composed','semantic.graph.reasoner']:['semantic.graph.reasoner','conversation.reference.guard'],decision} as SemanticCandidate}).sort((a,b)=>b.score-a.score);const selected=candidates.find(c=>c.decision==='ACCEPT');const mutationCandidates=candidates.map(c=>({semanticKind:'KNOWLEDGE',ownerDomain:'conversation',participantDomains:['conversation','memory','research','capability','verification'],subjectId:`semantic:${canonicalSha256Object({text,c})}`,payload:{text,candidate:c,graphGeneration:state.generation}}));return{input:text,candidates,selected,requiresResearch:!selected,mutationCandidates,receiptSha256:canonicalSha256Object({text,candidates,generation:state.generation})}}
 private state(generation:number,assets:SemanticAsset[]):SemanticGraphState{const ordered=[...assets].sort((a,b)=>a.assetId.localeCompare(b.assetId));return{generation,assets:ordered,sha256:canonicalSha256Object({generation,assets:ordered})}}
}
export const semanticGraphCoreP208Service=new SemanticGraphCoreP208Service();
