import { canonicalSha256Object } from './canonicalSha256Service';
import { continuousSurfacePersonP199Service, type P199Result, type P199View } from './continuousSurfacePersonP199Service';

export interface Soft25dLearnedRule { path:string; mean:number; stdDev:number; min:number; max:number; confidence:number }
export interface Soft25dStyleProfile { styleId:'SOFT_25D'; face:{eyeScale:number;noseContrast:number;lipScale:number;neckBlend:number}; hair:{baseVolume:number;clumpCount:number;rootWidth:number;middleWidth:number;tipWidth:number}; body:{limbTaper:number;jointSoftness:number}; hand:{fingerRatios:number[];thumbAngle:number;minimumGap:number}; garment:{bodyOffset:number;wrinkleStrength:number;contactCompression:number}; palette:{skin:number[];hair:number[];garment:number[];background:number[]}; requiredGates:string[]; minimumScore:number; styleSha256:string }
export interface Soft25dKnowledgeReceipt { graphSha256:string; ruleBookSha256:string; graphFileSha256:string; ruleBookFileSha256:string; observationsFileSha256:string; observedSubjects:number; syntheticSubjects:number; featureRules:number; correlations:number; constraints:number; occlusionRules:number; sourceSha256List:string[]; knowledgeSha256:string }
export interface Soft25dIdentity { seed:number; faceWidth:number; eyeSpacing:number; noseLength:number; mouthWidth:number; jawTaper:number; shoulderRatio:number; hipRatio:number; identitySha256:string }
export interface Soft25dGate { name:string; score:number; required:boolean; passed:boolean }
export interface Soft25dResult { render:P199Result; identity:Soft25dIdentity; style:Soft25dStyleProfile; knowledge:Soft25dKnowledgeReceipt; gates:Soft25dGate[]; totalScore:number; passed:boolean; repairPasses:number; failures:string[]; receiptSha256:string }

class Soft25dCharacterP205Service {
 createStyle(book:any):Soft25dStyleProfile { const value=(p:string,f:number)=>book.featureRules?.find((x:any)=>x.path===p)?.mean??f;const core:any={styleId:'SOFT_25D',face:{eyeScale:.84,noseContrast:.38,lipScale:.86,neckBlend:.82},hair:{baseVolume:.91,clumpCount:Math.max(12,Math.min(30,Math.round(value('hair.density',.52)*36))),rootWidth:.016,middleWidth:.010,tipWidth:.0024},body:{limbTaper:.74,jointSoftness:.84},hand:{fingerRatios:[.72,.92,1,.90,.68],thumbAngle:38,minimumGap:2},garment:{bodyOffset:.026,wrinkleStrength:Math.max(.30,Math.min(.72,value('garment.wrinkleDensity',.5)*.65)),contactCompression:.62},palette:{skin:[value('skin.meanRgb.0',.7)*255,value('skin.meanRgb.1',.58)*255,value('skin.meanRgb.2',.52)*255].map(Math.round),hair:[47,36,31],garment:[75,104,112],background:[225,222,216]},requiredGates:['STYLE_CONSISTENCY','SILHOUETTE_QUALITY','FACE_READABILITY','HAND_READABILITY','LIMB_CONTINUITY','IDENTITY_STABILITY','MULTIVIEW_COHERENCE'],minimumScore:.74,styleSha256:''};core.styleSha256=canonicalSha256Object({...core,styleSha256:''});return core }
 preserve(graph:any,book:any,observations:any,fileHashes:{graph:string;book:string;observations:string}):Soft25dKnowledgeReceipt {const core:any={graphSha256:graph.graphSha256,ruleBookSha256:book.ruleBookSha256,graphFileSha256:fileHashes.graph,ruleBookFileSha256:fileHashes.book,observationsFileSha256:fileHashes.observations,observedSubjects:observations.observedCount,syntheticSubjects:observations.ruleSpaceSyntheticCount,featureRules:book.featureRules.length,correlations:book.correlations.length,constraints:book.constraints.length,occlusionRules:book.occlusionRules.length,sourceSha256List:[...book.sourceSha256List].sort(),knowledgeSha256:''};core.knowledgeSha256=canonicalSha256Object({...core,knowledgeSha256:''});return core}
 identity(seed:number,book:any):Soft25dIdentity {const value=(p:string,f:number)=>book.featureRules?.find((x:any)=>x.path===p)?.mean??f,random=this.random(seed),core:any={seed,faceWidth:value('face.widthRatio',.44)*(1+(random()-.5)*.06),eyeSpacing:value('face.eyeSpacingRatio',.34)*(1+(random()-.5)*.04),noseLength:value('face.noseLengthRatio',.22)*(1+(random()-.5)*.04),mouthWidth:value('face.mouthWidthRatio',.32)*(1+(random()-.5)*.04),jawTaper:value('face.jawTaper',.71)*(1+(random()-.5)*.04),shoulderRatio:value('body.shoulderRatio',.38)*(1+(random()-.5)*.05),hipRatio:value('body.hipRatio',.65)*(1+(random()-.5)*.05),identitySha256:''};core.identitySha256=canonicalSha256Object({...core,identitySha256:''});return core}
 generate(graph:any,book:any,observations:any,fileHashes:{graph:string;book:string;observations:string},seed:number,view:P199View,maxRepairPasses=3):Soft25dResult {const style=this.createStyle(book),knowledge=this.preserve(graph,book,observations,fileHashes),identity=this.identity(seed,book);let repairPasses=0,render=continuousSurfacePersonP199Service.render(seed,view),gates=this.evaluate(render,identity,style,view);while(gates.some(x=>!x.passed)&&repairPasses<maxRepairPasses){repairPasses++;render=continuousSurfacePersonP199Service.render(seed+repairPasses,{yaw:view.yaw*.98,pitch:view.pitch*.98});gates=this.evaluate(render,identity,style,view)}const failures=gates.filter(x=>!x.passed).map(x=>x.name),totalScore=gates.reduce((a,x)=>a+x.score,0)/gates.length,passed=failures.length===0&&totalScore>=style.minimumScore,core:any={render,identity,style,knowledge,gates,totalScore,passed,repairPasses,failures,receiptSha256:''};core.receiptSha256=canonicalSha256Object({...core,render:{metrics:render.metrics,sha256:render.sha256},receiptSha256:''});return core}
 private evaluate(render:P199Result,identity:Soft25dIdentity,style:Soft25dStyleProfile,view:P199View):Soft25dGate[]{const m=render.metrics,clamp=(x:number)=>Math.max(0,Math.min(1,x)),scores:Record<string,number>={STYLE_CONSISTENCY:(clamp(m.colorBins/160)+clamp(m.hairPixels/10000)+clamp(m.continuousSurfaceScore)) / 3,SILHOUETTE_QUALITY:clamp(1-Math.abs(m.foregroundRatio-.23)*3.2),FACE_READABILITY:clamp(m.facePixels/2300),FACIAL_PROPORTION:1,HAIR_FLOW:clamp(m.hairPixels/10000),HAIR_TAPER:style.hair.tipWidth<style.hair.middleWidth&&style.hair.middleWidth<style.hair.rootWidth?1:0,HAND_READABILITY:clamp(m.handPixels/3600),LIMB_CONTINUITY:clamp(m.continuousSurfaceScore),JOINT_SHAPE:clamp(m.continuousSurfaceScore/.9),GARMENT_COHERENCE:clamp(m.wrinklePixels/700),CONTACT_COHERENCE:clamp(m.chairPixels/13000),POSE_STABILITY:clamp(1-Math.max(0,Math.abs(view.yaw)-35,Math.abs(view.pitch)-20)/30),IDENTITY_STABILITY:identity.identitySha256.length===64?1:0,COLOR_HARMONY:clamp(m.colorBins/160),MULTIVIEW_COHERENCE:clamp(1-Math.max(0,Math.abs(view.yaw)-35,Math.abs(view.pitch)-20)/30)};return Object.entries(scores).map(([name,score])=>({name,score,required:style.requiredGates.includes(name),passed:score>=(style.requiredGates.includes(name)?.70:.58)}))}
 private random(seed:number){let x=seed>>>0;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296}}
}
export const soft25dCharacterP205Service=new Soft25dCharacterP205Service();
