import { canonicalSha256Object } from './canonicalSha256Service';
export type CandidateLifecycleState='GENERATED'|'VALIDATED'|'REVIEWED'|'PACKAGED'|'ADOPTED'|'INVALIDATED'|'ROLLED_BACK'|'REJECTED';
export interface CandidateLifecycleNode {candidateId:string;revision:number;parentCandidateIds:string[];state:CandidateLifecycleState;artifactSha256:string;createdAt:number;updatedAt:number;metadata:Record<string,unknown>;}
export interface CandidateLifecycleTransition {transitionId:string;candidateId:string;from?:CandidateLifecycleState;to:CandidateLifecycleState;at:number;reason:string;evidenceIds:string[];transactionId?:string;}
const ALLOWED:Record<CandidateLifecycleState,CandidateLifecycleState[]>= {GENERATED:['VALIDATED','REJECTED','INVALIDATED'],VALIDATED:['REVIEWED','REJECTED','INVALIDATED'],REVIEWED:['PACKAGED','REJECTED','INVALIDATED'],PACKAGED:['ADOPTED','REJECTED','INVALIDATED'],ADOPTED:['INVALIDATED','ROLLED_BACK'],INVALIDATED:[],ROLLED_BACK:[],REJECTED:[]};
class UnifiedCandidateLifecycleGraphService {
 private nodes=new Map<string,CandidateLifecycleNode>();private transitions:CandidateLifecycleTransition[]=[];
 register(input:Omit<CandidateLifecycleNode,'createdAt'|'updatedAt'>):CandidateLifecycleNode {if(this.nodes.has(input.candidateId))throw new Error(`CANDIDATE_ALREADY_REGISTERED:${input.candidateId}`);for(const parent of input.parentCandidateIds)if(!this.nodes.has(parent))throw new Error(`CANDIDATE_PARENT_NOT_FOUND:${parent}`);if(input.parentCandidateIds.includes(input.candidateId))throw new Error('CANDIDATE_SELF_PARENT');const now=Date.now();const node={...input,parentCandidateIds:[...new Set(input.parentCandidateIds)],createdAt:now,updatedAt:now};this.nodes.set(node.candidateId,node);this.record(node.candidateId,undefined,node.state,'REGISTERED',[]);return this.get(node.candidateId)!;}
 transition(candidateId:string,to:CandidateLifecycleState,reason:string,evidenceIds:string[]=[],transactionId?:string):CandidateLifecycleNode {const current=this.nodes.get(candidateId);if(!current)throw new Error(`CANDIDATE_NOT_FOUND:${candidateId}`);if(!ALLOWED[current.state].includes(to))throw new Error(`ILLEGAL_CANDIDATE_TRANSITION:${current.state}->${to}`);const from=current.state;current.state=to;current.updatedAt=Date.now();this.record(candidateId,from,to,reason,evidenceIds,transactionId);return this.get(candidateId)!;}
 private record(candidateId:string,from:CandidateLifecycleState|undefined,to:CandidateLifecycleState,reason:string,evidenceIds:string[],transactionId?:string){const body={candidateId,from,to,reason,evidenceIds:[...new Set(evidenceIds)].sort(),transactionId,ordinal:this.transitions.length};this.transitions.push({transitionId:canonicalSha256Object(body),...body,at:Date.now()});}
 get(candidateId:string):CandidateLifecycleNode|undefined {const node=this.nodes.get(candidateId);return node?{...node,parentCandidateIds:[...node.parentCandidateIds],metadata:{...node.metadata}}:undefined;}
 traceCandidate(candidateId:string){const node=this.get(candidateId);if(!node)return undefined;return {node,ancestors:this.listAncestors(candidateId),descendants:this.listDescendants(candidateId),transitions:this.transitions.filter(x=>x.candidateId===candidateId).map(x=>({...x,evidenceIds:[...x.evidenceIds]}))};}
 listAncestors(candidateId:string):CandidateLifecycleNode[]{const result:CandidateLifecycleNode[]=[];const seen=new Set<string>();const visit=(id:string)=>{for(const parent of this.nodes.get(id)?.parentCandidateIds||[])if(!seen.has(parent)){seen.add(parent);const node=this.get(parent);if(node)result.push(node);visit(parent);}};visit(candidateId);return result;}
 listDescendants(candidateId:string):CandidateLifecycleNode[]{const result:CandidateLifecycleNode[]=[];const seen=new Set<string>();const visit=(id:string)=>{for(const node of this.nodes.values())if(node.parentCandidateIds.includes(id)&&!seen.has(node.candidateId)){seen.add(node.candidateId);result.push(this.get(node.candidateId)!);visit(node.candidateId);}};visit(candidateId);return result;}
 resetForTest(){this.nodes.clear();this.transitions=[];}
}
export const unifiedCandidateLifecycleGraphService=new UnifiedCandidateLifecycleGraphService();
