import { canonicalSha256Object } from './canonicalSha256Service';
export type LandmarkName='headTop'|'chin'|'leftShoulder'|'rightShoulder'|'leftHip'|'rightHip'|'leftKnee'|'rightKnee'|'leftAnkle'|'rightAnkle';
export interface Point2{ x:number;y:number;confidence:number; }
export interface BodyGeometryInput{landmarks:Partial<Record<LandmarkName,Point2>>;silhouetteWidths:{y:number;width:number;confidence:number}[];garmentBulkEstimate:number;sourceSha256:string;}
export interface BodyGeometryEstimate{shoulderToHeight:number;waistToHeight:number;hipToHeight:number;torsoToHeight:number;legToHeight:number;silhouetteConfidence:number;poseConfidence:number;garmentBulk:number;uncertainty:number;notHealthAssessment:true;estimateSha256:string;}
export interface DepthMap{width:number;height:number;values:number[];sourceSha256:string;}
export interface Layer25D{id:string;kind:'BACKGROUND'|'MIDGROUND'|'SUBJECT'|'FOREGROUND';near:number;far:number;parallax:number;maskThreshold:[number,number];occlusionOrder:number;}
export interface Scene25D{width:number;height:number;layers:Layer25D[];camera:{maxOffsetX:number;maxOffsetY:number;focusDepth:number};depthSha256:string;sceneSha256:string;}
export interface RepositoryAdoptionCandidate{name:string;url:string;license:string;adoption:'CONCEPT'|'OPTIONAL_ADAPTER'|'REJECTED';reason:string;bundled:false;}
class VisualLearningBody25dService{
 inferBodyGeometry(input:BodyGeometryInput):BodyGeometryEstimate{const lm=input.landmarks;const ys=Object.values(lm).filter(Boolean).map(p=>p!.y);if(ys.length<4)throw new Error('BODY_LANDMARKS_INSUFFICIENT');const top=Math.min(...ys),bottom=Math.max(...ys),height=Math.max(.001,bottom-top);const dist=(a?:Point2,b?:Point2)=>a&&b?Math.hypot(a.x-b.x,a.y-b.y):NaN;const shoulder=dist(lm.leftShoulder,lm.rightShoulder);const hip=dist(lm.leftHip,lm.rightHip);const torso=lm.leftShoulder&&lm.rightShoulder&&lm.leftHip&&lm.rightHip?Math.abs(((lm.leftHip.y+lm.rightHip.y)-(lm.leftShoulder.y+lm.rightShoulder.y))/2):NaN;const leg=lm.leftHip&&lm.leftAnkle?dist(lm.leftHip,lm.leftAnkle):lm.rightHip&&lm.rightAnkle?dist(lm.rightHip,lm.rightAnkle):NaN;const waistSamples=input.silhouetteWidths.filter(x=>x.y>.42&&x.y<.62);const waist=waistSamples.length?waistSamples.reduce((n,x)=>n+x.width*x.confidence,0)/Math.max(.001,waistSamples.reduce((n,x)=>n+x.confidence,0)):NaN;const poseConf=Object.values(lm).filter(Boolean).reduce((n,p)=>n+p!.confidence,0)/Object.values(lm).filter(Boolean).length;const silConf=input.silhouetteWidths.length?input.silhouetteWidths.reduce((n,x)=>n+x.confidence,0)/input.silhouetteWidths.length:0;const missing=[shoulder,hip,torso,leg,waist].filter(Number.isNaN).length;const seed={shoulderToHeight:Number.isNaN(shoulder)?0:shoulder/height,waistToHeight:Number.isNaN(waist)?0:waist/height,hipToHeight:Number.isNaN(hip)?0:hip/height,torsoToHeight:Number.isNaN(torso)?0:torso/height,legToHeight:Number.isNaN(leg)?0:leg/height,silhouetteConfidence:silConf,poseConfidence:poseConf,garmentBulk:input.garmentBulkEstimate,uncertainty:Math.min(1,.15+missing*.12+(1-poseConf)*.35+(1-silConf)*.25+input.garmentBulkEstimate*.2),notHealthAssessment:true as const};return{...seed,estimateSha256:canonicalSha256Object({...seed,sourceSha256:input.sourceSha256})};}
 compose25D(depth:DepthMap):Scene25D{if(depth.values.length!==depth.width*depth.height)throw new Error('INVALID_DEPTH_MAP');const sorted=[...depth.values].sort((a,b)=>a-b);const q=(p:number)=>sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*p))];const bands:[Layer25D['kind'],number,number,number][]=[['BACKGROUND',0,q(.2),.08],['MIDGROUND',q(.2),q(.55),.22],['SUBJECT',q(.55),q(.82),.48],['FOREGROUND',q(.82),1,.78]];const layers=bands.map((b,i)=>({id:`DEPTH_LAYER_${i+1}`,kind:b[0],near:b[1],far:b[2],parallax:b[3],maskThreshold:[b[1],b[2]] as [number,number],occlusionOrder:i}));const seed={width:depth.width,height:depth.height,layers,camera:{maxOffsetX:24,maxOffsetY:14,focusDepth:q(.65)},depthSha256:depth.sourceSha256};return{...seed,sceneSha256:canonicalSha256Object(seed)};}
 adoptionRegistry():RepositoryAdoptionCandidate[]{return[
{name:'Depth Anything V2 Small',url:'https://github.com/DepthAnything/Depth-Anything-V2',license:'Apache-2.0 code/small weights; verify artifact',adoption:'OPTIONAL_ADAPTER',reason:'monocular relative depth for 2.5D',bundled:false},
{name:'MediaPipe Pose',url:'https://github.com/google-ai-edge/mediapipe',license:'Apache-2.0',adoption:'CONCEPT',reason:'pose landmark contract and mobile deployment patterns',bundled:false},
{name:'MMPose RTMPose',url:'https://github.com/open-mmlab/mmpose',license:'Apache-2.0 code; verify model/data',adoption:'OPTIONAL_ADAPTER',reason:'whole-body keypoints when runtime permits',bundled:false},
{name:'Image Super-Resolution',url:'https://github.com/idealo/image-super-resolution',license:'Apache-2.0',adoption:'CONCEPT',reason:'residual dense reconstruction and evaluation concepts; archived repository',bundled:false},
{name:'Monodepth2',url:'https://github.com/nianticlabs/monodepth2',license:'non-commercial',adoption:'REJECTED',reason:'license incompatible with unrestricted adoption',bundled:false}
];}
 selfImprovementEvidence(body:BodyGeometryEstimate,scene:Scene25D){const seed={evidenceKind:'VISUAL_BODY_25D',bodyEstimateSha256:body.estimateSha256,sceneSha256:scene.sceneSha256,uses:['BODY_GEOMETRY_REGRESSION','DEPTH_LAYER_REGRESSION','PARALLAX_RENDERER_CANDIDATE'],directProductionMutation:false};return{...seed,evidenceSha256:canonicalSha256Object(seed)};}
}
export const visualLearningBody25dService=new VisualLearningBody25dService();
