import { canonicalSha256Object } from './canonicalSha256Service';
export type VisualLayerKind='SUBJECT_APPEARANCE'|'HAIR'|'FACE_STYLE'|'BODY_SHAPE'|'GARMENT_UPPER'|'GARMENT_LOWER'|'OUTERWEAR'|'FOOTWEAR'|'ACCESSORY'|'POSE'|'BACKGROUND'|'PALETTE'|'MOTION';
export interface VisualPhysicalAsset{assetId:string;kind:'SOURCE_REFERENCE'|'MASK'|'INDEXED_PIXEL'|'SPRITE_SHEET'|'TILE_SET'|'VIDEO_KEYFRAMES'|'CANVAS_SPEC';relativePath:string;mimeType:string;sha256:string;bytes:number;sourcePageUrl?:string;mediaUrl?:string;license:string;attribution?:string;temporary:boolean;}
export interface VisualSemanticLayer{layerId:string;kind:VisualLayerKind;assetIds:string[];maskAssetId?:string;parameters:Record<string,number|string|boolean>;sourceSha256List:string[];}
export interface VisualAssetLibraryManifest{libraryId:string;assets:VisualPhysicalAsset[];layers:VisualSemanticLayer[];manifestSha256:string;}
class VisualAssetLibraryService{
 create(libraryId:string,assets:VisualPhysicalAsset[],layers:VisualSemanticLayer[]):VisualAssetLibraryManifest{for(const asset of assets)this.validateAsset(asset);const ids=new Set(assets.map(x=>x.assetId));for(const layer of layers){for(const id of layer.assetIds)if(!ids.has(id))throw new Error(`VISUAL_LAYER_ASSET_MISSING:${id}`);if(layer.maskAssetId&&!ids.has(layer.maskAssetId))throw new Error(`VISUAL_LAYER_MASK_MISSING:${layer.maskAssetId}`);}const seed={libraryId,assets:[...assets].sort((a,b)=>a.assetId.localeCompare(b.assetId)),layers:[...layers].sort((a,b)=>a.layerId.localeCompare(b.layerId))};return{...seed,manifestSha256:canonicalSha256Object(seed)};}
 composeAvatar(library:VisualAssetLibraryManifest,input:{appearanceLayerId:string;garmentLayerIds:string[];poseLayerId?:string}){const required=[input.appearanceLayerId,...input.garmentLayerIds,...(input.poseLayerId?[input.poseLayerId]:[])];const selected=required.map(id=>library.layers.find(layer=>layer.layerId===id));if(selected.some(value=>!value))throw new Error('AVATAR_LAYER_MISSING');const seed={libraryId:library.libraryId,selectedLayerIds:required,renderOrder:['BODY_SHAPE','SUBJECT_APPEARANCE','GARMENT_LOWER','GARMENT_UPPER','OUTERWEAR','FOOTWEAR','ACCESSORY','HAIR','POSE'],outputKinds:['INDEXED_PIXEL','CANVAS_SPEC','SPRITE_SHEET']};return{...seed,compositionSha256:canonicalSha256Object(seed)};}
 deliveryCandidates(library:VisualAssetLibraryManifest){return library.assets.filter(asset=>Boolean(asset.mediaUrl||asset.sourcePageUrl)).map(asset=>({assetId:asset.assetId,imageUrl:asset.mimeType.startsWith('image/')?asset.mediaUrl:undefined,videoUrl:asset.mimeType.startsWith('video/')?asset.mediaUrl:undefined,sourcePageUrl:asset.sourcePageUrl,license:asset.license,attribution:asset.attribution,downloadable:!asset.temporary}));}
 selfImprovementEvidence(library:VisualAssetLibraryManifest){return{evidenceType:'VISUAL_ASSET_LIBRARY',manifestSha256:library.manifestSha256,paths:library.assets.map(x=>x.relativePath),layerKinds:[...new Set(library.layers.map(x=>x.kind))].sort(),allowedUses:['AVATAR_CANDIDATE','CANVAS_CANDIDATE','PIXEL_ART_CANDIDATE','VISUAL_REGRESSION_FIXTURE'],directProductionMutation:false};}
 private validateAsset(asset:VisualPhysicalAsset){if(!asset.relativePath.startsWith('visual/'))throw new Error('VISUAL_ASSET_PATH_INVALID');if(!/^[a-f0-9]{64}$/i.test(asset.sha256))throw new Error('VISUAL_ASSET_SHA_INVALID');if(asset.bytes<0)throw new Error('VISUAL_ASSET_SIZE_INVALID');}
}
export const visualAssetLibraryService=new VisualAssetLibraryService();
