import { canonicalSha256Object } from './canonicalSha256Service';
import { comprehensiveVisualProfileService, visualFact, type ComprehensiveVisualProfile, type EvidenceState } from './comprehensiveVisualProfileService';

export type BodyArchetypeId='NEUTRAL_BASELINE'|'UPPER_BODY_WIDE'|'LOWER_BODY_WIDE'|'STRAIGHT_TORSO'|'CURVED_TORSO'|'TALL_PROPORTION'|'SHORT_PROPORTION'|'SLENDER_BUILD'|'BROAD_BUILD'|'CUSTOM_BLEND';
export interface BodyArchetypeVector {headToHeight:number;shoulderWidth:number;ribcageWidth:number;ribcageDepth:number;chestSurfaceWidth:number;chestProjection:number;abdomenWidth:number;abdomenProjection:number;waistWidth:number;pelvisWidth:number;pelvisDepth:number;upperArmWidth:number;forearmWidth:number;thighWidth:number;calfWidth:number;legToHeight:number;torsoToHeight:number;}
export interface SkinAppearanceProfile {baseColors:string[];shadowColors:string[];highlightColors:string[];undertone:'COOL'|'NEUTRAL'|'WARM'|'OLIVE'|'UNKNOWN';saturation:number;valueRange:number;regionVariation:number;specular:number;subsurfaceHint:number;source:'OBSERVED'|'USER_DEFINED'|'PALETTE_PRESET';confidence:number;}
export interface PixelFidelityPlan {mode:'PIXEL_NATIVE'|'PIXEL_HD'|'ILLUSTRATION_HD';logicalWidth:number;logicalHeight:number;outputWidth:number;outputHeight:number;integerScale:number;paletteLimit:number;edgeMode:'HARD_GRID'|'CONTROLLED_AA';dither:'NONE'|'ORDERED'|'ERROR_DIFFUSION';detailPasses:string[];tileSize:number;frameConsistency:boolean;planSha256:string;}
const A:Record<Exclude<BodyArchetypeId,'CUSTOM_BLEND'>,BodyArchetypeVector>={
 NEUTRAL_BASELINE:{headToHeight:.13,shoulderWidth:.25,ribcageWidth:.25,ribcageDepth:.16,chestSurfaceWidth:.26,chestProjection:.08,abdomenWidth:.23,abdomenProjection:.07,waistWidth:.21,pelvisWidth:.24,pelvisDepth:.16,upperArmWidth:.07,forearmWidth:.055,thighWidth:.105,calfWidth:.072,legToHeight:.49,torsoToHeight:.32},
 UPPER_BODY_WIDE:{headToHeight:.125,shoulderWidth:.29,ribcageWidth:.28,ribcageDepth:.18,chestSurfaceWidth:.29,chestProjection:.09,abdomenWidth:.24,abdomenProjection:.07,waistWidth:.22,pelvisWidth:.235,pelvisDepth:.16,upperArmWidth:.082,forearmWidth:.062,thighWidth:.105,calfWidth:.074,legToHeight:.48,torsoToHeight:.33},
 LOWER_BODY_WIDE:{headToHeight:.13,shoulderWidth:.235,ribcageWidth:.235,ribcageDepth:.155,chestSurfaceWidth:.245,chestProjection:.08,abdomenWidth:.235,abdomenProjection:.075,waistWidth:.21,pelvisWidth:.285,pelvisDepth:.19,upperArmWidth:.065,forearmWidth:.052,thighWidth:.125,calfWidth:.08,legToHeight:.49,torsoToHeight:.31},
 STRAIGHT_TORSO:{headToHeight:.13,shoulderWidth:.255,ribcageWidth:.25,ribcageDepth:.16,chestSurfaceWidth:.255,chestProjection:.075,abdomenWidth:.235,abdomenProjection:.07,waistWidth:.23,pelvisWidth:.245,pelvisDepth:.165,upperArmWidth:.07,forearmWidth:.055,thighWidth:.108,calfWidth:.073,legToHeight:.48,torsoToHeight:.33},
 CURVED_TORSO:{headToHeight:.13,shoulderWidth:.245,ribcageWidth:.245,ribcageDepth:.165,chestSurfaceWidth:.27,chestProjection:.105,abdomenWidth:.225,abdomenProjection:.075,waistWidth:.19,pelvisWidth:.28,pelvisDepth:.19,upperArmWidth:.068,forearmWidth:.053,thighWidth:.12,calfWidth:.077,legToHeight:.49,torsoToHeight:.31},
 TALL_PROPORTION:{headToHeight:.115,shoulderWidth:.245,ribcageWidth:.24,ribcageDepth:.155,chestSurfaceWidth:.25,chestProjection:.08,abdomenWidth:.22,abdomenProjection:.065,waistWidth:.205,pelvisWidth:.235,pelvisDepth:.155,upperArmWidth:.063,forearmWidth:.05,thighWidth:.097,calfWidth:.067,legToHeight:.53,torsoToHeight:.3},
 SHORT_PROPORTION:{headToHeight:.145,shoulderWidth:.265,ribcageWidth:.265,ribcageDepth:.17,chestSurfaceWidth:.275,chestProjection:.085,abdomenWidth:.25,abdomenProjection:.08,waistWidth:.23,pelvisWidth:.26,pelvisDepth:.175,upperArmWidth:.075,forearmWidth:.06,thighWidth:.115,calfWidth:.08,legToHeight:.45,torsoToHeight:.35},
 SLENDER_BUILD:{headToHeight:.13,shoulderWidth:.235,ribcageWidth:.225,ribcageDepth:.145,chestSurfaceWidth:.235,chestProjection:.065,abdomenWidth:.205,abdomenProjection:.06,waistWidth:.19,pelvisWidth:.22,pelvisDepth:.145,upperArmWidth:.057,forearmWidth:.045,thighWidth:.09,calfWidth:.061,legToHeight:.5,torsoToHeight:.31},
 BROAD_BUILD:{headToHeight:.125,shoulderWidth:.29,ribcageWidth:.285,ribcageDepth:.19,chestSurfaceWidth:.3,chestProjection:.105,abdomenWidth:.27,abdomenProjection:.1,waistWidth:.25,pelvisWidth:.275,pelvisDepth:.19,upperArmWidth:.09,forearmWidth:.07,thighWidth:.13,calfWidth:.088,legToHeight:.47,torsoToHeight:.34}
};
class VisualArchetypePixelFidelityService {
 archetype(id:Exclude<BodyArchetypeId,'CUSTOM_BLEND'>){return structuredClone(A[id]);}
 blend(weights:Partial<Record<Exclude<BodyArchetypeId,'CUSTOM_BLEND'>,number>>):BodyArchetypeVector {const entries=Object.entries(weights).filter(([,v])=>Number(v)>0) as [Exclude<BodyArchetypeId,'CUSTOM_BLEND'>,number][];const total=entries.reduce((n,[,v])=>n+v,0);if(total<=0)throw new Error('ARCHETYPE_WEIGHT_REQUIRED');const keys=Object.keys(A.NEUTRAL_BASELINE) as (keyof BodyArchetypeVector)[];return Object.fromEntries(keys.map(k=>[k,entries.reduce((n,[id,w])=>n+A[id][k]*w,0)/total])) as unknown as BodyArchetypeVector;}
 applyUnknown(profile:ComprehensiveVisualProfile,vector:BodyArchetypeVector,sourceSha:string):ComprehensiveVisualProfile {const sf=(v:number)=>visualFact(v,'LEARNED_COMPLETION' as EvidenceState,.45,[sourceSha]);const patch:any={head:{headToHeight:profile.head.headToHeight.value===null?sf(vector.headToHeight):profile.head.headToHeight},neckShoulders:{shoulderWidth:profile.neckShoulders.shoulderWidth.value===null?sf(vector.shoulderWidth):profile.neckShoulders.shoulderWidth},ribcage:{middleWidth:profile.ribcage.middleWidth.value===null?sf(vector.ribcageWidth):profile.ribcage.middleWidth,depth:profile.ribcage.depth.value===null?sf(vector.ribcageDepth):profile.ribcage.depth},chestSurface:{totalWidth:profile.chestSurface.totalWidth.value===null?sf(vector.chestSurfaceWidth):profile.chestSurface.totalWidth,forwardProjection:profile.chestSurface.forwardProjection.value===null?sf(vector.chestProjection):profile.chestSurface.forwardProjection},abdomen:{middleWidth:profile.abdomen.middleWidth.value===null?sf(vector.abdomenWidth):profile.abdomen.middleWidth,middleProjection:profile.abdomen.middleProjection.value===null?sf(vector.abdomenProjection):profile.abdomen.middleProjection},waistPelvis:{waistWidth:profile.waistPelvis.waistWidth.value===null?sf(vector.waistWidth):profile.waistPelvis.waistWidth,pelvisWidth:profile.waistPelvis.pelvisWidth.value===null?sf(vector.pelvisWidth):profile.waistPelvis.pelvisWidth,pelvisDepth:profile.waistPelvis.pelvisDepth.value===null?sf(vector.pelvisDepth):profile.waistPelvis.pelvisDepth}};return comprehensiveVisualProfileService.revise(profile,patch,[sourceSha]);}
 skin(profile:ComprehensiveVisualProfile,input:SkinAppearanceProfile,sourceSha:string){this.validateSkin(input);return comprehensiveVisualProfileService.revise(profile,{appearance:{...profile.appearance,skinPalette:visualFact([...input.baseColors,...input.shadowColors,...input.highlightColors],input.source==='OBSERVED'?'OBSERVED':'USER_DEFINED',input.confidence,[sourceSha])}},[sourceSha]);}
 pixelPlan(input:{mode:PixelFidelityPlan['mode'];logicalWidth:number;logicalHeight:number;scale?:number;paletteLimit?:number;frameConsistency?:boolean}):PixelFidelityPlan {const scale=input.scale??(input.mode==='PIXEL_HD'?8:input.mode==='PIXEL_NATIVE'?4:1);if(!Number.isInteger(scale)||scale<1||scale>16)throw new Error('INTEGER_PIXEL_SCALE_REQUIRED');const seed={mode:input.mode,logicalWidth:input.logicalWidth,logicalHeight:input.logicalHeight,outputWidth:input.logicalWidth*scale,outputHeight:input.logicalHeight*scale,integerScale:scale,paletteLimit:input.paletteLimit??(input.mode==='ILLUSTRATION_HD'?256:64),edgeMode:input.mode==='ILLUSTRATION_HD'?'CONTROLLED_AA':'HARD_GRID',dither:input.mode==='PIXEL_NATIVE'?'ORDERED':'NONE',detailPasses:input.mode==='PIXEL_HD'?['silhouette','anatomy','material','subpixel-cluster','selective-highlight','palette-harmony']:input.mode==='PIXEL_NATIVE'?['silhouette','cluster-cleanup','palette-harmony']:['anatomy','material','lighting','texture','edge-refinement'],tileSize:input.mode==='PIXEL_HD'?64:32,frameConsistency:input.frameConsistency??true} as const;return{...seed,planSha256:canonicalSha256Object(seed)};}
 private validateSkin(v:SkinAppearanceProfile){const colors=[...v.baseColors,...v.shadowColors,...v.highlightColors];if(!colors.length||colors.some(x=>!/^#[0-9a-f]{6}$/i.test(x)))throw new Error('INVALID_SKIN_PALETTE');for(const n of [v.saturation,v.valueRange,v.regionVariation,v.specular,v.subsurfaceHint,v.confidence])if(!Number.isFinite(n)||n<0||n>1)throw new Error('INVALID_SKIN_APPEARANCE_VALUE');}
}
export const visualArchetypePixelFidelityService=new VisualArchetypePixelFidelityService();
