/**
 * MIKI Type Definitions
 */


export interface WorkspaceFile {
  path: string;
  name?: string;
  content: string;
  language: string;
  isModified?: boolean;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: number;
  speaker?: {
    name?: string;
    avatar?: string;
    color?: string;
  };
  meta?: any;
}

export interface PersonaConfig {
  name: string;
  userNickname: string;
  basePersonality?: string;
  speakingStyle?: string;
  avatar?: string;
  color?: string;
  [key: string]: any;
}

export interface MemoryItem {
  id: string;
  type?: string;
  content: string;
  timestamp?: number;
  importance?: number;
  tags?: string[];
  [key: string]: any;
}
export type AbstractProcedurePlan = any;
export type AbstractSymbolMapping = any;
export type AbstractTestCasePlan = any;
export type ActionPrediction = any;
export type AffectionDynamicState = any;
export type AffectionEvaluationResult = any;
export type AnswerContentIR = any;
export type AnswerPlanApplicationResult = any;
export type AnswerSkeletonType = any;
export type AntiPatternMatchResult = any;
export type AutoTeacherRequestRecord = any;
export type AutonomousDevCategory = any;
export type AutonomousDevLanguage = any;
export type AutonomousDevProject = any;
export type AutonomousDevSpec = any;
export type AutonomousDevTestCase = any;
export type AutonomousGrowthReport = any;
export type AutonomousSearchLearningRecord = any;
export type AutonomousSearchMessageMeta = any;
export type AutonomousVerificationData = any;
export type BackgroundExecutionConditions = any;
export type BackgroundTaskExecutionLog = any;
export type BenchmarkScores = any;
export type BenchmarkTestCase = any;
export type BenchmarkTestResult = any;
export type BranchReasoningSimulation = any;
export type CapabilityEvaluationTrial = any;
export type CapabilityGapEntry = any;
export type CapabilityGapType = any;
export type CapabilityLearningCandidate = any;
export type CapabilityMasteryProfile = any;
export type CapabilityMasteryState = any;
export type CapabilityPlugin = any;
export type CapabilityPluginStatus = any;
export type CapabilitySufficiencyAssessment = any;
export type ChangeContract = any;
export type ClaimFactStatus = any;
export type ClaimKind = any;
export type ClaimMaturity = any;
export type ClaimOpenWorldStatus = any;
export type ClaimRecord = any;
export type ClaimScope = any;
export type ClaimSelfProvenance = any;
export type ClaimVerificationStatus = any;
export type ClaimWorld = any;
export type CloudAiEscalationRequest = any;
export type CloudEscalationTrigger = any;
export type CodeHealingReport = any;
export type CodeHealthFinding = any;
export type CodeImprovementExperiencePayload = any;
export type CodeProcedureIR = any;
export type CodeProposal = any;
export type CodeSkeletonTemplate = any;
export type CodeUnderstandingIR = any;
export type CompiledRequestType = any;
export type CompletionChecklist = any;
export type CompletionEvaluation = any;
export type CompletionStatus = any;
export type ComponentCreationDecision = any;
export type ComponentSecurityClass = any;
export type ComponentStatus = any;
export type ComponentTestCategory = any;
export type ComponentTxtPackage = any;
export type ComprehensiveCodeVerification = any;
export type ConsoleLogItem = any;
export type ContextBudgetPlan = any;
export type ContextTier = any;
export type ConversationAnswerChangeCause = any;
export type ConversationAnswerChangeExplanation = any;
export type ConversationAnswerDecisionSnapshot = any;
export type ConversationBranch = any;
export type ConversationEvaluationCriterion = any;
export type ConversationEvaluationMetrics = any;
export type ConversationExplanationAdaptation = any;
export type ConversationGoalStatus = any;
export type ConversationOutcomeAssessment = any;
export type ConversationOutcomeKind = any;
export type ConversationQualityCause = any;
export type ConversationStage = any;
export type ConversationState = any;
export type ConversationStrategy = any;
export type ConversationTaskCard = any;
export type ConversationTaskCategory = any;
export type ConversationUnderstandingLevel = any;
export type CoreTrackingInfo = any;
export type CounterfactualEvaluationResult = any;
export type CounterfactualReflectionItem = any;
export type CounterfactualScenario = any;
export type CrossModuleCallEdge = any;
export type CrossModuleImpactAnalysis = any;
export type DecisionDelayCheckpoint = any;
export type DecisionFailureCause = any;
export type DecisionTable = any;
export type DelayedTeacherQueueItem = any;
export type DialogueAct = any;
export type DraftVerificationResult = any;
export type DualEvaluationReport = any;
export type DynamicDialogueEvaluationResult = any;
export type DynamicDialogueTurn = any;
export type DynamicEvaluationReport = any;
export type DynamicEvaluationTurn = any;
export type DynamicToolSynthesisRequest = any;
export type DynamicToolSynthesisResponse = any;
export type EmbeddingHealthCheckResult = any;
export type EmbeddingHealthStatus = any;
export type EngineMode = any;
export type EpistemicClaimClassification = any;
export type ExecutionStep = any;
export type ExperienceLink = any;
export type ExperienceRoutingFactors = any;
export type ExperienceRoutingResult = any;
export type ExplanationAdjustmentAdvice = any;
export type ExplanationLevel = any;
export type FailureCatalogStats = any;
export type FailureCategory = any;
export type FailureRecurrenceEntry = any;
export type FailureSeverity = any;
export type FailureSignature = any;
export type FailureSignatureStatus = any;
export type FalsificationCheckItem = any;
export type FalsificationEvaluation = any;
export type FeatureFlagState = any;
export type FeedbackStage = any;
export type FixedConversationScenario = any;
export type FixedConversationScenarioType = any;
export type FixedScenarioEvaluationResult = any;
export type FixedScenarioResult = any;
export type FixedScenarioTestCase = any;
export type FreshnessRevalidationResult = any;
export type FutureQuestionScenario = any;
export type GitHubRepoData = any;
export type GroundingChunk = any;
export type HeuristicRuleItem = any;
export type InvariantCheckItem = any;
export type LatentGoalInference = any;
export type LiveRepairRecord = any;
export type LiveRepairTriggerType = any;
export type LongTermMemoryType = any;
export type LoraTriggerAssessment = any;
export type ManualExplanationOverride = any;
export type MaterialValueMetric = any;
export type MemoryDestination = any;
export type MemoryLifecycleStatus = any;
export type MemoryPipelineSearchResult = any;
export type MemoryPipelineStepHit = any;
export type MemoryScope = any;
export type MemoryType = any;
export type Message = any;
export type MetacognitiveCalibrationResult = any;
export type MinimalScopeItem = any;
export type ModelGeneration = any;
export type ModelSizeComparisonReport = any;
export type ModelSizeProfile = any;
export type MultiAxisPersonaConfig = any;
export type MultiModuleAnalysisResult = any;
export type MultiTurnIntentSession = any;
export type MultiTurnIntentTrace = any;
export type NonLlmPipelineMeta = any;
export type OutboundDataClassification = any;
export type PluginConsentRequest = any;
export type PotentialUnknownBasis = any;
export type PotentialUnknownCandidate = any;
export type PredictionErrorInsightRecord = any;
export type PredictionErrorRecord = any;
export type PrivacyAuditLogEntry = any;
export type PrivacyAuditResult = any;
export type PrivacyViolationItem = any;
export type ProactiveSuggestionLevel = any;
export type ProficiencyDomain = any;
export type ReasoningDecomposition3B = any;
export type RedTeamAttackCase = any;
export type ReductionIntelligenceCategory = any;
export type RegressionSuiteRunReport = any;
export type RejectedTrainingSampleLog = any;
export type ResponseLength = any;
export type ResponseQualityEvaluation = any;
export type ResponseSkeleton = any;
export type ReviewQueueItem = any;
export type SafeMathResult = any;
export type SamplingConfig = any;
export type SamplingTuningStats = any;
export type SamplingTuningTrialResult = any;
export type SelfCodeAuditResult = any;
export type SelfImprovementProposal = any;
export type SelfImprovementRecord = any;
export type SemanticPreservationInspection = any;
export type SkillDiversityTestCase = any;
export type SkillDiversityTestResult = any;
export type SkillGraduationProgress = any;
export type SkillItem = any;
export type SpacedRecallAuditResult = any;
export type SpecificationChapterMeta = any;
export type SpecificationDriftItem = any;
export type StorageCapacityPlanReport = any;
export type StoragePartitionUsage = any;
export type StrategyOutcomeSignal = any;
export type StructuralMemoryItem = any;
export type SynthesizedWorkflow = any;
export type SynthesizedWorkflowStep = any;
export type SyntheticBatchSummary = any;
export type SyntheticProblem = any;
export type SyntheticProblemCategory = any;
export type SyntheticProblemStatus = any;
export type SystemFeatureFlags = any;
export type TaskPlan = any;
export type TaskPlanStatus = any;
export type TaskStep = any;
export type TaskStepStatus = any;
export type TeacherBudgetLimits = any;
export type TeacherBudgetStatus = any;
export type TeacherBudgetTier = any;
export type TeacherBudgetUsage = any;
export type TeacherDriftCheckResult = any;
export type TeacherGeneratedMaterial = any;
export type TeacherRequestPayload = any;
export type TeacherUsageRecord = any;
export type ToolDefinition = any;
export type ToolExecutionRequest = any;
export type ToolExecutionResult = any;
export type ToolPermissionLevel = any;
export type ToolRecommendation = any;
export type TrainingDataSplitStats = any;
export type TrainingSampleJSONL = any;
export type UncertaintyDivergenceItem = any;
export type UnifiedDecisionRecord = any;
export type UnifiedDiagnosticLog = any;
export type UserContextProfile = any;
export type UserContextProfileType = any;
export type UserEmotionalValenceType = any;
export type UserProficiencyScore = any;
export type VbaDesignSpecification = any;
export type VbaForbiddenPattern = any;
export type VbaModuleFile = any;
export type VbaProcedureDeclaration = any;
export type VbaSafetyAssessment = any;
export type VbaStaticVerificationResult = any;
export type VbaVariableDeclaration = any;
export type VirtualTrainingTrial = any;
export type WebCodeSearchResult = any;
export type WebCodeSnippet = any;
export type WebFetchMethod = any;
export type WebSearchResultItem = any;
export type WhyAnswerInspection = any;
export type WorkManagerConstraints = any;
export type WorkManagerStatus = any;
export type WorkingAgendaItem = any;
