import { storageService } from '../../../services/storageService';
import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
import { webResearchPolicyService } from './webResearchPolicyService';
import { queryPatternSelectionService } from './queryPatternSelectionService';

export type QueryIntentType='BASELINE'|'OFFICIAL_SPECIFICATION'|'CURRENT_ENVIRONMENT'|'COMPATIBILITY'|'VERSION_SPECIFIC'|'LIMITATION'|'COUNTEREVIDENCE'|'ALTERNATIVE'|'ERROR_DIAGNOSIS'|'IMPLEMENTATION_EXAMPLE'|'SECURITY'|'PRIMARY_SOURCE'|'UPDATE_OR_RETRACTION';
export type QueryReadiness='READY'|'TOO_BROAD'|'TOO_NARROW'|'AMBIGUOUS'|'ENVIRONMENT_MISMATCH'|'PRIVACY_BLOCKED'|'DUPLICATE_QUERY';
export type EnvironmentApplicability='DIRECTLY_APPLICABLE'|'APPLICABLE_WITH_ADAPTATION'|'REFERENCE_ONLY'|'NOT_APPLICABLE'|'ENVIRONMENT_UNKNOWN'|'CONFLICTING_ENVIRONMENT'|'REQUIRES_DEVICE_TEST'|'REQUIRES_EXTERNAL_ENVIRONMENT';
export interface EnvironmentFingerprint {os:string;device:string;architecture:string;runtime:string;executionLocation:string;apiLevel?:string;runtimeVersion?:string;requiredCapabilities:string[];requiredPermissions:string[];desktopUiRequired:boolean;dockerRequired:boolean;rootRequired:boolean;}
export interface ResearchQueryIntent {queryId:string;queryPlanId:string;parentQueryId?:string;researchQuestionId:string;intentType:QueryIntentType;targetClaimIds:string[];missingEvidenceType:string;environmentConstraints:EnvironmentFingerprint;sourceTierTarget:string;language:string;termsIncluded:string[];termsExcluded:string[];exactPhrases:string[];siteOrDomainConstraints:string[];timeConstraint?:string;expectedEvidence:string;stopCondition:string;createdBy:'CORE_18_DOMAINS';createdAt:number;queryText:string;readiness:QueryReadiness;applicability:EnvironmentApplicability;validationReasons:string[];}
export interface QueryPlanningPolicy {enabled:boolean;maxQueriesPerPlan:number;maxRevisionPerQuery:number;maxParallelQueries:number;maxTotalSearchRequests:number;maxQueryExecutionTimeMs:number;maxCandidateUrlsPerQuery:number;stopWhenEvidenceSatisfied:boolean;preferOfficialSources:boolean;requireCurrentEnvironmentCheck:boolean;requireCounterEvidenceSearch:boolean;linkAutoIndependentSourcePolicy:boolean;updatedAt:number;}
export interface ResearchQueryPlan {queryPlanId:string;researchQuestionId:string;canonicalResearchIntent:string;environment:EnvironmentFingerprint;policy:QueryPlanningPolicy;queries:ResearchQueryIntent[];usedQueryPatternIds:string[];excludedQueryPatternIds:string[];queryPatternSelectionId:string;queryPatternSelectionSha256:string;requiredDomains:Array<'research'|'unknown'|'strategy'|'verification'|'data'|'experience'|'learning'|'memory'|'execution'|'selfAwareness'>;status:'DRAFT'|'READY'|'BLOCKED'|'RUNNING'|'COMPLETED'|'STOPPED';planSha256:string;createdAt:number;updatedAt:number;}
export interface QueryRevisionPair {revisionPairId:string;queryId:string;originalQuery:string;revisedQuery:string;revisionReason:string;termsAdded:string[];termsRemoved:string[];beforeOutcome:Record<string,unknown>;afterOutcome?:Record<string,unknown>;resultingEvidenceIds:string[];acceptedByCore:boolean;pairSha256:string;createdAt:number;}
const POLICY_KEY='miki_research_query_planning_policy_v1';
const PLAN_KEY='miki_research_query_plans_v1';
const REVISION_KEY='miki_research_query_revision_pairs_v1';
const DEFAULT_POLICY:QueryPlanningPolicy={enabled:true,maxQueriesPerPlan:6,maxRevisionPerQuery:2,maxParallelQueries:2,maxTotalSearchRequests:12,maxQueryExecutionTimeMs:120000,maxCandidateUrlsPerQuery:10,stopWhenEvidenceSatisfied:true,preferOfficialSources:true,requireCurrentEnvironmentCheck:true,requireCounterEvidenceSearch:true,linkAutoIndependentSourcePolicy:true,updatedAt:0};
const DEVICE:EnvironmentFingerprint={os:'Android',device:'Galaxy S25',architecture:'arm64',runtime:'APK/Capacitor WebView',executionLocation:'GALAXY_S25',requiredCapabilities:[],requiredPermissions:[],desktopUiRequired:false,dockerRequired:false,rootRequired:false};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,Math.trunc(Number.isFinite(value)?value:min)));
const normalize=(text:string)=>text.normalize('NFKC').replace(/\s+/g,' ').trim();
class ResearchQueryPlanningService {
 getPolicy():QueryPlanningPolicy {const value=storageService.getJson<QueryPlanningPolicy>(POLICY_KEY, DEFAULT_POLICY);return this.normalizePolicy(value||DEFAULT_POLICY);}
 savePolicy(input:QueryPlanningPolicy):{policy:QueryPlanningPolicy;receiptId:string;policySha256:string}{const policy=this.normalizePolicy({...input,updatedAt:Date.now()});storageService.setItem(POLICY_KEY,policy);const policySha256=canonicalSha256Object(policy);return {policy,receiptId:`RQPR-${policySha256.slice(0,20)}`,policySha256};}
 listPlans():ResearchQueryPlan[]{return storageService.getJson<ResearchQueryPlan[]>(PLAN_KEY, []);}
 listRevisionPairs():QueryRevisionPair[]{return storageService.getJson<QueryRevisionPair[]>(REVISION_KEY, []);}
 buildPlan(question:string,targetClaimIds:string[]=[]):ResearchQueryPlan {const intent=normalize(question);if(!intent)throw new Error('RESEARCH_INTENT_REQUIRED');const policy=this.getPolicy();const researchQuestionId=`RQ-${canonicalSha256Object({intent}).slice(0,20)}`;const queryPlanId=`RQP-${canonicalSha256Object({intent,environment:DEVICE,policy}).slice(0,20)}`;const specs:Array<[QueryIntentType,string,string]>=[];specs.push(['BASELINE',intent,'全体条件を保持した基準検索']);if(policy.preferOfficialSources)specs.push(['OFFICIAL_SPECIFICATION',`${intent} official specification documentation`,'一次・公式情報']);if(policy.requireCurrentEnvironmentCheck)specs.push(['CURRENT_ENVIRONMENT',`${intent} Android arm64 Termux compatibility`,'Galaxy S25環境適合']);if(policy.requireCounterEvidenceSearch)specs.push(['COUNTEREVIDENCE',`${intent} limitation unsupported known issue`,'反証・制限']);const webPolicy=webResearchPolicyService.get();if(webPolicy.requirePrimarySource&&!specs.some(x=>x[0]==='PRIMARY_SOURCE'||x[0]==='OFFICIAL_SPECIFICATION'))specs.push(['PRIMARY_SOURCE',`${intent} primary source`,'一次情報']);const unique=new Map<string,[QueryIntentType,string,string]>();for(const item of specs){const key=normalize(item[1]).toLowerCase();if(!unique.has(key))unique.set(key,item);}const chosen=[...unique.values()].slice(0,policy.maxQueriesPerPlan);const queries=chosen.map((item,index)=>this.makeQuery(queryPlanId,researchQuestionId,intent,item[0],item[1],item[2],index));const patternSelection=queryPatternSelectionService.select(intent,chosen.map(item=>item[0]),DEVICE,Math.min(3,policy.maxQueriesPerPlan));const status=policy.enabled&&queries.every(q=>q.readiness==='READY')?'READY':'BLOCKED';const base= {queryPlanId,researchQuestionId,canonicalResearchIntent:intent,environment:DEVICE,policy,queries,usedQueryPatternIds:patternSelection.selectedPatternIds,excludedQueryPatternIds:patternSelection.excludedPatternIds,queryPatternSelectionId:patternSelection.selectionId,queryPatternSelectionSha256:patternSelection.selectionSha256,requiredDomains:['research','unknown','strategy','verification','data','experience','learning','memory','execution','selfAwareness'] as ResearchQueryPlan['requiredDomains'],status:status as ResearchQueryPlan['status'],createdAt:Date.now(),updatedAt:Date.now()};const plan:{planSha256:string}&typeof base={...base,planSha256:canonicalSha256Object(base)};const plans=[plan,...this.listPlans().filter(x=>x.queryPlanId!==plan.queryPlanId)].slice(0,100);storageService.setItem(PLAN_KEY,plans);return plan;}
 reviseQuery(planId:string,queryId:string,revisedText:string,reason:string,beforeOutcome:Record<string,unknown>):QueryRevisionPair {const plan=this.listPlans().find(x=>x.queryPlanId===planId);const query=plan?.queries.find(x=>x.queryId===queryId);if(!plan||!query)throw new Error('QUERY_NOT_FOUND');const revised=normalize(revisedText);if(!revised||revised===query.queryText)throw new Error('QUERY_REVISION_REQUIRED');const before=new Set(query.queryText.split(/\s+/));const after=new Set(revised.split(/\s+/));const base={queryId,originalQuery:query.queryText,revisedQuery:revised,revisionReason:normalize(reason)||'UNSPECIFIED',termsAdded:[...after].filter(x=>!before.has(x)),termsRemoved:[...before].filter(x=>!after.has(x)),beforeOutcome,resultingEvidenceIds:[],acceptedByCore:false,createdAt:Date.now()};const pair:{revisionPairId:string;pairSha256:string}&typeof base={...base,pairSha256:canonicalSha256Object(base),revisionPairId:''};pair.revisionPairId=`QRP-${pair.pairSha256.slice(0,20)}`;storageService.setItem(REVISION_KEY,[pair,...this.listRevisionPairs()].slice(0,500));return pair;}
 private makeQuery(planId:string,rqid:string,canonical:string,intentType:QueryIntentType,text:string,expected:string,index:number):ResearchQueryIntent {const queryText=normalize(text);const validation=this.validate(queryText,canonical,intentType);const queryId=`RQI-${canonicalSha256Object({planId,intentType,queryText,index}).slice(0,20)}`;return {queryId,queryPlanId:planId,researchQuestionId:rqid,intentType,targetClaimIds:[],missingEvidenceType:expected,environmentConstraints:DEVICE,sourceTierTarget:intentType.includes('OFFICIAL')||intentType==='PRIMARY_SOURCE'?'PRIMARY_OR_OFFICIAL':'ANY_VERIFIABLE',language:'ja',termsIncluded:queryText.split(/\s+/),termsExcluded:[],exactPhrases:[],siteOrDomainConstraints:[],expectedEvidence:expected,stopCondition:'EVIDENCE_SATISFIED_OR_BUDGET_REACHED',createdBy:'CORE_18_DOMAINS',createdAt:Date.now(),queryText,readiness:validation.readiness,applicability:validation.applicability,validationReasons:validation.reasons};}
 private validate(query:string,canonical:string,type:QueryIntentType):{readiness:QueryReadiness;applicability:EnvironmentApplicability;reasons:string[]}{const reasons:string[]=[];if(/(?:api[_-]?key|token|password|secret)\s*[=:]\s*\S+/i.test(query))return {readiness:'PRIVACY_BLOCKED',applicability:'ENVIRONMENT_UNKNOWN',reasons:['SECRET_LIKE_TEXT_DETECTED']};const words=query.split(/\s+/).filter(Boolean);if(words.length<2)reasons.push('QUERY_TOO_BROAD');if(words.length>24)reasons.push('QUERY_TOO_NARROW');if(!normalize(query).toLowerCase().includes(normalize(canonical).toLowerCase().slice(0,Math.min(12,canonical.length)).toLowerCase()))reasons.push('CANONICAL_INTENT_WEAK_MATCH');const pcOnly=/\b(?:windows|x64|docker|desktop only)\b/i.test(query)&&!/android|termux|arm64/i.test(query);return {readiness:reasons.includes('QUERY_TOO_BROAD')?'TOO_BROAD':reasons.includes('QUERY_TOO_NARROW')?'TOO_NARROW':'READY',applicability:pcOnly?'REFERENCE_ONLY':type==='CURRENT_ENVIRONMENT'?'DIRECTLY_APPLICABLE':'ENVIRONMENT_UNKNOWN',reasons};}
 private normalizePolicy(value:QueryPlanningPolicy):QueryPlanningPolicy{return {...DEFAULT_POLICY,...value,maxQueriesPerPlan:clamp(value.maxQueriesPerPlan,1,20),maxRevisionPerQuery:clamp(value.maxRevisionPerQuery,0,5),maxParallelQueries:clamp(value.maxParallelQueries,1,3),maxTotalSearchRequests:clamp(value.maxTotalSearchRequests,1,50),maxQueryExecutionTimeMs:clamp(value.maxQueryExecutionTimeMs,10000,600000),maxCandidateUrlsPerQuery:clamp(value.maxCandidateUrlsPerQuery,1,50)};}
}
export const researchQueryPlanningService=new ResearchQueryPlanningService();
export const CURRENT_MIKI_ENVIRONMENT=DEVICE;
