import { canonicalSha256Object } from '../../core/services/canonicalSha256Service';
export type VisualReferenceProvider='OPENVERSE'|'WIKIMEDIA_COMMONS'|'PIXABAY';
export interface VisualReferenceQuery{query:string;media:'IMAGE'|'VIDEO';purpose:'STYLE_TREND'|'PALETTE'|'POSE'|'CLOTHING'|'SCENE'|'MOTION';allowModification:boolean;commercialUse:boolean;limit:number;}
export interface VisualReferenceCandidate{provider:VisualReferenceProvider;id:string;title:string;pageUrl:string;previewUrl:string;creator?:string;license:string;licenseUrl?:string;attribution?:string;tags:string[];media:'IMAGE'|'VIDEO';width?:number;height?:number;sourceVerified:boolean;}
export interface VisualReferencePacket{query:VisualReferenceQuery;candidates:VisualReferenceCandidate[];accepted:VisualReferenceCandidate[];rejected:Array<{candidate:VisualReferenceCandidate;reason:string}>;trendHints:string[];packetSha256:string;}
class VisualReferenceResearchService{
 buildOpenverseUrl(input:VisualReferenceQuery){const params=new URLSearchParams({q:input.query,page_size:String(Math.max(1,Math.min(20,input.limit))),mature:'false'});if(input.allowModification)params.set('license_type','commercial,modification');else if(input.commercialUse)params.set('license_type','commercial');return`https://api.openverse.org/v1/images/?${params}`;}
 buildWikimediaUrl(input:VisualReferenceQuery){const params=new URLSearchParams({action:'query',generator:'search',gsrsearch:`filetype:bitmap ${input.query}`,gsrnamespace:'6',gsrlimit:String(Math.max(1,Math.min(20,input.limit))),prop:'imageinfo',iiprop:'url|extmetadata|size',format:'json',origin:'*'});return`https://commons.wikimedia.org/w/api.php?${params}`;}
 buildPixabayUrl(input:VisualReferenceQuery,apiKey?:string){if(!apiKey)return{blocked:true,reason:'PIXABAY_API_KEY_REQUIRED',url:''};const endpoint=input.media==='VIDEO'?'https://pixabay.com/api/videos/':'https://pixabay.com/api/';const params=new URLSearchParams({key:apiKey,q:input.query,safesearch:'true',per_page:String(Math.max(3,Math.min(20,input.limit)))});return{blocked:false,url:`${endpoint}?${params}`};}
 evaluate(input:VisualReferenceQuery,candidates:VisualReferenceCandidate[]):VisualReferencePacket{const accepted:VisualReferenceCandidate[]=[];const rejected:VisualReferencePacket['rejected']=[];for(const candidate of candidates){const reason=this.rejectionReason(input,candidate);if(reason)rejected.push({candidate,reason});else accepted.push(candidate);}const trendHints=this.hints(input,accepted);const seed={query:input,candidates,accepted,rejected,trendHints};return{...seed,packetSha256:canonicalSha256Object(seed)};}
 conversationalSuggestions(packet:VisualReferencePacket){if(!packet.accepted.length)return['参照候補のライセンス確認が取れていないため、素材を使わず形状・色・動作の条件を会話で指定してください。'];return packet.trendHints.slice(0,4).map((hint,index)=>`候補${index+1}: ${hint}。こういう方向をCanvasまたはドット絵候補に反映しますか？`);}
 learningPlan(packet:VisualReferencePacket){return{storeOriginalMedia:false,outputs:['PALETTE_PROFILE','SHAPE_TREND','POSE_MOTION','CLOTHING_TREND','PIXEL_GRID_HINT'],sourcePageUrls:packet.accepted.map(x=>x.pageUrl),attributions:packet.accepted.map(x=>x.attribution).filter(Boolean),packetSha256:packet.packetSha256};}
 private rejectionReason(input:VisualReferenceQuery,candidate:VisualReferenceCandidate){if(!candidate.sourceVerified)return'SOURCE_LICENSE_NOT_VERIFIED';const license=candidate.license.toLowerCase();if(license.includes('nd')&&input.allowModification)return'LICENSE_NO_DERIVATIVES';if(license.includes('nc')&&input.commercialUse)return'LICENSE_NONCOMMERCIAL';if(!candidate.pageUrl||!candidate.previewUrl)return'REFERENCE_URL_MISSING';if(candidate.media!==input.media)return'MEDIA_KIND_MISMATCH';return'';}
 private hints(input:VisualReferenceQuery,candidates:VisualReferenceCandidate[]){const tags=candidates.flatMap(x=>x.tags).map(x=>x.trim().toLowerCase()).filter(Boolean);const counts=new Map<string,number>();tags.forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1));const top=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,6).map(x=>x[0]);const prefix={STYLE_TREND:'画風',PALETTE:'配色',POSE:'姿勢',CLOTHING:'服装',SCENE:'場面',MOTION:'動き'}[input.purpose];return top.length?top.map(tag=>`${prefix}の傾向「${tag}」`):[`${prefix}の参照候補${candidates.length}件を比較`];}
}
export const visualReferenceResearchService=new VisualReferenceResearchService();
